### ISSUE TITLE
There seem to be a bunch of memory leaks in systemd-networkd

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10149]
I've just run the tests from https://github.com/systemd/systemd/pull/10147 and now I can see a lot of issues reported by Valgrind, which I'm going to paste here one by one.

```sh
==28238==
==28238== HEAP SUMMARY:
==28238==     in use at exit: 16,512 bytes in 4 blocks
==28238==   total heap usage: 4,071 allocs, 4,067 frees, 1,370,399 bytes allocated
==28238==
==28238== 128 bytes in 1 blocks are definitely lost in loss record 1 of 4
==28238==    at 0x4C2EA1E: calloc (vg_replace_malloc.c:711)
==28238==    by 0x12C69C: routing_policy_rule_new (networkd-routing-policy-rule.c:20)
==28238==    by 0x12D105: routing_policy_rule_add_internal (networkd-routing-policy-rule.c:236)
==28238==    by 0x12D32D: routing_policy_rule_add_foreign (networkd-routing-policy-rule.c:296)
==28238==    by 0x11CBE3: manager_rtnl_process_rule (networkd-manager.c:854)
==28238==    by 0x11F6FA: manager_rtnl_enumerate_rules (networkd-manager.c:1670)
==28238==    by 0x1169D1: main (networkd.c:114)
==28238==
==28238== LEAK SUMMARY:
==28238==    definitely lost: 128 bytes in 1 blocks
==28238==    indirectly lost: 0 bytes in 0 blocks
==28238==      possibly lost: 0 bytes in 0 blocks
==28238==    still reachable: 16,384 bytes in 3 blocks
==28238==         suppressed: 0 bytes in 0 blocks
==28238== Reachable blocks (those to which a pointer was found) are not shown.
==28238== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==28238==
```

**Comment by evverx** [comment]
```
==29297==
==29297== 128 bytes in 1 blocks are definitely lost in loss record 2 of 5
==29297==    at 0x4C2EA1E: calloc (vg_replace_malloc.c:711)
==29297==    by 0x12C69C: routing_policy_rule_new (networkd-routing-policy-rule.c:20)
==29297==    by 0x12D105: routing_policy_rule_add_internal (networkd-routing-policy-rule.c:236)
==29297==    by 0x12D2AD: routing_policy_rule_add (networkd-routing-policy-rule.c:281)
==29297==    by 0x12EF9D: routing_policy_rule_configure (networkd-routing-policy-rule.c:537)
==29297==    by 0x150E42: link_set_routing_policy_rule (networkd-link.c:778)
==29297==    by 0x151329: link_enter_set_routes (networkd-link.c:833)
==29297==    by 0x1531AD: link_enter_set_addresses (networkd-link.c:1199)
==29297==    by 0x15EF5F: link_carrier_gained (networkd-link.c:3409)
==29297==    by 0x16024E: link_update (networkd-link.c:3631)
==29297==    by 0x11BB98: manager_rtnl_process_link (networkd-manager.c:695)
==29297==    by 0x4FDB21A: process_match (sd-netlink.c:351)
==29297==
```

**Comment by evverx** [comment]
```sh
==29311== Invalid read of size 1
==29311==    at 0x5680400: __strcmp_ssse3 (in /usr/lib64/libc-2.26.so)
==29311==    by 0x4F52FEF: strcmp_ptr (string-util.c:26)
==29311==    by 0x12CCA9: routing_policy_rule_compare_func (networkd-routing-policy-rule.c:123)
==29311==    by 0x4F25033: base_bucket_scan (hashmap.c:1246)
==29311==    by 0x4F25471: internal_hashmap_get (hashmap.c:1354)
==29311==    by 0x12C4F2: set_get (set.h:34)
==29311==    by 0x130F7C: routing_policy_rule_purge (networkd-routing-policy-rule.c:1031)
==29311==    by 0x150F27: link_set_routing_policy_rule (networkd-link.c:788)
==29311==    by 0x151329: link_enter_set_routes (networkd-link.c:833)
==29311==    by 0x1519F6: address_handler (networkd-link.c:900)
==29311==    by 0x4FDB097: process_reply (sd-netlink.c:330)
==29311==    by 0x4FDB39F: process_running (sd-netlink.c:385)
==29311==  Address 0x9475bf8 is 56 bytes inside a block of size 92 free'd
==29311==    at 0x4C2DD18: free (vg_replace_malloc.c:530)
==29311==    by 0x4FCF698: sd_netlink_message_unref (netlink-message.c:107)
==29311==    by 0x1177A8: sd_netlink_message_unrefp (sd-netlink.h:179)
==29311==    by 0x11F73D: manager_rtnl_enumerate_rules (networkd-manager.c:1640)
==29311==    by 0x1169D1: main (networkd.c:114)
==29311==  Block was alloc'd at
==29311==    at 0x4C2CB6B: malloc (vg_replace_malloc.c:299)
==29311==    by 0x4EF061C: memdup (alloc-util.c:15)
==29311==    by 0x4FD400C: socket_read_message (netlink-socket.c:406)
==29311==    by 0x4FDC042: sd_netlink_call (sd-netlink.c:641)
==29311==    by 0x11F650: manager_rtnl_enumerate_rules (networkd-manager.c:1655)
==29311==    by 0x1169D1: main (networkd.c:114)
==29311==
==29311== Invalid read of size 1
==29311==    at 0x4C30C54: strcmp (vg_replace_strmem.c:846)
==29311==    by 0x4F52FEF: strcmp_ptr (string-util.c:26)
==29311==    by 0x12CCA9: routing_policy_rule_compare_func (networkd-routing-policy-rule.c:123)
==29311==    by 0x4F25033: base_bucket_scan (hashmap.c:1246)
==29311==    by 0x4F25471: internal_hashmap_get (hashmap.c:1354)
==29311==    by 0x12C4F2: set_get (set.h:34)
==29311==    by 0x130F7C: routing_policy_rule_purge (networkd-routing-policy-rule.c:1031)
==29311==    by 0x150F27: link_set_routing_policy_rule (networkd-link.c:788)
==29311==    by 0x151329: link_enter_set_routes (networkd-link.c:833)
==29311==    by 0x1519F6: address_handler (networkd-link.c:900)
==29311==    by 0x4FDB097: process_reply (sd-netlink.c:330)
==29311==    by 0x4FDB39F: process_running (sd-netlink.c:385)
==29311==  Address 0x9475bf9 is 57 bytes inside a block of size 92 free'd
==29311==    at 0x4C2DD18: free (vg_replace_malloc.c:530)
==29311==    by 0x4FCF698: sd_netlink_message_unref (netlink-message.c:107)
==29311==    by 0x1177A8: sd_netlink_message_unrefp (sd-netlink.h:179)
==29311==    by 0x11F73D: manager_rtnl_enumerate_rules (networkd-manager.c:1640)
==29311==    by 0x1169D1: main (networkd.c:114)
==29311==  Block was alloc'd at
==29311==    at 0x4C2CB6B: malloc (vg_replace_malloc.c:299)
==29311==    by 0x4EF061C: memdup (alloc-util.c:15)
==29311==    by 0x4FD400C: socket_read_message (netlink-socket.c:406)
==29311==    by 0x4FDC042: sd_netlink_call (sd-netlink.c:641)
==29311==    by 0x11F650: manager_rtnl_enumerate_rules (networkd-manager.c:1655)
==29311==    by 0x1169D1: main (networkd.c:114)
==29311==
```

**Comment by evverx** [comment]
```
==29486==
==29486== 17 bytes in 1 blocks are definitely lost in loss record 1 of 4
==29486==    at 0x4C2CB6B: malloc (vg_replace_malloc.c:299)
==29486==    by 0x55D4769: strdup (in /usr/lib64/libc-2.26.so)
==29486==    by 0x4F55998: free_and_strdup (string-util.c:1014)
==29486==    by 0x4EAE35B: config_parse_string (conf-parser.c:690)
==29486==    by 0x4EAB44A: next_assignment (conf-parser.c:138)
==29486==    by 0x4EABD2E: parse_line (conf-parser.c:263)
==29486==    by 0x4EAC37B: config_parse (conf-parser.c:380)
==29486==    by 0x4EAC609: config_parse_many_files (conf-parser.c:437)
==29486==    by 0x4EAC92C: config_parse_many (conf-parser.c:496)
==29486==    by 0x121A02: network_load_one (networkd-network.c:254)
==29486==    by 0x121F79: network_load (networkd-network.c:337)
==29486==    by 0x11EFDF: manager_load_config (networkd-manager.c:1523)
==29486==
```

**Comment by evverx** [comment]
```
==29577== 8 bytes in 1 blocks are definitely lost in loss record 1 of 4
==29577==    at 0x4C2CB6B: malloc (vg_replace_malloc.c:299)
==29577==    by 0x55D47B9: strndup (in /usr/lib64/libc-2.26.so)
==29577==    by 0x18459A: lease_parse_string (sd-dhcp-lease.c:329)
==29577==    by 0x185C86: dhcp_lease_parse_options (sd-dhcp-lease.c:645)
==29577==    by 0x182105: parse_options (dhcp-option.c:223)
==29577==    by 0x1821F9: dhcp_option_parse (dhcp-option.c:251)
==29577==    by 0x179E86: client_handle_ack (sd-dhcp-client.c:1381)
==29577==    by 0x17B0EC: client_handle_message (sd-dhcp-client.c:1639)
==29577==    by 0x17BDEB: client_receive_message_raw (sd-dhcp-client.c:1881)
==29577==    by 0x4FF2410: source_dispatch (sd-event.c:3064)
==29577==    by 0x4FF3C71: sd_event_dispatch (sd-event.c:3477)
==29577==    by 0x4FF4122: sd_event_run (sd-event.c:3534)
==29577==
```

**Comment by evverx** [comment]
If I didn't miss anything, that's it. For some reason I though that the code of `networkd` was fuzzed, but it doesn't seem to be the case :-(

**Comment by ssahani** [comment]
Thanks for verifying it.

**Comment by evverx** [comment]
Frankly, I wouldn't say I closely looked at the test. The only thing probably worth mentioning is that I changed it slightly so it wouldn't fail as soon as it started with:
```sh
ERROR

======================================================================
ERROR: setUpModule (__main__)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./systemd-networkd-tests.py", line 29, in setUpModule
    shutil.rmtree(networkd_ci_path)
  File "/usr/lib64/python3.6/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/networkd-ci'

----------------------------------------------------------------------
Ran 0 tests in 0.002s

FAILED (errors=1)
```
I'm still not sure that those tests should be kept upstream, but I think it would be better to continue this discussion in https://github.com/systemd/systemd/pull/10144.

**Comment by poettering** [comment]
@evverx btw, whenever you find bugs such as memory leaks, please mark them for the next upcoming milestone when creating the issue. memory leaks are such basic errors so that we shouldn't realease with known ones. Moreover, with today's tooling they are generally easy to track down hence there's little reason it would be OK to ignore them...

**Comment by yuwata** [comment]
Are there anyone working on this? If not, I will try to fix this tomorrow.

**Comment by yuwata** [comment]
@evverx Could you provide the modified script you use?

**Comment by evverx** [comment]
@yuwata sure! Below is the kludge I was talking about:
```diff
diff --git a/test/test-network/systemd-networkd-tests.py b/test/test-network/systemd-networkd-tests.py
index 3952e8753..80c6605cd 100755
--- a/test/test-network/systemd-networkd-tests.py
+++ b/test/test-network/systemd-networkd-tests.py
@@ -26,7 +26,7 @@ def setUpModule():

     os.makedirs(network_unit_file_path, exist_ok=True)

-    shutil.rmtree(networkd_ci_path)
+    shutil.rmtree(networkd_ci_path, ignore_errors=True)
     copytree('conf', networkd_ci_path)

 def tearDownModule():
```
It's also probably worth noting that a lot of tests are currently failing on my laptop even without `Valgrind`.

**Comment by yuwata** [comment]
> It's also probably worth noting that a lot of tests are currently failing on my laptop even without Valgrind.

Yeah, so I may be need a computer which have a interface for wired network...

**Comment by evverx** [comment]
@yuwata thank you! I'll try to take a look tomorrow.

By the way, I kind of started to work on a fuzzer for dhcp6-client. It's currently far from perfect, too limited and for some reason doesn't work in containers created by "tools/infra.py". On the positive side, it's able to trigger `client_parse_message` and looking at its output, I think I'm done with `systemd-networkd` for now :-) This was the first issue found by the fuzzer, but there're many more:
```
DHCPv6 CLIENT: Started in Managed mode
=================================================================
==3393==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000003900 at pc 0x7efe439c5433 bp 0x7ffe96858700 sp 0x7ffe96857ea8
READ of size 514 at 0x621000003900 thread T0
    #0 0x7efe439c5432  (/lib64/libasan.so.4+0x79432)
    #1 0x7efe42be090e in memdup ../src/basic/alloc-util.c:19
    #2 0x5651954602be in dhcp6_lease_set_serverid ../src/libsystemd-network/sd-dhcp6-lease.c:60
    #3 0x5651954541ad in client_parse_message ../src/libsystemd-network/sd-dhcp6-client.c:882
    #4 0x565195455b68 in client_receive_advertise ../src/libsystemd-network/sd-dhcp6-client.c:1082
    #5 0x5651954565d7 in client_receive_message ../src/libsystemd-network/sd-dhcp6-client.c:1181
    #6 0x7efe42ebeaf2 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3042
    #7 0x7efe42ec35f5 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3455
    #8 0x7efe42ec425c in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3512
    #9 0x565195444933 in LLVMFuzzerTestOneInput ../src/fuzz/fuzz-dhcp6-client.c:55
    #10 0x565195446d58 in main ../src/fuzz/fuzz-main.c:33
    #11 0x7efe4150df29 in __libc_start_main (/lib64/libc.so.6+0x20f29)
    #12 0x565195444169 in _start (/home/vagrant/systemd/build/fuzz-dhcp6-client+0x31169)

0x621000003900 is located 0 bytes to the right of 4096-byte region [0x621000002900,0x621000003900)
allocated by thread T0 here:
    #0 0x7efe43a2a850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x565195456116 in client_receive_message ../src/libsystemd-network/sd-dhcp6-client.c:1124
    #2 0x7efe42ebeaf2 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3042
    #3 0x7efe42ec35f5 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3455
    #4 0x7efe42ec425c in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3512
    #5 0x565195444933 in LLVMFuzzerTestOneInput ../src/fuzz/fuzz-dhcp6-client.c:55
    #6 0x565195446d58 in main ../src/fuzz/fuzz-main.c:33
    #7 0x7efe4150df29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.4+0x79432)
```
