### ISSUE TITLE
test-dhcp6-client seems to be failing under ASan

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10157]
It seems that the test has been failing since https://github.com/systemd/systemd/pull/9981 was merged. Below are the direct leaks reported by ASan:
```sh
Direct leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x7fa3b5c5da38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x5618d467b7db in dhcp6_lease_new ../src/libsystemd-network/sd-dhcp6-lease.c:397
    #2 0x5618d466d726 in client_receive_advertise ../src/libsystemd-network/sd-dhcp6-client.c:1078
    #3 0x5618d466e334 in client_receive_message ../src/libsystemd-network/sd-dhcp6-client.c:1181
    #4 0x7fa3b50f2916 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3064
    #5 0x7fa3b50f7419 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3477
    #6 0x7fa3b50f8080 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3534
    #7 0x7fa3b50f837d in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:3556
    #8 0x5618d465c814 in test_client_solicit ../src/libsystemd-network/test-dhcp6-client.c:929
    #9 0x5618d465caf4 in main ../src/libsystemd-network/test-dhcp6-client.c:951
    #10 0x7fa3b3744f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

Direct leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x7fa3b5c5da38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x5618d467b7db in dhcp6_lease_new ../src/libsystemd-network/sd-dhcp6-lease.c:397
    #2 0x5618d466d2b5 in client_receive_reply ../src/libsystemd-network/sd-dhcp6-client.c:1047
    #3 0x5618d466e39d in client_receive_message ../src/libsystemd-network/sd-dhcp6-client.c:1194
    #4 0x7fa3b50f2916 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3064
    #5 0x7fa3b50f7419 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3477
    #6 0x7fa3b50f8080 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3534
    #7 0x7fa3b50f837d in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:3556
    #8 0x5618d465c814 in test_client_solicit ../src/libsystemd-network/test-dhcp6-client.c:929
    #9 0x5618d465caf4 in main ../src/libsystemd-network/test-dhcp6-client.c:951
    #10 0x7fa3b3744f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

Direct leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x7fa3b5c5da38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x5618d467b7db in dhcp6_lease_new ../src/libsystemd-network/sd-dhcp6-lease.c:397
    #2 0x5618d466d2b5 in client_receive_reply ../src/libsystemd-network/sd-dhcp6-client.c:1047
    #3 0x5618d466e2af in client_receive_message ../src/libsystemd-network/sd-dhcp6-client.c:1170
    #4 0x7fa3b50f2916 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3064
    #5 0x7fa3b50f7419 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3477
    #6 0x7fa3b50f8080 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3534
    #7 0x7fa3b50f837d in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:3556
    #8 0x5618d465c814 in test_client_solicit ../src/libsystemd-network/test-dhcp6-client.c:929
    #9 0x5618d465caf4 in main ../src/libsystemd-network/test-dhcp6-client.c:951
    #10 0x7fa3b3744f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)
```

@pfl could you take a look?

**Comment by pfl** [comment]
Ok!
