### ISSUE TITLE
kdbus: telepathy crashes

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1021]
With systemd 53496ca and current kdbus, telepathy seems to be unable to connect to the bus and crashes. systemd v224 is fine. Launching `mission-control-5` or `goa-daemon` from a terminal works; they crash when launched from the user instance. I've already attempted importing the environment.

Backtraces:

```
Core was generated by `/usr/lib/telepathy/mission-control-5'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  mcd_service_run (self=0x0) at mcd-service.c:190
190     mcd-service.c: No such file or directory.
(gdb) bt
#0  mcd_service_run (self=0x0) at mcd-service.c:190
#1  0x000000000040e974 in main (argc=<optimized out>, argv=<optimized out>) at mc-server.c:194
```

```
Core was generated by `/usr/lib/gnome-online-accounts/goa-daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f71379ec940 in _tp_account_manager_new_internal (bus_daemon=0x0, factory=0xf43660) at account-manager.c:741
741     account-manager.c: No such file or directory.
(gdb) bt
#0  0x00007f71379ec940 in _tp_account_manager_new_internal (bus_daemon=0x0, factory=0xf43660) at account-manager.c:741
#1  tp_account_manager_new_with_factory (factory=0xf43660) at account-manager.c:792
#2  0x00007f713830bef6 in goa_utils_initialize_client_factory () from /usr/lib/libgoa-backend-1.0.so.1
#3  0x000000000040c0dc in ?? ()
#4  0x00007f7136e641b9 in g_type_class_ref () from /usr/lib/libgobject-2.0.so.0
#5  0x00007f7136e4c26a in g_object_newv () from /usr/lib/libgobject-2.0.so.0
#6  0x00007f7136e4c9f4 in g_object_new () from /usr/lib/libgobject-2.0.so.0
#7  0x00000000004091b2 in ?? ()
#8  0x00007f713715fbe6 in ?? () from /usr/lib/libgio-2.0.so.0
#9  0x00007f713715fe28 in ?? () from /usr/lib/libgio-2.0.so.0
#10 0x00007f71370fac27 in g_simple_async_result_complete () from /usr/lib/libgio-2.0.so.0
#11 0x00007f7137157c32 in ?? () from /usr/lib/libgio-2.0.so.0
#12 0x00007f71370fac27 in g_simple_async_result_complete () from /usr/lib/libgio-2.0.so.0
#13 0x00007f71370fac89 in ?? () from /usr/lib/libgio-2.0.so.0
#14 0x00007f7136b7090d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#15 0x00007f7136b70ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#16 0x00007f7136b71002 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#17 0x0000000000408fff in ?? ()
#18 0x00007f7136586610 in __libc_start_main () from /usr/lib/libc.so.6
#19 0x0000000000409059 in ?? ()
```

**Comment by heftig** [comment]
I think this may be because d4d0002 does:

``` diff
diff --git a/src/dbus1-generator/dbus1-generator.c b/src/dbus1-generator/dbus1-generator.c
index 4980fcc..25c8e20 100644
--- a/src/dbus1-generator/dbus1-generator.c
+++ b/src/dbus1-generator/dbus1-generator.c
@@ -84,7 +84,8 @@ static int create_dbus_files(
                         fprintf(f, "Environment=DBUS_STARTER_BUS_TYPE=%s\n", type);

                         if (streq(type, "system"))
-                                fprintf(f, "Environment=DBUS_STARTER_ADDRESS=" DEFAULT_SYSTEM_BUS_ADDRESS "\n");
+                                fprintf(f, "Environment=DBUS_STARTER_ADDRESS=%s\n",
+                                        is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);
                         else if (streq(type, "session")) {
                                 char *run;

@@ -94,8 +95,10 @@ static int create_dbus_files(
                                         return -EINVAL;
                                 }

-                                fprintf(f, "Environment=DBUS_STARTER_ADDRESS="KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT "\n",
-                                        getuid(), run);
+                                if (is_kdbus_available())
+                                        fprintf(f, "Environment=DBUS_STARTER_ADDRESS="KERNEL_USER_BUS_ADDRESS_FMT "\n", getuid());
+                                else
+                                        fprintf(f, "Environment=DBUS_STARTER_ADDRESS="UNIX_USER_BUS_ADDRESS_FMT "\n", run);
                         }
                 }
```

So under kdbus the starter address will only contain the kernel address and is missing the unix address, which the kdbus-incapable telepathy requires to connect.

**Comment by dvdhrm** [comment]
Wow.. that bug is on me. I totally didn't think that thing through. Thanks for the report! I guess we have to revert it and then fix sd-bus.

**Comment by heftig** [comment]
Maybe this is enough for now?

``` diff
diff --git i/src/dbus1-generator/dbus1-generator.c w/src/dbus1-generator/dbus1-generator.c
index 25c8e20..97d8d44 100644
--- i/src/dbus1-generator/dbus1-generator.c
+++ w/src/dbus1-generator/dbus1-generator.c
@@ -85,7 +85,7 @@ static int create_dbus_files(

                         if (streq(type, "system"))
                                 fprintf(f, "Environment=DBUS_STARTER_ADDRESS=%s\n",
-                                        is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);
+                                        is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS ";" UNIX_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);
                         else if (streq(type, "session")) {
                                 char *run;

@@ -96,7 +96,7 @@ static int create_dbus_files(
                                 }

                                 if (is_kdbus_available())
-                                        fprintf(f, "Environment=DBUS_STARTER_ADDRESS="KERNEL_USER_BUS_ADDRESS_FMT "\n", getuid());
+                                        fprintf(f, "Environment=DBUS_STARTER_ADDRESS="KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT "\n", getuid(), run);
                                 else
                                         fprintf(f, "Environment=DBUS_STARTER_ADDRESS="UNIX_USER_BUS_ADDRESS_FMT "\n", run);
                         }
```

**Comment by dvdhrm** [comment]
I reverted the patch. We will have to think of something else.

Thanks for the report!
