### ISSUE TITLE
UBSan seems to be complaining about a signed integer overflow in barrier.h

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10332]
Below is a backtrace from a machine where `libubsan` has just been upgraded to `8.1.1`:
```sh
<unknown>: runtime error: signed integer overflow: 1 - -9223372036854775807 cannot be represented in type 'long int'
    #0 0x7fa98e179aaa in barrier_is_aborted ../src/basic/barrier.h:67
    #1 0x7fa98e17bf0b in barrier_sync ../src/basic/barrier.c:393
    #2 0x5611d298c4d6 in barrier_place_and_sync ../src/basic/barrier.h:73
    #3 0x5611d29967b1 in setup_pam ../src/core/execute.c:1300
    #4 0x5611d29b65ea in exec_child ../src/core/execute.c:3168
    #5 0x5611d29c2ac4 in exec_spawn ../src/core/execute.c:3627
    #6 0x5611d2aba9ab in service_spawn ../src/core/service.c:1538
    #7 0x5611d2ac10f5 in service_enter_start ../src/core/service.c:2038
    #8 0x5611d2ac1ca5 in service_enter_start_pre ../src/core/service.c:2104
    #9 0x5611d2ac64cf in service_start ../src/core/service.c:2350
    #10 0x5611d2b6fa15 in unit_start ../src/core/unit.c:1850
    #11 0x5611d29e9799 in job_perform_on_unit ../src/core/job.c:532
    #12 0x5611d29ea600 in job_run_and_invalidate ../src/core/job.c:596
    #13 0x5611d2a55801 in manager_dispatch_run_queue ../src/core/manager.c:2090
    #14 0x7fa98e4c6516 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3052
    #15 0x7fa98e4cc1a3 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3435
    #16 0x7fa98e4cd0e8 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3492
    #17 0x5611d2a5fbb3 in manager_loop ../src/core/manager.c:2849
    #18 0x5611d2943064 in invoke_main_loop ../src/core/main.c:1665
    #19 0x5611d2949f22 in main ../src/core/main.c:2455
    #20 0x7fa98b7ae11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #21 0x5611d2931549 in _start (/usr/lib/systemd/systemd+0x4b7549)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior
<unknown>: runtime error: signed integer overflow: 1 - -9223372036854775807 cannot be represented in type 'long int'
    #0 0x7fa98e1799e2 in barrier_they_aborted ../src/basic/barrier.h:59
    #1 0x7fa98e17af71 in barrier_read ../src/basic/barrier.c:213
    #2 0x7fa98e17bf27 in barrier_sync ../src/basic/barrier.c:396
    #3 0x5611d298c4d6 in barrier_place_and_sync ../src/basic/barrier.h:73
    #4 0x5611d29967b1 in setup_pam ../src/core/execute.c:1300
    #5 0x5611d29b65ea in exec_child ../src/core/execute.c:3168
    #6 0x5611d29c2ac4 in exec_spawn ../src/core/execute.c:3627
    #7 0x5611d2aba9ab in service_spawn ../src/core/service.c:1538
    #8 0x5611d2ac10f5 in service_enter_start ../src/core/service.c:2038
    #9 0x5611d2ac1ca5 in service_enter_start_pre ../src/core/service.c:2104
    #10 0x5611d2ac64cf in service_start ../src/core/service.c:2350
    #11 0x5611d2b6fa15 in unit_start ../src/core/unit.c:1850
    #12 0x5611d29e9799 in job_perform_on_unit ../src/core/job.c:532
    #13 0x5611d29ea600 in job_run_and_invalidate ../src/core/job.c:596
    #14 0x5611d2a55801 in manager_dispatch_run_queue ../src/core/manager.c:2090
    #15 0x7fa98e4c6516 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3052
    #16 0x7fa98e4cc1a3 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3435
    #17 0x7fa98e4cd0e8 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3492
    #18 0x5611d2a5fbb3 in manager_loop ../src/core/manager.c:2849
    #19 0x5611d2943064 in invoke_main_loop ../src/core/main.c:1665
    #20 0x5611d2949f22 in main ../src/core/main.c:2455
    #21 0x7fa98b7ae11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #22 0x5611d2931549 in _start (/usr/lib/systemd/systemd+0x4b7549)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior
```

**Comment by poettering** [comment]
I think #10366 should fix this. PTAL
