### ISSUE TITLE
UBSan seems to be complaining about a left shift of 1 by 31 places that cannot be represented in type 'int'

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10347]
```sh
$ UBSAN_OPTIONS=print_stacktrace=1 ./build/test-bus-creds
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
sd_bus_creds_new_from_pid: Success
  PID=21304  PPID=840  TTY=pts/0
  UID=1000  EUID=1000  SUID=1000  FSUID=1000  OwnerUID=1000  GID=1000  EGID=1000  SGID=1000  FSGID=1000  SupplementaryGIDs=1000 1002
  Comm=test-bus-creds  Exe=/home/vagrant/systemd/build/test-bus-creds
  CommandLine=./build/test-bus-creds  Label=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
  CGroup=/user.slice/user-1000.slice/session-1.scope  Unit=session-1.scope  Slice=user-1000.slice  UserUnit=n/a  UserSlice=-.slice  Session=1
  AuditLoginUID=1000  AuditSessionID=1
../src/libsystemd/sd-bus/bus-creds.c:664:75: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
    #0 0x7fc3c9018433 in has_cap ../src/libsystemd/sd-bus/bus-creds.c:664
    #1 0x7fc3c90186c0 in sd_bus_creds_has_effective_cap ../src/libsystemd/sd-bus/bus-creds.c:674
    #2 0x7fc3c902841b in dump_capabilities ../src/libsystemd/sd-bus/bus-dump.c:314
    #3 0x7fc3c902bd82 in bus_creds_dump ../src/libsystemd/sd-bus/bus-dump.c:493
    #4 0x557217a937d1 in main ../src/libsystemd/sd-bus/test-bus-creds.c:23
    #5 0x7fc3c75eb11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #6 0x557217a93409 in _start (/home/vagrant/systemd/build/test-bus-creds+0x1409)

  EffectiveCapabilities=
  PermittedCapabilities=
  InheritableCapabilities=
  BoundingCapabilities=cap_chown cap_dac_override cap_dac_read_search
          cap_fowner cap_fsetid cap_kill cap_setgid
          cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service
          cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock
          cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot
          cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot
          cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config
          cap_mknod cap_lease cap_audit_write cap_audit_control
          cap_setfcap cap_mac_override cap_mac_admin cap_syslog
          cap_wake_alarm cap_block_suspend cap_audit_read

```

**Comment by poettering** [comment]
Fix waiting in #10349
