### ISSUE TITLE
test-bus-gvariant seems to be failing under ASan when strict_string_checks=1 is used

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10385]
I haven't looked closely at it yet, but it most likely indicates that string functions are used to handle binary data somewhere:
```sh
$ ASAN_OPTIONS=strict_string_checks=1 ./build/test-bus-gvariant
...
(byte 0x6c, byte 0x01, byte 0x00, byte 0x02, uint32 0, uint64 4711, {uint64 1: <objectpath '/an/object/path/which/is/really/really/long/so/that/we/hit/the/eight/bit/boundary/by/quite/some/margin/to/test/this/stuff/that/it/really/works'>, 3: <'AMethodName'>, 2: <'an.interface.name'>, 6: <'a.service.name'>}, <([(uint32 4711, 'first-string-parameter', <('X', uint64 1111)>), (4712, 'second-string-parameter', <([('Y', 5), ('Z', 6)],)>), (4713, 'third-string-parameter', <(uint32 1, uint32 2)>)],)>)
=================================================================
==9410==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6140000003fc at pc 0x7f0cb7864a7d bp 0x7fffbed13900 sp 0x7fffbed130a8
READ of size 10 at 0x6140000003fc thread T0
    #0 0x7f0cb7864a7c  (/lib64/libasan.so.5+0xada7c)
    #1 0x7f0cb690e904 in free_and_strndup ../src/basic/string-util.c:1046
    #2 0x7f0cb69d9fc0 in bus_message_parse_fields ../src/libsystemd/sd-bus/bus-message.c:5094
    #3 0x7f0cb69a27e3 in bus_message_from_malloc ../src/libsystemd/sd-bus/bus-message.c:560
    #4 0x557643a79c0f in test_marshal ../src/libsystemd/sd-bus/test-bus-gvariant.c:196
    #5 0x557643a7a04d in main ../src/libsystemd/sd-bus/test-bus-gvariant.c:220
    #6 0x7f0cb4bdd11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #7 0x557643a77509 in _start (/home/vagrant/systemd/build/test-bus-gvariant+0x5509)

0x6140000003fc is located 0 bytes to the right of 444-byte region [0x614000000240,0x6140000003fc)
allocated by thread T0 here:
    #0 0x7f0cb78a5c48 in malloc (/lib64/libasan.so.5+0xeec48)
    #1 0x7f0cb69de14c in bus_message_get_blob ../src/libsystemd/sd-bus/bus-message.c:5463
    #2 0x557643a79a22 in test_marshal ../src/libsystemd/sd-bus/test-bus-gvariant.c:180
    #3 0x557643a7a04d in main ../src/libsystemd/sd-bus/test-bus-gvariant.c:220
    #4 0x7f0cb4bdd11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
```

**Comment by poettering** [comment]
Fix waiting in #10798
