### ISSUE TITLE
test-journal-match and test-journal-stream seem to be failing under ASan when strict_string_checks=1 is passed

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#10383]
```
$ ASAN_OPTIONS=strict_string_checks=1 ./build/test-journal-match
...
==6894==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000001f5 at pc 0x7f51c629da7d bp 0x7ffc05d56380 sp 0x7ffc05d55b28
READ of size 6 at 0x6020000001f5 thread T0
    #0 0x7f51c629da7c  (/lib64/libasan.so.5+0xada7c)
    #1 0x7f51c55e8549 in match_make_string ../src/journal/sd-journal.c:384
    #2 0x7f51c55e85d6 in match_make_string ../src/journal/sd-journal.c:389
    #3 0x7f51c55e85d6 in match_make_string ../src/journal/sd-journal.c:389
    #4 0x7f51c55e85d6 in match_make_string ../src/journal/sd-journal.c:389
    #5 0x7f51c55e85d6 in match_make_string ../src/journal/sd-journal.c:389
    #6 0x7f51c55e8862 in journal_make_match_string ../src/journal/sd-journal.c:420
    #7 0x5653c23bacb7 in main ../src/journal/test-journal-match.c:53
    #8 0x7f51c370f11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #9 0x5653c23b9f89 in _start (/home/vagrant/systemd/build/test-journal-match+0x1f89)

0x6020000001f5 is located 0 bytes to the right of 5-byte region [0x6020000001f0,0x6020000001f5)
allocated by thread T0 here:
    #0 0x7f51c62dec48 in malloc (/lib64/libasan.so.5+0xeec48)
    #1 0x7f51c51e6e47 in memdup ../src/basic/alloc-util.c:15
    #2 0x7f51c55e798a in sd_journal_add_match ../src/journal/sd-journal.c:319
    #3 0x5653c23bac56 in main ../src/journal/test-journal-match.c:51
    #4 0x7f51c370f11a in __libc_start_main (/lib64/libc.so.6+0x2311a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.5+0xada7c)

$ ASAN_OPTIONS=strict_string_checks=1 ./build/test-journal-stream
==6909==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000004bba at pc 0x7fe6a9e45a7d bp 0x7fff684ca030 sp 0x7fff684c97d8
READ of size 11 at 0x602000004bba thread T0
    #0 0x7fe6a9e45a7c  (/lib64/libasan.so.5+0xada7c)
    #1 0x7fe6a9190549 in match_make_string ../src/journal/sd-journal.c:384
    #2 0x7fe6a91905d6 in match_make_string ../src/journal/sd-journal.c:389
    #3 0x7fe6a91905d6 in match_make_string ../src/journal/sd-journal.c:389
    #4 0x7fe6a91905d6 in match_make_string ../src/journal/sd-journal.c:389
    #5 0x7fe6a91905d6 in match_make_string ../src/journal/sd-journal.c:389
    #6 0x7fe6a9190862 in journal_make_match_string ../src/journal/sd-journal.c:420
    #7 0x5586f425f8f0 in main ../src/journal/test-journal-stream.c:154
    #8 0x7fe6a72b711a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #9 0x5586f425dba9 in _start (/home/vagrant/systemd/build/test-journal-stream+0x2ba9)

0x602000004bba is located 0 bytes to the right of 10-byte region [0x602000004bb0,0x602000004bba)
allocated by thread T0 here:
    #0 0x7fe6a9e86c48 in malloc (/lib64/libasan.so.5+0xeec48)
    #1 0x7fe6a8d8ee47 in memdup ../src/basic/alloc-util.c:15
    #2 0x7fe6a918f98a in sd_journal_add_match ../src/journal/sd-journal.c:319
    #3 0x5586f425f889 in main ../src/journal/test-journal-stream.c:152
    #4 0x7fe6a72b711a in __libc_start_main (/lib64/libc.so.6+0x2311a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.5+0xada7c)
```

**Comment by poettering** [comment]
I prepped a fix n #10454, that incorporates your #10384, but adds one more fix on top. PTAL.
