### ISSUE TITLE
systemd-resolved crash on PID1 daemon-reload

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#10725]
With recent git master:
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fe5fedf7895 in __GI_abort () at abort.c:79
#2  0x00007fe5ff57deda in log_assert_failed_realm (realm=LOG_REALM_SYSTEMD, 
    text=0x7fe5ff6939af "close_nointr(fd) != -EBADF", file=0x7fe5ff693990 "../src/basic/fd-util.c", line=66, 
    func=0x7fe5ff693bd0 <__PRETTY_FUNCTION__.10061> "safe_close") at ../src/basic/log.c:805
#3  0x00007fe5ff5545c1 in safe_close (fd=0) at ../src/basic/fd-util.c:66
#4  0x000055c3a63b56ea in dns_stream_stop (s=0x55c3a7ca4790) at ../src/resolve/resolved-dns-stream.c:19
#5  0x000055c3a63b58f5 in dns_stream_complete (s=0x55c3a7ca4790, error=22)
    at ../src/resolve/resolved-dns-stream.c:60
#6  0x000055c3a63b6d6a in on_stream_io (es=0x55c3a7c9fa30, fd=19, revents=1, userdata=0x55c3a7ca4790)
    at ../src/resolve/resolved-dns-stream.c:415
#7  0x00007fe5ff642563 in source_dispatch (s=0x55c3a7c9fa30) at ../src/libsystemd/sd-event/sd-event.c:3012
#8  0x00007fe5ff643dc4 in sd_event_dispatch (e=0x55c3a7c8a8c0) at ../src/libsystemd/sd-event/sd-event.c:3425
#9  0x00007fe5ff644275 in sd_event_run (e=0x55c3a7c8a8c0, timeout=18446744073709551615)
    at ../src/libsystemd/sd-event/sd-event.c:3482
#10 0x00007fe5ff64442b in sd_event_loop (e=0x55c3a7c8a8c0) at ../src/libsystemd/sd-event/sd-event.c:3504
#11 0x000055c3a6375e43 in main (argc=1, argv=0x7ffdad4fe4a8) at ../src/resolve/resolved.c:96
```

```
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {17179888130, 0, 0, 0, 0, 0, 140727511089152, 0, 18446744073709551615, 0, 
            18446744073709551615, 0, 4294967295, 0, 141733920767, 140625801977728}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fe5fedf7895 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fe5ff693bd0 <__PRETTY_FUNCTION__.10061>, 
            sa_sigaction = 0x7fe5ff693bd0 <__PRETTY_FUNCTION__.10061>}, sa_mask = {__val = {283467841536, 
              140625809324432, 111669149696, 8573157680, 0, 140727511146576, 140625808187009, 0, 0, 0, 0, 0, 
              140625809344144, 140625809325008, 140625809324432, 140625809324463}}, sa_flags = 66, 
          sa_restorer = 0x7fe5ff6b58d8}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fe5ff57deda in log_assert_failed_realm (realm=LOG_REALM_SYSTEMD, 
    text=0x7fe5ff6939af "close_nointr(fd) != -EBADF", file=0x7fe5ff693990 "../src/basic/fd-util.c", line=66, 
    func=0x7fe5ff693bd0 <__PRETTY_FUNCTION__.10061> "safe_close") at ../src/basic/log.c:805
No locals.
#3  0x00007fe5ff5545c1 in safe_close (fd=0) at ../src/basic/fd-util.c:66
        _saved_errno_ = 0
        __PRETTY_FUNCTION__ = "safe_close"
#4  0x000055c3a63b56ea in dns_stream_stop (s=0x55c3a7ca4790) at ../src/resolve/resolved-dns-stream.c:19
        __PRETTY_FUNCTION__ = "dns_stream_stop"
#5  0x000055c3a63b58f5 in dns_stream_complete (s=0x55c3a7ca4790, error=22)
    at ../src/resolve/resolved-dns-stream.c:60
        __PRETTY_FUNCTION__ = "dns_stream_complete"
#6  0x000055c3a63b6d6a in on_stream_io (es=0x55c3a7c9fa30, fd=19, revents=1, userdata=0x55c3a7ca4790)
    at ../src/resolve/resolved-dns-stream.c:415
        s = 0x55c3a7ca4790
        r = -22
        __PRETTY_FUNCTION__ = "on_stream_io"
#7  0x00007fe5ff642563 in source_dispatch (s=0x55c3a7c9fa30) at ../src/libsystemd/sd-event/sd-event.c:3012
        saved_type = SOURCE_IO
        r = 0
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
#8  0x00007fe5ff643dc4 in sd_event_dispatch (e=0x55c3a7c8a8c0) at ../src/libsystemd/sd-event/sd-event.c:3425
        ref = 0x55c3a7c8a8c0
        p = 0x55c3a7c9fa30
        r = 32765
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
#9  0x00007fe5ff644275 in sd_event_run (e=0x55c3a7c8a8c0, timeout=18446744073709551615)
    at ../src/libsystemd/sd-event/sd-event.c:3482
        r = 1
        __PRETTY_FUNCTION__ = "sd_event_run"
#10 0x00007fe5ff64442b in sd_event_loop (e=0x55c3a7c8a8c0) at ../src/libsystemd/sd-event/sd-event.c:3504
        ref = 0x55c3a7c8a8c0
        r = 1
        __PRETTY_FUNCTION__ = "sd_event_loop"
--Type <RET> for more, q to quit, c to continue without paging--c
#11 0x000055c3a6375e43 in main (argc=1, argv=0x7ffdad4fe4a8) at ../src/resolve/resolved.c:96
        m = 0x55c3a7c88800
        user = 0x55c3a63d9360 "systemd-resolve"
        uid = 193
        gid = 193
        r = 0
        __func__ = "main"
        __PRETTY_FUNCTION__ = "main"
```

**Comment by poettering** [comment]
Is this reproducible in any way?

**Comment by keszybz** [comment]
I haven't seen it since. Let's close. If I see it again, I'll reopen.

**Comment by poettering** [comment]
So my educated guess is that #11055 fixes this, but I am not entirely sure. I can't reproduce the issue (I don't see how PID 1 could effect anything in resolved actually), though. 

If you can reproduce this, it would be greatly appreciated to get more info. Also, would be to test if it's still reproducible with #11055.

**Comment by poettering** [comment]
Anyway, setting "has-pr" as I am confident enough that #11055 fixes this.
