### ISSUE TITLE
fuzz-compress doesn't seem to fuzz anything

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#11018]
Judging by https://storage.googleapis.com/oss-fuzz-coverage/systemd/reports/20181130/linux/src/systemd/src/fuzz/fuzz-compress.c.html#L58, fuzz-compress has never got past `compress` on ClusterFuzz. I suspect that's because both `lz4` and `xz` are excluded when the fuzzers are built. It's possible to link `fuzz-compress` against either or them, but, as far as I know, they should be linked statically as per https://github.com/google/oss-fuzz/blob/9aa11dbd251f393eee0e5d199797d0293e69cd71/docs/fuzzer_environment.md#runtime-dependencies.

**Comment by evverx** [comment]
By the way, built with `lz4` it fails almost immediately with
```sh
#30083	NEW    cov: 36 ft: 38 corp: 7/175b lim: 33 exec/s: 0 rss: 106Mb L: 33/33 MS: 2 ShuffleBytes-CrossOver-
Assertion '*buffer_size == 0 || *buffer' failed at ../../src/systemd/src/journal/compress.c:299, function int decompress_startswith_lz4(const void *, uint64_t, void **, size_t *, const void *, size_t, uint8_t)(). Aborting.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000000b (pc 0x7f3941d8f428 bp 0x7ffdcd2753d0 sp 0x7ffdcd275268 T0)
SCARINESS: 10 (signal)
    #0 0x7f3941d8f427 in gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
    #1 0x7f3941d91029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
    #2 0x7f394303b40a in log_assert_failed_realm /work/build/../../src/systemd/src/basic/log.c:795:9
    #3 0x7f39431cb0a6 in decompress_startswith_lz4 /work/build/../../src/systemd/src/journal/compress.c:299:9
    #4 0x7f39431cb188 in decompress_startswith /work/build/../../src/systemd/src/journal/compress.c:356:24
    #5 0x530e51 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-compress.c:76:13
    #6 0x55c345 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:571:15
    #7 0x55a217 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:480:3
    #8 0x55e022 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:708:19
    #9 0x560fb6 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:839:5
    #10 0x53e131 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:764:6
    #11 0x5311ec in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #12 0x7f3941d7a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x41d0e8 in _start (/out/fuzz-compress+0x41d0e8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35427) in gsignal
```
and similarly built with `lzma` it crashes with
```
#21220	NEW    cov: 17 ft: 18 corp: 4/76b lim: 25 exec/s: 0 rss: 38Mb L: 25/25 MS: 1 ChangeBinInt-
Assertion '*buffer_size == 0 || *buffer' failed at ../../src/systemd/src/journal/compress.c:242, function int decompress_startswith_xz(const void *, uint64_t, void **, size_t *, const void *, size_t, uint8_t)(). Aborting.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000000b (pc 0x7f2d67291428 bp 0x7ffc51be19b0 sp 0x7ffc51be1848 T0)
SCARINESS: 10 (signal)
    #0 0x7f2d67291427 in gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
    #1 0x7f2d67293029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
    #2 0x7f2d6853d3ca in log_assert_failed_realm /work/build/../../src/systemd/src/basic/log.c:795:9
    #3 0x7f2d686cd6ba in decompress_startswith_xz /work/build/../../src/systemd/src/journal/compress.c:242:9
    #4 0x7f2d686cd797 in decompress_startswith /work/build/../../src/systemd/src/journal/compress.c:351:24
    #5 0x530e51 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-compress.c:76:13
    #6 0x55c345 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:571:15
    #7 0x55a217 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:480:3
    #8 0x55e022 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:708:19
    #9 0x560fb6 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:839:5
    #10 0x53e131 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:764:6
    #11 0x5311ec in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #12 0x7f2d6727c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x41d0e8 in _start (/out/fuzz-compress+0x41d0e8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35427) in gsignal
==11==ABORTING
```

**Comment by evverx** [comment]
I don't think it's ever going to actually fuzz anything. Closing.
