### ISSUE TITLE
UBSan seems to be complaining that "index 108 out of bounds for type 'char [108]'" in src/basic/socket-util.c

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#11024]
`test-socket-util` built with `clang-6.0.1-2` on Fedora 28 started to fail recently (most likely when 15dca3711da63ac5 was merged):
```
"" → "<unnamed>" (expect "<unnamed>")
"" → "@_________________________there\'s 108 characters in this string_____________________________________________" (expect "@_________________________there\'s 108 characters in this string_____________________________________________")
"////////////////////////////////////////////////////////////////////////////////////////////////////////////" → "////////////////////////////////////////////////////////////////////////////////////////////////////////////" (expect "////////////////////////////////////////////////////////////////////////////////////////////////////////////")
../src/basic/socket-util.c:678:37: runtime error: index 108 out of bounds for type 'char [108]'
    #0 0x7f20a925b526 in sockaddr_pretty /home/vagrant/systemd/build/../src/basic/socket-util.c:678:37
    #1 0x7f20a9258f71 in socket_address_print /home/vagrant/systemd/build/../src/basic/socket-util.c:382:16
    #2 0x55beefdaab73 in test_socket_print_unix_one /home/vagrant/systemd/build/../src/test/test-socket-util.c:133:9
    #3 0x55beefd9d408 in test_socket_print_unix /home/vagrant/systemd/build/../src/test/test-socket-util.c:153:9
    #4 0x55beefd9c030 in main /home/vagrant/systemd/build/../src/test/test-socket-util.c:802:9
    #5 0x7f20a7ab911a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #6 0x55beefca24c9 in _start (/home/vagrant/systemd/build/test-socket-util+0x294c9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/basic/socket-util.c:678:37 in
-------
```

**Comment by poettering** [comment]
Fix waiting in #11051
