### ISSUE TITLE
fuzz-bus-message seems to be crashing when strict_string_checks is set to 1

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#11070]
Now that I can run the fuzzers against the corpora [automatically](https://github.com/google/oss-fuzz/pull/2008), I managed to trigger the following crash by additionally passing `strict_string_checks=1`:
```
Running: /corpus/./fuzz-bus-message/d547ac75b79a8581c1fe9c04c6e75ed4c5008c82
=================================================================
==60==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60b0000006da at pc 0x0000004bb5ca bp 0x7ffc47804190 sp 0x7ffc47803940
READ of size 60 at 0x60b0000006da thread T0
SCARINESS: 26 (multi-byte-read-heap-buffer-overflow)
    #0 0x4bb5c9 in __interceptor___strndup /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:391
    #1 0x7f916b095055 in bus_message_parse_fields /work/build/../../src/systemd/src/libsystemd/sd-bus/bus-message.c:5192:31
    #2 0x7f916b09472c in bus_message_from_malloc /work/build/../../src/systemd/src/libsystemd/sd-bus/bus-message.c:559:13
    #3 0x530c64 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-bus-message.c:32:13
    #4 0x55c315 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:571:15
    #5 0x531b3d in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #6 0x53d386 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:713:9
    #7 0x5311bc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #8 0x7f9169d3882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x41d198 in _start (/out/fuzz-bus-message+0x41d198)

0x60b0000006da is located 0 bytes to the right of 106-byte region [0x60b000000670,0x60b0000006da)
allocated by thread T0 here:
    #0 0x4ebeef in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x7f916af8e103 in memdup /work/build/../../src/systemd/src/basic/alloc-util.c:15:15
    #2 0x530c17 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-bus-message.c:30:9
    #3 0x55c315 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:571:15
    #4 0x531b3d in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x53d386 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:713:9
    #6 0x5311bc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f9169d3882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:391 in __interceptor___strndup
Shadow bytes around the buggy address:
  0x0c167fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff80a0: fa fa 00 00 00 00 00 00 00 00 00 00 00 00 00 02
  0x0c167fff80b0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c167fff80c0: 00 00 00 00 00 02 fa fa fa fa fa fa fa fa 00 00
=>0x0c167fff80d0: 00 00 00 00 00 00 00 00 00 00 00[02]fa fa fa fa
  0x0c167fff80e0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c167fff80f0: fd fa fa fa fa fa fa fa fa fa fd fd fd fd fd fd
  0x0c167fff8100: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c167fff8110: fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa
  0x0c167fff8120: fa fa fa fa fa fa fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==60==ABORTING
```
I'll add corpus/./fuzz-bus-message/d547ac75b79a8581c1fe9c04c6e75ed4c5008c82 shortly.

**Comment by evverx** [comment]
I'm not sure if it's fixed or not but if it still fails with `strict_string_checks ` it just means that the parser can cut off some stuff losing data along the way. Nothing to worry about.
