### ISSUE TITLE
read_line crashes when it tries to read "\x0a\xff"

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#11218]
This was originally discovered on ClusterFuzz and reported in https://oss-fuzz.com/testcase?key=5685684531101696, https://oss-fuzz.com/testcase?key=5649277502619648 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11936. I'm duplicating it here so that it won't be released accidentally.

**Comment by evverx** [comment]
```
./build/fuzz-network-parser <(printf '\x0a\xff')
/dev/fd/63... Assertion 'ungetc(c, f) != EOF' failed at ../src/basic/fileio.c:760, function int read_line_full(FILE *, size_t, ReadLineFlags, char **)(). Aborting.
Aborted (core dumped)

(gdb) bt
#0  0x00007ffff5491eab in raise () from /lib64/libc.so.6
#1  0x00007ffff547c5b9 in abort () from /lib64/libc.so.6
#2  0x00007ffff61f2acb in log_assert_failed_realm (realm=LOG_REALM_SYSTEMD, text=0x7ffff677b740 <.str.32> "ungetc(c, f) != EOF", file=0x7ffff677b956 "../src/basic/fileio.c", line=760,
    func=0x7ffff677b6e0 <__PRETTY_FUNCTION__.read_line_full> "int read_line_full(FILE *, size_t, ReadLineFlags, char **)") at ../src/basic/log.c:795
#3  0x00007ffff619b61d in read_line_full (f=0x616000001b80, limit=1048576, flags=(unknown: 0), ret=0x7fffffffc660) at ../src/basic/fileio.c:760
#4  0x00007ffff5f26409 in read_line (f=0x616000001b80, limit=1048576, ret=0x7fffffffc660) at ../src/basic/fileio.h:71
#5  0x00007ffff5f24f9b in config_parse (unit=0x0, filename=0x7fffffffe0e0 "/tmp/fuzz-networkd.36WsUV", f=0x616000001b80, sections=0x5555559bb900 <.str.6> "Match",
    lookup=0x7ffff5f233c0 <config_item_perf_lookup>, table=0x555555743040 <network_network_gperf_lookup>, flags=CONFIG_PARSE_WARN, userdata=0x61c000000080) at ../src/shared/conf-parser.c:308
#6  0x00007ffff5f28551 in config_parse_many_files (conf_file=0x7fffffffe0e0 "/tmp/fuzz-networkd.36WsUV", files=0x602000000270, sections=0x5555559bb900 <.str.6> "Match",
    lookup=0x7ffff5f233c0 <config_item_perf_lookup>, table=0x555555743040 <network_network_gperf_lookup>, flags=CONFIG_PARSE_WARN, userdata=0x61c000000080) at ../src/shared/conf-parser.c:434
#7  0x00007ffff5f291ea in config_parse_many (conf_file=0x7fffffffe0e0 "/tmp/fuzz-networkd.36WsUV", conf_file_dirs=0x555555c34b80 <network_dirs>, dropin_dirname=0x7fffffffcf40 "fuzz-networkd.network.d",
    sections=0x5555559bb900 <.str.6> "Match", lookup=0x7ffff5f233c0 <config_item_perf_lookup>, table=0x555555743040 <network_network_gperf_lookup>, flags=CONFIG_PARSE_WARN, userdata=0x61c000000080)
    at ../src/shared/conf-parser.c:493
#8  0x00005555556f2bb0 in network_load_one (manager=0x613000000040, filename=0x7fffffffe0e0 "/tmp/fuzz-networkd.36WsUV") at ../src/network/networkd-network.c:208
#9  0x00005555556cae70 in LLVMFuzzerTestOneInput (data=0x602000000030 "\n\377", size=2) at ../src/network/fuzz-network-parser.c:23
#10 0x00005555556cb5ea in main (argc=2, argv=0x7fffffffe498) at ../src/fuzz/fuzz-main.c:39
```
