### ISSUE TITLE
There seems to be a memory leak in systemd-journald

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#11253]
It was originally discovered in https://github.com/systemd/systemd/pull/11252 (where I'm trying to use Ubuntu Xenial on Travis CI to run `systemd` under ASan to start catching issues like https://github.com/systemd/systemd/issues/11251):
```

562/726 fuzz-journald-native-fd:basic:address   FAIL     0.07 s (exit status 1)

--- command ---
/usr/bin/env /build/build/fuzz-journald-native-fd:address /build/test/fuzz/fuzz-journald-native-fd/basic
--- stdout ---
/build/test/fuzz/fuzz-journald-native-fd/basic... 
--- stderr ---
Found container virtualization none.

=================================================================
==27402==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 4 object(s) allocated from:
    #0 0x7fd9eb8637e0 in strdup (/lib/x86_64-linux-gnu/libasan.so.5+0x3a7e0)
    #1 0x7fd9eb3300bd in cg_pid_get_path ../../../../src/basic/cgroup-util.c:1064
    #2 0x7fd9eb3320ae in cg_pid_get_path_shifted ../../../../src/basic/cgroup-util.c:1411
    #3 0x560b24bba27a in client_context_read_cgroup ../../../../src/journal/journald-context.c:255
    #4 0x560b24bbceca in client_context_really_refresh ../../../../src/journal/journald-context.c:495
    #5 0x560b24bbe0b4 in client_context_get_internal ../../../../src/journal/journald-context.c:651
    #6 0x560b24bbe1a5 in client_context_get ../../../../src/journal/journald-context.c:665
    #7 0x560b24b87c1d in server_process_native_message ../../../../src/journal/journald-native.c:293
    #8 0x560b24b8888e in server_process_native_file ../../../../src/journal/journald-native.c:383
    #9 0x560b24b848ed in LLVMFuzzerTestOneInput ../../../../src/fuzz/fuzz-journald-native-fd.c:36
    #10 0x560b24b8554e in main ../../../../src/fuzz/fuzz-main.c:39
    #11 0x7fd9eacda09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 4 allocation(s).
-------
```
Given that I can't reproduce it on a "normal" xenial machine it looks like it has something to do with the cgroup layout being used there.

**Comment by evverx** [comment]
```
$ bash -xc 'grep cgroup /proc/self/mountinfo; cat /proc/self/cgroup; ls -la /sys/fs/cgroup'
+grep cgroup /proc/self/mountinfo
29 20 0:25 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
30 29 0:26 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
32 29 0:28 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,blkio
33 29 0:29 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,net_cls,net_prio
34 29 0:30 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,devices
35 29 0:31 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,pids
36 29 0:32 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,perf_event
37 29 0:33 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,rdma
38 29 0:34 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,cpu,cpuacct
39 29 0:35 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,freezer
40 29 0:36 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,memory
41 29 0:37 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,cpuset
42 29 0:38 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:23 - cgroup cgroup rw,hugetlb
+cat /proc/self/cgroup
12:hugetlb:/
11:cpuset:/
10:memory:/user.slice
9:freezer:/
8:cpu,cpuacct:/user.slice
7:rdma:/
6:perf_event:/
5:pids:/user.slice/user-2000.slice
4:devices:/user.slice
3:net_cls,net_prio:/
2:blkio:/user.slice
1:name=systemd:/user.slice/user-2000.slice/session-2.scope
0::/
+ls -la /sys/fs/cgroup
total 0
drwxr-xr-x 14 root root 360 Dec 23 10:58 .
drwxr-xr-x 10 root root   0 Dec 23 10:58 ..
dr-xr-xr-x  6 root root   0 Dec 23 10:58 blkio
lrwxrwxrwx  1 root root  11 Dec 23 10:58 cpu -> cpu,cpuacct
lrwxrwxrwx  1 root root  11 Dec 23 10:58 cpuacct -> cpu,cpuacct
dr-xr-xr-x  6 root root   0 Dec 23 10:58 cpu,cpuacct
dr-xr-xr-x  3 root root   0 Dec 23 10:58 cpuset
dr-xr-xr-x  6 root root   0 Dec 23 10:58 devices
dr-xr-xr-x  3 root root   0 Dec 23 10:58 freezer
dr-xr-xr-x  3 root root   0 Dec 23 10:58 hugetlb
dr-xr-xr-x  6 root root   0 Dec 23 10:58 memory
lrwxrwxrwx  1 root root  16 Dec 23 10:58 net_cls -> net_cls,net_prio
dr-xr-xr-x  3 root root   0 Dec 23 10:58 net_cls,net_prio
lrwxrwxrwx  1 root root  16 Dec 23 10:58 net_prio -> net_cls,net_prio
dr-xr-xr-x  3 root root   0 Dec 23 10:58 perf_event
dr-xr-xr-x  6 root root   0 Dec 23 10:58 pids
dr-xr-xr-x  2 root root   0 Dec 23 10:58 rdma
dr-xr-xr-x  6 root root   0 Dec 23 10:58 systemd
travis_time:end:159cd0c8:start=1545562887668646770,finish=1545562887680362157,duration=11715387
[0K[32;1mThe command "bash -xc 'grep cgroup /proc/self/mountinfo; cat /proc/self/cgroup; ls -la /sys/fs/cgroup'" exited with 0.[0m
```

**Comment by evverx** [comment]
```
+ grep cgroup /proc/self/mountinfo
169 168 0:55 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:97 - tmpfs tmpfs ro,mode=755
170 169 0:26 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:98 master:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
171 169 0:28 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:99 master:13 - cgroup cgroup rw,blkio
172 169 0:29 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:100 master:14 - cgroup cgroup rw,net_cls,net_prio
173 169 0:30 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:101 master:15 - cgroup cgroup rw,devices
174 169 0:31 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:102 master:16 - cgroup cgroup rw,pids
175 169 0:32 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:103 master:17 - cgroup cgroup rw,perf_event
176 169 0:33 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:104 master:18 - cgroup cgroup rw,rdma
177 169 0:34 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:105 master:19 - cgroup cgroup rw,cpu,cpuacct
178 169 0:35 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:106 master:20 - cgroup cgroup rw,freezer
179 169 0:36 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:107 master:21 - cgroup cgroup rw,memory
180 169 0:37 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:108 master:22 - cgroup cgroup rw,cpuset
181 169 0:38 /docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7 /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:109 master:23 - cgroup cgroup rw,hugetlb
117 169 0:57 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:110 - cgroup2 cgroup2 rw,nsdelegate
+ cat /proc/self/cgroup
12:hugetlb:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
11:cpuset:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
10:memory:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
9:freezer:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
8:cpu,cpuacct:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
7:rdma:/
6:perf_event:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
5:pids:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
4:devices:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
3:net_cls,net_prio:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
2:blkio:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
1:name=systemd:/docker/9d60b656a6173fa28f54d59ba4d579a55d4429190c4054b50df64eba5c3052d7
0::/
+ ls -la /sys/fs/cgroup
total 0
dr-xr-xr-x 15 root root 380 Dec 23 10:59 .
drwxr-xr-x 10 root root   0 Dec 23 11:01 ..
drwxr-xr-x  2 root root   0 Dec 23 10:59 blkio
lrwxrwxrwx  1 root root  11 Dec 23 10:59 cpu -> cpu,cpuacct
drwxr-xr-x  2 root root   0 Dec 23 10:59 cpu,cpuacct
lrwxrwxrwx  1 root root  11 Dec 23 10:59 cpuacct -> cpu,cpuacct
drwxr-xr-x  2 root root   0 Dec 23 10:59 cpuset
drwxr-xr-x  3 root root   0 Dec 23 10:59 devices
drwxr-xr-x  2 root root   0 Dec 23 10:59 freezer
drwxr-xr-x  2 root root   0 Dec 23 10:59 hugetlb
drwxr-xr-x  3 root root   0 Dec 23 10:59 memory
lrwxrwxrwx  1 root root  16 Dec 23 10:59 net_cls -> net_cls,net_prio
drwxr-xr-x  2 root root   0 Dec 23 10:59 net_cls,net_prio
lrwxrwxrwx  1 root root  16 Dec 23 10:59 net_prio -> net_cls,net_prio
drwxr-xr-x  2 root root   0 Dec 23 10:59 perf_event
drwxr-xr-x  3 root root   0 Dec 23 10:59 pids
dr-xr-xr-x  2 root root   0 Dec 23 11:01 rdma
drwxr-xr-x  3 root root   0 Dec 23 10:59 systemd
dr-xr-xr-x  3 root root   0 Dec 23 10:59 unified
```

**Comment by evverx** [comment]
I fixed it in https://github.com/systemd/systemd/pull/11252 with
```diff
diff --git a/src/journal/journald-context.c b/src/journal/journald-context.c
index 8253a4512..2d711bc82 100644
--- a/src/journal/journald-context.c
+++ b/src/journal/journald-context.c
@@ -246,7 +246,7 @@ static int client_context_read_label(
 }

 static int client_context_read_cgroup(Server *s, ClientContext *c, const char *unit_id) {
-        char *t = NULL;
+        _cleanup_free_ char *t = NULL;
         int r;

         assert(c);
@@ -254,7 +254,6 @@ static int client_context_read_cgroup(Server *s, ClientContext *c, const char *u
         /* Try to acquire the current cgroup path */
         r = cg_pid_get_path_shifted(c->pid, s->cgroup_root, &t);
         if (r < 0 || empty_or_root(t)) {
-
                 /* We use the unit ID passed in as fallback if we have nothing cached yet and cg_pid_get_path_shifted()
                  * failed or process is running in a root cgroup. Zombie processes are automatically migrated to root cgroup
                  * on cgroupsv1 and we want to be able to map log messages from them too. */
@@ -268,10 +267,8 @@ static int client_context_read_cgroup(Server *s, ClientContext *c, const char *u
         }

         /* Let's shortcut this if the cgroup path didn't change */
-        if (streq_ptr(c->cgroup, t)) {
-                free(t);
+        if (streq_ptr(c->cgroup, t))
                 return 0;
-        }

         free_and_replace(c->cgroup, t);
```

**Comment by evverx** [comment]
In case anyone is interested the leak can be reproduced reliably by moving the pid of `bash` (or whatever else is used to run the test) into the root cgroup by writing it to, for example, `/sys/fs/cgroup/unified/cgroup.procs` if the hybrid hierarchy is used.
