### ISSUE TITLE
nss-resolve: PROTECT_ERRNO macro interfers with glibc logic to retry queries with a larger buffer

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#11321]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > Successful result of getaddrinfo call

**Unexpected behaviour you saw**
 > getaddrinfo returns -11

**Steps to reproduce the problem**
I found that I could no longer use `smbclient` to connect to shares in my AD domain.

```
$ smbclient  -d 3 -U user@ad.domain.example //ad.domain.example/share
...
resolve_hosts: Attempting host lookup for name ad.domain.example<0x20>
resolve_hosts: getaddrinfo failed for name ad.domain.example [System error]

$ ltrace getent ahosts ad.domain.example
...
getaddrinfo("ad.domain.example", nil, 0x7ffc9d377a10, 0x7ffc9d377a08) = -11
+++ exited (status 2) +++
```

Now weirdly `getent ahostsv{4,6} ad.domain.example` both work. This domain has a lot of domain controllers, and I've had problems running into size limits with it in the past (#10264). And I think that's what is going on here. glibc expects the NSS module to set errno to ERANGE and return NSS_TRY_AGAIN, which we're doing:

```
$ gdb --args getent ahosts ad.domain.example
...
(gdb) where
#0  0x00007ffff764a1cd in _nss_resolve_gethostbyname4_r (name=name@entry=0x5555555631b0 "ad.domain.example, pat=pat@entry=0x7fffffffd688, buffer=0x7fffffffd910 "", buflen=1024, errnop=errnop@entry=0x7ffff7fa74c0, h_errnop=h_errnop@entry=0x7ffff7fa7524, ttlp=0x0) at ../src/nss-resolve/nss-resolve.c:191
#1  0x00007ffff7ec8192 in gaih_inet (name=<optimized out>, name@entry=0x7fffffffe336 "ad.domain.example", service=<optimized out>, req=req@entry=0x7fffffffdd90, pai=pai@entry=0x7fffffffd898, naddrs=naddrs@entry=0x7fffffffd894, tmpbuf=tmpbuf@entry=0x7fffffffd900) at ../sysdeps/posix/getaddrinfo.c:770
#2  0x00007ffff7ec9194 in __GI_getaddrinfo (name=<optimized out>, service=<optimized out>, hints=0x7fffffffdd90, pai=0x7fffffffdd88) at ../sysdeps/posix/getaddrinfo.c:2265
#3  0x00005555555590da in  ()
#4  0x000055555555771c in  ()
#5  0x00007ffff7e0909b in __libc_start_main (main=0x555555557630, argc=3, argv=0x7fffffffdf98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf88) at ../csu/libc-start.c:308
#6  0x00005555555577ea in  ()
```

The topmost frame being:

```
        l = strlen(canonical);
        ms = ALIGN(l+1) + ALIGN(sizeof(struct gaih_addrtuple)) * c;
        if (buflen < ms) {
                *errnop = ERANGE;
                *h_errnop = NETDB_INTERNAL;
                return NSS_STATUS_TRYAGAIN; // ← here
        }
```

Accordingly:

```
(gdb) p buflen 
$20 = 1024

(gdb) p c
$21 = 32

(gdb) p ms
$22 = 1296
```

So the 32 results won't fit into the buffer passed by glibc. We're setting `errno` to `ERANGE` so that glibc retries with a larger buffer. But `PROTECT_ERRNO` added in 06202b9e659e5cc72aeecc5200155b7c012fccbc causes it to be reset to something else on the way out of `_nss_resolve_gethostbyname4_r`:

```
(gdb) n
189	                *errnop = ERANGE;

(gdb) display *errnop
1: *errnop = 11

(gdb) display *h_errnop
2: *h_errnop = 3

(gdb) n
190	                *h_errnop = NETDB_INTERNAL;
1: *errnop = 34
2: *h_errnop = 3

(gdb) n
191	                return NSS_STATUS_TRYAGAIN;
1: *errnop = 34
2: *h_errnop = -1

(gdb) n
126	        BLOCK_SIGNALS(NSS_SIGNALS_BLOCK);
1: *errnop = 34
2: *h_errnop = -1

(gdb) n
125	        PROTECT_ERRNO;
1: *errnop = 34
2: *h_errnop = -1

(gdb) n
118	        _cleanup_(sd_bus_flush_close_unrefp) sd_bus *bus = NULL;
1: *errnop = 22
2: *h_errnop = -1
```

**Comment by poettering** [comment]
@yuwata hmm, you reopened this issue? what's there left to fix that #11395 didn't address?
