### ISSUE TITLE
There seems to be a memory leak in udevadm

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#11966]
```
+ udevadm trigger --action=move --settle /sys/devices/virtual/net/lo

=================================================================
==320==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 28 byte(s) in 1 object(s) allocated from:
    #0 0x7f589b146320 in strdup (/usr/lib64/libasan.so.5.0.0+0x3b320)
    #1 0x7f589a19dc36 in set_put_strdup ../src/basic/hashmap.c:1775
    #2 0x418c54 in exec_list ../src/udev/udevadm-trigger.c:53
    #3 0x41c7b0 in trigger_main ../src/udev/udevadm-trigger.c:372
    #4 0x7f589a102c99 in dispatch_verb ../src/shared/verbs.c:119
    #5 0x40c3c8 in udevadm_main ../src/udev/udevadm.c:107
    #6 0x40c438 in run ../src/udev/udevadm.c:124
    #7 0x40c45a in main ../src/udev/udevadm.c:127
    #8 0x7f5897f3611a in __libc_start_main (/lib64/libc.so.6+0x2311a)

SUMMARY: AddressSanitizer: 28 byte(s) leaked in 1 allocation(s).
```

**Comment by yuwata** [comment]
Fix is waiting in #11969.
