### ISSUE TITLE
getpwnam_r segmentation fault when run from a statically compiled program

### ISSUE THREAD

**Issue by prashanthjbabu** [systemd/systemd#11970]
**systemd version the issue has been seen with**
> 237

**Used distribution**
 > ubuntu 18.04

**Expected behaviour you didn't see**
 > getpwnam_r returning user info

**Unexpected behaviour you saw**
 > segmentation fault

**Steps to reproduce the problem**

1.  Use the following gist https://gist.github.com/prashanthjbabu/123956cb2455924c41161eb222cffcc8
2.  Compile the code statically " cc main.c -static"
3. Run for an non-existant user "USERNAME=rowot ./a.out"
4. A segmentation fault will be seen.

```
Stack trace is : 
(gdb) run
Starting program: /tmp/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6e28c2d in is_main_thread () at ../src/basic/process-util.c:992
992	        if (_unlikely_(cached == 0))
(gdb) bt
#0  0x00007ffff6e28c2d in is_main_thread () at ../src/basic/process-util.c:992
#1  0x00007ffff6e1d261 in mempool_enabled () at ../src/basic/mempool.c:78
#2  0x00007ffff6e0f81b in hashmap_base_new (hash_ops=0x7ffff708f240 <uint64_hash_ops>, type=HASHMAP_TYPE_ORDERED) at ../src/basic/hashmap.c:774
#3  0x00007ffff6e0f9d4 in hashmap_base_ensure_allocated (h=0x7ffff76c3268, hash_ops=0x7ffff708f240 <uint64_hash_ops>, type=HASHMAP_TYPE_ORDERED) at ../src/basic/hashmap.c:829
#4  0x00007ffff6e0fa4a in internal_ordered_hashmap_ensure_allocated (h=0x7ffff76c3268, hash_ops=0x7ffff708f240 <uint64_hash_ops>) at ../src/basic/hashmap.c:842
#5  0x00007ffff6dc3fa8 in sd_bus_call_async (bus=0x7ffff76c31a0, slot=0x0, _m=0x7ffff76c3b30, callback=0x7ffff6dbeb61 <hello_callback>, userdata=0x0, usec=0)
    at ../src/libsystemd/sd-bus/sd-bus.c:2051
#6  0x00007ffff6dbee04 in bus_send_hello (bus=0x7ffff76c31a0) at ../src/libsystemd/sd-bus/sd-bus.c:580
#7  0x00007ffff6dc0d44 in sd_bus_start (bus=0x7ffff76c31a0) at ../src/libsystemd/sd-bus/sd-bus.c:1195
#8  0x00007ffff6dc117d in sd_bus_open_system_with_description (ret=0x7fffffffdea0, description=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:1293
#9  0x00007ffff6dc11f1 in sd_bus_open_system (ret=0x7fffffffdea0) at ../src/libsystemd/sd-bus/sd-bus.c:1302
#10 0x00007ffff6d992ea in _nss_systemd_getpwnam_r (name=0x7fffffffeeae "wwww", pwd=0x7fffffffe0b0, buffer=0x7fffffffe0e0 "ubuntu", buflen=1024, errnop=0x6ca840)
    at ../src/nss-systemd/nss-systemd.c:178
#11 0x000000000044938f in getpwnam_r ()
#12 0x0000000000400bc6 in main ()
```

**Comment by yuwata** [comment]
I guess this is already fixed in v240 by a5d8835c78112206bbf0812dd4cb471f803bfe88.

**Comment by yuwata** [comment]
So, please test v240 or newer. If newer release still has this issue, then please report again. Thank you.

**Comment by yuwata** [comment]
Note that the original report is in PR #10021. It is not for nss, but the root of the issues are the same.
