### ISSUE TITLE
ids_parser.py is broken with pyparsing-2.3

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#12021]
Gentoo bug report: https://bugs.gentoo.org/679876

Running ids_parser.py with pyparsing-2.3.0 or 2.3.1 installed produces the following error. Downgrading to pyparsing-2.2 makes it work again.

```
Traceback (most recent call last):
  File "ids_parser.py", line 347, in <module>
    usb_vendor_model(p)
  File "ids_parser.py", line 129, in usb_vendor_model
    vendor = vendor_group.VENDOR.vendor.upper()
AttributeError: 'str' object has no attribute 'vendor'
```

**Comment by floppym** [comment]
I added some debug code to dump the data after parsing, and ran it for the first entry in usb.ids with pyparsing-2.2.2 and pyparsing-2.3.1.
```
floppym@naomi hwids % PYTHONPATH=/home/floppym/tmp/pyparsing-2.2.2 python3 ids_parser.py usb
['0001', "Fry's Electronics", '7778', 'Counterfeit flash drive [Kingston]']
- VENDOR: ['0001', "Fry's Electronics"]
  - text: "Fry's Electronics"
  - vendor: '0001'
- VENDORS: [['0001', "Fry's Electronics", '7778', 'Counterfeit flash drive [Kingston]']]
  [0]:
    ['0001', "Fry's Electronics", '7778', 'Counterfeit flash drive [Kingston]']
    - VENDOR: ['0001', "Fry's Electronics"]
      - text: "Fry's Electronics"
      - vendor: '0001'
    - VENDOR_DEV: [['7778', 'Counterfeit flash drive [Kingston]']]
      [0]:
        ['7778', 'Counterfeit flash drive [Kingston]']
        - device: '7778'
        - text: 'Counterfeit flash drive [Kingston]'
    - device: '7778'
    - text: 'Counterfeit flash drive [Kingston]'
    - vendor: '0001'
- VENDOR_DEV: [['7778', 'Counterfeit flash drive [Kingston]']]
  [0]:
    ['7778', 'Counterfeit flash drive [Kingston]']
    - device: '7778'
    - text: 'Counterfeit flash drive [Kingston]'
- device: '7778'
- text: 'Counterfeit flash drive [Kingston]'
- vendor: '0001'

floppym@naomi hwids % PYTHONPATH=/home/floppym/tmp/pyparsing-2.3.1 python3 ids_parser.py usb
['0001', "Fry's Electronics", '7778', 'Counterfeit flash drive [Kingston]']
- VENDOR: ['0001', "Fry's Electronics"]
- VENDORS: [['0001', "Fry's Electronics", '7778', 'Counterfeit flash drive [Kingston]']]
  [0]:
    ['0001', "Fry's Electronics", '7778', 'Counterfeit flash drive [Kingston]']
- VENDOR_DEV: [['7778', 'Counterfeit flash drive [Kingston]']]
  [0]:
    ['7778', 'Counterfeit flash drive [Kingston]']
- device: '7778'
- text: 'Counterfeit flash drive [Kingston]'
- vendor: '0001'
```
