### ISSUE TITLE
Systemd-resolved dumps core when dns-over-tls enabled

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#12187]
**systemd version the issue has been seen with**
> systemd 241 (241.67-1-arch)

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Normal behavior. Resolving all the hosts. Being stable.

**Unexpected behaviour you saw**
 > systemd-resolved frequently fails to resolve hosts, crashes and dumps core.

**Steps to reproduce the problem**
Configure as follows:
```
    LLMNR setting: yes
    MulticastDNS setting: no
    DNSOverTLS setting: opportunistic
    DNSSEC setting: allow-downgrade
    DNSSEC supported: yes
```

Also when DNS over TLS is enabled it starts to spam log with something like:
> мар 20 17:42:34 SpectreArch systemd-resolved[587]: DNSSEC validation failed for question locprod1-elb-eu-west-1.prod.mozaws.net IN A: failed-auxiliary
> мар 20 17:42:34 SpectreArch audit[587]: ANOM_ABEND auid=4294967295 uid=980 gid=980 ses=4294967295 pid=587 comm="systemd-resolve" exe="/usr/lib/systemd/systemd-resolved" sig=6 res=1
> мар 20 17:42:34 SpectreArch systemd-resolved[587]: DNSSEC validation failed for question weather.gov.edgekey.net IN SOA: failed-auxiliary
> мар 20 17:42:34 SpectreArch systemd-resolved[587]: DNSSEC validation failed for question sancert.weather.gov.edgekey.net IN A: failed-auxiliary
> мар 20 17:42:34 SpectreArch systemd-resolved[587]: Assertion '*_head == _item' failed at ../systemd-stable/src/resolve/resolved-dns-transaction.c:93, function dns_transaction_free(). Aborting.

And it crashes some time after.

If I disable DNS Over TLS, "DNSSEC supported" also changes to "no" and DNSSEC validation errors disappear too, obviously.

[systemd-resolved.coredump.txt](https://github.com/systemd/systemd/files/3033794/systemd-resolved.coredump.txt)

**Comment by poettering** [comment]
Please update to v242. Thanks!

**Comment by poettering** [comment]
(resolved received a fix fixing an issue liek the one you describe in v242, that#s why. Most likely the issue is already fixed. If now, please reopen)

**Comment by Unb9rn** [comment]
Seems like the issue is still here with v242...
```
coredumpctl gdb  
           PID: 457 (systemd-resolve)
           UID: 980 (systemd-resolve)
           GID: 980 (systemd-resolve)
        Signal: 6 (ABRT)
     Timestamp: Thu 2019-04-18 11:28:40 +04 (5min ago)
  Command Line: /usr/lib/systemd/systemd-resolved
    Executable: /usr/lib/systemd/systemd-resolved
 Control Group: /system.slice/systemd-resolved.service
          Unit: systemd-resolved.service
         Slice: system.slice
       Boot ID: 392c0646fc1e41b4be6ccab2ca2cbe22
    Machine ID: 2eacdec89cd848c490e2abbe30d129ae
      Hostname: SpectreArch
       Storage: /var/lib/systemd/coredump/core.systemd-resolve.980.392c0646fc1e41b4be6ccab2ca2cbe22.457.1555572520000000.lz4
       Message: Process 457 (systemd-resolve) of user 980 dumped core.
                
                Stack trace of thread 457:
                #0  0x00007f81c1dd1d7f raise (libc.so.6)
                #1  0x00007f81c1dbc672 abort (libc.so.6)
                #2  0x00007f81c1b4902c n/a (libsystemd-shared-242.so)
                #3  0x000055e550273f7e n/a (systemd-resolved)
                #4  0x000055e550274271 n/a (systemd-resolved)
                #5  0x000055e550276088 n/a (systemd-resolved)
                #6  0x000055e550276821 n/a (systemd-resolved)
                #7  0x000055e5502640bb n/a (systemd-resolved)
                #8  0x00007f81c1b7984e n/a (libsystemd-shared-242.so)
                #9  0x00007f81c1b79b23 sd_event_dispatch (libsystemd-shared-242.so)
                #10 0x00007f81c1b79ce9 sd_event_run (libsystemd-shared-242.so)
                #11 0x00007f81c1b79f0c sd_event_loop (libsystemd-shared-242.so)
                #12 0x000055e55024d441 n/a (systemd-resolved)
                #13 0x00007f81c1dbe223 __libc_start_main (libc.so.6)
                #14 0x000055e55024ddee n/a (systemd-resolved)

GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/systemd/systemd-resolved...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 457]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/lib/systemd/systemd-resolved'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f81c1dd1d7f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f81c1dd1d7f in raise () from /usr/lib/libc.so.6
#1  0x00007f81c1dbc672 in abort () from /usr/lib/libc.so.6
#2  0x00007f81c1b4902c in ?? () from /usr/lib/systemd/libsystemd-shared-242.so
#3  0x000055e550273f7e in ?? ()
#4  0x000055e550274271 in ?? ()
#5  0x000055e550276088 in ?? ()
#6  0x000055e550276821 in ?? ()
#7  0x000055e5502640bb in ?? ()
#8  0x00007f81c1b7984e in ?? () from /usr/lib/systemd/libsystemd-shared-242.so
#9  0x00007f81c1b79b23 in sd_event_dispatch () from /usr/lib/systemd/libsystemd-shared-242.so
#10 0x00007f81c1b79ce9 in sd_event_run () from /usr/lib/systemd/libsystemd-shared-242.so
#11 0x00007f81c1b79f0c in sd_event_loop () from /usr/lib/systemd/libsystemd-shared-242.so
#12 0x000055e55024d441 in ?? ()
#13 0x00007f81c1dbe223 in __libc_start_main () from /usr/lib/libc.so.6
#14 0x000055e55024ddee in ?? ()

```
Can someone please reopen this?
