### ISSUE TITLE
test-cpu-set-util is failing under ASan on i386

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#12723]
```sh
$ ./build/test-cpu-set-util

/* test_cpu_set_to_from_dbus */
cpu_set_to_string: 1 3 8 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200
=================================================================
==3122==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xb4500b9c at pc 0xb72447a0 bp 0xbff4cad8 sp 0xbff4c6b0
READ of size 32 at 0xb4500b9c thread T0
    #0 0xb724479f in __interceptor_memcmp (/usr/lib/i386-linux-gnu/libasan.so.3+0x8f79f)
    #1 0x412940 in test_cpu_set_to_from_dbus ../src/test/test-cpu-set-util.c:255
    #2 0x4132eb in main ../src/test/test-cpu-set-util.c:283
    #3 0xb5e9f285 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18285)
    #4 0x40d470  (/home/vagrant/systemd/build/test-cpu-set-util+0x3470)

0xb4500b9c is located 0 bytes to the right of 28-byte region [0xb4500b80,0xb4500b9c)
allocated by thread T0 here:
    #0 0xb7273324 in __interceptor_calloc (/usr/lib/i386-linux-gnu/libasan.so.3+0xbe324)
    #1 0xb676781a in cpu_set_to_dbus ../src/shared/cpu-set-util.c:259
    #2 0x412861 in test_cpu_set_to_from_dbus ../src/test/test-cpu-set-util.c:251
    #3 0x4132eb in main ../src/test/test-cpu-set-util.c:283
    #4 0xb5e9f285 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18285)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/i386-linux-gnu/libasan.so.3+0x8f79f) in __interceptor_memcmp
Shadow bytes around the buggy address:
  0x368a0120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a0130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a0140: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a0150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a0160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x368a0170: 00 00 00[04]fa fa 00 00 00 04 fa fa 00 00 00 01
  0x368a0180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a0190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a01a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a01b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x368a01c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3122==ABORTING
```

**Comment by keszybz** [comment]
Should be fixed by a299ce058b41b21c87f36e77e2c563b0ddd1be0d.
