### ISSUE TITLE
There seems to be a stack-buffer-overflow in networkctl

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#12730]
```
test_delete_links (__main__.NetworkctlTests) ...
=================================================================
=================================================================
==20721==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffeb5145960 at pc 0x7f3bd72769c6 bp 0x7ffeb5145840 sp 0x7ffeb5145830
WRITE of size 8 at 0x7ffeb5145960 thread T0
    #0 0x7f3bd72769c5 in internal_hashmap_iterate ../src/basic/hashmap.c:724
    #1 0x7f3bd7276aae in set_iterate ../src/basic/hashmap.c:732
    #2 0x4193ec in link_delete ../src/network/networkctl.c:1555
    #3 0x7f3bd71e0dcc in dispatch_verb ../src/shared/verbs.c:119
    #4 0x419813 in networkctl_main ../src/network/networkctl.c:1670
    #5 0x4198e7 in run ../src/network/networkctl.c:1694
    #6 0x41991a in main ../src/network/networkctl.c:1697
    #7 0x7f3bd5c3e412 in __libc_start_main (/lib64/libc.so.6+0x24412)
    #8 0x404b7d in _start (/home/vagrant/systemd/build/networkctl+0x404b7d)

Address 0x7ffeb5145960 is located in stack of thread T0 at offset 32 in frame
    #0 0x418a36 in link_delete ../src/network/networkctl.c:1531

  This frame has 5 object(s):
    [32, 36) 'index' <== Memory access at offset 32 partially overflows this variable
    [96, 104) 'rtnl'
    [160, 168) 'indexes'
    [224, 240) 'j'
    [288, 305) 'ifname'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow ../src/basic/hashmap.c:724 in internal_hashmap_iterate
Shadow bytes around the buggy address:
  0x100056a20ad0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056a20ae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056a20af0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056a20b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056a20b10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100056a20b20: 00 00 00 00 00 00 00 00 f1 f1 f1 f1[04]f2 f2 f2
  0x100056a20b30: f2 f2 f2 f2 00 f2 f2 f2 f2 f2 f2 f2 00 f2 f2 f2
  0x100056a20b40: f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00 01 f2
  0x100056a20b50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056a20b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x100056a20b70: f1 f1 00 00 f2 f2 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==20721==ABORTING
ERROR
```

**Comment by keszybz** [comment]
Index is a 32 bit variable, and we're writing a 64 bit pointer to it. So yeah, it seems @yuwata's PR should fix this.
