### ISSUE TITLE
test-format-util seems to be failing on i386

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#12891]
Yesterday I tried to turn on bionic-i386 (now that https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1829829 is fixed) and got [the following](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/i386/s/systemd-upstream/20190625_234503_1f5f5@/log.gz):
```
293/497 test-format-util                        FAIL     0.17 s (killed by signal 6 SIGABRT)
--- command ---
PATH='/tmp/autopkgtest.zuX05u/build.QqJ/systemd/build-deb:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games' SYSTEMD_KBD_MODEL_MAP='/tmp/autopkgtest.zuX05u/build.QqJ/systemd/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/tmp/autopkgtest.zuX05u/build.QqJ/systemd/src/locale/language-fallback-map' /tmp/autopkgtest.zuX05u/build.QqJ/systemd/build-deb/test-format-util
--- stderr ---
Assertion 'streq_ptr(format_bytes_full(buf, sizeof buf, val, FORMAT_BYTES_USE_IEC | FORMAT_BYTES_BELOW_POINT | (trailing_B ? FORMAT_BYTES_TRAILING_B : 0)), iec_with_p)' failed at ../src/test/test-format-util.c:11, function test_format_bytes_one(). Aborting.
-------
```

As far as I can tell, it fails because "3T" can't fit into `size_t` on i386:
```
#0  0xb7fd9cf9 in __kernel_vsyscall ()
#1  0xb6bccdd0 in __libc_signal_restore_set (set=0xbffff310) at ../sysdeps/unix/sysv/linux/nptl-signals.h:79
#2  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb6bce297 in __GI_abort () at abort.c:89
#4  0xb717eaea in log_assert_failed_realm (realm=LOG_REALM_SYSTEMD,
    text=0x401300 "streq_ptr(format_bytes_full(buf, sizeof buf, val, FORMAT_BYTES_USE_IEC | FORMAT_BYTES_BELOW_POINT | (trailing_B ? FORMAT_BYTES_TRAILING_B : 0)), iec_with_p)",
    file=0x4012c0 "../src/test/test-format-util.c", line=11, func=0x401be0 <__PRETTY_FUNCTION__.3935> "test_format_bytes_one") at ../src/basic/log.c:795
#5  0x00400d0b in test_format_bytes_one (val=0, trailing_B=true, iec_with_p=0x401a20 "3.0T", iec_without_p=0x4019a0 "3T", non_iec_with_p=0x4019e0 "3.2T", non_iec_without_p=0x4019a0 "3T")
    at ../src/test/test-format-util.c:11
#6  0x004010c5 in test_format_bytes () at ../src/test/test-format-util.c:28
#7  0x0040115b in main () at ../src/test/test-format-util.c:35
```

**Comment by evverx** [comment]
@iainlane judging by http://autopkgtest.ubuntu.com/running#pkg-systemd-upstream, it seems Ubuntu CI keeps running the tests for [PR 12618](https://github.com/systemd/systemd/pull/12618), which was merged about a month ago. Could you stop it?
