### ISSUE TITLE
systemd/fuzz-network-parser: Direct-leak in memdup

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#12995]
This one was reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15678.
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
  | #0 0x49f5ed in __interceptor_malloc _asan_rtl_:3
  | #1 0x7f0e6aaad428 in memdup systemd/src/basic/alloc-util.c:16:15
  | #2 0x58f523 in config_parse_ndisc_black_listed_prefix systemd/src/network/networkd-ndisc.c:771:21
  | #3 0x7f0e6a9eed1e in next_assignment systemd/src/shared/conf-parser.c:133:32
  | #4 0x7f0e6a9e9d16 in parse_line systemd/src/shared/conf-parser.c:258:16
  | #5 0x7f0e6a9e8c41 in config_parse systemd/src/shared/conf-parser.c:379:21
  | #6 0x7f0e6a9ea4a0 in config_parse_many_files systemd/src/shared/conf-parser.c:436:21
  | #7 0x7f0e6a9ea970 in config_parse_many systemd/src/shared/conf-parser.c:495:16
  | #8 0x4e58c8 in network_load_one systemd/src/network/networkd-network.c:418:13
  | #9 0x4d190d in LLVMFuzzerTestOneInput systemd/src/network/fuzz-network-parser.c:26:16
  | #10 0x651890 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:553:15
  | #11 0x60767f in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:292:6
  | #12 0x614464 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:775:9
  | #13 0x606cd7 in main /src/libfuzzer/FuzzerMain.cpp:19:10
  | #14 0x7f0e697e482f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/libc-start.c:291
```
cc @yuwata @ssahani

**Comment by evverx** [comment]
Just to clarify, it's not that the issue is urgent or anything like that. I'm just kind of testing https://github.com/google/oss-fuzz/issues/2582.
