### ISSUE TITLE
v225: systemd-nspawn dumps core with --tmpfs=…

### ISSUE THREAD

**Issue by mbunkus** [systemd/systemd#1306]
This is a regression from v224. When I start a simple container with `systemd-nspawn --directory=/linux/centos-6 --tmpfs=/var/lock` then systemd-nspawn v225 dumps core immediately. The same command works nicely after downgrading back to v224.

Error message from the journal:

```
Sep 19 13:25:50 sweet-chili kernel: systemd-nspawn[8885]: segfault at 0 ip 00007fad821e00ca sp 00007ffc556b81c8 error 4 in libc-2.22.so[7fad8215f000+19b000]
```

I can provide one of those cores if required; just tell me where to send one.

This is Arch Linux 64bit; glibc 2.22; systemd-nspawn v225; kernel 4.1.6.

**Comment by poettering** [comment]
Hmmm, normally, "systemd-coredump" should collect the coredump and write a backtrace for it to the logs... are you seeing that anywhere? If you do "coredumpctl" do you see the crash? Or did your distro turn of "systemd-coredump"?

Either way, would be thankful for a proper backtrace.

**Comment by mbunkus** [comment]
The core dump is available. Here's a bt from `coredumpctl gdb`:

```
[1 root@sweet-chili ~] coredumpctl gdb
           PID: 12088 (systemd-nspawn)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Mon 2015-09-21 16:05:15 CEST (38s ago)
  Command Line: systemd-nspawn --directory=/ftp/.linux/32/centos/6 --tmpfs=/var/lock
    Executable: /usr/bin/systemd-nspawn
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (mosu)
       Boot ID: 52dc952893594b3ea169dfb2b13f8b45
    Machine ID: ac44a214c6aa464fa67f0f7548d48d1d
      Hostname: sweet-chili
      Coredump: /var/lib/systemd/coredump/core.systemd-nspawn.0.52dc952893594b3ea169dfb2b13f8b45.12088.1442844315000000.lz4
       Message: Process 12088 (systemd-nspawn) of user 0 dumped core.

GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/systemd-nspawn...(no debugging symbols found)...done.
[New LWP 12088]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `systemd-nspawn --directory=/ftp/.linux/32/centos/6 --tmpfs=/var/lock'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f394658e0ca in strlen () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f394658e0ca in strlen () from /usr/lib/libc.so.6
#1  0x00007f394658ddfe in strdup () from /usr/lib/libc.so.6
#2  0x000055ec968e73c8 in ?? ()
#3  0x000055ec968e2f4b in ?? ()
#4  0x00007f394652d610 in __libc_start_main () from /usr/lib/libc.so.6
#5  0x000055ec968e6969 in ?? ()
```

**Comment by mbunkus** [comment]
Huh… I've just updated my Arch Linux systemd packages to v226 (at the time of submitting the issue only v225 was available), and the issue is gone now. I can reproduce the segfault by downgrading to v225, and I can reproduce fixing it by further downgrading to v224 or by upgrading to v226.

I'll close this for the time being. If it happens again with a later release I'll shout. Thanks.
