### ISSUE TITLE
Load of misaligned address in client_parse_message() [sd-dhcp6-client.c]

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#13591]
Discovered by Fuzzit (UBSan):

```
FUZZER: ../src/libsystemd-network/sd-dhcp6-client.c:1008:39: runtime error: load of misaligned address 0x627000774de6 for type 'be32_t' (aka 'unsigned int'), which requires 4 byte alignment
FUZZER: 0x627000774de6: note: pointer points here
FUZZER:  00 20 00 04 00 00  00 00 f8 0a 07 f9 bd 00  00 00 00 00 00 00 00 03  00 5a 59 e4 1b 4a 00 00  00 00
FUZZER:              ^ 
FUZZER:     #0 0x596540 in client_parse_message /home/travis/build/systemd/systemd/build/../src/libsystemd-network/sd-dhcp6-client.c:1008:39
FUZZER:     #1 0x5942df in client_receive_advertise /home/travis/build/systemd/systemd/build/../src/libsystemd-network/sd-dhcp6-client.c:1092:13
FUZZER:     #2 0x591600 in client_receive_message /home/travis/build/systemd/systemd/build/../src/libsystemd-network/sd-dhcp6-client.c:1198:21
FUZZER:     #3 0x7f488792df2f in source_dispatch /home/travis/build/systemd/systemd/build/../src/libsystemd/sd-event/sd-event.c:2828:21
FUZZER:     #4 0x7f488792d04c in sd_event_dispatch /home/travis/build/systemd/systemd/build/../src/libsystemd/sd-event/sd-event.c:3241:21
FUZZER:     #5 0x7f488792f4d8 in sd_event_run /home/travis/build/systemd/systemd/build/../src/libsystemd/sd-event/sd-event.c:3299:21
FUZZER:     #6 0x5804f1 in fuzz_client /home/travis/build/systemd/systemd/build/../src/fuzz/fuzz-dhcp6-client.c:44:9
FUZZER:     #7 0x580167 in LLVMFuzzerTestOneInput /home/travis/build/systemd/systemd/build/../src/fuzz/fuzz-dhcp6-client.c:56:9
FUZZER:     #8 0x44a55a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:576:15
FUZZER:     #9 0x449c75 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:485:3
FUZZER:     #10 0x44c0ab in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:19
FUZZER:     #11 0x44cd85 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:844:5
FUZZER:     #12 0x4435d3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:765:6
FUZZER:     #13 0x46b2b2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
FUZZER:     #14 0x7f48862192e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
FUZZER:     #15 0x41fb08 in _start (/app/fuzzer+0x41fb08)
FUZZER: 
FUZZER: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/libsystemd-network/sd-dhcp6-client.c:1008:39 in 
```

Fuzzer input which caused the crash:
[unaligned-access-crash.tar.gz](https://github.com/systemd/systemd/files/3626419/unaligned-access-crash.tar.gz)

cc @yuwata

**Comment by yuwata** [comment]
Fix is waiting in #13592. Thank you.
