### ISSUE TITLE
Possible stack-overflow in json.c on s390x & aarch64

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#14396]
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > Ubuntu Bionic on s390x and aarch64

In my *yet another* attempt to finally wrap #13785 up, I stumbled upon a newly introduced issue when running `test-json`:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==24025==ERROR: AddressSanitizer: stack-overflow on address 0x03ffc63ff000 (pc 0x03ff7eb1eae0 bp 0x03ffc63ffe30 sp 0x03ffc63ffe30 T0)
    #0 0x3ff7eb1eadf in json_variant_ref /home/travis/build/systemd/systemd/build/../src/shared/json.c:785:1
    #1 0x3ff7eb1f359 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:745:14
    #2 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #3 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #4 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #5 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #6 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #7 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #8 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #9 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #10 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #11 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #12 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #13 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #14 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #15 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #16 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #17 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #18 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #19 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #20 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #21 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #22 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #23 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #24 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #25 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #26 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #27 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #28 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #29 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #30 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #31 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #32 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #33 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #34 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #35 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #36 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #37 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #38 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #39 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #40 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #41 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #42 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #43 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #44 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #45 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #46 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #47 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #48 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #49 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #50 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #51 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #52 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #53 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #54 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #55 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #56 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #57 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #58 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #59 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #60 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #61 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #62 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #63 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #64 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #65 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #66 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #67 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #68 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #69 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #70 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #71 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #72 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #73 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #74 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #75 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #76 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #77 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #78 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #79 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #80 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #81 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #82 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #83 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #84 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #85 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #86 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #87 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #88 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #89 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #90 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #91 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #92 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #93 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #94 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #95 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #96 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #97 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #98 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #99 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #100 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #101 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #102 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #103 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #104 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #105 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #106 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #107 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #108 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #109 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #110 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #111 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #112 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #113 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #114 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #115 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #116 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #117 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #118 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #119 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #120 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #121 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #122 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #123 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #124 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #125 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #126 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #127 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #128 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #129 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #130 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #131 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #132 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #133 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #134 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #135 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #136 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #137 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #138 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #139 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #140 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #141 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #142 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #143 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #144 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #145 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #146 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #147 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #148 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #149 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #150 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #151 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #152 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #153 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #154 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #155 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #156 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #157 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #158 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #159 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #160 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #161 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #162 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #163 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #164 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #165 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #166 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #167 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #168 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #169 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #170 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #171 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #172 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #173 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #174 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #175 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #176 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #177 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #178 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #179 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #180 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #181 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #182 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #183 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #184 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #185 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #186 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #187 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #188 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #189 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #190 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #191 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #192 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #193 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #194 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #195 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #196 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #197 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #198 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #199 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #200 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #201 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #202 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #203 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #204 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #205 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #206 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #207 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #208 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #209 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #210 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #211 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #212 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #213 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #214 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #215 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #216 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #217 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #218 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #219 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #220 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #221 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #222 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #223 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #224 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #225 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #226 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #227 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #228 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #229 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #230 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #231 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #232 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #233 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #234 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #235 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #236 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #237 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #238 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #239 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #240 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #241 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #242 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #243 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #244 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #245 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #246 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
    #247 0x3ff7eb1f995 in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:756:17
    #248 0x3ff7eb1fdfb in json_variant_free_inner /home/travis/build/systemd/systemd/build/../src/shared/json.c:764:25
    #249 0x3ff7eb1f25b in json_variant_unref /home/travis/build/systemd/systemd/build/../src/shared/json.c:800:25
SUMMARY: AddressSanitizer: stack-overflow /home/travis/build/systemd/systemd/build/../src/shared/json.c:785:1 in json_variant_ref
==24025==ABORTING
```

**Comment by poettering** [comment]
Fix in #14613
