### ISSUE TITLE
systemctl crashes on zsh tab-completion

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#1449]
Doing `systemctl restart openvp<TAB><TAB>` causes `systemctl` to crash using `zsh-5.0.5`'s tab-completion.
Running systemd @d4e783e44dccb3d5e7ea2fd42b107b2c3e44629b from git/master.

**Output on terminal:**

```
# systemctl restart openvp*** Error in `systemctl': double free or corruption (fasttop): 0x00005560b7796010 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x72cdf)[0x7f9f2b0f3cdf]
/lib64/libc.so.6(+0x7812e)[0x7f9f2b0f912e]
/lib64/libc.so.6(+0x78e66)[0x7f9f2b0f9e66]
systemctl(+0x4df45)[0x5560b75bbf45]
systemctl(+0x4df69)[0x5560b75bbf69]
systemctl(+0xcd5d)[0x5560b757ad5d]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f9f2b0a2b55]
systemctl(+0xe86c)[0x5560b757c86c]
======= Memory map: ========
5560b756e000-5560b7612000 r-xp 00000000 fb:00 8822190                    /usr/bin/systemctl
5560b7612000-5560b7617000 r--p 000a3000 fb:00 8822190                    /usr/bin/systemctl
5560b7617000-5560b7618000 rw-p 000a8000 fb:00 8822190                    /usr/bin/systemctl
5560b7618000-5560b7619000 rw-p 00000000 00:00 0 
5560b7795000-5560b77b6000 rw-p 00000000 00:00 0                          [heap]
7f9f2975c000-7f9f29771000 r-xp 00000000 fb:00 7977916                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/libgcc_s.so.1
7f9f29771000-7f9f29970000 ---p 00015000 fb:00 7977916                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/libgcc_s.so.1
7f9f29970000-7f9f29971000 r--p 00014000 fb:00 7977916                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/libgcc_s.so.1
7f9f29971000-7f9f29972000 rw-p 00015000 fb:00 7977916                    /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/libgcc_s.so.1
7f9f29972000-7f9f2a972000 r--s 00000000 00:01 16054376                   /kdbus-conn:sd-systemctl (deleted)
7f9f2a972000-7f9f2ac6a000 r--p 00000000 fb:00 13375215                   /usr/lib64/locale/locale-archive
7f9f2ac6a000-7f9f2ac6e000 r-xp 00000000 fb:00 8360292                    /lib64/libattr.so.1.1.0
7f9f2ac6e000-7f9f2ae6d000 ---p 00004000 fb:00 8360292                    /lib64/libattr.so.1.1.0
7f9f2ae6d000-7f9f2ae6e000 r--p 00003000 fb:00 8360292                    /lib64/libattr.so.1.1.0
7f9f2ae6e000-7f9f2ae6f000 rw-p 00004000 fb:00 8360292                    /lib64/libattr.so.1.1.0
7f9f2ae6f000-7f9f2ae80000 r-xp 00000000 fb:00 7897920                    /usr/lib64/libgpg-error.so.0.15.0
7f9f2ae80000-7f9f2b07f000 ---p 00011000 fb:00 7897920                    /usr/lib64/libgpg-error.so.0.15.0
7f9f2b07f000-7f9f2b080000 r--p 00010000 fb:00 7897920                    /usr/lib64/libgpg-error.so.0.15.0
7f9f2b080000-7f9f2b081000 rw-p 00011000 fb:00 7897920                    /usr/lib64/libgpg-error.so.0.15.0
7f9f2b081000-7f9f2b214000 r-xp 00000000 fb:00 8064742                    /lib64/libc-2.20.so
7f9f2b214000-7f9f2b414000 ---p 00193000 fb:00 8064742                    /lib64/libc-2.20.so
7f9f2b414000-7f9f2b418000 r--p 00193000 fb:00 8064742                    /lib64/libc-2.20.so
7f9f2b418000-7f9f2b41a000 rw-p 00197000 fb:00 8064742                    /lib64/libc-2.20.so
7f9f2b41a000-7f9f2b41e000 rw-p 00000000 00:00 0 
7f9f2b41e000-7f9f2b434000 r-xp 00000000 fb:00 8065141                    /lib64/libpthread-2.20.so
7f9f2b434000-7f9f2b633000 ---p 00016000 fb:00 8065141                    /lib64/libpthread-2.20.so
7f9f2b633000-7f9f2b634000 r--p 00015000 fb:00 8065141                    /lib64/libpthread-2.20.so
7f9f2b634000-7f9f2b635000 rw-p 00016000 fb:00 8065141                    /lib64/libpthread-2.20.so
7f9f2b635000-7f9f2b639000 rw-p 00000000 00:00 0 
7f9f2b639000-7f9f2b63d000 r-xp 00000000 fb:00 8767054                    /lib64/libcap.so.2.24
7f9f2b63d000-7f9f2b83d000 ---p 00004000 fb:00 8767054                    /lib64/libcap.so.2.24
7f9f2b83d000-7f9f2b83e000 r--p 00004000 fb:00 8767054                    /lib64/libcap.so.2.24
7f9f2b83e000-7f9f2b83f000 rw-p 00005000 fb:00 8767054                    /lib64/libcap.so.2.24
7f9f2b83f000-7f9f2b914000 r-xp 00000000 fb:00 8012021                    /usr/lib64/libgcrypt.so.20.0.3
7f9f2b914000-7f9f2bb14000 ---p 000d5000 fb:00 8012021                    /usr/lib64/libgcrypt.so.20.0.3
7f9f2bb14000-7f9f2bb15000 r--p 000d5000 fb:00 8012021                    /usr/lib64/libgcrypt.so.20.0.3
7f9f2bb15000-7f9f2bb1d000 rw-p 000d6000 fb:00 8012021                    /usr/lib64/libgcrypt.so.20.0.3
7f9f2bb1d000-7f9f2bb1e000 rw-p 00000000 00:00 0 
7f9f2bb1e000-7f9f2bb25000 r-xp 00000000 fb:00 7911254                    /usr/lib64/liblz4.so.1.3.0
7f9f2bb25000-7f9f2bd24000 ---p 00007000 fb:00 7911254                    /usr/lib64/liblz4.so.1.3.0
7f9f2bd24000-7f9f2bd25000 r--p 00006000 fb:00 7911254                    /usr/lib64/liblz4.so.1.3.0
7f9f2bd25000-7f9f2bd26000 rw-p 00007000 fb:00 7911254                    /usr/lib64/liblz4.so.1.3.0
7f9f2bd26000-7f9f2bd47000 r-xp 00000000 fb:00 7913172                    /lib64/liblzma.so.5.0.8
7f9f2bd47000-7f9f2bf47000 ---p 00021000 fb:00 7913172                    /lib64/liblzma.so.5.0.8
7f9f2bf47000-7f9f2bf48000 r--p 00021000 fb:00 7913172                    /lib64/liblzma.so.5.0.8
7f9f2bf48000-7f9f2bf49000 rw-p 00022000 fb:00 7913172                    /lib64/liblzma.so.5.0.8
7f9f2bf49000-7f9f2bf50000 r-xp 00000000 fb:00 8065145                    /lib64/librt-2.20.so
7f9f2bf50000-7f9f2c14f000 ---p 00007000 fb:00 8065145                    /lib64/librt-2.20.so
7f9f2c14f000-7f9f2c150000 r--p 00006000 fb:00 8065145                    /lib64/librt-2.20.so
7f9f2c150000-7f9f2c151000 rw-p 00007000 fb:00 8065145                    /lib64/librt-2.20.so
7f9f2c151000-7f9f2c172000 r-xp 00000000 fb:00 8064743                    /lib64/ld-2.20.so
7f9f2c31a000-7f9f2c320000 rw-p 00000000 00:00 0 
7f9f2c36e000-7f9f2c36f000 rw-p 00000000 00:00 0 
7f9f2c36f000-7f9f2c370000 rw-s 00000000 00:01 16054377                   /memfd:sd-systemctl (deleted)
7f9f2c370000-7f9f2c371000 rw-p 00000000 00:00 0 
7f9f2c371000-7f9f2c372000 r--p 00020000 fb:00 8064743                    /lib64/ld-2.20.so
7f9f2c372000-7f9f2c373000 rw-p 00021000 fb:00 8064743                    /lib64/ld-2.20.so
7f9f2c373000-7f9f2c374000 rw-p 00000000 00:00 0 
7fffe2815000-7fffe2836000 rw-p 00000000 00:00 0                          [stack]
7fffe2953000-7fffe2955000 r--p 00000000 00:00 0                          [vvar]
7fffe2955000-7fffe2957000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

**Backtrace obtained via `coredumpctl gdb …`:**

```
Thread 1 (Thread 0x7f9f2c31a780 (LWP 8055)):
#0  0x00007f9f2b0b5f17 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 8055
        selftid = 8055
#1  0x00007f9f2b0b727a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x3030303030303020, sa_sigaction = 0x3030303030303020}, sa_mask = {__val = {2319406834570502192, 3631653260693741616, 3256155515020260195, 3977631964012832311, 3276212736508309552, 3472328296227676275, 3544396885380837424, 3977580298945048864, 2314885530818453559, 2314885530818453536, 7882826771951788064, 8751388410364191846, 2336370277084394611, 7234316355399672872, 7147887955304450601, 4294967189}}, sa_flags = 86, sa_restorer = 0x7fffe28348f0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f9f2b0f3ce4 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f9f2b1e88f8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 32767, overflow_arg_area = 0x7fffe2834900, reg_save_area = 0x7fffe2834890}}
        fd = 5
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007f9f2b0f912e in malloc_printerr (action=3, str=0x7f9f2b1e8ae0 "double free or corruption (fasttop)", ptr=<optimized out>) at malloc.c:4958
        buf = "00005560b7796010"
        cp = <optimized out>
#4  0x00007f9f2b0f9e66 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3829
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
        __func__ = "_int_free"
#5  0x00005560b75bbf45 in strv_clear (l=l@entry=0x5560b7796030) at /var/tmp/portage/sys-apps/systemd-9999/work/systemd-9999/src/basic/strv.c:78
        k = 0x5560b7796030
#6  0x00005560b75bbf69 in strv_free (l=0x5560b7796030) at /var/tmp/portage/sys-apps/systemd-9999/work/systemd-9999/src/basic/strv.c:84
No locals.
#7  0x00005560b757ad5d in main (argc=<optimized out>, argv=0x7fffe2834b78) at /var/tmp/portage/sys-apps/systemd-9999/work/systemd-9999/src/systemctl/systemctl.c:7775
        r = 0
        __func__ = "main"
        __PRETTY_FUNCTION__ = "main"
```

**Comment by eliasp** [comment]
Updated now to @3c2f5a543de9cc3d958920b3bd18dc8657dc201f and can't reproduce it anymore. Closing for now.
