### ISSUE TITLE
Unstable `test-exec-deserialization.py`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#14632]
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > CentOS 7, Arch Linux

For the past week or two I noticed that `test-exec-deserialization.py` occasionally fails, despite being incredibly stable for the past few years. ~~Also, all fails I've seen were only on CentOS 7, not on Arch, not sure if it's related or just luck.~~ Happened several times on Arch as well. Was there any relevant code change, which could cause this?

```
...
======================================================================
FAIL: test_interleaved (__main__.ExecutionResumeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-exec-deserialization.py", line 158, in test_interleaved
    self.check_output(expected_output)
  File "test/test-exec-deserialization.py", line 105, in check_output
    self.assertEqual(output, expected_output)
AssertionError: 'baz\nfoo\nbar\n' != 'foo\nbar\n'
- baz
  foo
  bar

...

======================================================================
FAIL: test_removal (__main__.ExecutionResumeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-exec-deserialization.py", line 166, in test_removal
    self.assertTrue(not os.path.exists(self.output_file))
AssertionError: False is not true

----------------------------------------------------------------------

...
```

**Comment by anitazha** [comment]
Do you happen to have any debug level journal logs from this? I was a bit curious about this so I was looking through the git logs (didn't see anything particularly relevant) and was thinking about how the test could end up with this result.

The part of the code that resolves which command to continue from after deserialization hasn't changed recently, so I was thinking it might be some kind of "race" where the `NO_CHANGE` version of the unit is queued, but not yet running. And then it is replaced by the latter unit in the test (`COMMAND_INTERLEAVED` for `test_interleaved` or `REMOVAL` for `test_removal`) which results in the above getting printed when the job runs. But that's just a theory; I don't really know how to prove it.

**Comment by mrc0mmand** [comment]
@anitazha I managed to accidentally reproduce it with debug logs on in #14746, see https://gist.githubusercontent.com/mrc0mmand/0a9dee048523ac63a4713b8d17b626f6/raw/b85f632f68e6d83b4db62afe7ce61ec34dca6b72/test-exec-deserialization.py-test_interlaved for a full (and hopefully relevant) log.

**Comment by mrc0mmand** [comment]
From the log it indeed looks like the `NO_CHANGE` version didn't get chance to run and got overwritten by `COMMAND_INTERLEAVED` unit before it even started.

**Comment by mrc0mmand** [comment]
Relevant parts from the log:

```
$ grep test-issue-518.service /tmp/test-interleaved 
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: unit_file_build_name_map: normal unit file: /run/systemd/system/test-issue-518.service
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Trying to enqueue job test-issue-518.service/start/replace
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: Added job test-issue-518.service/start to transaction.
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: Pulling in sysinit.target/start from test-issue-518.service/start
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: Pulling in system.slice/start from test-issue-518.service/start
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: Pulling in shutdown.target/stop from test-issue-518.service/start
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: Keeping job sysinit.target/start because of test-issue-518.service/start
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Installed new job test-issue-518.service/start as 1715
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Enqueued job test-issue-518.service/start as 1715
Feb 03 14:09:40 n27.dusty.ci.centos.org systemd[1]: unit_file_build_name_map: normal unit file: /run/systemd/system/test-issue-518.service
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Reinstalled deserialized job test-issue-518.service/start as 1715
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Passing 0 fds to service
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: About to execute: /bin/bash -c 'echo baz >> /tmp/tmpfchy7ca0'
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Forked /bin/bash as 586896
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Changed dead -> start
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: Starting test-issue-518.service...
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[586896]: test-issue-518.service: Executing: /bin/bash -c 'echo baz >> /tmp/tmpfchy7ca0'
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Child 586896 belongs to test-issue-518.service.
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Main process exited, code=exited, status=0/SUCCESS
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Running next main command for state start.
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Passing 0 fds to service
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: About to execute: /bin/sleep 2
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Forked /bin/sleep as 586898
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[1]: Got cgroup empty notification for: /system.slice/test-issue-518.service
Feb 03 14:09:41 n27.dusty.ci.centos.org systemd[586898]: test-issue-518.service: Executing: /bin/sleep 2
Feb 03 14:09:43 n27.dusty.ci.centos.org systemd[586919]: test-issue-518.service: Executing: /bin/bash -c 'echo foo >> /tmp/tmpfchy7ca0'
Feb 03 14:09:43 n27.dusty.ci.centos.org systemd[586921]: test-issue-518.service: Executing: /bin/bash -c 'echo bar >> /tmp/tmpfchy7ca0'
Feb 03 14:09:43 n27.dusty.ci.centos.org systemd[1]: test-issue-518.service: Succeeded.
Feb 03 14:09:43 n27.dusty.ci.centos.org systemd[1]: Started test-issue-518.service.
```
