### ISSUE TITLE
fuzz-network-parser seems to crash somewhere in config_parse_address_generation_type

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#14811]
It was reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20548. I'm just going to leave it here so that it won't get lost:
```

Assertion 's' failed at src/basic/in-addr-util.c:408, function int in_addr_from_string(int, const char *, union in_addr_union *)(). Aborting.
--
  | MemorySanitizer:DEADLYSIGNAL
  | ==1==ERROR: MemorySanitizer: ABRT on unknown address 0x000000000001 (pc 0x7f12df49a428 bp 0x7ffe3a49be00 sp 0x7ffe3a49bc58 T1)
  | #0 0x7f12df49a428 in gsignal /build/glibc-LK5gWL/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54
  | #1 0x7f12df49c029 in abort /build/glibc-LK5gWL/glibc-2.23/stdlib/abort.c:89
  | #2 0x7f12e08a0f77 in log_assert_failed_realm systemd/src/basic/log.c:809:9
  | #3 0x7f12e088faaf in in_addr_from_string systemd/src/basic/in-addr-util.c:408:9
  | #4 0x679dcc in config_parse_address_generation_type systemd/src/network/networkd-ndisc.c:1004:13
  | #5 0x7f12e05dc3fc in next_assignment systemd/src/shared/conf-parser.c:132:32
  | #6 0x7f12e05cec1d in parse_line systemd/src/shared/conf-parser.c:270:16
  | #7 0x7f12e05cc184 in config_parse systemd/src/shared/conf-parser.c:391:21
  | #8 0x7f12e05d0092 in config_parse_many_files systemd/src/shared/conf-parser.c:448:21
  | #9 0x7f12e05d0989 in config_parse_many systemd/src/shared/conf-parser.c:507:16
  | #10 0x4e2a74 in network_load_one systemd/src/network/networkd-network.c:461:13
  | #11 0x4a6001 in LLVMFuzzerTestOneInput systemd/src/network/fuzz-network-parser.c:26:16
  | #12 0x7eb609 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:556:15
  | #13 0x771f40 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:292:6
  | #14 0x785c9f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:774:9
  | #15 0x771000 in main /src/libfuzzer/FuzzerMain.cpp:19:10
  | #16 0x7f12df48582f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:291
  | #17 0x429d78 in _start (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_systemd_51c8b794cfaad5e5fa22044d2c9d4cb97d349941/revisions/fuzz-network-parser+0x429d78)
```
cc @ssahani

**Comment by yuwata** [comment]
Fix is waiting in #14805.
