### ISSUE TITLE
There seems to be a memory leak in userdbctl (when -s is passed to it)

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#14947]
```sh
# userdbctl -s ssh
...
=================================================================
==91==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f7ada244c58 in __interceptor_malloc (/usr/lib64/libasan.so.5+0x10dc58)
    #1 0x7f7ad91c3c26 in malloc_multiply ../src/basic/alloc-util.h:96
    #2 0x7f7ad91c601c in strv_split_full ../src/basic/strv.c:266
    #3 0x403ac5 in strv_split ../src/basic/strv.h:75
    #4 0x40c2e1 in parse_argv ../src/userdb/userdbctl.c:704
    #5 0x40c7cf in run ../src/userdb/userdbctl.c:767
    #6 0x40cd61 in main ../src/userdb/userdbctl.c:790
    #7 0x7f7ad7a11f42 in __libc_start_main (/usr/lib64/libc.so.6+0x23f42)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f7ada244c58 in __interceptor_malloc (/usr/lib64/libasan.so.5+0x10dc58)
    #1 0x7f7ada1ad383  (/usr/lib64/libasan.so.5+0x76383)
    #2 0x7f7ad91c613b in strv_split_full ../src/basic/strv.c:272
    #3 0x403ac5 in strv_split ../src/basic/strv.h:75
    #4 0x40c2e1 in parse_argv ../src/userdb/userdbctl.c:704
    #5 0x40c7cf in run ../src/userdb/userdbctl.c:767
    #6 0x40cd61 in main ../src/userdb/userdbctl.c:790
    #7 0x7f7ad7a11f42 in __libc_start_main (/usr/lib64/libc.so.6+0x23f42)

SUMMARY: AddressSanitizer: 20 byte(s) leaked in 2 allocation(s).
```

**Comment by yuwata** [comment]
Fix is waiting in #14948.
