### ISSUE TITLE
ASan seems to be complaining about a heap-buffer-overflow in udev-rules

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#15162]
As far as I can tell, it appears it happens when there is at least one comma at the end of a rule. It can be reproduced by applying the following patch:
```diff
diff --git a/test/udev-test.pl b/test/udev-test.pl
index 95013279b8..b85a82e0f6 100755
--- a/test/udev-test.pl
+++ b/test/udev-test.pl
@@ -61,7 +61,7 @@ EOF
                 exp_name        => "boot_disk",
                 rules           => <<EOF
 SUBSYSTEMS=="scsi", ATTRS{vendor}=="ATA", SYMLINK+="boot_disk%n"
-KERNEL=="ttyACM0", SYMLINK+="modem"
+KERNEL=="ttyACM0", SYMLINK+="modem",
 EOF
         },
         {
```
```sh
=================================================================
==3468==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6040000543f5 at pc 0x00000044bd52 bp 0x7fffbc2e6850 sp 0x7fffbc2e6840
READ of size 1 at 0x6040000543f5 thread T0
    #0 0x44bd51 in token_match_string ../src/udev/udev-rules.c:1344
    #1 0x44f0c8 in udev_rule_apply_token_to_event ../src/udev/udev-rules.c:1567
    #2 0x464632 in udev_rule_apply_line_to_event ../src/udev/udev-rules.c:2242
    #3 0x464e9a in udev_rules_apply_to_event ../src/udev/udev-rules.c:2269
    #4 0x41b8f7 in udev_event_execute_rules ../src/udev/udev-event.c:986
    #5 0x40d180 in run ../src/test/test-udev.c:125
    #6 0x40d2c8 in main ../src/test/test-udev.c:131
    #7 0x7f4127adcf42 in __libc_start_main (/lib64/libc.so.6+0x23f42)
    #8 0x40ac5d in _start (/home/vagrant/systemd/build/test-udev+0x40ac5d)

0x6040000543f5 is located 0 bytes to the right of 37-byte region [0x6040000543d0,0x6040000543f5)
allocated by thread T0 here:
    #0 0x7f412a32552d in strdup (/lib64/libasan.so.5+0x9652d)
    #1 0x445ab6 in rule_add_line ../src/udev/udev-rules.c:1095
    #2 0x44ab17 in parse_file ../src/udev/udev-rules.c:1269
    #3 0x44b32a in udev_rules_new ../src/udev/udev-rules.c:1302
    #4 0x40c158 in run ../src/test/test-udev.c:90
    #5 0x40d2c8 in main ../src/test/test-udev.c:131
    #6 0x7f4127adcf42 in __libc_start_main (/lib64/libc.so.6+0x23f42)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../src/udev/udev-rules.c:1344 in token_match_string
Shadow bytes around the buggy address:
  0x0c0880002820: fa fa 00 00 00 00 01 fa fa fa 00 00 00 00 01 fa
  0x0c0880002830: fa fa 00 00 00 00 02 fa fa fa 00 00 00 00 00 00
  0x0c0880002840: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880002850: fa fa 00 00 00 00 02 fa fa fa 00 00 00 00 00 fa
  0x0c0880002860: fa fa 00 00 00 00 00 fa fa fa 00 00 00 00 00 fa
=>0x0c0880002870: fa fa 00 00 00 00 00 fa fa fa 00 00 00 00[05]fa
  0x0c0880002880: fa fa 00 00 00 00 00 fa fa fa 00 00 00 00 00 fa
  0x0c0880002890: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fd
  0x0c08800028a0: fa fa fd fd fd fd fd fd fa fa fd fd fd fd fd fd
  0x0c08800028b0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fd
  0x0c08800028c0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3468==ABORTING
```

**Comment by poettering** [comment]
Should be fixed by #15561, ptal
