### ISSUE TITLE
Passing TTYPath= with StandardInput/Output/ErrorFileDescriptor= will cause an assertion failure

### ISSUE THREAD

**Issue by refi64** [systemd/systemd#15344]
**systemd version the issue has been seen with**
> 245.4

**Used distribution**
 > Fedora 32

**Expected behaviour you didn't see**
 > systemd to not have an assertion failure

**Unexpected behaviour you saw**
 > systemd had an assertion failure

**Steps to reproduce the problem**

- `systemd-run --user -qP -p TTYPath=/dev/console --wait echo`
- ...
- Profit?

The full error message is:

```
Assertion 'a' failed at src/basic/path-util.c:486, function path_compare(). Aborting.
```

Backtrace:

Note that this was from the system instance, not the user instance like the example. I used the user instance since it shows the assertion failure inline in the command output.

```
#0  0x00007f641decaa25 in raise () from /lib64/libc.so.6
#1  0x00007f641deb3895 in abort () from /lib64/libc.so.6
#2  0x00007f641dc5b1d8 in log_assert_failed_realm (realm=<optimized out>, text=0x7f641dde1db6 "a", file=0x7f641de00fb9 "src/basic/path-util.c", line=486, 
    func=0x7f641de02048 <__PRETTY_FUNCTION__.12.lto_priv.18> "path_compare") at ../src/basic/log.c:809
#3  0x00007f641dd24729 in path_compare (a=a@entry=0x0, b=b@entry=0x55ea6c85ac6e "/dev/console") at ../src/basic/path-util.c:486
#4  0x00007f641dd2476d in path_equal (a=a@entry=0x0, b=b@entry=0x55ea6c85ac6e "/dev/console") at ../src/basic/path-util.c:530
#5  0x000055ea6c849072 in build_environment (ret=<synthetic pointer>, journal_stream_ino=0, journal_stream_dev=0, shell=<optimized out>, username=0x0, home=0x0, n_fds=0, p=0x7ffeaf3bc020, 
    c=0x55ea6d1a58e8, u=0x55ea6d1a5320) at ../src/core/execute.c:1792
#6  exec_child.constprop.0 (unit=unit@entry=0x55ea6d1a5320, command=command@entry=0x55ea6d175050, context=context@entry=0x55ea6d1a58e8, params=params@entry=0x7ffeaf3bc020, 
    runtime=runtime@entry=0x0, dcreds=dcreds@entry=0x55ea6d1a5d88, socket_fd=<optimized out>, named_iofds=<optimized out>, fds=<optimized out>, n_socket_fds=<optimized out>, 
    n_storage_fds=<optimized out>, files_env=<optimized out>, user_lookup_fd=<optimized out>, exit_status=<optimized out>) at ../src/core/execute.c:3433
#7  0x000055ea6c7bf3d8 in exec_spawn (unit=<optimized out>, command=0x55ea6d175050, context=<optimized out>, params=0x7ffeaf3bc020, runtime=0x0, dcreds=0x55ea6d1a5d88, ret=0x7ffeaf3bc010)
    at ../src/core/execute.c:4088
#8  0x000055ea6c7ec1e8 in service_spawn (s=<optimized out>, c=<optimized out>, timeout=<optimized out>, flags=<optimized out>, _pid=<optimized out>) at ../src/core/service.c:1594
#9  0x000055ea6c7f0c1a in service_enter_start (s=0x55ea6d1a5320) at ../src/core/service.c:2152
#10 0x000055ea6c7f1232 in service_enter_condition (s=0x55ea6d1a5320) at ../src/core/service.c:2256
#11 service_start (u=0x55ea6d1a5320) at ../src/core/service.c:2504
#12 0x000055ea6c7c9b94 in unit_start (u=0x55ea6d1a5320) at ../src/core/unit.h:626
#13 job_perform_on_unit (j=0x7ffeaf3bc238) at ../src/core/job.c:615
#14 0x000055ea6c7d6542 in job_run_and_invalidate (j=<optimized out>) at ../src/basic/hashmap.h:271
#15 manager_dispatch_run_queue (source=<optimized out>, userdata=<optimized out>) at ../src/core/manager.c:2175
#16 manager_dispatch_run_queue (source=<optimized out>, userdata=0x55ea6d0b1490) at ../src/core/manager.c:2164
#17 0x00007f641ddaeb92 in source_dispatch (s=s@entry=0x55ea6d0b1380) at ../src/libsystemd/sd-event/sd-event.c:3233
#18 0x00007f641ddaeffd in sd_event_dispatch (e=0x55ea6d0b0ab0) at ../src/libsystemd/sd-event/sd-event.c:3634
#19 0x00007f641ddb02c8 in sd_event_run (e=0x55ea6d0b0ab0, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3692
#20 0x000055ea6c7df6f6 in manager_loop (m=0x55ea6d0b1490) at ../src/core/manager.c:2941
#21 0x000055ea6c79ca98 in invoke_main_loop (ret_error_message=0x7ffeaf3bc480, ret_switch_root_init=<synthetic pointer>, ret_switch_root_dir=<synthetic pointer>, ret_fds=0x7ffeaf3bc470, 
    ret_shutdown_verb=<synthetic pointer>, ret_retval=<synthetic pointer>, ret_reexecute=<synthetic pointer>, saved_rlimit_memlock=0x7ffeaf3bc490, saved_rlimit_nofile=0x7ffeaf3bc4a0, 
    m=0x55ea6d0b1490) at ../src/core/main.c:1704
#22 main (argc=<optimized out>, argv=0x7ffeaf3bc6d8) at ../src/core/main.c:2702
```

[`exec_context_tty_path`](https://github.com/systemd/systemd/blob/v245/src/core/execute.c#L178-L179) returns NULL if stdio is supposed to be going over FDs:

```c
        if (context->stdio_as_fds)
                return NULL;
```

[That return value is later passed directly to `path_equal`](https://github.com/systemd/systemd/blob/v245/src/core/execute.c#L1786-L1792):

```c
                tty_path = exec_context_tty_path(c);

                /* If we are forked off PID 1 and we are supposed to operate on /dev/console, then let's try to inherit
                 * the $TERM set for PID 1. This is useful for containers so that the $TERM the container manager
                 * passes to PID 1 ends up all the way in the console login shown. */

                if (path_equal(tty_path, "/dev/console") && getppid() == 1)
```

I'm not necessarily expecting this to actually work (was messing around with different tty/stdio related properties), but it probably shouldn't crash either...

**Comment by poettering** [comment]
Fix in #15548
