### ISSUE TITLE
There seems to be a pointer-overflow in buffer_peek

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#15583]
It was reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19446. The issue was closed automatically because the pointer-overflow check was rolled back but it's still there:
```
../src/libsystemd/sd-bus/bus-message.c:3086:35: runtime error: addition of unsigned offset to 0x0000018df7b0 overflowed to 0x0000018df7af
    #0 0x7f0d376bb02c in buffer_peek /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:3086:35
    #1 0x7f0d37682ffc in bus_message_parse_fields /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:5212:29
    #2 0x7f0d376803d3 in bus_message_from_malloc /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:571:13
    #3 0x46ea9d in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/fuzz/fuzz-bus-message.c:30:13
    #4 0x42ab98 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/systemd/out/fuzz-bus-message+0x42ab98)
    #5 0x40fcb5 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/vagrant/systemd/out/fuzz-bus-message+0x40fcb5)
    #6 0x418bf9 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/systemd/out/fuzz-bus-message+0x418bf9)
    #7 0x408c56 in main (/home/vagrant/systemd/out/fuzz-bus-message+0x408c56)
    #8 0x7f0d36acc1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #9 0x408cad in _start (/home/vagrant/systemd/out/fuzz-bus-message+0x408cad)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/libsystemd/sd-bus/bus-message.c:3086:35 in
```

**Comment by evverx** [comment]
Now that https://github.com/systemd/systemd/pull/15860 is merge, the issue can be closed.
