### ISSUE TITLE
There seems to be a memory leak in config_parse_dhcp_server_pop3_servers

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#15951]
```sh
$ cat ../clusterfuzz-testcase-minimized-fuzz-network-parser-5162542791131136
[DHCPServer]
POP3Servers=1.8.5.0

$ ./out/fuzz-network-parser ../clusterfuzz-testcase-minimized-fuzz-network-parser-5162542791131136
INFO: Seed: 1356000512
INFO: Loaded 2 modules   (199856 inline 8-bit counters): 136728 [0x7f45690f2e30, 0x7f4569114448), 63128 [0xadfab0, 0xaef148),
INFO: Loaded 2 PC tables (199856 PCs): 136728 [0x7f4569114448,0x7f456932a5c8), 63128 [0xaef148,0xbe5ac8),
./out/fuzz-network-parser: Running 1 inputs 1 time(s) each.
Running: ../clusterfuzz-testcase-minimized-fuzz-network-parser-5162542791131136

=================================================================
==9117==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x50e9ac in reallocarray (/home/vagrant/systemd/out/fuzz-network-parser+0x50e9ac)
    #1 0x68aae7 in config_parse_dhcp_lease_server_list /home/vagrant/systemd/build/../src/network/networkd-dhcp-server.c:437:37
    #2 0x68b223 in config_parse_dhcp_server_pop3_servers /home/vagrant/systemd/build/../src/network/networkd-dhcp-server.c:517:16
    #3 0x7f456869530e in next_assignment /home/vagrant/systemd/build/../src/shared/conf-parser.c:133:32
    #4 0x7f456868d7d3 in parse_line /home/vagrant/systemd/build/../src/shared/conf-parser.c:271:16
    #5 0x7f456868c0bc in config_parse /home/vagrant/systemd/build/../src/shared/conf-parser.c:396:21
    #6 0x7f456868e63e in config_parse_many_files /home/vagrant/systemd/build/../src/shared/conf-parser.c:453:21
    #7 0x7f456868eca7 in config_parse_many /home/vagrant/systemd/build/../src/shared/conf-parser.c:512:16
    #8 0x57c39c in network_load_one /home/vagrant/systemd/build/../src/network/networkd-network.c:471:13
    #9 0x5434b0 in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/network/fuzz-network-parser.c:26:16
    #10 0x44e408 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/systemd/out/fuzz-network-parser+0x44e408)
    #11 0x433525 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/vagrant/systemd/out/fuzz-network-parser+0x433525)
    #12 0x43c469 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/systemd/out/fuzz-network-parser+0x43c469)
    #13 0x42c4c6 in main (/home/vagrant/systemd/out/fuzz-network-parser+0x42c4c6)
    #14 0x7f4567b821a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
```

**Comment by evverx** [comment]
cc @ssahani
