### ISSUE TITLE
fuzz-network-parser seems to crash somewhere in traffic_control_free

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#16386]
It was reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23950 yesterday
```
Running: /crash-e78459a5bcadfa87c5725c2837e8739299e93d5d
--
  | Code should not be reached 'Invalid traffic control type' at src/network/tc/tc.c:20, function void traffic_control_free(TrafficControl *)(). Aborting.
  | MemorySanitizer:DEADLYSIGNAL
  | ==1==ERROR: MemorySanitizer: ABRT on unknown address 0x000000000001 (pc 0x7faf258d1428 bp 0x7ffef137b1c0 sp 0x7ffef137b018 T1)
  | #0 0x7faf258d1428 in gsignal /build/glibc-LK5gWL/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
  | #1 0x7faf258d3029 in abort /build/glibc-LK5gWL/glibc-2.23/stdlib/abort.c:89
  | #2 0x7faf26cf71f7 in log_assert_failed_unreachable_realm systemd/src/basic/log.c:856:9
  | #3 0x538459 in traffic_control_free systemd/src/network/tc/tc.c:20:17
  | #4 0x4e52e0 in network_free systemd/src/network/networkd-network.c:742:9
  | #5 0x4e2fd9 in network_unref systemd/src/network/networkd-network.c:770:1
  | #6 0x4e22cf in network_unrefp systemd/src/network/networkd-network.h:335:1
  | #7 0x4e1840 in network_load_one systemd/src/network/networkd-network.c:572:1
  | #8 0x4a675c in LLVMFuzzerTestOneInput systemd/src/network/fuzz-network-parser.c:26:16
  | #9 0x80d7c5 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:558:15
  | #10 0x79effb in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:296:6
  | #11 0x7b2471 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:796:9
  | #12 0x79e220 in main /src/libfuzzer/FuzzerMain.cpp:19:10
  | #13 0x7faf258bc82f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/libc-start.c:291
  | #14 0x42abd8 in _start
  |  
  | MemorySanitizer can not provide additional info.
  | SUMMARY: MemorySanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35428)
  | ==1==ABORTING
```

**Comment by evverx** [comment]
Looking at the testcase analysis on other jobs at https://oss-fuzz.com/testcase-detail/5699230107435008
![Screenshot 2020-07-07 at 06 19 22](https://user-images.githubusercontent.com/10195800/86700522-d8aaa980-c019-11ea-924e-cdfde04b0240.png)
I think it's a duplicate of https://github.com/systemd/systemd/issues/16367. I'm not sure why it was reported after that bug was fixed. I'll go ahead and close it.

**Comment by yuwata** [comment]
Yeah, it seems so. I cannot reproduce the error anymore.
