### ISSUE TITLE
systemd-resolve misses CNAME in DNS response for DNAME zones

### ISSUE THREAD

**Issue by bdrung** [systemd/systemd#16598]
**systemd version the issue has been seen with**
245.4-4ubuntu3.2

**Used distribution**
Ubuntu 20.04

**Expected behaviour you didn't see**
When using systemd-resolve in combination with DNS zones with DNAME, I expect clients to successfully resolve IP addresses for hosts in those DNAME zones:

```
$ dig internal-host1.alias.example.org @127.0.0.53
[...]
;; ANSWER SECTION:
alias.example.org.               604800  IN    DNAME   real.example.org.
internal-host1.alias.example.org. 604800 IN    CNAME   internal-host1.real.example.org.
internal-host1.real.example.org. 7199    IN    A       192.168.0.1
$ host internal-host1.alias.example.org
internal-host1.alias.example.org is an alias for internal-host1.real.example.org.
internal-host1.real.example.org has address 192.168.0.1
```

**Unexpected behaviour you saw**

Resolving the first hostname in the zones succeeds (like shows above), but all consecutive hostnames will fail for at least these clients:

* `gethostbyname` fails with: Unknown server error
* `getaddrinfo` fails with EAI_NODATA: No address associated with hostname
* Go’s native DNS resolver stub

The response from systemd-resolve is different in those cases:

```
$ dig internal-host2.alias.example.org @127.0.0.53
[...]
;; ANSWER SECTION:
alias.example.org.             7010    IN      DNAME   real.example.org.
internal-host2.real.example.org. 86400 IN      A       192.168.0.2
$ host internal-host2.alias.example.org
alias.example.org has DNAME record real.example.org.
internal-host2.real.example.org has address 192.168.0.2
alias.example.org has DNAME record real.example.org.
alias.example.org has DNAME record real.example.org.
```

The DNS response from systemd-resolve lacks an CNAME entry which causes the clients mentioned above to fail.

**Steps to reproduce the problem**

1. Create a DNS DNAME entry pointing from `alias.example.org` to `real.example.org` and at least two DNS entries in `real.example.org`.

2. Create a small DNS client, e.g. `getaddrinfo.py` which uses `getaddrinfo`:

```python
#!/usr/bin/python3

import socket
import sys

for hostname in sys.argv[1:]:
    info = socket.getaddrinfo(hostname, None, family=socket.AF_INET, type=socket.SOCK_DGRAM)
    for (family, type_, proto, canonname, sockaddr) in info:
        print(sockaddr[0])
```

3. Flush the caches:
```
systemd-resolve --flush-caches
```

4. Resolve the first host successfully:
```
$ systemd-resolve internal-host1.alias.example.org
internal-host1.alias.example.org: 192.168.0.1       -- link: tun0
                                  (internal-host1.real.example.org)

-- Information acquired via protocol DNS in 37.1ms.
-- Data is authenticated: no
```

```
$ dig internal-host1.alias.example.org @127.0.0.53
[...]
;; ANSWER SECTION:
internal-host1.alias.example.org. 7149 IN      CNAME   internal-host1.real.example.org.
internal-host1.real.example.org.  7149 IN      A       192.168.0.1
```

```
$ ./getaddrinfo.py internal-host1.alias.example.org
192.168.0.1
```

```
$ host internal-host1.alias.example.org
internal-host1.alias.example.org is an alias for internal-host1.real.example.org.
internal-host1.real.example.org has address 192.168.0.1
```

5. Resolve the second host which will fail:
```
$ systemd-resolve internal-host2.alias.example.org
internal-host2.alias.example.org: 192.168.0.2 -- link: tun0
                                  (internal-host2.real.example.org)

-- Information acquired via protocol DNS in 35.6ms.
-- Data is authenticated: no
```

```
$ dig internal-host2.alias.example.org @127.0.0.53
[...]
;; ANSWER SECTION:
alias.example.org.               7150  IN      DNAME   real.example.org.
internal-host2.real.example.org. 7186  IN      A       192.168.0.2
```

```python
$ ./getaddrinfo.py internal-host2.alias.example.org
Traceback (most recent call last):
  File "./getaddrinfo.py", line 7, in <module>
    info = socket.getaddrinfo(hostname, None, family=socket.AF_INET, type=socket.SOCK_DGRAM)
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
```

```
$ host internal-host2.alias.example.org
alias.example.org has DNAME record real.example.org.
internal-host2.real.example.org has address 192.168.0.2
alias.example.org has DNAME record real.example.org.
alias.example.org has DNAME record real.example.org.
```

**Comment by AngusMcGyver** [comment]
any news on that? still happen on ubuntu 24.04.

only the first query contains the CNAME in answer section and therefor programs cant resolve ip addresses correctly.

```
/lib/systemd/systemd-resolved --version

systemd 255 (255.4-1ubuntu8.4)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

```
#ask the actual dns (bind9)
dig host1.aliasdomain @10.10.10.10
    […]
    ;; QUESTION SECTION:
    ;host1.aliasdomain.		IN	A
    
    ;; ANSWER SECTION:
    aliasdomain.		43200	IN	DNAME	domain.
    host1.aliasdomain.		43200	IN	CNAME	host1.domain.
    host1.domain.		3600	IN	A	10.10.10.1
    […]

dig host2.aliasdomain @10.10.10.10
    […]
    ;; QUESTION SECTION:
    ;host2.aliasdomain.		IN	A
    
    ;; ANSWER SECTION:
    aliasdomain.		43200	IN	DNAME	domain.
    host2.aliasdomain.		43200	IN	CNAME	host2.domain.
    host2.domain.		3600	IN	A	10.10.10.1
    […]
```

```
#ask local systemd-resolve
systemctl restart systemd-resolved.service

dig host1.aliasdomain @127.0.0.53
    […]
    ;; QUESTION SECTION:
    ;host1.aliasdomain.		IN	A
    
    ;; ANSWER SECTION:
    aliasdomain.		43200	IN	DNAME	domain.
    host1.aliasdomain.		43200	IN	CNAME	host1.domain.
    host1.domain.		3600	IN	A	10.10.10.1
    […]

dig host2.aliasdomain @127.0.0.53
    […]
    ;; QUESTION SECTION:
    ;host2.aliasdomain.		IN	A

    ;; ANSWER SECTION:
    aliasdomain.		43200	IN	DNAME	domain.
    host2.domain.		3600	IN	A	10.10.10.2
    […]
```

```
#test with ping
systemctl restart systemd-resolved.service

ping host1.aliasdomain
    PING host1.domain (10.10.10.1) 56(84) bytes of data.
    64 bytes from host1.domain (10.10.10.1): icmp_seq=1 ttl=64 time=0.447 ms
    ^C

ping host2.aliasdomain
    ping: Could not resolve hostname host2.aliasdomain: Name or service not known
```

**Comment by AngusMcGyver** [comment]
**update:**

as a workaround with high performance cost you can disable caching.

```
/etc/systemd/resolved.conf:
    […]
    Cache=no

systemctl restart systemd-resolved.service
```

**Comment by llucas-sb** [comment]
alternatively, you can use the `127.0.0.54` [proxy stub resolver](https://www.freedesktop.org/software/systemd/man/251/systemd-resolved.html#Description) by modifying the `/usr/lib/systemd/resolv.conf` file that is [not controlled](/usr/lib/systemd/resolv.conf) by systemd-resolved so it won't be modified if you adjust the daemon settings

edit that file to point to the proxy stub resolver and modify the symlink, then you lose dnssec, llmnr/mDNS but you get to keep the caching benefit
