### ISSUE TITLE
systemd PID 1 spinning on a loop

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#17590]
**systemd version the issue has been seen with**
 > 246 (to be precise, 246.1-1.fb3 from [Facebook rpm-backports](https://github.com/facebookincubator/rpm-backports/tree/master/rpms/systemd)).

**Used distribution**
 > CentOS 8

**Linux kernel version used** (`uname -a`)
 > 5.2.9

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 > systemd PID 1 spinning on a loop

`top` indicates that PID 1 is spending 100% CPU on one core.

System doesn't respond to `systemctl`, even after a while.

I got a live coredump (`gcore`) of PID 1 and inspected it with a debugger, found this backtrace:

```
(gdb) bt                                                                                
#0  unit_get_needs_bpf_firewall (u=0x560281dffc50) at ../src/core/cgroup.c:1397
#1  unit_get_bpf_mask (u=0x560281dffc50) at ../src/core/cgroup.c:1453
#2  unit_get_own_mask (u=0x560281dffc50) at ../src/core/cgroup.c:1472
#3  unit_get_own_mask (u=<optimized out>, u=<optimized out>) at ../src/core/cgroup.c:1459                                                                                        
#4  0x0000560281977568 in unit_get_subtree_mask (u=0x560281dffc50) at ../src/core/cgroup.c:1565                                                                                  
#5  unit_get_members_mask (u=0x560281e00800) at ../src/core/cgroup.c:1515                                                                                                        
#6  unit_get_members_mask (u=<optimized out>, u=<optimized out>) at ../src/core/cgroup.c:1498                                                                                    
#7  0x00005602819775fa in unit_get_target_mask (u=u@entry=0x560281e00800) at ../src/core/cgroup.c:1578                                                                           
#8  0x000056028197c19a in unit_realize_cgroup_now (u=0x560281e00800, state=MANAGER_STARTING) at ../src/core/cgroup.c:2260                                                        
#9  0x00005602819fb1f3 in manager_dispatch_cgroup_realize_queue (m=0x560281ca55d0) at ../src/core/cgroup.c:2307                                                                  
#10 manager_loop (m=0x560281ca55d0) at ../src/core/manager.c:2959
#11 invoke_main_loop (m=0x560281ca55d0, saved_rlimit_nofile=<optimized out>, saved_rlimit_memlock=<optimized out>, ret_reexecute=<optimized out>, ret_retval=<optimized out>, 
    ret_shutdown_verb=<optimized out>, ret_fds=<optimized out>, ret_switch_root_dir=<optimized out>, ret_switch_root_init=<optimized out>, ret_error_message=<optimized out>)
    at ../src/core/main.c:1862         
#12 0x0000560281937162 in main (argc=5, argv=0x7ffdc1fd9068) at ../src/core/main.c:2841
```

Inspecting the relevant part of the code, it looks like systemd is looping on slice units going through parent units, but for some reason it seems this particular unit points back to itself (?).

```
(gdb) p u->id                                                                                                                                                                    
$1 = 0x560281d846e0 "service_cert_scribed_client.service"                                                                                                                        
(gdb) p u->slice->target->id                                                            
$2 = 0x560281da7b00 "system-timers-service_cert_scribed_client.slice"
(gdb) p u->slice->target->slice->target->id
$3 = 0x560281da7b00 "system-timers-service_cert_scribed_client.slice"
```

I have the core file, so let me know if you'd like me to check for other information from the file (perhaps to validate a hypothesis of what might have gone wrong...)

cc @anitazha @cdown.

**Comment by poettering** [comment]
yikes. Any idea how to to reproduce this?

**Comment by filbranden** [comment]
Not really... Also, I only saw it in one box. So, for what it's worth, we could just blame gamma rays and be done with it...

**Comment by vcaputo** [comment]
Seems likely to be a real bug, or at least it's prudent to assume it's probably real and not flaky RAM or gamma rays...

Presumably it wouldn't be difficult to detect creating such a tight loop and throwing an assert when attempted.

**Comment by thesamesam** [comment]
I think I might have hit this too.

strace -p has a bunch of:
```
close(149591)                           = 0
sendmsg(77, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\232\0\0\0.#\0\0\240\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=176}, {iov_base="2\0\0\0drkonqi-coredump-processor@8"..., iov_len=154}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 330
sendmsg(77, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1L\0\0\0/#\0\0\246\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=184}, {iov_base=" \0\0\0org.freedesktop.systemd1.Man"..., iov_len=76}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 260
close(149592)                           = 0
close(149593)                           = 0
sendmsg(77, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\232\0\0\0000#\0\0\240\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=176}, {iov_base="2\0\0\0drkonqi-coredump-processor@6"..., iov_len=154}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 330
sendmsg(77, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1L\0\0\0001#\0\0\246\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=184}, {iov_base=" \0\0\0org.freedesktop.systemd1.Man"..., iov_len=76}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 260
close(149594)                           = 0
close(149595)                           = 0
sendmsg(77, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\231\0\0\0002#\0\0\240\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=176}, {iov_base="1\0\0\0drkonqi-coredump-processor@9"..., iov_len=153}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 329
sendmsg(77, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1L\0\0\0003#\0\0\246\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=184}, {iov_base=" \0\0\0org.freedesktop.systemd1.Man"..., iov_len=76}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 260
close(149596)                           = 0
close(149597)                           = 0
sendmsg(77, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\231\0\0\0004#\0\0\240\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=176}, {iov_base="1\0\0\0drkonqi-coredump-processor@4"..., iov_len=153}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 329
```

Attaching gdb to PID 1 gives:
```
0x00007f9fbcc5011e in unit_get_own_mask (u=0x55a7f49f1900) at ../systemd-stable-255.4/src/core/cgroup.c:2094

warning: 2094   ../systemd-stable-255.4/src/core/cgroup.c: No such file or directory
(gdb) bt
#0  0x00007f9fbcc5011e in unit_get_own_mask (u=0x55a7f49f1900) at ../systemd-stable-255.4/src/core/cgroup.c:2094
#1  unit_get_subtree_mask (u=0x55a7f49f1900) at ../systemd-stable-255.4/src/core/cgroup.c:2132
#2  unit_get_members_mask (u=u@entry=0x55a7d7f88620) at ../systemd-stable-255.4/src/core/cgroup.c:2149
#3  0x00007f9fbcc50156 in unit_get_members_mask (u=<optimized out>) at ../systemd-stable-255.4/src/core/cgroup.c:2140
#4  unit_get_subtree_mask (u=0x55a7d7f88620) at ../systemd-stable-255.4/src/core/cgroup.c:2132
#5  unit_get_members_mask (u=0x55a7d7f463a0) at ../systemd-stable-255.4/src/core/cgroup.c:2149
#6  0x00007f9fbcc429ac in unit_get_members_mask (u=<optimized out>) at ../systemd-stable-255.4/src/core/cgroup.c:2135
#7  unit_get_siblings_mask (u=0x55a813c83900) at ../systemd-stable-255.4/src/core/cgroup.c:2166
#8  unit_get_target_mask (u=0x55a813c83900) at ../systemd-stable-255.4/src/core/cgroup.c:2211
#9  0x00007f9fbcc51139 in unit_add_family_to_cgroup_realize_queue (u=0x55a7d7f463a0) at ../systemd-stable-255.4/src/core/cgroup.c:2231
#10 unit_add_family_to_cgroup_realize_queue (u=u@entry=0x55a7d7f88620) at ../systemd-stable-255.4/src/core/cgroup.c:2996
#11 0x00007f9fbcd3d746 in unit_free (u=0x55a7ede40020) at ../systemd-stable-255.4/src/core/unit.c:799
#12 0x00007f9fbcce0375 in manager_clear_jobs_and_units (m=m@entry=0x55a7d7cc93f0) at ../systemd-stable-255.4/src/core/manager.c:1593
#13 0x00007f9fbcce0a4f in manager_clear_jobs_and_units (m=0x55a7d7cc93f0) at ../systemd-stable-255.4/src/core/manager.c:1590
#14 manager_reload (m=m@entry=0x55a7d7cc93f0) at ../systemd-stable-255.4/src/core/manager.c:3567
#15 0x000055a7d608b200 in invoke_main_loop (m=0x55a7d7cc93f0, saved_rlimit_nofile=0x7ffe9b8aa150, saved_rlimit_memlock=0x7ffe9b8aa140, ret_retval=<synthetic pointer>,
    ret_fds=0x7ffe9b8aa118, ret_switch_root_dir=<synthetic pointer>, ret_switch_root_init=<synthetic pointer>, ret_error_message=0x7ffe9b8aa128)
    at ../systemd-stable-255.4/src/core/main.c:1998
#16 main (argc=<optimized out>, argv=0x7ffe9b8aa848) at ../systemd-stable-255.4/src/core/main.c:3124
```

I don't have a way of reproducing it, unfortunately.

**Comment by poettering** [comment]
So the original issue wasn't reproducible and 4 years passed. Let#s close this. If anyone manages to reproduce this, please open a new issue.
