### ISSUE TITLE
`test_ipv6_token_*` subtests (systemd-networkd-tests.py) intermittently fail

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#18453]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux & CentOS 7

Some of the `test_ipv6_token_*` subtests of `systemd-networkd-tests.py` started failing sporadically. According to CentOS CI logs the first fail happened around today's midnight (2021-02-03 12:50 AM CET).

```
======================================================================
ERROR: test_ipv6_token_prefixstable_without_address (__main__.NetworkdRATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/test/test-network/systemd-networkd-tests.py", line 3519, in test_ipv6_token_prefixstable_without_address
    self.wait_online(['veth99:routable', 'veth-peer:degraded'])
  File "/build/test/test-network/systemd-networkd-tests.py", line 575, in wait_online
    check_output(*args, env=env)
  File "/build/test/test-network/systemd-networkd-tests.py", line 49, in check_output
    return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/systemd-meson-build/systemd-networkd-wait-online', '--timeout=20s', '--interface=veth99:routable', '--interface=veth-peer:degraded']' returned non-zero exit status 1.

----------------------------------------------------------------------
```
Logs:
 * [Arch+ASan] https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/2468/artifact//systemd-centos-ci/artifacts_all/artifacts_4_LY95/vagrant-logs.pIs/vagrant-arch-sanitizers-clang-testsuite.exh/systemd-networkd_sanitizers_FAIL.log

```
======================================================================
ERROR: test_ipv6_token_static (__main__.NetworkdRATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/./test/test-network/systemd-networkd-tests.py", line 3497, in test_ipv6_token_static
    self.wait_online(['veth99:routable', 'veth-peer:degraded'])
  File "/build/./test/test-network/systemd-networkd-tests.py", line 575, in wait_online
    check_output(*args, env=env)
  File "/build/./test/test-network/systemd-networkd-tests.py", line 49, in check_output
    return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/systemd/systemd-networkd-wait-online', '--timeout=20s', '--interface=veth99:routable', '--interface=veth-peer:degraded']' returned non-zero exit status 1.

----------------------------------------------------------------------
```
Logs:
 * [Arch] https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/2489/artifact//systemd-centos-ci/artifacts_53cRlw/vagrant-logs.7GP/vagrant-arch-testsuite.P2P/systemd-networkd-tests.py_FAIL.log
 * [Arch+ASan] https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/2471/artifact//systemd-centos-ci/artifacts_all/artifacts_zsq5YI/vagrant-logs.huX/vagrant-arch-sanitizers-clang-testsuite.T2c/systemd-networkd_sanitizers_FAIL.log
 * [Arch] https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/2501/artifact//systemd-centos-ci/artifacts_RIEicG/vagrant-logs.naS/vagrant-arch-testsuite.w9K/systemd-networkd-tests.py_FAIL.log

```
======================================================================
ERROR: test_ipv6_token_prefixstable (__main__.NetworkdRATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/test/test-network/systemd-networkd-tests.py", line 3509, in test_ipv6_token_prefixstable
    self.wait_online(['veth99:routable', 'veth-peer:degraded'])
  File "/build/test/test-network/systemd-networkd-tests.py", line 575, in wait_online
    check_output(*args, env=env)
  File "/build/test/test-network/systemd-networkd-tests.py", line 49, in check_output
    return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/systemd-meson-build/systemd-networkd-wait-online', '--timeout=20s', '--interface=veth99:routable', '--interface=veth-peer:degraded']' returned non-zero exit status 1.

----------------------------------------------------------------------
```
Logs:
 * [Arch+ASan] https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/2476/artifact//systemd-centos-ci/artifacts_all/artifacts_XtjQNr/vagrant-logs.dId/vagrant-arch-sanitizers-clang-testsuite.0Ms/systemd-networkd_sanitizers_FAIL.log

```
======================================================================
FAIL: test_ipv6_prefix_delegation (__main__.NetworkdRATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 3478, in test_ipv6_prefix_delegation
    self.wait_online(['veth99:routable', 'veth-peer:degraded'])
  File "./test/test-network/systemd-networkd-tests.py", line 583, in wait_online
    self.wait_operstate(link.split(':')[0], None, setup_state, setup_timeout)
  File "./test/test-network/systemd-networkd-tests.py", line 548, in wait_operstate
    self.fail(f'Timed out waiting for {link} to reach state {operstate}/{setup_state}')
AssertionError: Timed out waiting for veth99 to reach state \S+/configured

----------------------------------------------------------------------
```
Logs:
 * [CentOS 7] https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos7/2470/artifact//systemd-centos-ci/artifacts_LAsfpE/testsuite-logs-upstream.8dd/systemd-networkd-tests.py_FAIL.log

/cc @bluca, @yuwata

**Comment by yuwata** [comment]
It seems that the issue is caused by the following:
1. veth99 once becomes in 'configured' state, however veth-peer not, as it does not have `IPv6AcceptRA=no` (which was added in #18454.)
2. veth99 receives another RA message, then its state is changed to 'configuring' state.
3. veth-peer becomes in 'configured' state, when NDISC timeouts.
4. unfortunately, `wait-for-online` reaches to the timeout before veth99 finishes to process the second RA message.

So, I guess, #18454 should 'fix' this issue, as veth-peer enters configured state earlier now, so veth99 only receives one RA message.


I think, NDISC should not change the state 'configured' -> 'configuring' when no new addresses or routes will be assigned.

**Comment by yuwata** [comment]
#18455 should fix the root of this issue.
