### ISSUE TITLE
Possible dynamic-stack-buffer-overflow in dissected_image_acquire_metadata()

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#18893]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux

In https://github.com/systemd/systemd-centos-ci/pull/351 I'm slowly trying to extend our sanitizer coverage, and currently the TEST-50-DISSECT fails under ASan with following:

```
testsuite-50.sh[295]: ==295==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffcabf84819 at pc 0x7fe9ad16d1aa bp 0x7ffcabf847b0 sp 0x7ffcabf847a8
testsuite-50.sh[295]: READ of size 1 at 0x7ffcabf84819 thread T0 ((sd-dissect))
testsuite-50.sh[295]:     #0 0x7fe9ad16d1a9 in dissected_image_acquire_metadata /systemd-meson-build/../build/src/shared/dissect-image.c:2323:25
testsuite-50.sh[295]:     #1 0x55ba1c0420c2 in action_dissect /systemd-meson-build/../build/src/dissect/dissect.c:377:13
testsuite-50.sh[295]:     #2 0x55ba1c03fb54 in run /systemd-meson-build/../build/src/dissect/dissect.c:784:21
testsuite-50.sh[295]:     #3 0x55ba1c03f83a in main /systemd-meson-build/../build/src/dissect/dissect.c:803:1
testsuite-50.sh[295]:     #4 0x7fe9aca2fb24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
testsuite-50.sh[295]:     #5 0x55ba1c03f73d in _start (/usr/bin/systemd-dissect+0xa73d)
testsuite-50.sh[295]: Address 0x7ffcabf84819 is located in stack of thread T0 ((sd-dissect))
testsuite-50.sh[295]: SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow /systemd-meson-build/../build/src/shared/dissect-image.c:2323:25 in dissected_image_acquire_metadata
```

/cc @bluca

**Comment by bluca** [comment]
I think I see the issue - is the current CI running this test (to verify) ?

**Comment by mrc0mmand** [comment]
> I think I see the issue - is the current CI running this test (to verify) ?

Not yet, but if you file a PR I can run it manually against my CentOS CI branch.

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/18897
