### ISSUE TITLE
Semaphore CI: Assertion 'format' failed at src/core/unit-printf.c:232, function unit_full_printf(). Aborting

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#19178]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Debian Testing (LXC)

For the past day or so Semaphore CI has been failing when installing the latest systemd. Closer inspection shows systemd crashes during reload:

```
[ 8893.590912] systemd[1]: tmp.mount: Failed to load configuration: No such file or directory
[ 8893.590949] systemd[1]: var-lib.mount: Failed to load configuration: No such file or directory
[ 8893.590987] systemd[1]: var-lib-systemd.mount: Failed to load configuration: No such file or directory
[ 8893.591027] systemd[1]: var-lib-systemd-timers.mount: Failed to load configuration: No such file or directory
[ 8893.591063] systemd[1]: /lib/systemd/system/fstrim.service:16: Failed to parse system call, ignoring: close_range
[ 8893.591110] systemd[1]: /lib/systemd/system/fstrim.service:16: Failed to parse system call, ignoring: close_range
[ 8893.591816] systemd[1]: connman.service: Failed to load configuration: No such file or directory
[ 8893.591905] systemd[1]: NetworkManager.service: Failed to load configuration: No such file or directory
[ 8893.591953] systemd[1]: unit_file_find_fragment: systemd-networkd.service has alias dbus-org.freedesktop.network1.service
[ 8893.592078] systemd[1]: /lib/systemd/system/systemd-networkd.service:49: Failed to parse system call, ignoring: close_range
[ 8893.592598] systemd[1]: run-systemd-netif.mount: Failed to load configuration: No such file or directory
[ 8893.592697] systemd[1]: unit_file_find_fragment: multi-user.target has alias runlevel4.target
[ 8893.592753] systemd[1]: unit_file_find_fragment: multi-user.target has alias runlevel3.target
[ 8893.592796] systemd[1]: unit_file_find_fragment: multi-user.target has alias runlevel2.target
[ 8893.593416] systemd[1]: home.mount: Failed to load configuration: No such file or directory
[ 8893.593992] systemd[1]: var-log.mount: Failed to load configuration: No such file or directory
[ 8893.594072] systemd[1]: var-log-wtmp.mount: Failed to load configuration: No such file or directory
[ 8893.594121] systemd[1]: unit_file_find_fragment: runlevel5.target has alias default.target
[ 8893.594159] systemd[1]: unit_file_find_fragment: runlevel5.target has alias graphical.target
[ 8893.594735] systemd[1]: display-manager.service: Failed to load configuration: No such file or directory
[ 8893.594819] systemd[1]: unit_file_find_fragment: runlevel1.target has alias rescue.target
[ 8893.595353] systemd[1]: auditd.service: Failed to load configuration: No such file or directory
[ 8893.595436] systemd[1]: unit_file_find_fragment: systemd-logind.service has alias dbus-org.freedesktop.login1.service
[ 8893.595587] systemd[1]: /lib/systemd/system/systemd-logind.service:60: Failed to parse system call, ignoring: close_range
[ 8893.596137] systemd[1]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=240 reply_cookie=0 signature=s error-name=n/a error-message=n/a
[ 8893.596226] systemd[1]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=241 reply_cookie=0 signature=s error-name=n/a error-message=n/a
[ 8893.596283] systemd[1]: systemd-logind.service: Watching D-Bus name 'org.freedesktop.login1'.
[ 8893.596323] systemd[1]: run-systemd-users.mount: Failed to load configuration: No such file or directory
[ 8893.596359] systemd[1]: run-systemd-inhibit.mount: Failed to load configuration: No such file or directory
[ 8893.596442] systemd[1]: run-systemd-sessions.mount: Failed to load configuration: No such file or directory
[ 8893.596493] systemd[1]: run-systemd-shutdown.mount: Failed to load configuration: No such file or directory
[ 8893.596545] systemd[1]: var-lib-systemd-linger.mount: Failed to load configuration: No such file or directory
[ 8893.596584] systemd[1]: run-systemd-seats.mount: Failed to load configuration: No such file or directory
[ 8893.597331] systemd[1]: run-systemd-ask\x2dpassword.mount: Failed to load configuration: No such file or directory
[ 8893.598253] systemd[1]: unit_file_find_fragment: systemd-modules-load.service has alias kmod.service
[ 8893.598537] systemd[1]: apparmor.service: Failed to load configuration: No such file or directory
[ 8893.598758] systemd[1]: systemd-udev-trigger.service: Failed to load configuration: No such file or directory
[ 8893.599100] systemd[1]: unit_file_find_fragment: getty@tty1.service has alias autovt@tty1.service
[ 8893.599959] systemd[1]: plymouth-quit-wait.service: Failed to load configuration: No such file or directory
[ 8893.602126] systemd[1]: unit_file_find_fragment: systemd-sysctl.service has alias procps.service
[ 8893.602421] systemd[1]: Assertion 'format' failed at src/core/unit-printf.c:232, function unit_full_printf(). Aborting.
[ 8894.619434] systemd[1]: Caught <ABRT>, dumped core as pid 488.
[ 8894.620071] systemd[1]: Exiting PID 1...
```

I'll try to pinpoint the issue even more if possible.

**Comment by mrc0mmand** [comment]
The culprit seems to be 8a29862e32fc7981fe16fc8dd79ad6863a8dc486 - systemd without this commit chokes when it encounters `LoadCredential=` directive in a unit file:

```
# systemctl --version
systemd 247 (247.3-3)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
# lsb_release -cs
bullseye

# printf "[Service]\nLoadCredential=hello\n" > hello.service
# systemd-analyze verify ./hello.service 
Assertion 'format' failed at src/core/unit-printf.c:232, function unit_full_printf(). Aborting.
Aborted
```

<details>
<summary>Full backtrace</summary>

```gdb
(gdb) Starting program: /usr/bin/systemd-analyze verify ./hello.service
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Assertion 'format' failed at src/core/unit-printf.c:232, function unit_full_printf(). Aborting.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {8927191084203854339, 0, 112, 80, 93824994902016, 0, 
            32, 93824994924320, 18446744073709551615, 0, 80, 140737348782774, 
            4294967295, 140737350044544, 93824994924256, 140737350050208}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7a7f537 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x6a, sa_sigaction = 0x6a}, 
          sa_mask = {__val = {5, 93824994938757, 4330259647686753024, 
              93824994925669, 93824993363920, 2, 93824993356791, 232, 
              93824994931552, 93824994933072, 140737352426434, 0, 0, 0, 
              140737353912032, 93824992768224}}, sa_flags = 0, 
          sa_restorer = 0x5555557d7440}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff7d97a2e in log_assert_failed_realm (
    realm=realm@entry=LOG_REALM_SYSTEMD, 
    text=text@entry=0x55555565afd4 "format", 
    file=file@entry=0x555555666bf7 "src/core/unit-printf.c", 
    line=line@entry=232, 
    func=func@entry=0x5555556687d0 <__PRETTY_FUNCTION__.8.lto_priv.6> "unit_full_printf") at ../src/basic/log.c:864
No locals.
#3  0x00005555555d8369 in unit_full_printf (u=<optimized out>, 
    format=<optimized out>, ret=<optimized out>)
    at ../src/core/unit-printf.c:232
        table = {{specifier = 105 'i', 
            lookup = 0x7ffff7e0dbf0 <specifier_string>, data = 0x0}, {
            specifier = 73 'I', 
            lookup = 0x5555555d7180 <specifier_instance_unescaped>, 
            data = 0x0}, {specifier = 106 'j', 
            lookup = 0x5555555d71d0 <specifier_last_component>, data = 0x0}, {
            specifier = 74 'J', 
            lookup = 0x5555555d72b0 <specifier_last_component_unescaped>, 
            data = 0x0}, {specifier = 110 'n', 
            lookup = 0x7ffff7e0dbf0 <specifier_string>, 
            data = 0x5555557d7440}, {specifier = 78 'N', 
            lookup = 0x5555555d70a0 <specifier_prefix_and_instance>, 
            data = 0x0}, {specifier = 112 'p', 
            lookup = 0x5555555d3dd0 <specifier_prefix>, data = 0x0}, {
            specifier = 80 'P', 
            lookup = 0x5555555d70e0 <specifier_prefix_unescaped>, data = 0x0}, 
          {specifier = 102 'f', lookup = 0x5555555d7320 <specifier_filename>, 
            data = 0x0}, {specifier = 99 'c', 
            lookup = 0x5555555d7380 <specifier_cgroup>, data = 0x0}, {
            specifier = 114 'r', 
            lookup = 0x5555555d7470 <specifier_cgroup_slice>, data = 0x0}, {
            specifier = 82 'R', 
            lookup = 0x5555555d7400 <specifier_cgroup_root>, data = 0x0}, {
            specifier = 67 'C', 
            lookup = 0x5555555d7510 <specifier_special_directory>, 
            data = 0x2}, {specifier = 69 'E', 
            lookup = 0x5555555d7510 <specifier_special_directory>, 
            data = 0x4}, {specifier = 76 'L', 
            lookup = 0x5555555d7510 <specifier_special_directory>, 
            data = 0x3}, {specifier = 83 'S', 
            lookup = 0x5555555d7510 <specifier_special_directory>, 
            data = 0x1}, {specifier = 116 't', 
            lookup = 0x5555555d7510 <specifier_special_directory>, 
            data = 0x0}, {specifier = 104 'h', 
            lookup = 0x7ffff7e12150 <specifier_user_home>, data = 0x0}, {
            specifier = 115 's', 
            lookup = 0x7ffff7e12160 <specifier_user_shell>, data = 0x0}, {
            specifier = 97 'a', 
            lookup = 0x7ffff7e11ec0 <specifier_architecture>, data = 0x0}, {
            specifier = 98 'b', lookup = 0x7ffff7e11e10 <specifier_boot_id>, 
            data = 0x0}, {specifier = 66 'B', 
            lookup = 0x7ffff7e12070 <specifier_os_build_id>, data = 0x0}, {
            specifier = 72 'H', lookup = 0x7ffff7e11e80 <specifier_host_name>, 
            data = 0x0}, {specifier = 108 'l', 
            lookup = 0x7ffff7e11ea0 <specifier_short_host_name>, data = 0x0}, {
            specifier = 109 'm', 
            lookup = 0x7ffff7e11da0 <specifier_machine_id>, data = 0x0}, {
            specifier = 111 'o', lookup = 0x7ffff7e11f70 <specifier_os_id>, 
            data = 0x0}, {specifier = 118 'v', 
            lookup = 0x7ffff7e0dad0 <specifier_kernel_release>, data = 0x0}, {
            specifier = 119 'w', 
            lookup = 0x7ffff7e11ff0 <specifier_os_version_id>, data = 0x0}, {
            specifier = 87 'W', 
            lookup = 0x7ffff7e11ef0 <specifier_os_variant_id>, data = 0x0}, {
            specifier = 103 'g', 
            lookup = 0x7ffff7e120f0 <specifier_group_name>, data = 0x0}, {
            specifier = 71 'G', lookup = 0x7ffff7e0db50 <specifier_group_id>, 
            data = 0x0}, {specifier = 117 'u', 
            lookup = 0x7ffff7e12120 <specifier_user_name>, data = 0x0}, {
            specifier = 85 'U', lookup = 0x7ffff7e0db80 <specifier_user_id>, 
            data = 0x0}, {specifier = 84 'T', 
            lookup = 0x7ffff7e12170 <specifier_tmp_dir>, data = 0x0}, {
            specifier = 86 'V', 
            lookup = 0x7ffff7e121d0 <specifier_var_tmp_dir>, data = 0x0}, {
            specifier = 0 '\000', lookup = 0x0, 
            data = 0x7ffff7e689d4 <filename_is_valid+36>}}
        __PRETTY_FUNCTION__ = "unit_full_printf"
#4  0x00005555555ac892 in config_parse_load_credential (
    unit=0x5555557d7440 "hello.service", 
    filename=0x55555570b5b0 "/vagrant_data/./hello.service", line=2, 
    section=<optimized out>, section_line=<optimized out>, 
    lvalue=<optimized out>, ltype=0, rvalue=0x5555557da58f "hello", 
    data=0x5555557e7950, userdata=0x5555557e7360)
    at ../src/core/load-fragment.c:4588
        word = 0x5555557e5c60 "hello"
        k = 0x5555557e8f80 "hello"
        q = 0x0
        context = 0x5555557e7950
        u = 0x5555557e7360
        p = 0x0
        r = 0
        __PRETTY_FUNCTION__ = "config_parse_load_credential"
        __func__ = "config_parse_load_credential"
#5  0x00007ffff7dc3aec in next_assignment (userdata=0x5555557e7360, 
    flags=(unknown: 0), rvalue=0x5555557da58f "hello", 
    lvalue=0x5555557da580 "LoadCredential", section_line=1, 
    section=0x5555557d0a40 "Service", 
    table=0x5555555e7950 <load_fragment_gperf_lookup>, lookup=<optimized out>, 
    line=2, filename=0x55555570b5b0 "/vagrant_data/./hello.service", 
    unit=0x5555557d7440 "hello.service") at ../src/shared/conf-parser.c:133
        func = 0x5555555ac5c0 <config_parse_load_credential>
        ltype = 0
        data = 0x5555557e7950
        r = <optimized out>
        func = <optimized out>
        ltype = <optimized out>
        data = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        __func__ = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
#6  parse_line (unit=0x5555557d7440 "hello.service", 
    filename=0x55555570b5b0 "/vagrant_data/./hello.service", line=2, 
    sections=<optimized out>, lookup=<optimized out>, 
    table=0x5555555e7950 <load_fragment_gperf_lookup>, flags=(unknown: 0), 
    section=0x7fffffffe0c0, section_line=0x7fffffffe0b4, 
    section_ignored=0x7fffffffe0b3, l=<optimized out>, userdata=0x5555557e7360)
    at ../src/shared/conf-parser.c:240
        e = <optimized out>
        __PRETTY_FUNCTION__ = "parse_line"
        __func__ = "parse_line"
#7  0x00007ffff7dc42d6 in config_parse (unit=0x5555557d7440 "hello.service", 
    filename=0x55555570b5b0 "/vagrant_data/./hello.service", 
    f=f@entry=0x5555556fecf0, sections=0x55555565d169 "Unit", 
    lookup=0x7ffff7dbb700 <config_item_perf_lookup>, 
    table=0x5555555e7950 <load_fragment_gperf_lookup>, flags=(unknown: 0), 
    userdata=0x5555557e7360, latest_mtime=0x0)
    at ../src/shared/conf-parser.c:378
        buf = 0x5555557da580 "LoadCredential"
        escaped = false
        e = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        l = 0x5555557da580 "LoadCredential"
        p = <optimized out>
        _level = <optimized out>
        section = 0x5555557d0a40 "Service"
        continuation = 0x0
        ours = 0x0
        line = 2
        section_line = 1
        section_ignored = false
        bom_seen = false
        r = <optimized out>
        fd = <optimized out>
        mtime = 1617306448210830
        __PRETTY_FUNCTION__ = "config_parse"
        __func__ = "config_parse"
#8  0x00005555555df262 in unit_load_fragment (u=0x5555557e7360)
    at ../src/core/unit.h:642
        f = 0x5555556fecf0
        st = {st_dev = 65027, st_ino = 1177672, st_nlink = 1, st_mode = 33188, 
          st_uid = 0, st_gid = 0, __pad0 = 0, st_rdev = 0, st_size = 31, 
          st_blksize = 4096, st_blocks = 8, st_atim = {tv_sec = 1617306454, 
            tv_nsec = 230830753}, st_mtim = {tv_sec = 1617306448, 
            tv_nsec = 210830753}, st_ctim = {tv_sec = 1617306448, 
            tv_nsec = 210830753}, __glibc_reserved = {0, 0, 0}}
        fragment = 0x55555570b5b0 "/vagrant_data/./hello.service"
        merged = 0x7fffffffe240
        names = 0x555555793480
        r = 0
        id = <optimized out>
        free_id = 0x555555706d30 " \\oUUU"
        fragment = <optimized out>
        names = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        __func__ = <optimized out>
        merged = <optimized out>
        id = <optimized out>
        free_id = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        f = <optimized out>
        st = <optimized out>
        _u = <optimized out>
        _u = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
#9  unit_load_fragment_and_dropin (u=0x5555557e7360, 
    fragment_required=<optimized out>) at ../src/core/unit.c:1439
        r = <optimized out>
        __PRETTY_FUNCTION__ = "unit_load_fragment_and_dropin"
        st = <optimized out>
#10 0x00005555555b8f86 in service_load (u=0x5555557e7360)
    at ../src/core/service.c:770
        s = 0x5555557e7360
        r = <optimized out>
#11 0x00005555555e53d3 in unit_load (u=0x5555557e7360)
    at ../src/core/unit.h:642
        r = <optimized out>
        __PRETTY_FUNCTION__ = "unit_load"
        __func__ = "unit_load"
#12 0x000055555564d0f5 in manager_dispatch_load_queue (m=0x5555556f5c20)
    at ../src/core/manager.c:1930
        u = <optimized out>
        n = <optimized out>
        u = <optimized out>
        n = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
#13 manager_dispatch_load_queue.isra.0 (m=0x5555556f5c20)
    at ../src/core/manager.c:1912
        u = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
#14 0x00005555555b4080 in manager_load_unit (m=0x5555556f5c20, 
    name=<optimized out>, path=<optimized out>, e=<optimized out>, 
    _ret=0x7fffffffe488) at ../src/core/manager.c:2060
        r = 0
        __PRETTY_FUNCTION__ = "manager_load_unit"
#15 0x00005555555960b7 in manager_load_startable_unit_or_warn (name=0x0, 
    ret=0x7fffffffe440, path=0x55555573e980 "/vagrant_data/./hello.service", 
    m=<optimized out>) at ../src/core/manager.c:2066
        error = {name = 0x0, message = 0x0, _need_free = 0}
        unit = 0x5555557e7360
        r = <optimized out>
        error = <optimized out>
        unit = <optimized out>
        r = <optimized out>
        __func__ = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
#16 verify_units (run_generators=<optimized out>, check_man=true, 
    scope=<optimized out>, filenames=<optimized out>)
    at ../src/analyze/analyze-verify.c:266
        prepared = 0x55555573e980 "/vagrant_data/./hello.service"
        flags = <optimized out>
        m = 0x5555556f5c20
        units = 0x7fffffffe440
        var = 0x5555556f59b0 ".::"
        k = 0
        i = <optimized out>
        count = 0
        r = 0
        filename = 0x7fffffffe648
        flags = <optimized out>
        m = <optimized out>
        units = <optimized out>
        var = <optimized out>
        r = <optimized out>
        k = <optimized out>
        i = <optimized out>
        count = <optimized out>
        filename = <optimized out>
        __func__ = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        prepared = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
#17 do_verify (argc=<optimized out>, argv=<optimized out>, 
    userdata=<optimized out>) at ../src/analyze/analyze.c:2155
No locals.
#18 0x000055555558f8ea in run (argv=0x7fffffffe638, argc=3)
    at ../src/analyze/analyze.c:2458
        r = <optimized out>
        verbs = <optimized out>
        r = <optimized out>
#19 main (argc=3, argv=0x7fffffffe638) at ../src/analyze/analyze.c:2461
        r = <optimized out>

```
</details>

/cc @poettering @bluca

**Comment by bluca** [comment]
uh I'm very confused, how can `assert(format)` trigger if the commit added an explicit check `if (isempty(p))` (p == format)

**Comment by mrc0mmand** [comment]
> uh I'm very confused, how can `assert(format)` trigger if the commit added an explicit check `if (isempty(p))` (p == format)

The crashing systemd _doesn't_ have the mentioned commit (thus is missing the `isempty()` cond). This happens during systemd upgrade in Semaphore CI.

**Comment by bluca** [comment]
Ah I see - where is the LoadCredential= coming from in the CI?

**Comment by mrc0mmand** [comment]
> Ah I see - where is the LoadCredential= coming from in the CI?

In upstream it's afaik present in [systemd-firstboot.service](https://github.com/systemd/systemd/blob/main/units/systemd-firstboot.service) and [systemd-sysusers.service](https://github.com/systemd/systemd/blob/main/units/systemd-sysusers.service). So I guess one of them gets installed via the `systemd.deb` package and when installing `systemd-timesyncd.deb` a daemon-reload happens:

```
Preparing to unpack .../0-systemd-timesyncd.deb ...
Unpacking systemd-timesyncd (248.87.g3d5e43ae6a.0) over (247.3-3) ...
Preparing to unpack .../1-systemd-sysv.deb ...
Unpacking systemd-sysv (248.87.g3d5e43ae6a.0) over (247.3-3) ...
Preparing to unpack .../2-libpam-systemd.deb ...
Unpacking libpam-systemd:amd64 (248.87.g3d5e43ae6a.0) over (247.3-3) ...
Preparing to unpack .../3-libnss-systemd.deb ...
Unpacking libnss-systemd:amd64 (248.87.g3d5e43ae6a.0) over (247.3-3) ...
Preparing to unpack .../4-systemd.deb ...
Unpacking systemd (248.87.g3d5e43ae6a.0) over (247.3-3) ...
Preparing to unpack .../5-libsystemd0.deb ...
Unpacking libsystemd0:amd64 (248.87.g3d5e43ae6a.0) over (247.3-3) ...
Setting up libsystemd0:amd64 (248.87.g3d5e43ae6a.0) ...
...
(Reading database ... 16339 files and directories currently installed.)
Preparing to unpack .../binaries/./libudev1.deb ...
Unpacking libudev1:amd64 (248.87.g3d5e43ae6a.0) over (247.3-3) ...
Setting up libudev1:amd64 (248.87.g3d5e43ae6a.0) ...
Setting up systemd-timesyncd (248.87.g3d5e43ae6a.0) ...
Installing new version of config file /etc/systemd/timesyncd.conf ...
Failed to reload daemon: Connection reset by peer
```

**Comment by bluca** [comment]
it's not empty in any of those though:

```
$ git grep -r LoadCrede units/
units/systemd-firstboot.service:LoadCredential=passwd.hashed-password.root
units/systemd-firstboot.service:LoadCredential=passwd.plaintext-password.root
units/systemd-firstboot.service:LoadCredential=passwd.shell.root
units/systemd-firstboot.service:LoadCredential=firstboot.locale
units/systemd-firstboot.service:LoadCredential=firstboot.locale-messages
units/systemd-firstboot.service:LoadCredential=firstboot.keymap
units/systemd-firstboot.service:LoadCredential=firstboot.timezone
units/systemd-sysusers.service:LoadCredential=passwd.hashed-password.root
units/systemd-sysusers.service:LoadCredential=passwd.plaintext-password.root
units/systemd-sysusers.service:LoadCredential=passwd.shell.root
```

**Comment by mrc0mmand** [comment]
I compiled the latest [v247-stable](https://github.com/systemd/systemd-stable) on F33 to probe this even further:

```
# systemctl --version
systemd 247 (247.6)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

# printf "[Service]\nLoadCredential=passwd.hashed-password.root\n" > hello.service
# systemd-analyze verify ./hello.service 
...
Assertion 'format' failed at src/core/unit-printf.c:232, function unit_full_printf(). Aborting.
Aborted (core dumped)
```

```gdb
(gdb) del break
(gdb) break config_parse_load_credential
Breakpoint 5 at 0x43ba02: file ../src/core/load-fragment.c, line 4549.
(gdb) run
...
(gdb) fin
Run till exit from #0  extract_first_word (p=p@entry=0x7fffffffdd30, ret=ret@entry=0x7fffffffdd18, separators=separators@entry=0x500121 ":", flags=flags@entry=EXTRACT_DONT_COALESCE_SEPARATORS)
    at ../src/basic/extract-word.c:20
0x000000000043bac2 in config_parse_load_credential (unit=0x5c8b00 "hello.service", filename=0x5fb8f0 "/tmp/./hello.service", line=2, section=<optimized out>, section_line=<optimized out>, 
    lvalue=<optimized out>, ltype=0, rvalue=0x5c80bf "passwd.hashed-password.root", data=0x5dbae0, userdata=0x5db4f0) at ../src/core/load-fragment.c:4569
4569	        r = extract_first_word(&p, &word, ":", EXTRACT_DONT_COALESCE_SEPARATORS);
Value returned is $6 = 1
(gdb) info locals
word = 0x5dcdb0 "passwd.hashed-password.root"
k = 0x0
q = 0x0
context = 0x5dbae0
u = 0x5db4f0
p = 0x0
r = <optimized out>
__PRETTY_FUNCTION__ = "config_parse_load_credential"
__func__ = "config_parse_load_credential"
...
(gdb) s
4586	        r = unit_full_printf(u, p, &q);
(gdb) s
unit_full_printf (u=u@entry=0x5db4f0, format=0x0, ret=ret@entry=0x7fffffffdd28) at ../src/core/unit-printf.c:207
207	int unit_full_printf(const Unit *u, const char *format, char **ret) {
(gdb) 
(gdb) p format
$9 = 0x0
```

So I guess the aforementioned patch (and possibly others) should be backported to v247-stable?

**Comment by bluca** [comment]
I think we want a smaller fix for v247, that doesn't allow an empty value - I'll prepare one

**Comment by bluca** [comment]
Still unclear how semaphore gets in a pickle though - is it running v247/v248 and then upgrades to the PR build?

**Comment by mrc0mmand** [comment]
> Still unclear how semaphore gets in a pickle though - is it running v247/v248 and then upgrades to the PR build?

Yes - the LXC container in Semaphore CI is based on Debian Testing, so it's upgrading from v247 (`Unpacking systemd (248.87.g3d5e43ae6a.0) over (247.3-3)`), whereas Ubuntu CI upgrades from v237 (`Unpacking systemd (248.86.gd872093ba0.0) over (237-3ubuntu10.45)`). I'd assume it would bump into the same issue if it was upgrading from v247 as well.

**Comment by bluca** [comment]
Ah, I understand now - ping @mbiebl you might want to backport this for bullseye, as there's a crash with invalid syntax in unit file: https://github.com/systemd/systemd-stable/pull/99

**Comment by bluca** [comment]
@mbiebl backport for Bullseye on Salsa: https://salsa.debian.org/systemd-team/systemd/-/merge_requests/126

**Comment by evverx** [comment]
I think it should have been caught by `fuzz-unit-file` but to judge from https://storage.googleapis.com/oss-fuzz-coverage/systemd/reports/20210401/linux/src/systemd/src/core/load-fragment.c.html#L4564 the fuzzer has never covered `config_parse_load_credential` (along with `config_parse_set_credential`) (probably because `test/fuzz/fuzz-unit-file/directives.service` hasn't been updated).

@mrc0mmand could you add something like
```
printf "service\n[Service]\nLoadCredential=passwd.hashed-password.root\n" >test/fuzz/fuzz-unit-file/github-19178
```
?

Looking at the other functions that have never been covered there, I think by analogy with `fuzz-network-parser` it would make sense to add a script blocking PRs where new directives are added without updating the seed corpora.

**Comment by mrc0mmand** [comment]
> I think it should have been caught by `fuzz-unit-file` but to judge from https://storage.googleapis.com/oss-fuzz-coverage/systemd/reports/20210401/linux/src/systemd/src/core/load-fragment.c.html#L4564 the fuzzer has never covered `config_parse_load_credential` (along with `config_parse_set_credential`) (probably because `test/fuzz/fuzz-unit-file/directives.service` hasn't been updated).
> 
> @mrc0mmand could you add something like
> 
> ```
> printf "service\n[Service]\nLoadCredential=passwd.hashed-password.root\n" >test/fuzz/fuzz-unit-file/github-19178
> ```
> 
> ?

Thanks for the analysis, definitely will do!

> 
> Looking at the other functions that have never been covered there, I think by analogy with `fuzz-network-parser` it would make sense to add a script blocking PRs where new directives are added without updating the seed corpora.

That's a very good point, will look into that.

**Comment by bluca** [comment]
I've opened https://github.com/systemd/systemd/pull/19184 to remove LoadCredential from those units, so that we can stop the failures. Also folks who build and install from the main tree would have a borken system until a forced reboot.
