### ISSUE TITLE
TypeError in mlog.py

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#19296]
```console
$ cat >meson.build <<EOF
project('a', 'c',
        version : 0)
EOF

$ meson build
ninja: Entering directory `build'
[0/1] Regenerating build files.
The Meson build system
Version: 0.56.2
Source dir: /home/zbyszek/src/systemd/a
Build dir: /home/zbyszek/src/systemd/a/build
Build type: native build
Project name: a
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 178, in _generate
    intr = interpreter.Interpreter(b)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter.py", line 2436, in __init__
    self.parse_project()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 504, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 544, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 537, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 550, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 909, in function_call
    return func(node, func_args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 197, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 228, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter.py", line 3211, in func_project
    mlog.log('Project version:', mlog.bold(self.project_version))
  File "/usr/lib/python3.9/site-packages/mesonbuild/mlog.py", line 225, in log
    arr = process_markup(args, True)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mlog.py", line 178, in process_markup
    arr.append(arg.get_text(keep))
  File "/usr/lib/python3.9/site-packages/mesonbuild/mlog.py", line 128, in get_text
    text = self.code + self.text + AnsiDecorator.plain_code
TypeError: can only concatenate str (not "int") to str
FAILED: build.ninja 
/usr/bin/meson --internal regenerate /home/zbyszek/src/systemd/a /home/zbyszek/src/systemd/a/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Comment by keszybz** [comment]
I guess it should reject the unquoted 0 early if such syntax is not allowed…

**Comment by keszybz** [comment]
https://github.com/mesonbuild/meson/issues/8644
