### ISSUE TITLE
networkd: dhcp4_address_handler can access deleted address.

### ISSUE THREAD

**Issue by williamspatrick** [systemd/systemd#20007]
**systemd version the issue has been seen with**
 > v248

**Used distribution**
 > Yocto / OpenBMC master

**Linux kernel version used** (`uname -a`)
 > `Linux bletchley 5.10.43-ba6fcac #1 SMP Tue Jun 22 16:56:03 UTC 2021 armv7l GNU/Linux`

**CPU architecture issue was seen on**
 > `arm32`

**Unexpected behaviour you saw**
 > `SIGABRT` in systemd-network

Assertion that failed was:
```
Jun 24 03:40:25 bletchley systemd-networkd[372]: Assertion 'a' failed at src/net
work/networkd-address.c:1860, function address_is_ready(). Aborting.
```

**Steps to reproduce the problem**
 > Seems to be a race condition in early boot sequence when running ARM32 hardware in QEMU (ast2600 chip using evb-ast2600 model in QEMU).

**Additional program output to the terminal or log subsystem illustrating the issue**

Backtrace:
```
Core was generated by `/lib/systemd/systemd-networkd'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x76bd2f60 in __GI_abort () at abort.c:79
#2  0x76e44bbc in log_assert_failed (text=<optimized out>, 
    file=<optimized out>, line=line@entry=1859, func=<optimized out>)
    at ../git/src/basic/log.c:860
#3  0x0048d95c in address_is_ready (a=<optimized out>)
    at ../git/src/network/networkd-address.c:1859
#4  address_is_ready (a=<optimized out>)
    at ../git/src/network/networkd-address.c:1858
#5  dhcp4_address_handler (link=0x76faa010, m=0x13feb58, rtnl=0x13e4d70)
    at ../git/src/network/networkd-dhcp4.c:782
#6  dhcp4_address_handler (rtnl=0x13e4d70, m=0x13feb58, link=0x76faa010)
    at ../git/src/network/networkd-dhcp4.c:766
#7  0x76ed4a88 in process_reply (m=<optimized out>, rtnl=0x13e4d70)
    at ../git/src/libsystemd/sd-netlink/sd-netlink.c:413
#8  process_running (ret=0x0, rtnl=0x13e4d70)
    at ../git/src/libsystemd/sd-netlink/sd-netlink.c:479
#9  sd_netlink_process (rtnl=0x13e4d70, ret=ret@entry=0x0)
    at ../git/src/libsystemd/sd-netlink/sd-netlink.c:508
#10 0x76ed4d5c in io_callback (s=s@entry=0x13e4e90, fd=<optimized out>, 
    revents=<optimized out>, userdata=<optimized out>)
    at ../git/src/libsystemd/sd-netlink/sd-netlink.c:784
#11 0x76f09f38 in source_dispatch (s=0x13e4e90)
    at ../git/src/libsystemd/sd-event/sd-event.c:3512
#12 0x76f0a298 in sd_event_dispatch (e=e@entry=0x13e34f0)
    at ../git/src/libsystemd/sd-event/sd-event.c:4077
#13 0x76f0b894 in sd_event_run (e=e@entry=0x13e34f0, timeout=<optimized out>)
    at ../git/src/libsystemd/sd-event/sd-event.c:4138
#14 0x76f0bb20 in sd_event_loop (e=0x13e34f0)
    at ../git/src/libsystemd/sd-event/sd-event.c:4159
#15 0x0043d118 in run (argv=<optimized out>, argc=<optimized out>)
    at ../git/src/network/networkd.c:104
#16 main (argc=<optimized out>, argv=<optimized out>)
    at ../git/src/network/networkd.c:111
```

Relevant journald (there is nothing clipped between these entries):
```
Jun 24 03:40:25 bletchley systemd[1]: Started Process Core Dump (PID 394/UID 0).

Jun 24 03:40:25 bletchley systemd-networkd[372]: Assertion 'a' failed at src/net
work/networkd-address.c:1860, function address_is_ready(). Aborting.
Jun 24 03:40:24 bletchley systemd-networkd[372]: eth1: address_free: 0x7d48c0
Jun 24 03:40:24 bletchley systemd-networkd[372]: eth1: address_free: 0x7d3d28
Jun 24 03:40:24 bletchley systemd-networkd[372]: Could not set hostname: Access 
denied
Jun 24 03:40:24 bletchley systemd-networkd[372]: eth1: dhcp_address: 0x7d48c0
Jun 24 03:40:24 bletchley systemd-networkd[372]: eth1: DHCPv4 address 10.0.2.15/
24 via 10.0.2.2
Jun 24 03:40:24 bletchley systemd[1]: Finished Wait for Network to be Configured
.
Jun 24 03:40:24 bletchley systemd-networkd[372]: sit0: Failed
Jun 24 03:40:24 bletchley systemd-networkd[372]: sit0: DHCP4 CLIENT: Failed to s
et MAC address: Invalid argument
Jun 24 03:40:24 bletchley systemd[1]: Starting Wait for Network to be Configured
```

The `address_free` and `dhcp_address` were added by me with the following patch:
 
```
diff --git a/src/network/networkd-address.c b/src/network/networkd-address.c
index 58b089901b..57bd93e207 100644
--- a/src/network/networkd-address.c
+++ b/src/network/networkd-address.c
@@ -114,6 +114,7 @@ Address *address_free(Address *address) {
         }
 
         if (address->link) {
+                log_link_warning(address->link, "address_free: %p", address);
                 NDiscAddress *n;
 
                 set_remove(address->link->addresses, address);
diff --git a/src/network/networkd-dhcp4.c b/src/network/networkd-dhcp4.c
index 6f06e2218d..c560634772 100644
--- a/src/network/networkd-dhcp4.c
+++ b/src/network/networkd-dhcp4.c
@@ -877,6 +877,7 @@ static int dhcp4_update_address(Link *link, bool announce) {
 
         if (!address_equal(link->dhcp_address, ret))
                 link->dhcp_address_old = link->dhcp_address;
+        log_link_warning(link, "dhcp_address: %p", ret);
         link->dhcp_address = ret;
 
         return 0;
```

I do not know why `address_free` is being called (yet) but it seems like there are cases where `address_free` is called on a DHCP4 address while the `dhcp4_address_handler` callback is pending.  When `dhcp4_address_handler` runs it is executing on a stale `address` handle and the `link->dhcp_address` has become `NULL`.  `address_is_ready` does an immediate assert if passed a `NULL` ptr (hence the assert listed above).

**Comment by yuwata** [comment]
Which point release (v248.x) do you use? If I remember correctly, I fixed similar issue soon after v248 was released.

**Comment by yuwata** [comment]
Ah, maybe duplicate of #18108, which is fixed in v249-rc1, but not fixed in any v248 point releases...

**Comment by williamspatrick** [comment]
@yuwata Thanks for the pointer. I tried to search for this in closed issues and failed, so sorry for the extra issue report. I’ll see if I can get those patches backported for testing or maybe try v249-rc1. 

That change looks like it was quite a bit of work, so thanks for fixing it already!

**Comment by williamspatrick** [comment]
v249-rc1 doesn't have the problem anymore.  Thanks again @yuwata.

```
Jun 24 12:14:31 bletchley systemd-networkd[332]: eth2: Gained IPv6LL
Jun 24 12:14:31 bletchley systemd-networkd[332]: eth1: Gained IPv6LL
Jun 24 12:14:31 bletchley systemd-networkd[332]: eth0: Gained IPv6LL
Jun 24 12:14:31 bletchley systemd-networkd[332]: Enumeration completed
Jun 24 12:14:31 bletchley systemd[1]: Started Network Service.
Jun 24 12:14:31 bletchley systemd-networkd[332]: sit0: DHCP4 CLIENT: Failed to set MAC address: Invalid argument
Jun 24 12:14:31 bletchley systemd-networkd[332]: sit0: Failed
Jun 24 12:14:32 bletchley systemd-networkd[332]: eth1: DHCPv4 address 10.0.2.15/24 via 10.0.2.2
Jun 24 12:14:33 bletchley systemd-networkd[332]: Could not set hostname: Access denied
Jun 24 12:14:33 bletchley systemd-networkd[332]: Could not set hostname: Access denied
```
