### ISSUE TITLE
systemd-resolved starts to busy loop when network is unreachable

### ISSUE THREAD

**Issue by Lastique** [systemd/systemd#20062]
systemd version: 247.3-3ubuntu3.1
Used distribution: Kubuntu 21.04 x86-64
Linux kernel version used: `5.11.0-22-lowlatency #23-Ubuntu SMP PREEMPT Thu Jun 17 01:38:59 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
CPU architecture issue was seen on: x86-64

**Steps to reproduce the problem**

1. Have your PC connected to a router, which is connected to the Internet. Configure `systemd-resolved` to use DoT (in my case, using public Google DNS).
2. Disconnect WAN from the router (unplug the WAN port).
3. Initiate host name resolution, for example, `ping ya.ru`.
4. Wait about 30-40 seconds.

**Unexpected behaviour you saw**

Name resolution does not complete (`ping` remains hanging with no output). After about 30 seconds, the `systemd-resolved` process starts consuming 100% of one logical CPU core. This CPU consumption does not end until `systemd-resolved` is restarted or WAN is re-connected.

**Expected behaviour you didn't see**

No excessive CPU consumption is expected.

**Additional program output to the terminal or log subsystem illustrating the issue**

I've collected a few backtraces of `systemd-resolved` while it was consuming CPU. They all look similar to this:

```
*** Stacktrace of process 166993 ***
Executable name: /usr/lib/systemd/systemd-resolved
0x00007fa3e035b05a in epoll_wait (epfd=4, events=0x556902d92990, maxevents=maxevents@entry=100, timeout=0) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  Id   Target Id                        Frame.
* 1    process 166993 "systemd-resolve" 0x00007fa3e035b05a in epoll_wait (epfd=4, events=0x556902d92990, maxevents=maxevents@entry=100, timeout=0) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30

Thread 1 (process 166993 "systemd-resolve"):
#0  0x00007fa3e035b05a in epoll_wait (epfd=4, events=0x556902d92990, maxevents=maxevents@entry=100, timeout=0) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007fa3e0aa5919 in sd_event_wait (e=e@entry=0x556902d6c700, timeout=timeout@entry=0) at ../src/libsystemd/sd-event/sd-event.c:3554
#2  0x00007fa3e0aa643c in sd_event_prepare (e=e@entry=0x556902d6c700) at ../src/libsystemd/sd-event/sd-event.c:3524
#3  0x00007fa3e0aa6a6e in sd_event_run (e=e@entry=0x556902d6c700, timeout=timeout@entry=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3741
#4  0x00007fa3e0aa6cdf in sd_event_loop (e=0x556902d6c700) at ../src/libsystemd/sd-event/sd-event.c:3772
#5  0x000055690134ee1d in run (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:92
#6  0x00005569013223ba in main (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:99
[Inferior 1 (process 166993) detached]
```

I also collected strace, which shows that the process is constantly looping in `epoll_wait`; the following two lines repeat:

```
epoll_wait(4, [{events=EPOLLHUP, data={u32=48026736, u64=93909507953776}}], 57, -1) = 1
gettid()                                = 166993
```

**Comment by poettering** [comment]
Is this reproducible with 248?

Does this use openssl or gnutls as TLS implemenation for DoT? (both are supported upstream, you distro made a choice there).

debug log  when this happens would be good. i.e. "systemctl service-log-level systemd-resolved debug" before this happens, then reproduce the isse, and paste any log otuput from the service then.

**Comment by Lastique** [comment]
> Is this reproducible with 248?

Sorry, I can't test. This is happening on my working machine, I don't want to break it by updating a core component such as systemd.

> Does this use openssl or gnutls as TLS implemenation for DoT? (both are supported upstream, you distro made a choice there).

Looks like it's using GnuTLS. Though, it looks like the issue is not related to TLS; it looks like a socket/epoll issue.

> debug log when this happens would be good. i.e. "systemctl service-log-level systemd-resolved debug" before this happens, then reproduce the isse, and paste any log otuput from the service then.

Here are the reduced logs:

[syslog.txt](https://github.com/systemd/systemd/files/6748948/syslog.txt)

I had to remove ~500MiB of repeating "Got POLLHUP from socket" messages in the middle.

**Comment by eworm-de** [comment]
I've seen this as well... No DoT involved here.
I am pretty sure this happens with v248, not sure for v249(rc) though.

Sadly I've never had the time to debug this when it happened.

**Comment by showermat** [comment]
I've been seeing this issue for a while on Arch, currently 249.4.  I have DoT enabled, but disabling it temporarily didn't appear to change anything.  Unlike the first comment, CPU usage jumps almost immediately after disconnection, not after 30 seconds.  How do I tell whether I'm using OpenSSL or GnuTLS?  Both are installed on my system.

Strace shows a characteristic busy-loop:

```
$ sudo strace -p $(pidof systemd-resolved)
read(10, "\1\0\0\0\0\0\0\0", 8)         = 8
gettid()                                = 1860401
timerfd_settime(10, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=1}}, NULL) = 0
epoll_wait(4, [{events=EPOLLHUP, data={u32=1698388240, u64=94555403409680}}, {events=EPOLLHUP, data={u32=1697136864, u64=94555402158304}}, {events=EPOLLHUP, data={u32=1697365424, u64=94555402386864}}, {events=EPOLLHUP, data={u32=1702121840, u64=94555407143280}}, {events=EPOLLHUP, data={u32=1697320208, u64=94555402341648}}, {events=EPOLLHUP, data={u32=1697060928, u64=94555402082368}}, {events=EPOLLHUP, data={u32=1697298688, u64=94555402320128}}, {events=EPOLLHUP, data={u32=1697506128, u64=94555402527568}}, {events=EPOLLHUP, data={u32=1697451344, u64=94555402472784}}, {events=EPOLLHUP, data={u32=1700404208, u64=94555405425648}}, {events=EPOLLHUP, data={u32=1697277632, u64=94555402299072}}, {events=EPOLLHUP, data={u32=1691635392, u64=94555396656832}}, {events=EPOLLHUP, data={u32=1697310640, u64=94555402332080}}, {events=EPOLLHUP, data={u32=1697093248, u64=94555402114688}}, {events=EPOLLHUP, data={u32=1697479696, u64=94555402501136}}, {events=EPOLLHUP, data={u32=1702694576, u64=94555407716016}}, {events=EPOLLHUP, data={u32=1697171024, u64=94555402192464}}, {events=EPOLLHUP, data={u32=1697130176, u64=94555402151616}}, {events=EPOLLHUP, data={u32=1697274512, u64=94555402295952}}, {events=EPOLLHUP, data={u32=1697360560, u64=94555402382000}}, {events=EPOLLHUP, data={u32=1698247552, u64=94555403268992}}, {events=EPOLLHUP, data={u32=1697218096, u64=94555402239536}}, {events=EPOLLHUP, data={u32=1697314272, u64=94555402335712}}, {events=EPOLLIN, data={u32=1692184128, u64=94555397205568}}], 570, 0) = 24
read(10, "\1\0\0\0\0\0\0\0", 8)         = 8
gettid()                                = 1860401
timerfd_settime(10, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=1}}, NULL) = 0
epoll_wait(4, [{events=EPOLLHUP, data={u32=1698388240, u64=94555403409680}}, {events=EPOLLHUP, data={u32=1697136864, u64=94555402158304}}, {events=EPOLLHUP, data={u32=1697365424, u64=94555402386864}}, {events=EPOLLHUP, data={u32=1702121840, u64=94555407143280}}, {events=EPOLLHUP, data={u32=1697320208, u64=94555402341648}}, {events=EPOLLHUP, data={u32=1697060928, u64=94555402082368}}, {events=EPOLLHUP, data={u32=1697298688, u64=94555402320128}}, {events=EPOLLHUP, data={u32=1697506128, u64=94555402527568}}, {events=EPOLLHUP, data={u32=1697451344, u64=94555402472784}}, {events=EPOLLHUP, data={u32=1700404208, u64=94555405425648}}, {events=EPOLLHUP, data={u32=1697277632, u64=94555402299072}}, {events=EPOLLHUP, data={u32=1691635392, u64=94555396656832}}, {events=EPOLLHUP, data={u32=1697310640, u64=94555402332080}}, {events=EPOLLHUP, data={u32=1697093248, u64=94555402114688}}, {events=EPOLLHUP, data={u32=1697479696, u64=94555402501136}}, {events=EPOLLHUP, data={u32=1702694576, u64=94555407716016}}, {events=EPOLLHUP, data={u32=1697171024, u64=94555402192464}}, {events=EPOLLHUP, data={u32=1697130176, u64=94555402151616}}, {events=EPOLLHUP, data={u32=1697274512, u64=94555402295952}}, {events=EPOLLHUP, data={u32=1697360560, u64=94555402382000}}, {events=EPOLLHUP, data={u32=1698247552, u64=94555403268992}}, {events=EPOLLHUP, data={u32=1697218096, u64=94555402239536}}, {events=EPOLLHUP, data={u32=1697314272, u64=94555402335712}}, {events=EPOLLIN, data={u32=1692184128, u64=94555397205568}}], 570, 0) = 24
read(10, "\1\0\0\0\0\0\0\0", 8)         = 8
gettid()                                = 1860401
timerfd_settime(10, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=1}}, NULL) = 0
epoll_wait(4, [{events=EPOLLHUP, data={u32=1698388240, u64=94555403409680}}, {events=EPOLLHUP, data={u32=1697136864, u64=94555402158304}}, {events=EPOLLHUP, data={u32=1697365424, u64=94555402386864}}, {events=EPOLLHUP, data={u32=1702121840, u64=94555407143280}}, {events=EPOLLHUP, data={u32=1697320208, u64=94555402341648}}, {events=EPOLLHUP, data={u32=1697060928, u64=94555402082368}}, {events=EPOLLHUP, data={u32=1697298688, u64=94555402320128}}, {events=EPOLLHUP, data={u32=1697506128, u64=94555402527568}}, {events=EPOLLHUP, data={u32=1697451344, u64=94555402472784}}, {events=EPOLLHUP, data={u32=1700404208, u64=94555405425648}}, {events=EPOLLHUP, data={u32=1697277632, u64=94555402299072}}, {events=EPOLLHUP, data={u32=1691635392, u64=94555396656832}}, {events=EPOLLHUP, data={u32=1697310640, u64=94555402332080}}, {events=EPOLLHUP, data={u32=1697093248, u64=94555402114688}}, {events=EPOLLHUP, data={u32=1697479696, u64=94555402501136}}, {events=EPOLLHUP, data={u32=1702694576, u64=94555407716016}}, {events=EPOLLHUP, data={u32=1697171024, u64=94555402192464}}, {events=EPOLLHUP, data={u32=1697130176, u64=94555402151616}}, {events=EPOLLHUP, data={u32=1697274512, u64=94555402295952}}, {events=EPOLLHUP, data={u32=1697360560, u64=94555402382000}}, {events=EPOLLHUP, data={u32=1698247552, u64=94555403268992}}, {events=EPOLLHUP, data={u32=1697218096, u64=94555402239536}}, {events=EPOLLHUP, data={u32=1697314272, u64=94555402335712}}, {events=EPOLLIN, data={u32=1692184128, u64=94555397205568}}], 570, 0) = 24
```

```
(gdb) bt
#0  0x00007ffff75be8ea in epoll_wait () from /usr/lib/libc.so.6
#1  0x00007ffff7ef58d2 in sd_event_wait () from /usr/lib/systemd/libsystemd-shared-249.so
#2  0x00007ffff7ef65db in sd_event_prepare () from /usr/lib/systemd/libsystemd-shared-249.so
#3  0x00007ffff7ef6bed in sd_event_run () from /usr/lib/systemd/libsystemd-shared-249.so
#4  0x00007ffff7ef6e60 in sd_event_loop () from /usr/lib/systemd/libsystemd-shared-249.so
#5  0x00005555555947c5 in ?? ()
#6  0x000055555555f126 in ?? ()
#7  0x00007ffff74e7b25 in __libc_start_main () from /usr/lib/libc.so.6
#8  0x000055555555f1ce in ?? ()
```

```
$ systemctl --version
systemd 249 (249.4-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

```
$ resolvectl
Global
           Protocols: +LLMNR +mDNS +DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
  Current DNS Server: 1.1.1.1
         DNS Servers: 1.1.1.1 2606:4700:4700::1111
Fallback DNS Servers: 8.8.8.8 2001:4860:4860::8888
          DNS Domain: ~.

[...]

Link 3 (wl0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6 mDNS/IPv4 mDNS/IPv6
         Protocols: -DefaultRoute +LLMNR +mDNS +DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.86.1
       DNS Servers: 192.168.86.1
        DNS Domain: lan
```
Here's a heavily trimmed log of a short disconnection, with some context on either side: [resolved.log](https://github.com/systemd/systemd/files/7281911/resolved.log).  As mentioned in a prior comment, most of the log was full of "Got POLLHUP from socket".

**Comment by jameshilliard** [comment]
Think I'm seeing this as well:
```
Oct 21 02:27:55 buildroot systemd-resolved[211]: Using feature level UDP for transaction 59363.
Oct 21 02:27:55 buildroot systemd-resolved[211]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Oct 21 02:27:55 buildroot systemd-resolved[211]: Sending query packet with id 59363 of size 40.
Oct 21 02:27:55 buildroot systemd-resolved[211]: Timeout reached on transaction 3233.
Oct 21 02:27:55 buildroot systemd-resolved[211]: Retrying transaction 3233, after switching servers.
Oct 21 02:27:55 buildroot systemd-resolved[211]: Cache miss for bing.com IN A
Oct 21 02:27:55 buildroot systemd-resolved[211]: Firing regular transaction 3233 for <bing.com IN A> scope dns on enp1s0/* (validate=yes).
Oct 21 02:27:55 buildroot systemd-resolved[211]: Using feature level UDP for transaction 3233.
Oct 21 02:27:55 buildroot systemd-resolved[211]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Oct 21 02:27:55 buildroot systemd-resolved[211]: Sending query packet with id 3233 of size 26.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
Oct 21 02:27:56 buildroot systemd-resolved[211]: varlink-33: Got POLLHUP from socket.
```

```
# systemctl --version
systemd 249 (249)
-PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK -SECCOMP +GCRYPT +GNUTLS +OPENSSL -ACL +BLKID +CURL +ELFUTILS -FIDO2 -IDN2 -IDN +IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 -LZ4 +XZ +ZLIB -ZSTD +XKBCOMMON -UTMP -SYSVINIT default-hierarchy=hybrid
```

```
# resolvectl --no-pager
Global
           Protocols: +LLMNR +mDNS DNSOverTLS=opportunistic DNSSEC=allow-downgrade/unsupported
    resolv.conf mode: uplink
Fallback DNS Servers: 1.1.1.1#cloudflare-dns.com 8.8.8.8#dns.google 1.0.0.1#cloudflare-dns.com 8.8.4.4#dns.google 2606:4700:4700::1111#cloudflare-dns.com 2001:4860:4860::8888#dns.google
                      2606:4700:4700::1001#cloudflare-dns.com 2001:4860:4860::8844#dns.google

Link 2 (enp1s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS DNSOverTLS=opportunistic DNSSEC=allow-downgrade/unsupported
Current DNS Server: 192.168.0.101
       DNS Servers: 192.168.0.101

Link 3 (sit0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS DNSOverTLS=opportunistic DNSSEC=allow-downgrade/supported

Link 4 (wlp2s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS DNSOverTLS=opportunistic DNSSEC=allow-downgrade/supported

Link 5 (wg2)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS DNSOverTLS=opportunistic DNSSEC=allow-downgrade/supported

Link 6 (wg0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS DNSOverTLS=opportunistic DNSSEC=allow-downgrade/supported

Link 7 (wg1)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS DNSOverTLS=opportunistic DNSSEC=allow-downgrade/supported
```
