### ISSUE TITLE
Assertion failure in logind when removing file

### ISSUE THREAD

**Issue by Vogtinator** [systemd/systemd#20177]
**systemd version the issue has been seen with**
 > 248.3

**Used distribution**
 > openSUSE Tumbleweed

**Linux kernel version used** (`uname -a`)

 > `Linux localhost.localdomain 5.13.0-1-default #1 SMP Fri Jul 2 05:54:32 UTC 2021 (aa40472) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > `x86_64`

**Unexpected behaviour you saw**
A buggy script deleted `/run/utmp` while the system was running. That causes `systemd-logind` to crash:

```
Jul 08 08:15:45 localhost.localdomain systemd-logind[1151]: Failed to read /var/run/utmp, ignoring: No such file or directory
Jul 08 08:15:45 localhost.localdomain systemd-logind[1151]: Assertion '*_head == _item' failed at src/libsystemd/sd-event/sd-event.c:3344, function event_inotify_data_drop(). Aborting.
```

While `/run/utmp` really shouldn't be deleted by anything, that shouldn't cause `logind` to crash.

**Steps to reproduce the problem**
 > Log into a graphical session (in my case, Plasma (X11)), then run `sudo rm /run/utmp`.

**Additional program output to the terminal or log subsystem illustrating the issue**

Backtrace:

```
#2  0x00007f0eb2ebf07e in log_assert_failed (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ../src/basic/log.c:860
#3  0x00007f0eb30443dd in event_inotify_data_drop (e=0x55b50aef74f0, e@entry=<error reading variable: Cannot access memory at address 0x7fff2fcc7888>, d=d@entry=0x55b50aef82a0, sz=sz@entry=16) at ../src/libsystemd/sd-event/sd-event.c:3344
#4  0x00007f0eb304c145 in source_dispatch (s=s@entry=0x55b50aef8010) at ../src/libsystemd/sd-event/sd-event.c:3572
#5  0x00007f0eb304c365 in dispatch_exit (e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:3660
#6  sd_event_dispatch (e=e@entry=0x55b50aef74f0) at ../src/libsystemd/sd-event/sd-event.c:4070
#7  0x00007f0eb304d8c0 in sd_event_run (e=0x55b50aef74f0, timeout=timeout@entry=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4138
#8  0x000055b50953cbca in manager_run (m=0x55b50aef6240) at ../src/login/logind.c:1151
#9  run (argv=<optimized out>, argc=<optimized out>) at ../src/login/logind.c:1199
#10 main (argc=<optimized out>, argv=<optimized out>) at ../src/login/logind.c:1202
```

Seems very similar to https://github.com/systemd/systemd/issues/18594, probably similar bug also in logind?

**Comment by poettering** [comment]
Is this reproducible with v249?

**Comment by mbiebl** [comment]
Running v249 here, I can reproduce the crash

**Comment by Vogtinator** [comment]
I just built v249 and tried it a few times without getting a crash, while with v248 it happens most of the time (but not always)

It still crashes for @mbiebl though, so I might've just gotten (un)lucky with the heap layout.

**Comment by mbiebl** [comment]
It's easily reproducible here (after a reboot):
```

-- Journal begins at Thu 2021-07-08 11:08:05 CEST, ends at Thu 2021-07-08 16:03:03 CEST. --
Jul 08 16:02:31 debian systemd[1]: Starting User Login Management...
Jul 08 16:02:32 debian systemd-logind[378]: New seat seat0.
Jul 08 16:02:32 debian systemd-logind[378]: Watching system buttons on /dev/input/event3 (Power Button)
Jul 08 16:02:32 debian systemd-logind[378]: Watching system buttons on /dev/input/event0 (AT Translated Set 2 keyboard)
Jul 08 16:02:32 debian systemd[1]: Started User Login Management.
Jul 08 16:02:36 debian systemd-logind[378]: New session 1 of user root.
Jul 08 16:02:52 debian systemd-logind[378]: Failed to read /var/run/utmp, ignoring: No such file or directory
Jul 08 16:02:52 debian systemd-logind[378]: Assertion '*_head == _item' failed at src/libsystemd/sd-event/sd-event.c:3337, function event_inotify_data_drop(). Aborting.
Jul 08 16:02:52 debian systemd[1]: systemd-logind.service: Main process exited, code=killed, status=6/ABRT
Jul 08 16:02:52 debian systemd[1]: systemd-logind.service: Failed with result 'signal'.
Jul 08 16:02:52 debian systemd[1]: systemd-logind.service: Scheduled restart job, restart counter is at 1.
Jul 08 16:02:52 debian systemd[1]: Stopped User Login Management.
Jul 08 16:02:52 debian systemd[1]: Starting User Login Management...
Jul 08 16:02:52 debian systemd-logind[486]: New seat seat0.
Jul 08 16:02:52 debian systemd-logind[486]: Watching system buttons on /dev/input/event3 (Power Button)
Jul 08 16:02:52 debian systemd-logind[486]: Watching system buttons on /dev/input/event0 (AT Translated Set 2 keyboard)
Jul 08 16:02:52 debian systemd-logind[486]: Failed to read /var/run/utmp, ignoring: No such file or directory
Jul 08 16:02:52 debian systemd[1]: Started User Login Management.
Jul 08 16:02:52 debian systemd-logind[486]: New session 1 of user root.
```
```
systemd 249 (249-1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```
