### ISSUE TITLE
An assert fails in pam_systemd_home.c when trying to unlock the system via Cinnamon Screensaver lockscreen

### ISSUE THREAD

**Issue by software-artificer** [systemd/systemd#20639]
**systemd version the issue has been seen with**
 > systemd 249 (249)
+PAM -AUDIT -SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID -CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)

 > `Linux heliodor 5.12.19-gentoo-heliodor #1 SMP PREEMPT Thu Jul 29 17:53:02 AEST 2021 x86_64 AMD Ryzen 9 5950X 16-Core Processor AuthenticAMD GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > The system successfully unlocked

**Unexpected behaviour you saw**
 > Lock screen is displaying "unlocking in progress" animation indefinitely, until any key is pressed on the keyboard, then it displays the unlocking password prompt again.

**Steps to reproduce the problem**
 > - Using Cinnamon 4.8.6 with Cinnamon Screensaver 4.8.1 and systemd 249
 > - Using a user created using the `homectl` command (using the directory storage)
 > - Log-in as a user, then lock the system (via menu or Ctrl+Alt+L)
 > - Observe lockscreen (handled by the Cinnamon Screensaver component)
 > - Try unlocking the system using the valid user password

**Additional program output to the terminal or log subsystem illustrating the issue**

**coredumpctl**
```text
           PID: 90351 (cinnamon-screen)
           UID: 60466 (garry)
           GID: 60466 (garry)
        Signal: 6 (ABRT)
     Timestamp: Sat 2021-09-04 13:11:04 AEST (1min 8s ago)
  Command Line: /usr/libexec/cinnamon-screensaver-pam-helper
    Executable: /usr/libexec/cinnamon-screensaver-pam-helper
 Control Group: /user.slice/user-60466.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-60466.slice
       Session: c2
     Owner UID: 60466 (garry)
       Boot ID: 73a5927eaaff4de3b52d631698db9269
    Machine ID: 2d22bf845283d81cb944209f60c374c4
      Hostname: heliodor
       Storage: /var/lib/systemd/coredump/core.cinnamon-screen.60466.73a5927eaaff4de3b52d631698db9269.90351.1630725064000000.zst (present)
     Disk Size: 1.2M
       Message: Process 90351 (cinnamon-screen) of user 60466 dumped core.
                
                Found module linux-vdso.so.1 with build-id: 50d36783038b34424def76a5d57e31c528f09e28
                Found module pam_deny.so without build-id.
                Found module pam_limits.so without build-id.
                Found module pam_gnome_keyring.so without build-id.
                Found module pam_systemd_home.so without build-id.
                Found module pam_unix.so without build-id.
                Found module pam_faillock.so without build-id.
                Found module pam_env.so without build-id.
                Found module libgvfscommon.so without build-id.
                Found module libgvfsdbus.so without build-id.
                Found module libogg.so.0 without build-id.
                Found module libvorbis.so.0 without build-id.
                Found module libltdl.so.7 without build-id.
                Found module libvorbisfile.so.3 without build-id.
                Found module libcanberra.so.0 without build-id.
                Found module libgthread-2.0.so.0 without build-id.
                Found module libcanberra-gtk3.so.0 without build-id.
                Found module libcanberra-gtk-module.so without build-id.
                Found module libgcc_s.so.1 without build-id.
                Found module libstdc++.so.6 without build-id.
                Found module libicudata.so.69 without build-id.
                Found module libicuuc.so.69 without build-id.
                Found module libxkbfile.so.1 without build-id.
                Found module libxml2.so.2 without build-id.
                Found module libxklavier.so.16 without build-id.
                Found module libgnomekbd.so.8 without build-id.
                Found module libgnomekbdui.so.8 without build-id.
                Found module libxapp.so.1 without build-id.
                Found module libxapp-gtk3-module.so without build-id.
                Found module libcrypt.so.1 without build-id.
                Found module libnss_systemd.so.2 without build-id.
                Found module libnss_files.so.2 without build-id.
                Found module libgpg-error.so.0 without build-id.
                Found module libmd.so.0 without build-id.
                Found module libgcrypt.so.20 without build-id.
                Found module libcap.so.2 without build-id.
                Found module libzstd.so.1 without build-id.
                Found module librt.so.1 without build-id.
                Found module libbsd.so.0 without build-id.
                Found module libsystemd.so.0 without build-id.
                Found module libGLX.so.0 without build-id.
                Found module libGLdispatch.so.0 without build-id.
                Found module libXdmcp.so.6 without build-id.
                Found module libXau.so.6 without build-id.
                Found module libblkid.so.1 without build-id.
                Found module libuuid.so.1 without build-id.
                Found module libexpat.so.1 without build-id.
                Found module libatspi.so.0 without build-id.
                Found module libdbus-1.so.3 without build-id.
                Found module libGL.so.1 without build-id.
                Found module libXrender.so.1 without build-id.
                Found module libxcb-render.so.0 without build-id.
                Found module libxcb-shm.so.0 without build-id.
                Found module libpng16.so.16 without build-id.
                Found module libEGL.so.1 without build-id.
                Found module libpixman-1.so.0 without build-id.
                Found module libdl.so.2 without build-id.
                Found module libxcb.so.1 without build-id.
                Found module libXdamage.so.1 without build-id.
                Found module libXcomposite.so.1 without build-id.
                Found module libXcursor.so.1 without build-id.
                Found module libXrandr.so.2 without build-id.
                Found module ld-linux-x86-64.so.2 without build-id.
                Found module libpcre.so.1 without build-id.
                Found module libffi.so.7 without build-id.
                Found module libresolv.so.2 without build-id.
                Found module libmount.so.1 without build-id.
                Found module libz.so.1 without build-id.
                Found module libfreetype.so.6 without build-id.
                Found module libfontconfig.so.1 without build-id.
                Found module libharfbuzz.so.0 without build-id.
                Found module libpango-1.0.so.0 without build-id.
                Found module libpangoft2-1.0.so.0 without build-id.
                Found module libm.so.6 without build-id.
                Found module libfribidi.so.0 without build-id.
                Found module libepoxy.so.0 without build-id.
                Found module libatk-bridge-2.0.so.0 without build-id.
                Found module libatk-1.0.so.0 without build-id.
                Found module libgdk_pixbuf-2.0.so.0 without build-id.
                Found module libcairo.so.2 without build-id.
                Found module libcairo-gobject.so.2 without build-id.
                Found module libXfixes.so.3 without build-id.
                Found module libXi.so.6 without build-id.
                Found module libpangocairo-1.0.so.0 without build-id.
                Found module libgmodule-2.0.so.0 without build-id.
                Found module libpthread.so.0 without build-id.
                Found module libpam.so.0 without build-id.
                Found module libXext.so.6 without build-id.
                Found module libX11.so.6 without build-id.
                Found module libgdk-3.so.0 without build-id.
                Found module libc.so.6 without build-id.
                Found module libglib-2.0.so.0 without build-id.
                Found module libgobject-2.0.so.0 without build-id.
                Found module libgio-2.0.so.0 without build-id.
                Found module libgtk-3.so.0 without build-id.
                Found module libcscreensaver.so.0 without build-id.
                Found module cinnamon-screensaver-pam-helper without build-id.
                Stack trace of thread 90355:
                #0  0x00007f1731dc3881 raise (libc.so.6 + 0x38881)
                #1  0x00007f1731dad2b6 abort (libc.so.6 + 0x222b6)
                #2  0x00007f172d3727d5 log_assert_failed (pam_systemd_home.so + 0xb7d5)
                #3  0x00007f172d37369f handle_generic_user_record_error (pam_systemd_home.so + 0xc69f)
                #4  0x00007f172d373f3c acquire_home (pam_systemd_home.so + 0xcf3c)
                #5  0x00007f172d374c24 pam_sm_acct_mgmt (pam_systemd_home.so + 0xdc24)
                #6  0x00007f1731b633cd n/a (libpam.so.0 + 0x33cd)
                #7  0x00007f1732a6dcfe n/a (libcscreensaver.so.0 + 0x25cfe)
                #8  0x00007f1731f88f1d n/a (libglib-2.0.so.0 + 0x7ef1d)
                #9  0x00007f1731b47e5e start_thread (libpthread.so.0 + 0x7e5e)
                #10 0x00007f1731e7a14f __clone (libc.so.6 + 0xef14f)
                
                Stack trace of thread 90354:
                #0  0x00007f1731e6cd7c __read (libc.so.6 + 0xe1d7c)
                #1  0x00007f1731e095f4 _IO_file_underflow (libc.so.6 + 0x7e5f4)
                #2  0x00007f1731e0a8b2 _IO_default_uflow (libc.so.6 + 0x7f8b2)
                #3  0x00007f1731dfd6a6 _IO_getline_info (libc.so.6 + 0x726a6)
                #4  0x00007f1731dfc605 _IO_fgets (libc.so.6 + 0x71605)
                #5  0x00005623c54e4964 n/a (cinnamon-screensaver-pam-helper + 0x1964)
                #6  0x00007f17321496de n/a (libgio-2.0.so.0 + 0xae6de)
                #7  0x00007f1731f89834 n/a (libglib-2.0.so.0 + 0x7f834)
                #8  0x00007f1731f88f1d n/a (libglib-2.0.so.0 + 0x7ef1d)
                #9  0x00007f1731b47e5e start_thread (libpthread.so.0 + 0x7e5e)
                #10 0x00007f1731e7a14f __clone (libc.so.6 + 0xef14f)
                
                Stack trace of thread 90352:
                #0  0x00007f1731e7112f __poll (libc.so.6 + 0xe612f)
                #1  0x00007f1731f5e36e n/a (libglib-2.0.so.0 + 0x5436e)
                #2  0x00007f1731f5e48f g_main_context_iteration (libglib-2.0.so.0 + 0x5448f)
                #3  0x00007f1731f5e4e1 n/a (libglib-2.0.so.0 + 0x544e1)
                #4  0x00007f1731f88f1d n/a (libglib-2.0.so.0 + 0x7ef1d)
                #5  0x00007f1731b47e5e start_thread (libpthread.so.0 + 0x7e5e)
                #6  0x00007f1731e7a14f __clone (libc.so.6 + 0xef14f)
                
                Stack trace of thread 90351:
                #0  0x00007f1731e7112f __poll (libc.so.6 + 0xe612f)
                #1  0x00007f1731f5e36e n/a (libglib-2.0.so.0 + 0x5436e)
                #2  0x00007f1731f5e6d3 g_main_loop_run (libglib-2.0.so.0 + 0x546d3)
                #3  0x00007f17324c8a9d gtk_main (libgtk-3.so.0 + 0x253a9d)
                #4  0x00007f1732a6e07e cs_auth_verify_user (libcscreensaver.so.0 + 0x2607e)
                #5  0x00005623c54e4d49 n/a (cinnamon-screensaver-pam-helper + 0x1d49)
                #6  0x00007f1731f5e028 g_main_context_dispatch (libglib-2.0.so.0 + 0x54028)
                #7  0x00007f1731f5e3d8 n/a (libglib-2.0.so.0 + 0x543d8)
                #8  0x00007f1731f5e6d3 g_main_loop_run (libglib-2.0.so.0 + 0x546d3)
                #9  0x00007f17324c8a9d gtk_main (libgtk-3.so.0 + 0x253a9d)
                #10 0x00005623c54e46a5 n/a (cinnamon-screensaver-pam-helper + 0x16a5)
                #11 0x00007f1731dae57d __libc_start_main (libc.so.6 + 0x2357d)
                #12 0x00005623c54e479a n/a (cinnamon-screensaver-pam-helper + 0x179a)
                
                Stack trace of thread 90353:
                #0  0x00007f1731e7112f __poll (libc.so.6 + 0xe612f)
                #1  0x00007f1731f5e36e n/a (libglib-2.0.so.0 + 0x5436e)
                #2  0x00007f1731f5e6d3 g_main_loop_run (libglib-2.0.so.0 + 0x546d3)
                #3  0x00007f17321b2566 n/a (libgio-2.0.so.0 + 0x117566)
                #4  0x00007f1731f88f1d n/a (libglib-2.0.so.0 + 0x7ef1d)
                #5  0x00007f1731b47e5e start_thread (libpthread.so.0 + 0x7e5e)
                #6  0x00007f1731e7a14f __clone (libc.so.6 + 0xef14f)
```

**gdb backtrace**
(only have debug symbols for systemd, but can rebuild with other libraries if needed)
```
#0  0x00007f1731dc3881 in raise () from /lib64/libc.so.6
#1  0x00007f1731dad2b6 in abort () from /lib64/libc.so.6
#2  0x00007f172d3727d5 in log_assert_failed (text=text@entry=0x7f172d3c8043 "secret", file=file@entry=0x7f172d3c0368 "src/home/pam_systemd_home.c", line=line@entry=284, 
    func=func@entry=0x7f172d3cbea0 <__PRETTY_FUNCTION__.2> "handle_generic_user_record_error") at ../systemd-stable-249.2/src/basic/log.c:862
#3  0x00007f172d37369f in handle_generic_user_record_error (handle=handle@entry=0x5623c628f5d0, user_name=<optimized out>, secret=secret@entry=0x0, ret=ret@entry=-13, 
    error=error@entry=0x7f172c9ba8e0) at ../systemd-stable-249.2/src/home/pam_systemd_home.c:284
#4  0x00007f172d373f3c in acquire_home (handle=handle@entry=0x5623c628f5d0, please_authenticate=please_authenticate@entry=false, please_suspend=false, debug=<optimized out>)
    at ../systemd-stable-249.2/src/home/pam_systemd_home.c:592
#5  0x00007f172d374c24 in pam_sm_acct_mgmt (handle=0x5623c628f5d0, flags=<optimized out>, argc=0, argv=0x0) at ../systemd-stable-249.2/src/home/pam_systemd_home.c:854
#6  0x00007f1731b633cd in ?? () from /lib64/libpam.so.0
#7  0x00007f1732a6dcfe in ?? () from /usr/lib64/libcscreensaver.so.0
#8  0x00007f1731f88f1d in ?? () from /usr/lib64/libglib-2.0.so.0
#9  0x00007f1731b47e5e in start_thread () from /lib64/libpthread.so.0
#10 0x00007f1731e7a14f in clone () from /lib64/libc.so.6
```

**Comment by yuwata** [comment]
Hi. If possible, could you test PR #20640?

**Comment by filakhtov** [comment]
@yuwata, thanks a lot - just tested with that PR and it works properly 😻 appreciate the really quick turnaround!

**Comment by yuwata** [comment]
@filakhtov Thank you for testing!
