### ISSUE TITLE
systemd-coredump: null pointer dereference

### ISSUE THREAD

**Issue by nE0sIghT** [systemd/systemd#20784]
**systemd version the issue has been seen with**
 > 249.4

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)

 > `Linux vortex 5.13.18-gentoo #1 SMP PREEMPT Sat Sep 18 13:56:55 +04 2021 x86_64 AMD Ryzen 7 5800X 8-Core Processor AuthenticAMD GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > systemd-coredump doesn't sigsegv trying to get coredump of faulted application

**Unexpected behaviour you saw**
 > systemd-coredump got sigsegv trying to get coredump of faulted application

**Steps to reproduce the problem**
 > ...

**Additional program output to the terminal or log subsystem illustrating the issue**

data must be checked for NULL at https://github.com/systemd/systemd/blob/v249/src/coredump/stacktrace.c#L296

```text
(gdb) thread apply all bt full

Thread 1 (Thread 0x7fbf080ca8c0 (LWP 65967)):
#0  0x0000558e1129bc24 in module_callback (mod=0x558e12c27910, userdata=0x558e12c27920, name=0x558e12c1c620 "/home/ne0sight/.local/share/Steam/steamapps/common/ATOM RPG Trudograd/Trudograd.x86_64", start=2097152, arg=0x7ffc9c4996c0) at ../systemd-stable-249.4/src/coredump/stacktrace.c:303
        mem = {p_type = 1, p_flags = 6, p_offset = 2038738944, p_vaddr = 140426371661824, p_paddr = 0, p_filesz = 268435456, p_memsz = 268435456, p_align = 4096}
        program_header = 0x7ffc9c4995d0
        data = 0x0
        memelf = 0x558e12c8f490
        i = 415
        id_json = 0x558e12c1cac0
        c = 0x7ffc9c4996c0
        n_program_headers = 739
        id_vaddr = 2097908
        bias = 24129
        id = 0x558e12c2c500 "\212\005\301yw\352\313e"
        id_len = 8
        r = 0
        elf = 0x0
        __PRETTY_FUNCTION__ = "module_callback"
        __func__ = "module_callback"
#1  0x00007fbf08d48205 in dwfl_getmodules () from /usr/lib64/libdw.so.1
No symbol table info available.
#2  0x0000558e1129bef3 in parse_core (fd=6, executable=0x558e12c1bdcd "/home/ne0sight/.local/share/Steam/steamapps/common/ATOM RPG Trudograd/Trudograd.x86_64", ret=0x7ffc9c499808, ret_package_metadata=0x7ffc9c4997f0) at ../systemd-stable-249.4/src/coredump/stacktrace.c:366
        callbacks = {find_elf = 0x7fbf08d4c460 <dwfl_build_id_find_elf>, find_debuginfo = 0x7fbf08d4bfc0 <dwfl_standard_find_debuginfo>, section_address = 0x7fbf08d470f0 <dwfl_offline_section_address>, debuginfo_path = 0x0}
        package_metadata = 0x0
        modules = 0x0
        c = {f = 0x558e12c24550, dwfl = 0x558e12c26870, elf = 0x558e12c26760, n_thread = 0, n_frame = 0, package_metadata = 0x7ffc9c499690, modules = 0x7ffc9c499698}
        buf = 0x0
        sz = 0
        r = 1920399053
        __PRETTY_FUNCTION__ = "parse_core"
#3  0x0000558e1129c05d in coredump_parse_core (fd=6, executable=0x558e12c1bdcd "/home/ne0sight/.local/share/Steam/steamapps/common/ATOM RPG Trudograd/Trudograd.x86_64", ret=0x7ffc9c499808, ret_package_metadata=0x7ffc9c4997f0) at ../systemd-stable-249.4/src/coredump/stacktrace.c:406
        r = -260042240
        __PRETTY_FUNCTION__ = "coredump_parse_core"
        __func__ = "coredump_parse_core"
#4  0x0000558e11295ace in submit_coredump (context=0x7ffc9c499a10, iovw=0x7ffc9c499990, input_fd=5) at ../systemd-stable-249.4/src/coredump/coredump.c:827
        json_metadata = 0x0
        coredump_fd = 6
        coredump_node_fd = 7
        filename = 0x558e12c24250 "/var/lib/systemd/coredump/core.Trudograd\\x2ex86_6.1000.a7698137c0354be4814aa846e04bb0bb.65845.1631991326000000.zst"
        coredump_data = 0x0
        stacktrace = 0x0
        core_message = 0x558e1129cebb "systemd-journald.service"
        module_name = 0x558e12c1a35d "65845"
        coredump_size = 2147483648
        coredump_compressed_size = 311433658
        truncated = true
        module_json = 0x7ffc9c4998a0
        r = 0
        __PRETTY_FUNCTION__ = "submit_coredump"
        __func__ = "submit_coredump"
#5  0x0000558e112970bc in process_socket (fd=3) at ../systemd-stable-249.4/src/coredump/coredump.c:1041
        input_fd = 5
        context = {meta = {0x558e12c1a35d "65845", 0x558e12c1bb4d "1000", 0x558e12c1bb6d "1000", 0x558e12c1bc40 "11", 0x558e12c1a413 "1631991326000000", 0x558e12c1a3e0 "18446744073709551615", 0x558e12c1a382 "vortex", 0x558e12c1a32e "Trudograd.x86_6", 0x558e12c1bdcd "/home/ne0sight/.local/share/Steam/steamapps/common/ATOM RPG Trudograd/Trudograd.x86_64", 0x558e12c1a48e "user@1000.service"}, pid = 65845, is_pid1 = false, is_journald = false}
        iovw = {iovec = 0x558e12c20a80, count = 28}
        iovec = {iov_base = 0x558e12c1c580, iov_len = 0}
        r = 0
        __PRETTY_FUNCTION__ = "process_socket"
--Type <RET> for more, q to quit, c to continue without paging--
        __func__ = "process_socket"
#6  0x0000558e11299769 in run (argc=1, argv=0x7ffc9c499bf8) at ../systemd-stable-249.4/src/coredump/coredump.c:1416
        r = 1
        __PRETTY_FUNCTION__ = "run"
        __func__ = "run"
#7  0x0000558e11299844 in main (argc=1, argv=0x7ffc9c499bf8) at ../systemd-stable-249.4/src/coredump/coredump.c:1422
        r = 0

```

**Comment by nE0sIghT** [comment]
Sorry for noice, looks like that was fixed in master
