### ISSUE TITLE
Possible stack-use-after-scope in net_get_unique_predictable_data_from_name()

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#21292]
**systemd version the issue has been seen with**
 > latest main

**Used distribution**
 > Arch Linux (gcc)

Tonight's cron job started complaining about a possible stack-use-after-scope when running the systemd-networkd and udev test suites under sanitizers (w/ gcc):

```
[   20.631520] systemd-udevd[452]: ==452==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f77b356c5e0 at pc 0x7f77b901986f bp 0x7fff07e0e790 sp 0x7fff07e0e780
[   20.631873] systemd-udevd[452]: READ of size 8 at 0x7f77b356c5e0 thread T0
[   21.105896] systemd-udevd[452]:     #0 0x7f77b901986e in unaligned_read_le64 ../build/src/basic/unaligned.h:62
[   21.106636] systemd-udevd[452]:     #1 0x7f77b901986e in siphash24_init ../build/src/basic/siphash24.c:59
[   21.107405] systemd-udevd[452]:     #2 0x7f77b901aae5 in siphash24 ../build/src/basic/siphash24.c:198
[   21.119777] systemd-udevd[452]:     #3 0x7f77b8ea108d in net_get_unique_predictable_data_from_name ../build/src/shared/netif-util.c:101
[   21.120711] systemd-udevd[452]:     #4 0x7f77b8ea1738 in net_get_unique_predictable_data ../build/src/shared/netif-util.c:70
[   21.127617] systemd-udevd[452]:     #5 0x556a353cd8a3 in get_mac ../build/src/udev/net/link-config.c:517
[   21.128905] systemd-udevd[452]:     #6 0x556a353ce0ff in link_config_apply_rtnl_settings ../build/src/udev/net/link-config.c:547
[   21.129547] systemd-udevd[452]:     #7 0x556a353cfadc in link_config_apply ../build/src/udev/net/link-config.c:747
[   21.130679] systemd-udevd[452]:     #8 0x556a353b688e in builtin_net_setup_link ../build/src/udev/udev-builtin-net_setup_link.c:41
[   21.134502] systemd-udevd[452]:     #9 0x556a353a2948 in udev_builtin_run ../build/src/udev/udev-builtin.c:127
[   21.146496] systemd-udevd[452]:     #10 0x556a35392397 in udev_rule_apply_token_to_event ../build/src/udev/udev-rules.c:1833
[   21.147265] systemd-udevd[452]:     #11 0x556a3539d16c in udev_rule_apply_line_to_event ../build/src/udev/udev-rules.c:2329
[   21.148116] systemd-udevd[452]:     #12 0x556a3539fadf in udev_rules_apply_to_event ../build/src/udev/udev-rules.c:2357
[   21.152649] systemd-udevd[452]:     #13 0x556a3536961e in udev_event_execute_rules ../build/src/udev/udev-event.c:1043
[   21.158050] systemd-udevd[452]:     #14 0x556a3534ed9c in worker_process_device ../build/src/udev/udevd.c:526
[   21.158392] systemd-udevd[452]:     #15 0x556a3534f3cb in worker_device_monitor_handler ../build/src/udev/udevd.c:557
[   21.160594] systemd-udevd[452]:     #16 0x556a3534fc3a in worker_main ../build/src/udev/udevd.c:622
[   21.161612] systemd-udevd[452]:     #17 0x556a35351136 in worker_spawn ../build/src/udev/udevd.c:710
[   21.163596] systemd-udevd[452]:     #18 0x556a35351c97 in event_run ../build/src/udev/udevd.c:771
[   21.164763] systemd-udevd[452]:     #19 0x556a35352334 in event_queue_start ../build/src/udev/udevd.c:970
[   21.166769] systemd-udevd[452]:     #20 0x556a35356901 in on_uevent ../build/src/udev/udevd.c:1046
[   21.167949] systemd-udevd[452]:     #21 0x7f77b9158be9 in device_monitor_event_handler ../build/src/libsystemd/sd-device/device-monitor.c:238
[   21.176822] systemd-udevd[452]:     #22 0x7f77b927fc64 in source_dispatch ../build/src/libsystemd/sd-event/sd-event.c:3571
[   21.177840] systemd-udevd[452]:     #23 0x7f77b928165e in sd_event_dispatch ../build/src/libsystemd/sd-event/sd-event.c:4155
[   21.178788] systemd-udevd[452]:     #24 0x7f77b9281f0b in sd_event_run ../build/src/libsystemd/sd-event/sd-event.c:4216
[   21.179771] systemd-udevd[452]:     #25 0x7f77b9282199 in sd_event_loop ../build/src/libsystemd/sd-event/sd-event.c:4237
[   21.180734] systemd-udevd[452]:     #26 0x556a35348d0e in main_loop ../build/src/udev/udevd.c:1872
[   21.181627] systemd-udevd[452]:     #27 0x556a35359160 in run_udevd ../build/src/udev/udevd.c:1984
[   21.183347] systemd-udevd[452]:     #28 0x556a3533793a in run ../build/src/udev/udevadm.c:116
[   21.184165] systemd-udevd[452]:     #29 0x556a353379ad in main ../build/src/udev/udevadm.c:133
[   21.185072] systemd-udevd[452]:     #30 0x7f77b7957b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
[   21.186784] systemd-udevd[452]:     #31 0x556a353372bd in _start (/usr/bin/udevadm+0xd02bd)
[   21.187623] systemd-udevd[452]: Address 0x7f77b356c5e0 is located in stack of thread T0 at offset 32 in frame
[   21.188736] systemd-udevd[452]:     #0 0x7f77b8ea0eee in net_get_unique_predictable_data_from_name ../build/src/shared/netif-util.c:76
[   21.189469] systemd-udevd[452]:   This frame has 1 object(s):
[   21.190292] systemd-udevd[452]:     [32, 48) '<unknown>' <== Memory access at offset 32 is inside this variable
[   21.191268] systemd-udevd[452]: HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
[   21.192116] systemd-udevd[452]:       (longjmp and C++ exceptions *are* supported)
[   21.192849] systemd-udevd[452]: SUMMARY: AddressSanitizer: stack-use-after-scope ../build/src/basic/unaligned.h:62 in unaligned_read_le64
```

```
systemd-networkd[127766]: ==127766==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7feb06df36a0 at pc 0x7feb0c76186f bp 0x7ffd91e72e00 sp 0x7ffd91e72df0
systemd-networkd[127766]: READ of size 8 at 0x7feb06df36a0 thread T0
systemd-networkd[127766]:     #0 0x7feb0c76186e in unaligned_read_le64 ../build/src/basic/unaligned.h:62
systemd-networkd[127766]:     #1 0x7feb0c76186e in siphash24_init ../build/src/basic/siphash24.c:59
systemd-networkd[127766]:     #2 0x7feb0c762ae5 in siphash24 ../build/src/basic/siphash24.c:198
systemd-networkd[127766]:     #3 0x7feb0c5e908d in net_get_unique_predictable_data_from_name ../build/src/shared/netif-util.c:101
systemd-networkd[127766]:     #4 0x7feb0c5e9738 in net_get_unique_predictable_data ../build/src/shared/netif-util.c:70
systemd-networkd[127766]:     #5 0x5621ea44ab33 in ipv4ll_configure ../build/src/network/networkd-ipv4ll.c:191
systemd-networkd[127766]:     #6 0x5621ea4653a3 in link_configure ../build/src/network/networkd-link.c:1139
systemd-networkd[127766]:     #7 0x5621ea4694b8 in link_initialized_and_synced ../build/src/network/networkd-link.c:1449
systemd-networkd[127766]:     #8 0x5621ea469a75 in link_initialized_handler ../build/src/network/networkd-link.c:1459
systemd-networkd[127766]:     #9 0x7feb0c8fb4dc in process_reply ../build/src/libsystemd/sd-netlink/sd-netlink.c:413
systemd-networkd[127766]:     #10 0x7feb0c8fbfbe in process_running ../build/src/libsystemd/sd-netlink/sd-netlink.c:498
systemd-networkd[127766]:     #11 0x7feb0c8fe968 in sd_netlink_process ../build/src/libsystemd/sd-netlink/sd-netlink.c:526
systemd-networkd[127766]:     #12 0x7feb0c8feb52 in time_callback ../build/src/libsystemd/sd-netlink/sd-netlink.c:809
systemd-networkd[127766]:     #13 0x7feb0c9c7eb2 in source_dispatch ../build/src/libsystemd/sd-event/sd-event.c:3579
systemd-networkd[127766]:     #14 0x7feb0c9c965e in sd_event_dispatch ../build/src/libsystemd/sd-event/sd-event.c:4155
systemd-networkd[127766]:     #15 0x7feb0c9c9f0b in sd_event_run ../build/src/libsystemd/sd-event/sd-event.c:4216
systemd-networkd[127766]:     #16 0x7feb0c9ca199 in sd_event_loop ../build/src/libsystemd/sd-event/sd-event.c:4237
systemd-networkd[127766]:     #17 0x5621ea2dea8c in run ../build/src/network/networkd.c:104
systemd-networkd[127766]:     #18 0x5621ea2df217 in main ../build/src/network/networkd.c:111
systemd-networkd[127766]:     #19 0x7feb0b157b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
systemd-networkd[127766]:     #20 0x5621ea2de3dd in _start (/systemd-meson-build/systemd-networkd+0x3483dd)
systemd-networkd[127766]: Address 0x7feb06df36a0 is located in stack of thread T0 at offset 32 in frame
systemd-networkd[127766]:     #0 0x7feb0c5e8eee in net_get_unique_predictable_data_from_name ../build/src/shared/netif-util.c:76
systemd-networkd[127766]:   This frame has 1 object(s):
systemd-networkd[127766]:     [32, 48) '<unknown>' <== Memory access at offset 32 is inside this variable
systemd-networkd[127766]: HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
systemd-networkd[127766]:       (longjmp and C++ exceptions *are* supported)
systemd-networkd[127766]: SUMMARY: AddressSanitizer: stack-use-after-scope ../build/src/basic/unaligned.h:62 in unaligned_read_le64
```

Full job: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-cron-build/420/artifact//systemd-centos-ci/index.html

/cc @yuwata

**Comment by yuwata** [comment]
Thanks. Fix is waiting in #21295.
