### ISSUE TITLE
`test_altname` from `systemd-networkd-tests.py` started failing on CentOS 8

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#21404]
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > CentOS 8

Not sure what changed, but all the recent C8 CentOS CI run keep failing in the systemd-networkd test suite:
```
======================================================================
ERROR: test_altname (__main__.NetworkctlTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 705, in test_altname
    self.wait_online(['dummy98:degraded'])
  File "./test/test-network/systemd-networkd-tests.py", line 642, in wait_online
    check_output(*args, env=env)
  File "./test/test-network/systemd-networkd-tests.py", line 57, in check_output
    return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/systemd/systemd-networkd-wait-online', '--timeout=20s', '--interface=dummy98:degraded']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 157 tests in 2285.401s

FAILED (errors=1, expected failures=8)
```

I suspect this has to do something with the release of CentOS 8.5 and the respective kernel updates regarding netdev alt names.

Example failing jobs:
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/4394/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/4387/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/4391/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/4398/artifact//systemd-centos-ci/index.html

/cc @yuwata

**Comment by yuwata** [comment]
Was the kernel recently updated on the CI?

**Comment by yuwata** [comment]
```
Nov 16 21:08:17 n9.dusty.ci.centos.org systemd-udevd[220625]: Network interface NamePolicy= disabled on kernel command line, ignoring.
```
Is this new?

**Comment by yuwata** [comment]
> ```
> Nov 16 21:08:17 n9.dusty.ci.centos.org systemd-udevd[220625]: Network interface NamePolicy= disabled on kernel command line, ignoring.
> ```
> 
> Is this new?

But the log is for `NamePolicy=`, not for `AlternativeNamePolicy=`. Hmm..

**Comment by yuwata** [comment]
```
Nov 16 21:08:17 n9.dusty.ci.centos.org NetworkManager[1131]: <info>  [1637093297.8411] manager: (dummy98): new Dummy device (/org/freedesktop/NetworkManager/Devices/26)
```
Hm? NetworkManager is running. Is this intended?

**Comment by yuwata** [comment]
https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/4419/artifact//systemd-centos-ci/artifacts_nq3a2ldp/testsuite-logs-upstream.9OB/journalctl-testsuite_PASS.log
```
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-udevd[206005]: dummy98: Setting alternative names: hogehogehogehogehogehoge
(...)
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-udevd[206005]: dummy98: Device processed (SEQNUM=4807, ACTION=add)
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-udevd[206005]: dummy98: sd-device-monitor: Passed 409 byte to netlink monitor
(...)
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-networkd[206004]: dummy98: udev initialized link
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-networkd[206004]: dummy98: State changed: pending -> initialized
(...)
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-networkd[206004]: dummy98: Received new alternative names: 
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-networkd[206004]: dummy98: Link state is up-to-date
Nov 17 03:50:24 n29.crusty.ci.centos.org systemd-networkd[206004]: dummy98: State changed: initialized -> unmanaged
```

**Comment by yuwata** [comment]
Maybe I got the root of the issue. I hope #21406 fixes this.
