### ISSUE TITLE
assertion failure with `networkctl --json`

### ISSUE THREAD

**Issue by LaserEyess** [systemd/systemd#21567]
**systemd version the issue has been seen with**
 > 
systemd 249 (249.r2531.g8e560cd090-1-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.15.5-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > json printed

**Unexpected behaviour you saw**
 > crash

**Steps to reproduce the problem**
 > `networkctl status $interface --json={pretty,short}

**Additional program output to the terminal or log subsystem illustrating the issue**

```
Nov 29 17:20:31 homura systemd-networkd[1085]: Assertion 'u' failed at src/basic/in-addr-util.c:34, function in_addr_is_null(). Aborting.
```
See full backtrace:
<details>
  <summary>backtrace</summary>

  ```
#0  0x00007f3c7b6b6d22 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007f3c7b6a0862 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007f3c7b91353d in log_assert_failed (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ../systemd/src/basic/log.c:866
No locals.
#3  0x00007f3c7ba115d0 in in_addr_is_null (family=<optimized out>, u=<optimized out>) at ../systemd/src/basic/in-addr-util.c:34
        __PRETTY_FUNCTION__ = <optimized out>
#4  in_addr_is_null (family=<optimized out>, u=<optimized out>) at ../systemd/src/basic/in-addr-util.c:33
        __PRETTY_FUNCTION__ = "in_addr_is_null"
#5  0x00007f3c7b9982a8 in in_addr_is_set (u=<optimized out>, family=<optimized out>) at ../systemd/src/basic/in-addr-util.h:33
No locals.
#6  json_buildv (ret=<optimized out>, ap=0x7fffac6b9060) at ../systemd/src/shared/json.c:4046
        a = <optimized out>
        n = 0x5633bcf0324b "ConfigProvider"
        f = 2
        add = 0x0
        current = 0x5633be021328
        command = <optimized out>
        add_more = 0x0
        n_subtract = 0
        stack = 0x5633be021300
        n_stack = 2
        i = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "json_buildv"
#7  0x00007f3c7b9996de in json_build (ret=ret@entry=0x7fffac6b9210) at ../systemd/src/shared/json.c:4163
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffac6b9200, reg_save_area = 0x7fffac6b9080}}
        r = <optimized out>
#8  0x00005633bce8cebc in dns_build_json_one (link=<optimized out>, a=<optimized out>, s=<optimized out>, p=<optimized out>, ret=0x5633be031c60)
    at ../systemd/src/network/networkd-json.c:516
        v = 0x0
        r = <optimized out>
        __PRETTY_FUNCTION__ = "dns_build_json_one"
#9  0x00005633bce90802 in dns_build_json (ret=0x7fffac6b92b8, link=0x5633be03ed50) at ../systemd/src/network/networkd-json.c:564
        i = 0
        elements = 0x5633be031c60
        n = 0
        r = <optimized out>
        elements = <optimized out>
        n = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        finalize = <optimized out>
        i = <optimized out>
        i = <optimized out>
        dns = <optimized out>
        s = <optimized out>
        n_dns = <optimized out>
        i = <optimized out>
        dns = <optimized out>
        s = <optimized out>
        n_dns = <optimized out>
        i = <optimized out>
        a = <optimized out>
        __unique_prefix_i16 = <optimized out>
#10 link_build_json (link=0x5633be03ed50, ret=0x5633be032300) at ../systemd/src/network/networkd-json.c:1229
        v = 0x5633be050870
        w = 0x0
        type = 0x5633be040aa0 "bond"
        flags = 0x5633be0436b0 "up,broadcast,running,master,multicast,lower-up"
        r = <optimized out>
        __PRETTY_FUNCTION__ = "link_build_json"
#11 0x00005633bce27a1f in links_build_json (ret=0x7fffac6b94d8, manager=0x5633be015ea0) at ../systemd/src/network/networkd-json.c:1367
        __unique_prefix_i22 = {idx = 10, next_key = 0x3}
        link = 0x5633be03ed50
        elements = 0x5633be0322e0
        n = 4
        r = <optimized out>
        elements = <optimized out>
        link = <optimized out>
        n = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        finalize = <optimized out>
        __unique_prefix_i22 = <optimized out>
        _func_ = <optimized out>
#12 manager_build_json (ret=0x7fffac6b94c8, manager=0x5633be015ea0) at ../systemd/src/network/networkd-json.c:1390
        v = 0x0
        w = 0x0
        r = <optimized out>
        v = <optimized out>
        w = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        _pptr_ = <optimized out>
        _ptr_ = <optimized out>
#13 bus_method_describe (message=0x5633be045e00, userdata=0x5633be015ea0, error=<optimized out>) at ../systemd/src/network/networkd-manager-bus.c:243
        reply = 0x0
        v = 0x0
        text = 0x0
        manager = 0x5633be015ea0
        r = <optimized out>
        __PRETTY_FUNCTION__ = "bus_method_describe"
        __func__ = "bus_method_describe"
#14 0x00007f3c7ba72c64 in method_callbacks_run (found_object=0x7fffac6b96b7, require_fallback=false, c=0x5633be01e5b0, m=0x5633be045e00, bus=0x5633be01b550) at ../systemd/src/libsystemd/sd-bus/bus-objects.c:414
        slot = 0x5633be01d980
        error = {name = 0x0, message = 0x0, _need_free = 0}
        signature = <optimized out>
        u = 0x5633be015ea0
        r = <optimized out>
        error = <optimized out>
        signature = <optimized out>
        u = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        slot = <optimized out>
        __unique_prefix_A14 = <optimized out>
#15 object_find_and_run (bus=0x5633be01b550, m=0x5633be045e00, p=0x5633be03b498 "/org/freedesktop/network1", require_fallback=false, found_object=0x7fffac6b96b7) at ../systemd/src/libsystemd/sd-bus/bus-objects.c:1323
        n = 0x5633be01d930
        vtable_key = {path = 0x5633be03b498 "/org/freedesktop/network1", interface = 0x5633be03b4d8 "org.freedesktop.network1.Manager", member = 0x5633be03b4c0 "Describe", parent = 0x5633be01b5c8, last_iteration = 3187782992, vtable = 0x5633be01b5c8}
        v = 0x5633be01e5b0
        r = <optimized out>
        __PRETTY_FUNCTION__ = "object_find_and_run"
#16 0x00007f3c7ba74190 in bus_process_object (bus=0x5633be01b550, m=0x5633be045e00) at ../systemd/src/libsystemd/sd-bus/bus-objects.c:1443
        prefix = 0x5633be044740 "T\033\070\335\066V"
        r = <optimized out>
        pl = <optimized out>
        found_object = true
        __PRETTY_FUNCTION__ = "bus_process_object"
#17 0x00007f3c7ba87877 in process_message (m=0x5633be045e00, bus=0x5633be01b550) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:2963
        r = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        __func__ = <optimized out>
        finish = <optimized out>
        _mm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
#18 process_running (ret=0x0, bus=<optimized out>) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3005
        m = 0x5633be045e00
        r = 1
        null_message = <optimized out>
        m = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        null_message = <optimized out>
        __func__ = <optimized out>
        _found = <optimized out>
        __assert_in_set = <optimized out>
        _pptr_ = <optimized out>
        _ptr_ = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
#19 bus_process_internal (bus=<optimized out>, ret=0x0) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3225
        r = <optimized out>
        _dont_destroy_bus = 0x5633be01b550
        __PRETTY_FUNCTION__ = "bus_process_internal"
#20 0x00007f3c7ba88312 in io_callback (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x5633be01b550) at ../systemd/src/libsystemd/sd-bus/sd-bus.c:3603
        bus = 0x5633be01b550
        r = <optimized out>
        __PRETTY_FUNCTION__ = "io_callback"
        __func__ = "io_callback"
#21 0x00007f3c7bade0ae in source_dispatch (s=0x5633be020750) at ../systemd/src/libsystemd/sd-event/sd-event.c:3598
        saved_event = 0x5633be0161c0
        saved_type = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
#22 0x00007f3c7bade29e in sd_event_dispatch (e=0x5633be0161c0) at ../systemd/src/libsystemd/sd-event/sd-event.c:4183
        ref = 0x5633be0161c0
        p = 0x5633be020750
        r = <optimized out>
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
#23 0x00007f3c7badf9e9 in sd_event_run (e=0x5633be0161c0, timeout=18446744073709551615) at ../systemd/src/libsystemd/sd-event/sd-event.c:4244
        r = 1
        ref = 0x5633be0161c0
        __PRETTY_FUNCTION__ = "sd_event_run"
#24 0x00007f3c7badfbc0 in sd_event_loop (e=0x5633be0161c0) at ../systemd/src/libsystemd/sd-event/sd-event.c:4265
        r = <optimized out>
        ref = <optimized out>
        __PRETTY_FUNCTION__ = "sd_event_loop"
#25 0x00005633bce2497b in run (argv=<optimized out>, argc=<optimized out>) at ../systemd/src/network/networkd.c:114
        m = 0x5633be015ea0
        notify_message = 0x5633bcee47d8 "STOPPING=1\nSTATUS=Shutting down..."
        r = 0
        m = <optimized out>
        notify_message = <optimized out>
        r = <optimized out>
        __func__ = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        user = <optimized out>
        uid = <optimized out>
        gid = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _error = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
#26 main (argc=<optimized out>, argv=<optimized out>) at ../systemd/src/network/networkd.c:121
        r = <optimized out>

  ```
</details>

On the surface, this seems to be an issue with https://github.com/systemd/systemd/pull/21532, but I'm not 100% sure. I will try to bisect the actual commit. 

The interface doesn't matter. I can also reproduce this at will, so let me know if you need more information or to compile with optimizations off.

**Comment by yuwata** [comment]
Thank you for the report. I hope #21568 fixes this issue. PTAL.
