### ISSUE TITLE
journal: #21598 causes system freeze ~15sec

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#21675]
E.g. 
- https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5019/
- https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5048/
- https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5049/

From journal:
- [5048](https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5048/artifact/systemd-centos-ci/artifacts_ny8sds2j/testsuite-logs-upstream.jgR/journalctl-testsuite_PASS.log)
```
Dec 07 18:07:28 n5.gusty.ci.centos.org kernel: Linux version 4.18.0-348.2.1.el8_5.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)) #1 SMP Tue Nov 16 14:42:35 UTC 2021
(snip)
Dec 07 19:07:04 n5.gusty.ci.centos.org systemd-networkd[218859]: macvtap99: Requested to set master interface
Dec 07 19:07:19 n5.gusty.ci.centos.org systemd-networkd[218859]: macvtap99: Requested to activate link
```
- [5049](https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5049/artifact/systemd-centos-ci/artifacts_ak9no7rj/testsuite-logs-upstream.0zU/journalctl-testsuite_PASS.log)
```
Dec 07 18:11:08 n25.crusty.ci.centos.org kernel: Linux version 4.18.0-348.2.1.el8_5.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)) #1 SMP Tue Nov 16 14:42:35 UTC 2021
(snip)
Dec 07 19:13:57 n25.crusty.ci.centos.org systemd-networkd[237982]: test1: Received new foreign route (configured): dst: fe80::3c27:a9ff:fec9:d9b6/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Dec 07 19:14:12 n25.crusty.ci.centos.org systemd-networkd[237982]: macvtap99: udev initialized link
```

@mrc0mmand The kernel on CentOS Stream 8 is updated recently? I checked full journal, but there is no logs between the two gaps. It seems the system freezes for a while when repeatedly create/delete macvtap netdev.

**Comment by mrc0mmand** [comment]
> @mrc0mmand The kernel on CentOS Stream 8 is updated recently? I checked full journal, but there is no logs between the two gaps. It seems the system freezes for a while when repeatedly create/delete macvtap netdev.

I looked at jobs for the past week and the kernel remained the same (4.18.0-348.2.1.el8_5.x86_64). Is there anything I could do to help debug this?

**Comment by mrc0mmand** [comment]
I tried to reproduce this "locally" (successfully), and noticed a couple of setroubleshoot alerts around the failed test (selinux is set to permissive, but setroubleshootd is a *bit* resource-heavy, especially when the test generates a lot of denials in a succession). After removing it I couldn't reproduce the issue anymore, but since the reproducer is already pretty luck based, it's hard to say if it's indeed the root cause.

Anyway, since we don't care about selinux denials and they just unnecessarily clutter the logs, I just removed setroubleshoot-server from C8S nodes (https://github.com/systemd/systemd-centos-ci/pull/447). Let's see if it's going to help.

**Comment by mrc0mmand** [comment]
Oh well, that didn't help :(

https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5155/artifact//systemd-centos-ci/index.html

**Comment by mrc0mmand** [comment]
Interesting, the same issue popped up in the `test_macvlan` as well:

```
======================================================================
ERROR: test_macvlan (__main__.NetworkdNetDevTests) (mode='passthru')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 1231, in test_macvlan
    'test1:carrier' if mode == 'passthru' else 'test1:degraded'])
  File "./test/test-network/systemd-networkd-tests.py", line 654, in wait_online
    check_output(*args, env=env)
  File "./test/test-network/systemd-networkd-tests.py", line 59, in check_output
    return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/systemd/systemd-networkd-wait-online', '--timeout=20s', '--interface=macvlan99:degraded', '--interface=test1:carrier']' returned non-zero exit status 1.
```

https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5206/artifact//systemd-centos-ci/index.html

There's a "spurious" ~17 second "freeze", like in the `test_macvtap` case:
```
Dec 13 22:56:00 n62.dusty.ci.centos.org systemd-networkd[266113]: eth6: Link state is up-to-date
Dec 13 22:56:00 n62.dusty.ci.centos.org systemd-networkd[266113]: eth6: State changed: initialized -> unmanaged
Dec 13 22:56:00 n62.dusty.ci.centos.org systemd-networkd[266113]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_38 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=17 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 13 22:56:00 n62.dusty.ci.centos.org systemd-networkd[266113]: eth5: Link state is up-to-date
Dec 13 22:56:17 n62.dusty.ci.centos.org systemd-networkd[266113]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_37 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=18 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 13 22:56:17 n62.dusty.ci.centos.org systemd-networkd[266113]: eth4: Link state is up-to-date
Dec 13 22:56:17 n62.dusty.ci.centos.org systemd-networkd[266113]: eth4: State changed: initialized -> unmanaged
```

**Comment by mrc0mmand** [comment]
Hah, interesting. When looking at the test journal around the "hang", it always shows an error from journald and the log message order is also a bit strange:

https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5019/artifact//systemd-centos-ci/index.html
```
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-networkd[238370]: test1: loaded dummy
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-networkd[238370]: test1: Using MAC address: 66:23:6f:fc:e8:69
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-networkd[238370]: test1: Creating
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-networkd[238370]: test1: Creating
Dec 07 09:13:54 n3.crusty.ci.centos.org systemd-journald[893]: Failed to write entry (26 items, 738 bytes), rotating before retrying: Argument list too long
Dec 07 09:13:38 n3.crusty.ci.centos.org audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-resolved[226195]: Found new link 276/test1
Dec 07 09:13:38 n3.crusty.ci.centos.org rsyslogd[1394]: imjournal: journal files changed, reloading...  [v8.2102.0-6.el8 try https://www.rsyslog.com/e/0 ]
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-networkd[238370]: macvtap99: loaded macvtap
Dec 07 09:13:41 n3.crusty.ci.centos.org setroubleshoot[238226]: AnalyzeThread.run(): Cancel pending alarm
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-udevd[238361]: test1: The log level is changed to 'debug' while processing device (SEQNUM=9902, ACTION=add)
Dec 07 09:13:41 n3.crusty.ci.centos.org setroubleshoot[238226]: failed to retrieve rpm info for /run/systemd/userdb/io.systemd.Machine
Dec 07 09:13:38 n3.crusty.ci.centos.org systemd-networkd[238370]: No virtualization found in DMI vendor table.
```

https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5206/artifact//systemd-centos-ci/index.html
```
Dec 13 22:55:57 n62.dusty.ci.centos.org systemd-resolved[257923]: Retrying transaction 44883.
Dec 13 22:55:57 n62.dusty.ci.centos.org systemd-resolved[257923]: Firing regular transaction 44883 for <n62 IN ANY> scope llmnr on macvlan99/INET (validate=yes).
Dec 13 22:55:57 n62.dusty.ci.centos.org systemd-resolved[257923]: Sending query packet with id 44883 on interface 278/AF_INET of size 21.
Dec 13 22:56:17 n62.dusty.ci.centos.org systemd-journald[908]: Failed to write entry (25 items, 782 bytes), rotating before retrying: Argument list too long
Dec 13 22:56:17 n62.dusty.ci.centos.org kernel: device test1 left promiscuous mode
Dec 13 22:56:17 n62.dusty.ci.centos.org kernel: proc: Bad value for 'hidepid'
Dec 13 22:55:58 n62.dusty.ci.centos.org audit: ANOM_PROMISCUOUS dev=test1 prom=0 old_prom=256 auid=0 uid=0 gid=0 ses=1
Dec 13 22:55:58 n62.dusty.ci.centos.org audit[266103]: SYSCALL arch=c000003e syscall=46 success=yes exit=32 a0=3 a1=7ffdc8c9b090 a2=0 a3=0 items=0 ppid=257767 pid=266103 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="ip" exe="/usr/sbin/ip" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null)
Dec 13 22:55:58 n62.dusty.ci.centos.org audit: PROCTITLE proctitle=6970006C696E6B0064656C00646576006D6163766C616E3939
Dec 13 22:55:59 n62.dusty.ci.centos.org audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 13 22:55:59 n62.dusty.ci.centos.org audit: BPF prog-id=890 op=LOAD
Dec 13 22:55:59 n62.dusty.ci.centos.org audit[266113]: SYSCALL arch=c000003e syscall=42 success=yes exit=0 a0=6 a1=7ffe44ba9640 a2=29 a3=1eaca00 items=0 ppid=1 pid=266113 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="(networkd)" exe="/usr/lib/systemd/systemd" subj=system_u:system_r:init_t:s0 key=(null)
Dec 13 22:55:59 n62.dusty.ci.centos.org audit: PROCTITLE proctitle="(networkd)"
Dec 13 22:56:00 n62.dusty.ci.centos.org audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 13 22:55:57 n62.dusty.ci.centos.org systemd-resolved[257923]: Received llmnr UDP packet of size 21, ifindex=278, ttl=255, fragsize=0, sender=169.254.45.100, destination=224.0.0.252
```

https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5048/artifact//systemd-centos-ci/index.html
```
Dec 07 19:07:03 n5.gusty.ci.centos.org systemd-networkd[218818]: macvtap99: Forgetting foreign route (n/a): dst: fe80::/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: anycast, nexthop: 0, priority: 0, flags: n/a
Dec 07 19:07:03 n5.gusty.ci.centos.org systemd-networkd[218818]: macvtap99: Forgetting foreign route (n/a): dst: fe80::/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: anycast, nexthop: 0, priority: 0, flags: n/a
Dec 07 19:07:19 n5.gusty.ci.centos.org systemd-journald[894]: Failed to write entry (26 items, 921 bytes), rotating before retrying: Argument list too long
Dec 07 19:07:19 n5.gusty.ci.centos.org kernel: proc: Bad value for 'hidepid'
Dec 07 19:07:04 n5.gusty.ci.centos.org audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 07 19:07:04 n5.gusty.ci.centos.org audit: BPF prog-id=891 op=LOAD
Dec 07 19:07:04 n5.gusty.ci.centos.org audit[218859]: AVC avc:  denied  { mounton } for  pid=218859 comm="(networkd)" path="/run/systemd/unit-root/dev/kmsg" dev="devtmpfs" ino=13413 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:kmsg_device_t:s0 tclass=chr_file permissive=1
Dec 07 19:07:04 n5.gusty.ci.centos.org audit[218859]: SYSCALL arch=c000003e syscall=165 success=yes exit=0 a0=1c55f60 a1=7fffd4362390 a2=0 a3=5000 items=1 ppid=1 pid=218859 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="(networkd)" exe="/usr/lib/systemd/systemd" subj=system_u:system_r:init_t:s0 key=(null)
Dec 07 19:07:04 n5.gusty.ci.centos.org audit: CWD cwd="/"
Dec 07 19:07:04 n5.gusty.ci.centos.org audit: PATH item=0 name="/run/systemd/inaccessible/chr" inode=17308 dev=00:18 mode=020000 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:init_var_run_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
Dec 07 19:07:04 n5.gusty.ci.centos.org audit: PROCTITLE proctitle="(networkd)"
```

etc. The message ` systemd-journald[893]: Failed to write entry (26 items, 738 bytes), rotating before retrying: Argument list too long` is the common denominator in all the test fails.

**Comment by mrc0mmand** [comment]
So I guess a workaround would be to rotate the journal before running the systemd-networkd test suite to avoid rotation during time-sensitive parts of the test.

**Comment by yuwata** [comment]
Hmm... @DaanDeMeyer and @vcaputo Do you have any idea?

**Comment by mrc0mmand** [comment]
> > So I guess a workaround would be to rotate the journal before running the systemd-networkd test suite to avoid rotation during time-sensitive parts of the test.
> 
> Maybe. Could you try that in systemd-centos-ci repo?

Will do.

**Comment by yuwata** [comment]
Thank you.

**Comment by mrc0mmand** [comment]
So, this is really strange, I went through several dozens of logs and before December 7th they all have the messages in sequential order without any delay when rotating journal:

```
Dec 03 12:53:41 n52.dusty.ci.centos.org systemd[1]: Started Network Configuration.
Dec 03 12:53:41 n52.dusty.ci.centos.org systemd-resolved[241397]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/resolve1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=3018 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 03 12:53:41 n52.dusty.ci.centos.org systemd-networkd[253754]: Bus bus-api-network: changing state AUTHENTICATING â†’ HELLO
Dec 03 12:53:41 n52.dusty.ci.centos.org systemd-networkd[253754]: Bus bus-api-network: changing state AUTHENTICATING â†’ HELLO
Dec 03 12:53:41 n52.dusty.ci.centos.org systemd-journald[909]: Failed to write entry (25 items, 771 bytes), rotating before retrying: Argument list too long
Dec 03 12:53:41 n52.dusty.ci.centos.org rsyslogd[1278]: imjournal: journal files changed, reloading...  [v8.2102.0-6.el8 try https://www.rsyslog.com/e/0 ]
Dec 03 12:53:41 n52.dusty.ci.centos.org systemd-networkd[253754]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Dec 03 12:53:41 n52.dusty.ci.centos.org systemd-networkd[253754]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
```

```
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: eth0: Gained carrier
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: eth0: udev initialized link
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: eth0: State changed: pending -> initialized
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: eth0: State changed: pending -> initialized
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-journald[892]: Failed to write entry (26 items, 766 bytes), rotating before retrying: Argument list too long
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: lo: Saved new link: ifindex=1, iftype=LOOPBACK(772), kind=n/a
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: lo: Saved permanent hardware address: 00:00:00:00:00:00
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: lo: Failed to get driver, continuing without: Operation not supported
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: lo: Saved original MTU 65536 (min: 0, max: 4294967295)
Dec 06 12:55:31 n28.gusty.ci.centos.org systemd-networkd[220764]: lo: Saved hardware address: 00:00:00:00:00:00
```

```
Dec 07 08:06:36 n4.gusty.ci.centos.org systemd-networkd[221011]: rtnl: received non-static neighbor, ignoring.
Dec 07 08:06:36 n4.gusty.ci.centos.org systemd-networkd[221011]: rtnl: received non-static neighbor, ignoring.
Dec 07 08:06:36 n4.gusty.ci.centos.org systemd-journald[896]: Failed to write entry (25 items, 772 bytes), rotating before retrying: Argument list too long
Dec 07 08:06:36 n4.gusty.ci.centos.org kernel: device test1 entered promiscuous mode
Dec 07 08:06:36 n4.gusty.ci.centos.org audit: ANOM_PROMISCUOUS dev=test1 prom=256 old_prom=0 auid=4294967295 uid=982 gid=982 ses=4294967295
Dec 07 08:06:36 n4.gusty.ci.centos.org audit[221011]: SYSCALL arch=c000003e syscall=44 success=yes exit=32 a0=3 a1=12580b0 a2=20 a3=0 items=0 ppid=1 pid=221011 auid=4294967295 uid=982 gid=982 euid=982 suid=982 fsuid=982 egid=982 sgid=982 fsgid=982 tty=(none) ses=4294967295 comm="systemd-network" exe="/usr/lib/systemd/systemd-networkd" subj=system_u:system_r:systemd_networkd_t:s0 key=(null)
Dec 07 08:06:36 n4.gusty.ci.centos.org audit: PROCTITLE proctitle="(networkd)"
Dec 07 08:06:36 n4.gusty.ci.centos.org rsyslogd[1233]: imjournal: journal files changed, reloading...  [v8.2102.0-6.el8 try https://www.rsyslog.com/e/0 ]
Dec 07 08:06:36 n4.gusty.ci.centos.org systemd-networkd[221011]: rtnl: received non-static neighbor, ignoring.
Dec 07 08:06:36 n4.gusty.ci.centos.org systemd-networkd[221011]: rtnl: received non-static neighbor, ignoring.
```

But logs from jobs following the previous one started showing the symptoms described in https://github.com/systemd/systemd/issues/21675#issuecomment-993524324 - logs in a non-sequential order and a noticeable delay during rotation:

```
Dec 07 11:30:07 n35.dusty.ci.centos.org systemd-networkd[255879]: eth3: Gained carrier
Dec 07 11:30:07 n35.dusty.ci.centos.org systemd-networkd[255879]: eth3: Gained carrier
Dec 07 11:30:28 n35.dusty.ci.centos.org systemd-journald[909]: Failed to write entry (26 items, 747 bytes), rotating before retrying: Argument list too long
Dec 07 11:30:28 n35.dusty.ci.centos.org kernel: device test1 entered promiscuous mode
Dec 07 11:30:28 n35.dusty.ci.centos.org kernel: device test1 left promiscuous mode
Dec 07 11:30:07 n35.dusty.ci.centos.org audit: ANOM_PROMISCUOUS dev=test1 prom=256 old_prom=0 auid=4294967295 uid=982 gid=982 ses=4294967295
Dec 07 11:30:07 n35.dusty.ci.centos.org audit[255879]: SYSCALL arch=c000003e syscall=44 success=yes exit=32 a0=3 a1=27620b0 a2=20 a3=0 items=0 ppid=1 pid=255879 auid=4294967295 uid=982 gid=982 euid=982 suid=982 fsuid=982 egid=982 sgid=982 fsgid=982 tty=(none) ses=4294967295 comm="systemd-network" exe="/usr/lib/systemd/systemd-networkd" subj=system_u:system_r:systemd_networkd_t:s0 key=(null)
Dec 07 11:30:07 n35.dusty.ci.centos.org audit: PROCTITLE proctitle="(networkd)"
```

So this indeed looks like a regression.

**Comment by yuwata** [comment]
Thank you for the investigation. #21598 is marged on Dec. 7th.

**Comment by yuwata** [comment]
(#21527 is merged on Dec. 8th, but I cannot find any issue on the PR)

**Comment by yuwata** [comment]
@mrc0mmand It maybe better to revert https://github.com/systemd/systemd-centos-ci/pull/448. As the networkd test failure can 'easily' detect this issue, and I am concerning that https://github.com/systemd/systemd-centos-ci/pull/448 may hide the issue.

**Comment by bluca** [comment]
Most of the TEST-29-PORTABLE failures I see on focal-ppc64el have the ~15sec freeze

**Comment by mrc0mmand** [comment]
> @mrc0mmand It maybe better to revert [systemd/systemd-centos-ci#448](https://github.com/systemd/systemd-centos-ci/pull/448). As the networkd test failure can 'easily' detect this issue, and I am concerning that [systemd/systemd-centos-ci#448](https://github.com/systemd/systemd-centos-ci/pull/448) may hide the issue.

Indeed, done: https://github.com/systemd/systemd-centos-ci/commit/0555e72ac8fbc736f17937ef8e0602fd1ba62a5b.
