### ISSUE TITLE
coredumpctl: segfault when malloc() fails

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#21867]
**systemd version the issue has been seen with**
 > latest main

**Used distribution**
 > Fedora 34

I had a bit of spare time on my hands and got a wild thought to somehow test various parts of systemd in cases where malloc/calloc/realloc/reallocarray fails. For that I wrote a dumb little project (https://github.com/mrc0mmand/test-malloc-fail) and after some spelunking I managed to trigger following segfault in coredumpctl:

```
$ MALLOC_FAIL_AT=181 LD_PRELOAD=~/repos/test-malloc-fail/build/libtest_malloc_fail.so build/coredumpctl --no-pager
Failed to add match "MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1": Cannot allocate memory
Segmentation fault (core dumped)
```

```gdb
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc9197a8ba6 in match_free (m=0x4a62c0) at ../src/libsystemd/sd-journal/sd-journal.c:222
222	                LIST_REMOVE(matches, m->parent->matches, m);
(gdb) bt full
#0  0x00007fc9197a8ba6 in match_free (m=0x4a62c0) at ../src/libsystemd/sd-journal/sd-journal.c:222
        _head = 0xb0f7f4e48cd73129
        _item = 0x4a62c0
        __PRETTY_FUNCTION__ = "match_free"
#1  0x00007fc9197a9634 in sd_journal_flush_matches (j=0x4a1ff0) at ../src/libsystemd/sd-journal/sd-journal.c:425
No locals.
#2  0x00007fc9197b0f59 in sd_journal_close (j=0x4a1ff0) at ../src/libsystemd/sd-journal/sd-journal.c:2146
        d = 0xfffffff400000000
#3  0x0000000000403951 in sd_journal_closep (p=0x7ffe3d0e1b98) at ../src/systemd/sd-journal.h:173
No locals.
#4  0x00000000004049db in acquire_journal (ret=0x7ffe3d0e1c48, matches=0x7ffe3d0e1d08) at ../src/coredump/coredumpctl.c:115
        j = 0x4a1ff0
        r = -12
        __PRETTY_FUNCTION__ = "acquire_journal"
        __func__ = "acquire_journal"
#5  0x0000000000407cd4 in dump_list (argc=1, argv=0x7ffe3d0e1d00, userdata=0x0) at ../src/coredump/coredumpctl.c:807
        j = 0x0
        t = 0x0
        n_found = 0
        verb_is_info = false
        r = 32766
        __func__ = "dump_list"
        __PRETTY_FUNCTION__ = "dump_list"
#6  0x00007fc919656e36 in dispatch_verb (argc=2, argv=0x7ffe3d0e1ef8, verbs=0x40cd60 <verbs>, userdata=0x0) at ../src/shared/verbs.c:110
        fake = {0x40cd33 "list", 0x0}
        verb = 0x40cd60 <verbs>
        name = 0x0
        left = 1
        __PRETTY_FUNCTION__ = "dispatch_verb"
        __func__ = "dispatch_verb"
#7  0x000000000040ac76 in coredumpctl_main (argc=2, argv=0x7ffe3d0e1ee8) at ../src/coredump/coredumpctl.c:1257
        verbs = {{verb = 0x40cd33 "list", min_args = 4294967295, max_args = 4294967295, flags = VERB_DEFAULT, dispatch = 0x407c3c <dump_list>}, {verb = 0x40c1df "info", 
            min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x407c3c <dump_list>}, {verb = 0x40cd38 "dump", min_args = 4294967295, max_args = 4294967295, 
            flags = 0, dispatch = 0x409388 <dump_core>}, {verb = 0x40cd3d "debug", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x4096a7 <run_debug>}, {
            verb = 0x40c585 "gdb", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x4096a7 <run_debug>}, {verb = 0x40c8fb "help", min_args = 4294967295, 
            max_args = 1, flags = 0, dispatch = 0x4049f7 <verb_help>}, {verb = 0x0, min_args = 0, max_args = 0, flags = 0, dispatch = 0x0}}
#8  0x000000000040ace5 in run (argc=2, argv=0x7ffe3d0e1ee8) at ../src/coredump/coredumpctl.c:1277
        r = 1
        units_active = 0
#9  0x000000000040ad69 in main (argc=2, argv=0x7ffe3d0e1ee8) at ../src/coredump/coredumpctl.c:1288
        r = 32713
```

Question: do we even care for segfaults in such situations?

**Comment by bluca** [comment]
> Question: do we even care for segfaults in such situations?

This sounds like as sympton of not correctly handling function failure somewhere, so I'd say yes, we should fix it
