### ISSUE TITLE
SIGBUS on SPARC caused by NSS lookups

### ISSUE THREAD

**Issue by thesamesam** [systemd/systemd#21935]
**systemd version the issue has been seen with**
>Known good versions:
>- sys-apps/systemd-249.4-r4 (but not recompiled it yet)
>
>Known bad versions:
>- sys-apps/systemd-249.6-r1
>- sys-apps/systemd-249.7
>- sys-apps/systemd-250-r1

**Used distribution**
 > Gentoo Linux.

**Linux kernel version used** (`uname -a`)

 > `5.15.5-gentoo`

**CPU architecture issue was seen on**
 > sparc64

**Expected behaviour you didn't see**
 > Commands which end up involving NSS lookups like `ls -al` succeeding.

**Unexpected behaviour you saw**
 > SIGBUS on `ls -al`, `sudo su`.

**Steps to reproduce the problem**
 > 1. Install >sys-apps/systemd-249.4 on a `sparc64` machine
 > 2. Have systemd configured for NSS lookups in `/etc/nsswitch.conf`
 > 3. Try to run `ls -al` or some other command which will need to lookup entries via NSS

**Additional program output to the terminal or log subsystem illustrating the issue**

Originally reported downstream in Gentoo [here](https://bugs.gentoo.org/830275).

```
$ sudo su
Bus error (core dumped)
```

```
$ ls -al
Bus error (core dumped)
```

Backtrace:
```
(gdb) bt
#0  copy_synthesized_group (dest=0xfff800010049bf90 <resbuf>, src=0xfff8000100706b08 <root_group>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:254
#1  0xfff80001005b6730 in _nss_systemd_getgrgid_r (gid=<optimized out>, gr=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:498
#2  0xfff80001002f1f54 in __getgrgid_r (gid=<optimized out>, resbuf=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, result=0x7fefff207e0) at ../nss/getXXbyYY_r.c:274
#3  0xfff80001002f150c in getgrgid (gid=<optimized out>) at ../nss/getXXbyYY.c:135
#4  0x0000010000012d3c in getgroup (gid=<optimized out>) at lib/idcache.c:167
#5  0x000001000000dc84 in format_group_width (g=0) at src/ls.c:4183
#6  gobble_file (name=0x1000012f623 "glibc-2.30-r9.ebuild", type=<optimized out>, command_line_arg=<optimized out>, dirname=<optimized out>, inode=0) at src/ls.c:3534
#7  0x000001000000e484 in print_dir (name=0x100001276e0 ".", realname=<optimized out>, command_line_arg=<optimized out>) at src/ls.c:2989
#8  0x00000100000046e4 in main (argc=<optimized out>, argv=<optimized out>) at src/ls.c:1778
(gdb)
```

Note that the machine is running glibc-2.33 and the 2.30 reference in the backtrace is just because there's a bunch of glibc ebuilds (=filenames) in the directory I was in.

I don't think there was anything else related/useful in the journal.

**Comment by thesamesam** [comment]
Reverting 47fd7fa6c650d7a0ac41bc89747e3b866ffb9534 from #20679 with 250 works.

`/etc/nsswitch.conf` I'm using to trigger this:
```
# In alphabetical order. Re-order as required to optimize peformance.
aliases:    files
ethers:     files
group:      files [SUCCESS=merge] systemd
gshadow:    files systemd
hosts:      files dns
# Allow initgroups to default to the setting for group.
# initgroups: files
netgroup:   files
networks:   files dns
passwd:     files systemd
protocols:  files
publickey:  files
rpc:        files
shadow:     files systemd
services:   files
```

**Comment by yuwata** [comment]
Thank you for the report. Could you test PR #21938?

**Comment by thesamesam** [comment]
> Thank you for the report. Could you test PR #21938?

Thanks @yuwata. Sadly, `ls -al` still ends up SIGBUSing for me. The backtrace seems the same too:
```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `ls --color=auto -al'.
Program terminated with signal SIGUSR1, User defined signal 1.
#0  copy_synthesized_group (dest=0xfff800010049bf90 <resbuf>, src=0xfff8000100ca6b08 <root_group>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:254
254             *dest->gr_mem = NULL;
(gdb) bt
#0  copy_synthesized_group (dest=0xfff800010049bf90 <resbuf>, src=0xfff8000100ca6b08 <root_group>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:254
#1  0xfff8000100b56730 in _nss_systemd_getgrgid_r (gid=<optimized out>, gr=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:498
#2  0xfff80001002f1f54 in __getgrgid_r (gid=<optimized out>, resbuf=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, result=0x7feffef8820) at ../nss/getXXbyYY_r.c:274
#3  0xfff80001002f150c in getgrgid (gid=<optimized out>) at ../nss/getXXbyYY.c:135
#4  0x0000010000012d3c in getgroup (gid=<optimized out>) at lib/idcache.c:167
#5  0x000001000000dc84 in format_group_width (g=0) at src/ls.c:4183
#6  gobble_file (name=0x1000012f623 ".bash_history", type=<optimized out>, command_line_arg=<optimized out>, dirname=<optimized out>, inode=0) at src/ls.c:3534
#7  0x000001000000e484 in print_dir (name=0x100001276e0 ".", realname=<optimized out>, command_line_arg=<optimized out>) at src/ls.c:2989
#8  0x00000100000046e4 in main (argc=<optimized out>, argv=<optimized out>) at src/ls.c:1778
(gdb)
```

Did double check that the patch is applied. Let me know if I can try anything else / give any other information too.

**Comment by yuwata** [comment]
Ouch. Could you test #21944?

**Comment by thesamesam** [comment]
Thanks! But not yet:

```
Program terminated with signal SIGUSR1, User defined signal 1.
#0  copy_synthesized_group (dest=0xfff800010049bf90 <resbuf>, src=0xfff8000100ca6b08 <root_group>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:254
254             *dest->gr_mem = NULL;
(gdb) bt
#0  copy_synthesized_group (dest=0xfff800010049bf90 <resbuf>, src=0xfff8000100ca6b08 <root_group>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:254
#1  0xfff8000100b56730 in _nss_systemd_getgrgid_r (gid=<optimized out>, gr=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:498
#2  0xfff80001002f1f54 in __getgrgid_r (gid=<optimized out>, resbuf=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, result=0x7feffef8820) at ../nss/getXXbyYY_r.c:274
#3  0xfff80001002f150c in getgrgid (gid=<optimized out>) at ../nss/getXXbyYY.c:135
#4  0x0000010000012d3c in getgroup (gid=<optimized out>) at lib/idcache.c:167
#5  0x000001000000dc84 in format_group_width (g=0) at src/ls.c:4183
#6  gobble_file (name=0x1000012f623 ".bash_history", type=<optimized out>, command_line_arg=<optimized out>, dirname=<optimized out>, inode=0) at src/ls.c:3534
#7  0x000001000000e484 in print_dir (name=0x100001276e0 ".", realname=<optimized out>, command_line_arg=<optimized out>) at src/ls.c:2989
#8  0x00000100000046e4 in main (argc=<optimized out>, argv=<optimized out>) at src/ls.c:1778
(gdb)
```

If necessary, you're free to have access to this porting machine FWIW.

**Comment by yuwata** [comment]
Could you apply the following, and then run `build/test-nss-util systemd root`?
```
diff --git a/src/nss-systemd/nss-systemd.c b/src/nss-systemd/nss-systemd.c
index be794934bd..eb2aa00fce 100644
--- a/src/nss-systemd/nss-systemd.c
+++ b/src/nss-systemd/nss-systemd.c
@@ -253,6 +253,9 @@ static enum nss_status copy_synthesized_group(
         dest->gr_mem = (char **) (stpcpy(dest->gr_passwd, src->gr_passwd) + 1);
         *dest->gr_mem = NULL;
 
+        log_info("%s(): buffer:%p, dest:%p, gr_name:%p, gr_passwd:%p, gr_mem:%p, gr_mem[0]:%p",
+                 __func__, buffer, dest, dest->gr_name, dest->gr_passwd, dest->gr_mem, dest->gr_mem[0]);
+
         return NSS_STATUS_SUCCESS;
 }
 
```
On my machine (x86_64), I get the following:
```
copy_synthesized_group(): buffer:0x1ffefffde0, dest:0x1fff000270, gr_name:0x1ffefffde0, gr_passwd:0x1ffefffde5, gr_mem:0x1ffefffde7, gr_mem[0]:(nil)
```

**Comment by thesamesam** [comment]
Hm, I don't see `test-nss-util` anywhere. But I do have `test-nss-users` and `test-nss-hosts` so I'll run users:

```
# ./test-nss-users systemd root
======== systemd ========
_nss_systemd_getpwnam_r("root") → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0:0
        passwd="x"
        gecos="Super User"
        dir="/root"
        shell="/bin/sh"
Bus error (core dumped)
```

I think it's good news that this breaks too:
```
Program terminated with signal SIGUSR1, User defined signal 1.
#0  0xfff800010219524c in copy_synthesized_group (dest=0x7feffa630d0, src=0xfff80001022e6b08 <root_group>, buffer=0x7feffa62cc0 "root", buflen=1024, errnop=0x7feffa630cc)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:256
256             log_info("%s(): buffer:%p, dest:%p, gr_name:%p, gr_passwd:%p, gr_mem:%p, gr_mem[0]:%p",
(gdb) bt
#0  0xfff800010219524c in copy_synthesized_group (dest=0x7feffa630d0, src=0xfff80001022e6b08 <root_group>, buffer=0x7feffa62cc0 "root", buflen=1024, errnop=0x7feffa630cc)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:256
#1  0xfff8000102196478 in _nss_systemd_getgrnam_r (name=0x10000106330 "root", gr=0x7feffa630d0, buffer=0x7feffa62cc0 "root", buflen=1024, errnop=0x7feffa630cc)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:457
#2  0x0000010000002054 in test_getgrnam_r (handle=0x100001063c0, module=<optimized out>, name=0x10000106330 "root") at ../systemd-250/src/test/test-nss-users.c:90
#3  0x00000100000010a8 in test_byname (name=0x10000106330 "root", module=0x100001062f0 "systemd", handle=0x100001063c0) at ../systemd-250/src/test/test-nss-users.c:153
#4  test_one_module (names=0x10000106310, module=0x100001062f0 "systemd", dir=<optimized out>) at ../systemd-250/src/test/test-nss-users.c:175
#5  run (argv=<optimized out>, argc=<optimized out>) at ../systemd-250/src/test/test-nss-users.c:250
#6  main (argc=<optimized out>, argv=<optimized out>) at ../systemd-250/src/test/test-nss-users.c:258
(gdb)
```

Maybe helpful:
```
(gdb) p dest->gr_mem[0]
$5 = 0x2f62696e2f7368 <error: Cannot access memory at address 0x2f62696e2f7368>
(gdb) p dest->gr_mem
$6 = (char **) 0x7feffa62cc7
```

**Comment by yuwata** [comment]
Thanks. Could you test the PR again?

**Comment by thesamesam** [comment]
Huge thanks to you. Looks great (original fix in master + your PR):

```
# ./test-nss-users systemd root
======== systemd ========
_nss_systemd_getpwnam_r("root") → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0:0
        passwd="x"
        gecos="Super User"
        dir="/root"
        shell="/bin/sh"
_nss_systemd_getgrnam_r("root") → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0
        passwd="x"
        members=
```

```
# ls -al
total 2020
drwxr-xr-x   3 root root    4096 Dec 25 15:05 .
drwxr-xr-x 293 root root   12288 Dec  6 10:45 ..
-rw-r--r--   1 root root 1972773 Dec 20 20:36 build.log
drwxr-xr-x   2 root root    4096 Dec 25 10:45 files
-rw-r--r--   1 root root     936 Dec 23 13:25 Manifest
-rw-r--r--   1 root root    2627 Dec 25 13:45 metadata.xml
-rw-r--r--   1 root root   14730 Dec  7 12:45 systemd-249.6-r1.ebuild
-rw-r--r--   1 root root   14731 Dec 24 17:25 systemd-249.7.ebuild
-rw-r--r--   1 root root   15274 Dec 25 15:05 systemd-250-r1.ebuild
-rw-r--r--   1 root root   15236 Dec 25 15:05 systemd-9999.ebuild
```

**Comment by yuwata** [comment]
Yay! Thank you for testing so many times!

**Comment by evverx** [comment]
FWIW UBsan could have caught this if the test had been run
```
$ UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1 ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 ./build/test-nss-users
======== systemd ========
_nss_systemd_getpwnam_r("root") → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0:0
        passwd="x"
        gecos="Super User"
        dir="/root"
        shell="/bin/sh"
../src/nss-systemd/nss-systemd.c:254:23: runtime error: store to misaligned address 0x7ffec31c18ee for type 'char *', which requires 8 byte alignment
0x7ffec31c18ee: note: pointer points here
 65 72 20 55 73 65  72 00 2f 72 6f 6f 74 00  2f 62 69 6e 2f 73 68 00  10 00 00 00 00 00 00 00  58 83
             ^
    #0 0x7faf080956fd in copy_synthesized_group ../src/nss-systemd/nss-systemd.c:254
    #1 0x7faf08098305 in _nss_systemd_getgrnam_r ../src/nss-systemd/nss-systemd.c:454
    #2 0x404c4c in test_getgrnam_r ../src/test/test-nss-users.c:90
    #3 0x4066de in test_byname ../src/test/test-nss-users.c:153
    #4 0x406993 in test_one_module ../src/test/test-nss-users.c:175
    #5 0x407780 in run ../src/test/test-nss-users.c:250
    #6 0x407908 in main ../src/test/test-nss-users.c:258
    #7 0x7faf0d65655f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #8 0x7faf0d65660b in __libc_start_main_impl (/lib64/libc.so.6+0x2d60b)
    #9 0x4023b4 in _start (/home/vagrant/systemd/build/test-nss-users+0x4023b4)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/nss-systemd/nss-systemd.c:254:23 in
```

**Comment by evverx** [comment]
I'm not sure why it isn't run though. It seems to be "manual" for some reason and the CI just skips it.

**Comment by evverx** [comment]
Just to clarify, with that PR applied the issue is gone :-)

But
```
$ UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1 ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 ./build/test-nss-hosts
======== myhostname ========
../src/nss-myhostname/nss-myhostname.c:139:16: runtime error: applying non-zero offset 18446744073709551584 to null pointer
    #0 0x7fb9429cf369 in _nss_myhostname_gethostbyname4_r ../src/nss-myhostname/nss-myhostname.c:139
    #1 0x404cea in test_gethostbyname4_r ../src/test/test-nss-hosts.c:116
    #2 0x409bc5 in test_byname ../src/test/test-nss-hosts.c:312
    #3 0x40a986 in test_one_module ../src/test/test-nss-hosts.c:381
    #4 0x40c1dc in run ../src/test/test-nss-hosts.c:478
    #5 0x40c39b in main ../src/test/test-nss-hosts.c:486
    #6 0x7fb947d2a55f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #7 0x7fb947d2a60b in __libc_start_main_impl (/lib64/libc.so.6+0x2d60b)
    #8 0x4024d4 in _start (/home/vagrant/systemd/build/test-nss-hosts+0x4024d4)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/nss-myhostname/nss-myhostname.c:139:16 in
```
:-) Those tests certainly should be run from time to time automatically

**Comment by yuwata** [comment]
@evverx Let's see that #21946 catch the issues.

**Comment by evverx** [comment]
On the bright side, the alignment UBSan check will be rolled out on OSS-Fuzz once https://github.com/systemd/systemd/pull/21915 is merged so SPARC machines are going to be covered much better in 2022 in general :-)

**Comment by yuwata** [comment]
Fix for nss-myhostname issue is now also in #21944.

**Comment by evverx** [comment]
Looks like UBsan is happy. Thanks!

Apparently those tests aren't ready to be run yet but at least eventually they hopefully can be used to catch and prevent issues like that.

**Comment by evverx** [comment]
The tests are hopefully on the way: https://github.com/systemd/systemd/pull/21778 but https://github.com/systemd/systemd/issues/21975 prevents them from being rolled out

**Comment by thesamesam** [comment]
Thank you all and I appreciate the efforts to get the tests running to avoid regressions/catch future cases!
