### ISSUE TITLE
[systemd-networkd] regular crashes since v250 release

### ISSUE THREAD

**Issue by pfactum** [systemd/systemd#22253]
**systemd version the issue has been seen with**

```
systemd 250 (250.3-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```
**Used distribution**

Latest Arch Linux.

**Linux kernel version used** (`uname -a`)

```
$ uname -a
Linux defiant 5.16.0-pf2 #1 SMP PREEMPT Sun, 23 Jan 2022 08:47:42 +0000 x86_64 GNU/Linux
```

(_it was the same with v5.15_)

**CPU architecture issue was seen on**

`x86_64`

**Expected behaviour you didn't see**

`systemd-neworkd` should not segfault.

**Unexpected behaviour you saw**

`systemd-neworkd` segfaults once DHCP client connects via Wi-Fi.

**Steps to reproduce the problem**

There's a static lease defined for device:

```
[DHCPServerStaticLease]
MACAddress=xx:xx:xx:xx:xx:xx
Address=1.2.3.4
```

The Wi-Fi interface is used by hostapd, but hostapd doesn't do anything with bridging, VLANs etc. All the networking stuff is on `systemd-networkd`. The Wi-Fi interface is a part of bridge:

```
[Match]
Name=wlp1s0

[Network]
Bridge=wifi-br
```

The bridge is defined as following:

```
[NetDev]
Name=wifi-br
Kind=bridge
```

```
[Match]
Name=wifi-br

[Network]
LinkLocalAddressing=no
IPv6AcceptRA=no
```

The bridge also contains a gateway interface:

```
[NetDev]
Name=wifi-gw
Kind=veth

[Peer]
Name=wifi-gw-br
```

```
[Match]
Name=wifi-gw-br

[Network]
Bridge=wifi-br
LinkLocalAddressing=no
IPv6AcceptRA=no
```

```
[Match]
Name=wifi-gw

[Network]
Address=1.2.3.1/24
LinkLocalAddressing=no
IPv6AcceptRA=no
DHCPServer=yes

[DHCPServer]
DNS=1.2.3.1
NTP=1.2.3.1
SendOption=15:string:example.home.arpa
```

**Additional program output to the terminal or log subsystem illustrating the issue**

Once `systemd-networkd` crashes the following stack trace applies:

```
Core was generated by `/usr/lib/systemd/systemd-networkd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f122d9dfb30 in main_arena () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f122d9dfb30 in main_arena () from /usr/lib/libc.so.6
#1  0x00007f122dba2c78 in base_bucket_hash (h=h@entry=0x7f122d9dfb50 <main_arena+336>, p=p@entry=0x55c9d5366648) at ../systemd-stable/src/basic/hashmap.c:341
#2  0x00007f122dba574f in _hashmap_get (h=0x7f122d9dfb50 <main_arena+336>, key=key@entry=0x55c9d5366648) at ../systemd-stable/src/basic/hashmap.c:1350
#3  0x000055c9d3845493 in hashmap_get (key=0x55c9d5366648, h=<optimized out>) at ../systemd-stable/src/basic/hashmap.h:176
#4  dhcp_lease_free (lease=lease@entry=0x55c9d5366640) at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:34
#5  0x000055c9d3846e56 in dhcp_server_cleanup_expired_leases (server=0x55c9d532a310) at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:874
#6  dhcp_server_handle_message (length=<optimized out>, message=0x55c9d53429b0, server=0x55c9d532a310) at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:921
#7  server_receive_message (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>)
at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:1245
#8  0x00007f122dc70d9e in source_dispatch (s=0x55c9d535f420) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3598
#9  0x00007f122dc70f8e in sd_event_dispatch (e=0x55c9d52fd1c0) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:4183
#10 0x00007f122dc727a9 in sd_event_run (e=0x55c9d52fd1c0, timeout=18446744073709551615) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:4244
#11 0x00007f122dc72980 in sd_event_loop (e=0x55c9d52fd1c0) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:4265
#12 0x000055c9d379eb2b in run (argv=<optimized out>, argc=<optimized out>) at ../systemd-stable/src/network/networkd.c:114
#13 main (argc=<optimized out>, argv=<optimized out>) at ../systemd-stable/src/network/networkd.c:121
```

Sometimes it is different:

```
free(): double free detected in tcache 2
```

```
Core was generated by `/usr/lib/systemd/systemd-networkd'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0cb42a3d22 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f0cb42a3d22 in raise () from /usr/lib/libc.so.6
#1  0x00007f0cb428d862 in abort () from /usr/lib/libc.so.6
#2  0x00007f0cb42e5d28 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f0cb42ed92a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f0cb42ef408 in _int_free () from /usr/lib/libc.so.6
#5  0x00007f0cb42f29e8 in free () from /usr/lib/libc.so.6
#6  0x000055e7575104bb in dhcp_lease_free (lease=lease@entry=0x55e757850280) at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:47
#7  0x000055e757511e56 in dhcp_server_cleanup_expired_leases (server=0x55e75783b700) at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:874
#8  dhcp_server_handle_message (length=<optimized out>, message=0x55e757866f80, server=0x55e75783b700) at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:921
#9  server_receive_message (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>)
at ../systemd-stable/src/libsystemd-network/sd-dhcp-server.c:1245
#10 0x00007f0cb46b8d9e in source_dispatch (s=0x55e757836200) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3598
#11 0x00007f0cb46b8f8e in sd_event_dispatch (e=0x55e75780e1c0) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:4183
#12 0x00007f0cb46ba7a9 in sd_event_run (e=0x55e75780e1c0, timeout=18446744073709551615) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:4244
#13 0x00007f0cb46ba980 in sd_event_loop (e=0x55e75780e1c0) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:4265
#14 0x000055e757469b2b in run (argv=<optimized out>, argc=<optimized out>) at ../systemd-stable/src/network/networkd.c:114
#15 main (argc=<optimized out>, argv=<optimized out>) at ../systemd-stable/src/network/networkd.c:121
```

The issue doesn't happen in 100% of cases, but pretty often (_≈75% maybe_).

**Comment by pfactum** [comment]
Probably introduced by d635a7f9e4c58c5578f4fe2989bb799325067232 /cc @tohojo

**Comment by tohojo** [comment]
Yeah, I've been seeing these as well, but haven't had time to investigate properly :(

**Comment by yuwata** [comment]
Could you test #22254?

**Comment by pfactum** [comment]
@yuwata no crash observed after a dozen of reconnections.

**Comment by yuwata** [comment]
Thank you for testing! But I pushed one more commit to the PR. If possible, please test again.

**Comment by pfactum** [comment]
@yuwata no crash after applying both commits as well. thank you!

**Comment by yuwata** [comment]
Thank you testing the PR so quickly!!
