### ISSUE TITLE
machined: AddressSanitizer: stack-buffer-overflow on address 0x7fffd8fd26d0 at pc 0x7f3f70d7aa5f bp 0x7fffd8fd1900 sp 0x7fffd8fd18f8

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#22555]
**systemd version the issue has been seen with**
```
$ git describe
v250-981-gd8cf1af526
```

It was discovered in https://github.com/systemd/systemd/pull/22547 thanks to @mrc0mmand and dfuzzer.

```sh
busctl call org.freedesktop.machine1 /org/freedesktop/machine1/image/_2ehost org.freedesktop.machine1.Image MarkReadOnly "b" true
```

```sh
Got message type=method_call sender=:1.490 destination=org.freedesktop.machine1 path=/org/freedesktop/machine1/image/_2ehost interface=org.freedesktop.machine1.Image member=MarkReadOnly cookie=2 reply_coo
kie=0 signature=b error-name=n/a error-message=n/a
=================================================================
==408284==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffd8fd26d0 at pc 0x7f3f70d7aa5f bp 0x7fffd8fd1900 sp 0x7fffd8fd18f8
WRITE of size 4 at 0x7fffd8fd26d0 thread T0
    #0 0x7f3f70d7aa5e in sd_bus_message_read_basic ../src/libsystemd/sd-bus/bus-message.c:3543
    #1 0x7f3f70d86c36 in sd_bus_message_readv ../src/libsystemd/sd-bus/bus-message.c:4478
    #2 0x7f3f70d8803e in sd_bus_message_read ../src/libsystemd/sd-bus/bus-message.c:4610
    #3 0x432801 in bus_image_method_mark_read_only ../src/machine/image-dbus.c:235
    #4 0x7f3f70d9ca72 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:413
    #5 0x7f3f70da620e in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1322
    #6 0x7f3f70da7b58 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1452
    #7 0x7f3f70e0675d in process_message ../src/libsystemd/sd-bus/sd-bus.c:2963
    #8 0x7f3f70e06c77 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3005
    #9 0x7f3f70e09ad8 in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3225
    #10 0x7f3f70e09c72 in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3252
    #11 0x7f3f70e0d373 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3603
    #12 0x7f3f70fc887f in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3598
    #13 0x7f3f70fd1099 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4183
    #14 0x7f3f70fd220e in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4244
    #15 0x7f3f7082eff5 in bus_event_loop_with_idle ../src/shared/bus-util.c:122
    #16 0x40b5a4 in manager_run ../src/machine/machined.c:312
    #17 0x40bc23 in run ../src/machine/machined.c:357
    #18 0x40be3a in main ../src/machine/machined.c:364
    #19 0x7f3f6f2d655f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #20 0x7f3f6f2d660b in __libc_start_main_alias_1 (/lib64/libc.so.6+0x2d60b)
    #21 0x407104 in _start (/home/vagrant/systemd/build/systemd-machined+0x407104)

Address 0x7fffd8fd26d0 is located in stack of thread T0 at offset 48 in frame
    #0 0x432644 in bus_image_method_mark_read_only ../src/machine/image-dbus.c:226

  This frame has 2 object(s):
    [48, 49) 'read_only' (line 230) <== Memory access at offset 48 partially overflows this variable
    [64, 120) 'details' (line 239)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow ../src/libsystemd/sd-bus/bus-message.c:3543 in sd_bus_message_read_basic
Shadow bytes around the buggy address:
  0x10007b1f2480: f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3
  0x10007b1f2490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007b1f24a0: f1 f1 f1 f1 00 00 00 f3 f3 f3 f3 f3 00 00 00 00
  0x10007b1f24b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007b1f24c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007b1f24d0: 00 00 00 00 f1 f1 f1 f1 f1 f1[01]f2 00 00 00 00
  0x10007b1f24e0: 00 00 00 f3 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x10007b1f24f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x10007b1f2500: f1 f1 00 f2 f2 f2 00 00 00 f3 f3 f3 f3 f3 00 00
  0x10007b1f2510: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007b1f2520: 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 f2 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==408284==ABORTING
```

**Comment by evverx** [comment]
It was introduced in 8dd3f6a3fdf1e3f45 so it hasn't even been released yet. I'm not sure why `int` was replaced with `bool` there though
