### ISSUE TITLE
test-oomd-util seems to fail under Valgrind

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#22577]
```
==225787== Memcheck, a memory error detector
==225787== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==225787== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==225787== Command: /home/vagrant/systemd/build/test-oomd-util
==225787==
test-oomd-util: not root, skipping tests.
==225787== Conditional jump or move depends on uninitialised value(s)
==225787==    at 0x405FEF: oomd_pressure_above (oomd-util.c:86)
==225787==    by 0x404579: test_oomd_pressure_above (test-oomd-util.c:307)
==225787==    by 0x405622: main (test-oomd-util.c:455)
==225787==
```
As far as I can tell Valgrind is right because `mem_pressure_limit_hit_start` isn't initialized at that point.

I ran it as root in https://github.com/evverx/systemd/pull/91:
```
2022-02-21T02:21:47.0702015Z stderr:
2022-02-21T02:21:47.0702301Z ==24458== Memcheck, a memory error detector
2022-02-21T02:21:47.0702776Z ==24458== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
2022-02-21T02:21:47.0703549Z ==24458== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
2022-02-21T02:21:47.0704104Z ==24458== Command: /home/runner/work/systemd/systemd/build/test-oomd-util
2022-02-21T02:21:47.0704398Z ==24458== 
2022-02-21T02:21:47.0704890Z Error converting 'MemTotal:       32495256 kB trailing' from /oomdgetsysctxtestjrNS1A to uint64_t: Invalid argument
2022-02-21T02:21:47.0705333Z ==24458== Conditional jump or move depends on uninitialised value(s)
2022-02-21T02:21:47.0705791Z ==24458==    at 0x10E909: oomd_pressure_above (oomd-util.c:86)
2022-02-21T02:21:47.0706234Z ==24458==    by 0x10CC9A: test_oomd_pressure_above (test-oomd-util.c:307)
2022-02-21T02:21:47.0706670Z ==24458==    by 0x10DECE: main (test-oomd-util.c:455)
2022-02-21T02:21:47.0706992Z ==24458==  Uninitialised value was created by a stack allocation
2022-02-21T02:21:47.0707462Z ==24458==    at 0x10C98D: test_oomd_pressure_above (test-oomd-util.c:283)
2022-02-21T02:21:47.0707750Z ==24458== 
2022-02-21T02:21:47.0708028Z ==24458== Conditional jump or move depends on uninitialised value(s)
2022-02-21T02:21:47.0708486Z ==24458==    at 0x10E93E: oomd_pressure_above (oomd-util.c:90)
2022-02-21T02:21:47.0708924Z ==24458==    by 0x10CC9A: test_oomd_pressure_above (test-oomd-util.c:307)
2022-02-21T02:21:47.0709347Z ==24458==    by 0x10DECE: main (test-oomd-util.c:455)
2022-02-21T02:21:47.0709821Z ==24458==  Uninitialised value was created by a stack allocation
2022-02-21T02:21:47.0710253Z ==24458==    at 0x10C98D: test_oomd_pressure_above (test-oomd-util.c:283)
2022-02-21T02:21:47.0710517Z ==24458== 
2022-02-21T02:21:47.0710934Z ==24458== Conditional jump or move depends on uninitialised value(s)
2022-02-21T02:21:47.0711665Z ==24458==    at 0x10CD71: test_oomd_pressure_above (test-oomd-util.c:310)
2022-02-21T02:21:47.0712233Z ==24458==    by 0x10DECE: main (test-oomd-util.c:455)
2022-02-21T02:21:47.0712560Z ==24458==  Uninitialised value was created by a stack allocation
2022-02-21T02:21:47.0713005Z ==24458==    at 0x10C98D: test_oomd_pressure_above (test-oomd-util.c:283)
2022-02-21T02:21:47.0713264Z ==24458== 
2022-02-21T02:21:47.0713730Z ==24458== Conditional jump or move depends on uninitialised value(s)
2022-02-21T02:21:47.0714224Z ==24458==    at 0x10E909: oomd_pressure_above (oomd-util.c:86)
2022-02-21T02:21:47.0714831Z ==24458==    by 0x10CF8B: test_oomd_pressure_above (test-oomd-util.c:322)
2022-02-21T02:21:47.0715241Z ==24458==    by 0x10DECE: main (test-oomd-util.c:455)
2022-02-21T02:21:47.0715734Z ==24458==  Uninitialised value was created by a stack allocation
2022-02-21T02:21:47.0716196Z ==24458==    at 0x10C98D: test_oomd_pressure_above (test-oomd-util.c:283)
2022-02-21T02:21:47.0716612Z ==24458== 
2022-02-21T02:21:47.0717073Z ==24458== Conditional jump or move depends on uninitialised value(s)
2022-02-21T02:21:47.0717508Z ==24458==    at 0x10E93E: oomd_pressure_above (oomd-util.c:90)
2022-02-21T02:21:47.0718111Z ==24458==    by 0x10CF8B: test_oomd_pressure_above (test-oomd-util.c:322)
2022-02-21T02:21:47.0718560Z ==24458==    by 0x10DECE: main (test-oomd-util.c:455)
2022-02-21T02:21:47.0718885Z ==24458==  Uninitialised value was created by a stack allocation
2022-02-21T02:21:47.0719347Z ==24458==    at 0x10C98D: test_oomd_pressure_above (test-oomd-util.c:283)
2022-02-21T02:21:47.0719611Z ==24458== 
2022-02-21T02:21:47.0719903Z ==24458== Conditional jump or move depends on uninitialised value(s)
2022-02-21T02:21:47.0720377Z ==24458==    at 0x10D09E: test_oomd_pressure_above (test-oomd-util.c:326)
2022-02-21T02:21:47.0720778Z ==24458==    by 0x10DECE: main (test-oomd-util.c:455)
2022-02-21T02:21:47.0721109Z ==24458==  Uninitialised value was created by a stack allocation
2022-02-21T02:21:47.0721555Z ==24458==    at 0x10C98D: test_oomd_pressure_above (test-oomd-util.c:283)
```

**Comment by evverx** [comment]
FWIW It was confirmed by MSan
```
11:11:58 PATH=/src/systemd/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/out MALLOC_PERTURB_=1 SYSTEMD_LANGUAGE_FALLBACK_MAP=/src/systemd/src/locale/language-fallback-map /src/system
d/build/test-oomd-util
----------------------------------- output -----------------------------------
stderr:
Error converting 'MemTotal:       32495256 kB trailing' from /oomdgetsysctxtestxZolCi to uint64_t: Invalid argument
==14073==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4a61d9 in oomd_pressure_above /src/systemd/build/../src/oom/oomd-util.c:86:29
    #1 0x49f581 in test_oomd_pressure_above /src/systemd/build/../src/oom/test-oomd-util.c:307:9
    #2 0x49f581 in main /src/systemd/build/../src/oom/test-oomd-util.c:455:9
    #3 0x7fba43a350b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #4 0x41d5cd in _start (/src/systemd/build/test-oomd-util+0x41d5cd)

  Uninitialized value was created by an allocation of 'ctx.i9' in the stack frame of function 'main'
    #0 0x49e1c0 in main /src/systemd/build/../src/oom/test-oomd-util.c:448

SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/systemd/build/../src/oom/oomd-util.c:86:29 in oomd_pressure_above
Exiting
```
