### ISSUE TITLE
Semaphore CI: autopkgtest-reboot no longer works, affects 2 test cases

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#22991]
https://the-real-systemd.semaphoreci.com/jobs/8ffc9a76-b341-4483-8280-c71f60df208d

```
autopkgtest [00:52:41]: test boot-smoke: [-----------------------
reboot #0
bash: line 1:  5686 Killed                  /tmp/autopkgtest-lxc.mw9ay7yf/downtmp/build.5j7/src/debian/tests/boot-smoke 2> >(tee -a /tmp/autopkgtest-lxc.mw9ay7yf/downtmp/boot-smoke-stderr >&2) > >(tee -a /tmp/autopkgtest-lxc.mw9ay7yf/downtmp/boot-smoke-stdout)
autopkgtest [00:52:41]: test process requested reboot with marker 1
autopkgtest-virt-lxc [00:53:47]: ERROR: WARNING: Cannot kill timed out process ['sudo', 'lxc-attach', '--name', 'autopkgtest-lxc-fkvllx', '--', 'sh', '-ec', 'if [ -d /run/systemd/system ]; then systemctl start network-online.target; else while ps -ef | grep -q "/etc/init\\.d/rc"; do sleep 1; done; fi']: [Errno 1] Operation not permitted
Unexpected error:
Traceback (most recent call last):
  File "/tmp/autopkgtest/lib/VirtSubproc.py", line 768, in mainloop
    command()
  File "/tmp/autopkgtest/lib/VirtSubproc.py", line 697, in command
    r = f(c, ce)
  File "/tmp/autopkgtest/lib/VirtSubproc.py", line 392, in cmd_reboot
    caller.hook_wait_reboot(**wait_reboot_args)
  File "/tmp/autopkgtest/virt/autopkgtest-virt-lxc", line 312, in hook_wait_reboot
    wait_booted(lxc_container_name)
  File "/tmp/autopkgtest/virt/autopkgtest-virt-lxc", line 131, in wait_booted
    VirtSubproc.check_exec(sudoify(['lxc-attach', '--name', lxc_name, '--', 'sh', '-ec', r'if [ -d /run/systemd/system ]; then systemctl start network-online.target; else while ps -ef | grep -q "/etc/init\.d/rc"; do sleep 1; done; fi']), timeout=60)
  File "/tmp/autopkgtest/lib/VirtSubproc.py", line 183, in check_exec
    (status, out, err) = execute_timeout(None, timeout, real_argv,
  File "/tmp/autopkgtest/lib/VirtSubproc.py", line 145, in execute_timeout
    (out, err) = sp.communicate(instr)
  File "/usr/lib/python3.8/subprocess.py", line 1018, in communicate
    stderr = self.stderr.read()
  File "/tmp/autopkgtest/lib/VirtSubproc.py", line 65, in alarm_handler
    raise Timeout()
VirtSubproc.Timeout
autopkgtest [00:53:49]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
+ '[' 16 -eq 2 ']'
```

The affected tests are for now disabled to get the rest working again: https://github.com/systemd/systemd/pull/22985

Filing this so that I don't forget to try and fix that too

**Comment by bluca** [comment]
Looks like the problem is that those tests install Network-Manager, and then running `systemctl start network-online.target` gets stuck (`systemd-networkd-wait-online.service` never completes). Probably they conflict fighting for the interfaces. No idea why this started just now.

I'll disable networkd in those tests that enable Network-Manager, it seems to fix the problem when debugging manually.
