### ISSUE TITLE
systemd-analyze security segfaults on some units

### ISSUE THREAD

**Issue by vedranmiletic** [systemd/systemd#23224]
**systemd version the issue has been seen with**

```
systemd 250 (250.5-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**

Arch Linux

**Linux kernel version used** (`uname -a`)

`Linux ares.miletic.net 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**

x86-64

**Expected behaviour you didn't see**

No segfault

**Unexpected behaviour you saw**

Segfault

**Steps to reproduce the problem**

```
$ systemd-analyze security systemd-udevd.service
$ systemd-analyze security systemd-networkd.service
$ systemd-analyze security systemd-journald.service
$ systemd-analyze security systemd-logind.service
```

**Additional program output to the terminal or log subsystem illustrating the issue**

Output from each of these commands:

```
Segmentacijska greška (**krah**: stanje (dump) memorije je zapisano!)
```

dmesg:

```
[89654.403252] systemd-analyze[274922]: segfault at 1 ip 00007fb2c66604bd sp 00007fff50764478 error 4 in libc.so.6[7fb2c6509000+176000]
[89654.403283] Code: f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f8 48 89 fa c5 f9 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 33 01 00 00 <c5> fd 74 0f c5 fd d7 c1 85 c0 74 57 f3 0f bc c0 c5 f8 77 c3 66 66
```

**Comment by mrc0mmand** [comment]
Also reproducible with the latest main:

```gdb
 bt
#0  0x00007ff008cfa4bd in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00007ff008fbf99c in string_hash_func (p=0x1 <error: Cannot access memory at address 0x1>, state=0x7ffea5e370c0) at ../src/basic/hash-funcs.c:9
#2  0x00007ff008fc0205 in base_bucket_hash (h=0x563ef7d1a170, p=0x1) at ../src/basic/hashmap.c:342
#3  0x00007ff008fc29ac in _hashmap_contains (h=0x563ef7d1a170, key=0x1) at ../src/basic/hashmap.c:1385
#4  0x0000563ef7ce6a64 in set_contains (s=0x563ef7d1a170, key=0x1) at ../src/basic/set.h:43
#5  0x0000563ef7ce82f8 in assess_system_call_architectures (a=0x563ef7d09ac0 <security_assessor_table+6240>, info=0x563ef7d142a0, data=0x563ef7d142a0, ret_badness=0x7ffea5e372a0, ret_description=0x7ffea5e37298)
    at ../src/analyze/analyze-security.c:554
#6  0x0000563ef7ce99bd in assess (info=0x563ef7d142a0, overview_table=0x0, flags=0, threshold=100, policy=0x0, pager_flags=0, json_format_flags=JSON_FORMAT_OFF) at ../src/analyze/analyze-security.c:1781
#7  0x0000563ef7cec5ed in analyze_security_one (bus=0x563ef7d13630, name=0x563ef7d134b0 "systemd-udevd.service", overview_table=0x0, flags=0, threshold=100, policy=0x0, pager_flags=0, json_format_flags=JSON_FORMAT_OFF)
    at ../src/analyze/analyze-security.c:2441
#8  0x0000563ef7ceebc6 in analyze_security (bus=0x563ef7d13630, units=0x7ffea5e37968, policy=0x0, scope=LOOKUP_SCOPE_SYSTEM, check_man=true, run_generators=false, offline=false, threshold=100, root=0x0, profile=0x0, 
    json_format_flags=JSON_FORMAT_OFF, pager_flags=0, flags=0) at ../src/analyze/analyze-security.c:2873
#9  0x0000563ef7cef1f9 in verb_security (argc=2, argv=0x7ffea5e37960, userdata=0x0) at ../src/analyze/analyze-security.c:2924
#10 0x00007ff008f84249 in dispatch_verb (argc=3, argv=0x7ffea5e37960, verbs=0x563ef7d0c2a0 <verbs>, userdata=0x0) at ../src/shared/verbs.c:103
#11 0x0000563ef7cf89e9 in run (argc=3, argv=0x7ffea5e37958) at ../src/analyze/analyze.c:607
#12 0x0000563ef7cf8aaa in main (argc=3, argv=0x7ffea5e37958) at ../src/analyze/analyze.c:610
```

```gdb
#0  0x00007ff008cfa4bd in __strlen_avx2 () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ff008fbf99c in string_hash_func (p=0x1 <error: Cannot access memory at address 0x1>, state=0x7ffea5e370c0) at ../src/basic/hash-funcs.c:9
No locals.
#2  0x00007ff008fc0205 in base_bucket_hash (h=0x563ef7d1a170, p=0x1) at ../src/basic/hashmap.c:342
        state = {v0 = 7225593592205315004, v1 = 2237416931861620398, v2 = 8885739601544256680, v3 = 1082817585044417712, padding = 0, inlen = 0}
        hash = 140731681567168
#3  0x00007ff008fc29ac in _hashmap_contains (h=0x563ef7d1a170, key=0x1) at ../src/basic/hashmap.c:1385
        hash = 22078
#4  0x0000563ef7ce6a64 in set_contains (s=0x563ef7d1a170, key=0x1) at ../src/basic/set.h:43
No locals.
#5  0x0000563ef7ce82f8 in assess_system_call_architectures (a=0x563ef7d09ac0 <security_assessor_table+6240>, info=0x563ef7d142a0, data=0x563ef7d142a0, ret_badness=0x7ffea5e372a0, ret_description=0x7ffea5e37298) at ../src/analyze/analyze-security.c:554
        native = 0
        d = 0x563ef7d09ac0 <security_assessor_table+6240> "\004\356\317\367>V"
        b = 40
        __PRETTY_FUNCTION__ = "assess_system_call_architectures"
        __func__ = "assess_system_call_architectures"
#6  0x0000563ef7ce99bd in assess (info=0x563ef7d142a0, overview_table=0x0, flags=0, threshold=100, policy=0x0, pager_flags=0, json_format_flags=JSON_FORMAT_OFF) at ../src/analyze/analyze-security.c:1781
        a = 0x563ef7d09ac0 <security_assessor_table+6240>
        data = 0x563ef7d142a0
        weight = 1000
        range = 10
        d = 0x0
        badness = 0
        badness_table = {{exposure = 100, name = 0x563ef7d00255 "DANGEROUS", color = 0x563ef7cfb534 "\033[0;1;31m", smiley = SPECIAL_GLYPH_DEPRESSED_SMILEY}, {exposure = 90, name = 0x563ef7d0025f "UNSAFE", color = 0x563ef7cfb534 "\033[0;1;31m", smiley = SPECIAL_GLYPH_UNHAPPY_SMILEY}, {exposure = 75, name = 0x563ef7d00266 "EXPOSED", color = 0x563ef7d0026e "\033[0;1;38;5;185m", smiley = SPECIAL_GLYPH_SLIGHTLY_UNHAPPY_SMILEY}, {exposure = 50, name = 0x563ef7d0027e "MEDIUM", 
            color = 0x0, smiley = SPECIAL_GLYPH_NEUTRAL_SMILEY}, {exposure = 10, name = 0x563ef7d00285 "OK", color = 0x563ef7cfb53e "\033[0;1;32m", smiley = SPECIAL_GLYPH_SLIGHTLY_HAPPY_SMILEY}, {exposure = 1, name = 0x563ef7d00288 "SAFE", color = 0x563ef7cfb53e "\033[0;1;32m", smiley = SPECIAL_GLYPH_HAPPY_SMILEY}, {exposure = 0, name = 0x563ef7d0028d "PERFECT", color = 0x563ef7cfb53e "\033[0;1;32m", smiley = _SPECIAL_GLYPH_FIRST_EMOJI}}
        badness_sum = 31360
        weight_sum = 40535
        exposure = 94828445671616
        details_table = 0x563ef7d149a0
        i = 65
        r = 0
        __func__ = "assess"
        __PRETTY_FUNCTION__ = "assess"
#7  0x0000563ef7cec5ed in analyze_security_one (bus=0x563ef7d13630, name=0x563ef7d134b0 "systemd-udevd.service", overview_table=0x0, flags=0, threshold=100, policy=0x0, pager_flags=0, json_format_flags=JSON_FORMAT_OFF) at ../src/analyze/analyze-security.c:2441
        info = 0x563ef7d142a0
        __func__ = "analyze_security_one"
        r = 0
        __PRETTY_FUNCTION__ = "analyze_security_one"
#8  0x0000563ef7ceebc6 in analyze_security (bus=0x563ef7d13630, units=0x7ffea5e37968, policy=0x0, scope=LOOKUP_SCOPE_SYSTEM, check_man=true, run_generators=false, offline=false, threshold=100, root=0x0, profile=0x0, json_format_flags=JSON_FORMAT_OFF, pager_flags=0, flags=0) at ../src/analyze/analyze-security.c:2873
        mangled = 0x563ef7d134b0 "systemd-udevd.service"
        instance = 0x0
        name = 0x563ef7d134b0 "systemd-udevd.service"
        i = 0x7ffea5e37968
        __unique_prefix_i24 = 0x7ffea5e37968
        overview_table = 0x0
        ret = 0
        r = 0
        __PRETTY_FUNCTION__ = "analyze_security"
        __func__ = "analyze_security"
#9  0x0000563ef7cef1f9 in verb_security (argc=2, argv=0x7ffea5e37960, userdata=0x0) at ../src/analyze/analyze-security.c:2924
        bus = 0x563ef7d13630
        policy = 0x0
        r = -2
        line = 0
        column = 150485495
        __PRETTY_FUNCTION__ = "verb_security"
        __func__ = "verb_security"
#10 0x00007ff008f84249 in dispatch_verb (argc=3, argv=0x7ffea5e37960, verbs=0x563ef7d0c2a0 <verbs>, userdata=0x0) at ../src/shared/verbs.c:103
        verb = 0x563ef7d0c5e0 <verbs+832>
        name = 0x7ffea5e38ec5 "security"
        left = 2
        __PRETTY_FUNCTION__ = "dispatch_verb"
        __func__ = "dispatch_verb"
#11 0x0000563ef7cf89e9 in run (argc=3, argv=0x7ffea5e37958) at ../src/analyze/analyze.c:607
        loop_device = 0x0
        decrypted_image = 0x0
        unlink_dir = 0x0
        verbs = {{verb = 0x563ef7d02b9a "help", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cf6c25 <help>}, {verb = 0x563ef7d02dbe "time", min_args = 4294967295, max_args = 1, flags = VERB_DEFAULT, dispatch = 0x563ef7cf0630 <verb_time>}, {verb = 0x563ef7d03540 "blame", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x563ef7cdc015 <verb_blame>}, {verb = 0x563ef7d03546 "critical-chain", min_args = 4294967295, max_args = 4294967295, 
            flags = 0, dispatch = 0x563ef7cdfa77 <verb_critical_chain>}, {verb = 0x563ef7d03555 "plot", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x563ef7ce4c3a <verb_plot>}, {verb = 0x563ef7d02dc3 "dot", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x563ef7ce06aa <verb_dot>}, {verb = 0x563ef7d0355a "log-level", min_args = 4294967295, max_args = 2, flags = 0, dispatch = 0x563ef7ce3c4f <verb_log_control>}, {
            verb = 0x563ef7d03564 "log-target", min_args = 4294967295, max_args = 2, flags = 0, dispatch = 0x563ef7ce3c4f <verb_log_control>}, {verb = 0x563ef7d0356f "set-log-level", min_args = 2, max_args = 2, flags = 0, dispatch = 0x563ef7ce3c4f <verb_log_control>}, {verb = 0x563ef7d0357d "get-log-level", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x563ef7ce3c4f <verb_log_control>}, {verb = 0x563ef7d0358b "set-log-target", min_args = 2, max_args = 2, 
            flags = 0, dispatch = 0x563ef7ce3c4f <verb_log_control>}, {verb = 0x563ef7d0359a "get-log-target", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x563ef7ce3c4f <verb_log_control>}, {verb = 0x563ef7d035a9 "service-watchdogs", min_args = 4294967295, max_args = 2, flags = 0, dispatch = 0x563ef7cef287 <verb_service_watchdogs>}, {verb = 0x563ef7d035bb "dump", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x563ef7ce10aa <verb_dump>}, {
            verb = 0x563ef7d02e25 "cat-config", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cdda0b <verb_cat_config>}, {verb = 0x563ef7d035c0 "unit-files", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cf3482 <verb_unit_files>}, {verb = 0x563ef7d02dc7 "unit-paths", min_args = 1, max_args = 1, flags = 0, dispatch = 0x563ef7cf3823 <verb_unit_paths>}, {verb = 0x563ef7d035cb "exit-status", min_args = 4294967295, 
            max_args = 4294967295, flags = 0, dispatch = 0x563ef7ce1454 <verb_exit_status>}, {verb = 0x563ef7d035d7 "syscall-filter", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x563ef7ceff10 <verb_syscall_filters>}, {verb = 0x563ef7d035e6 "capability", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cdd501 <verb_capabilities>}, {verb = 0x563ef7d035f1 "filesystems", min_args = 4294967295, max_args = 4294967295, 
            flags = 0, dispatch = 0x563ef7ce2228 <verb_filesystems>}, {verb = 0x563ef7d02eaa "condition", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cde901 <verb_condition>}, {verb = 0x563ef7d02dd2 "verify", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cf3e6a <verb_verify>}, {verb = 0x563ef7d035fd "calendar", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cdd3e1 <verb_calendar>}, {
            verb = 0x563ef7d03606 "timestamp", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cf31f5 <verb_timestamp>}, {verb = 0x563ef7d03610 "timespan", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x563ef7cf2343 <verb_timespan>}, {verb = 0x563ef7d02cda "security", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x563ef7ceede2 <verb_security>}, {verb = 0x563ef7d02d24 "inspect-elf", min_args = 2, max_args = 4294967295, 
            flags = 0, dispatch = 0x563ef7ce3bdd <verb_elf_inspection>}, {verb = 0x0, min_args = 0, max_args = 0, flags = 0, dispatch = 0x0}}
        r = 1
        __PRETTY_FUNCTION__ = "run"
        __func__ = "run"
#12 0x0000563ef7cf8aaa in main (argc=3, argv=0x7ffea5e37958) at ../src/analyze/analyze.c:610
        r = 32752
        __PRETTY_FUNCTION__ = "main"
```

**Comment by mrc0mmand** [comment]
The culprit seems to be 1449b0f8a96b272547e405913b37715cbbe4768a, and I'm not sure about the claim from the commit message:

>Enum values are stored in the set, not strings

since it seems that the strings are indeed stored there:

```
(gdb) list
546	        assert(ret_badness);
547	        assert(ret_description);
548	
549	        assert_se(seccomp_arch_from_string("native", &native) >= 0);
550	
551	        if (set_isempty(info->system_call_architectures)) {
552	                b = 10;
553	                d = strdup("Service may execute system calls with all ABIs");
554	        } else if (set_contains(info->system_call_architectures, UINT32_TO_PTR(native)) &&
555	                   set_size(info->system_call_architectures) == 1) {
(gdb) call (char*)set_first(info->system_call_architectures)
$13 = 0x555555598100 "native"
```

**Comment by bluca** [comment]
> The culprit seems to be [1449b0f](https://github.com/systemd/systemd/commit/1449b0f8a96b272547e405913b37715cbbe4768a), and I'm not sure about the claim from the commit message:
> 
> > Enum values are stored in the set, not strings
> 
> since it seems that the strings are indeed stored there:
> 
> ```gdb
> (gdb) list
> 546	        assert(ret_badness);
> 547	        assert(ret_description);
> 548	
> 549	        assert_se(seccomp_arch_from_string("native", &native) >= 0);
> 550	
> 551	        if (set_isempty(info->system_call_architectures)) {
> 552	                b = 10;
> 553	                d = strdup("Service may execute system calls with all ABIs");
> 554	        } else if (set_contains(info->system_call_architectures, UINT32_TO_PTR(native)) &&
> 555	                   set_size(info->system_call_architectures) == 1) {
> (gdb) call (char*)set_first(info->system_call_architectures)
> $13 = 0x555555598100 "native"
> ```

They are stored as pointers in the context, but as string when they come through D-Bus - ops!
