### ISSUE TITLE
I/O errors on journal files can make apps using sd-journal SIGBUS (such as qtcreator)

### ISSUE THREAD

**Issue by Serafean** [systemd/systemd#2323]
Qtcreator 3.6.0 crashes on startup with a Bus Error. (systemd 228) 
Backtrace goes into journald : 

```
#0  __memcmp_ssse3 () at ../sysdeps/x86_64/multiarch/memcmp-ssse3.S:1688
#1  0x00007f108364dafc in journal_file_verify_header (f=0x236ba80) at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/journal-file.c:266
#2  journal_file_open (fname=fname@entry=0x7ffd1b554ed0 "/var/log/journal/834e0379a11194bc40bbbb5355991e92/system@00051edc2b292afb-55cfc70e3b2ec97e.journal~", flags=flags@entry=0, mode=mode@entry=0, 
    compress=compress@entry=false, seal=seal@entry=false, metrics=metrics@entry=0x0, mmap_cache=0x2356900, template=template@entry=0x0, ret=ret@entry=0x7ffd1b554ea8)
    at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/journal-file.c:2719
#3  0x00007f108364531f in add_any_file (j=j@entry=0x2356810, path=path@entry=0x7ffd1b554ed0 "/var/log/journal/834e0379a11194bc40bbbb5355991e92/system@00051edc2b292afb-55cfc70e3b2ec97e.journal~")
    at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/sd-journal.c:1253
#4  0x00007f10836455fe in add_file (j=j@entry=0x2356810, prefix=0x2356bb0 "/var/log/journal/834e0379a11194bc40bbbb5355991e92", filename=filename@entry=0x236176b "system@00051edc2b292afb-55cfc70e3b2ec97e.journal~")
    at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/sd-journal.c:1295
#5  0x00007f1083645854 in add_directory (j=j@entry=0x2356810, prefix=<optimized out>, dirname=dirname@entry=0x2358cd3 "834e0379a11194bc40bbbb5355991e92")
    at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/sd-journal.c:1424
#6  0x00007f1083645f56 in add_root_directory (j=j@entry=0x2356810, p=<optimized out>, p@entry=0x7f108366f3f1 <search_paths+17> "/var/log/journal", missing_ok=missing_ok@entry=true)
    at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/sd-journal.c:1515
#7  0x00007f108364600d in add_search_paths (j=0x2356810) at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/sd-journal.c:1564
#8  0x00007f1083648054 in sd_journal_open (ret=0x2355f18, flags=<optimized out>) at /var/tmp/portage/sys-apps/systemd-228-r1/work/systemd-228/src/journal/sd-journal.c:1656
#9  0x00007f10683db163 in ProjectExplorer::Internal::JournaldWatcherPrivate::setup (this=0x2355f10) at journaldwatcher.cpp:82
#10 0x00007f10683dc3a2 in ProjectExplorer::JournaldWatcher::JournaldWatcher (this=0x2355d00) at journaldwatcher.cpp:202
#11 0x00007f10682550cb in ProjectExplorer::ProjectExplorerPlugin::initialize (this=0x2016270, arguments=..., error=<optimized out>) at projectexplorer.cpp:454
#12 0x00007f10877cb7c6 in ExtensionSystem::Internal::PluginSpecPrivate::initializePlugin (this=0x1fedcc0) at pluginspec.cpp:983
#13 0x00007f10877c37ec in ExtensionSystem::Internal::PluginManagerPrivate::loadPlugin (this=this@entry=0x1fb8960, spec=0x1feba40, destState=destState@entry=ExtensionSystem::PluginSpec::Initialized) at pluginmanager.cpp:1391
#14 0x00007f10877c7650 in ExtensionSystem::Internal::PluginManagerPrivate::loadPlugins (this=0x1fb8960) at pluginmanager.cpp:1223
#15 0x00007f10877c77ec in ExtensionSystem::PluginManager::loadPlugins () at pluginmanager.cpp:368
#16 0x00000000004094c8 in main (argc=1, argv=<optimized out>) at main.cpp:516
```

Granted ,the file in question is indeed not readable (cat and cp fail with an Input/Output error)...

**Comment by poettering** [comment]
Not sure what we can do about this... I/O errors on memory mapped files are reported as SIGBUS. If you have a file with I/O errors you'll hence get SIGBUS. It's possible to catch that (and in fact journalctl does), but it's really nasty to do that from libraries (since SIGBUS handlers can only have one owner), and hence we currently don't.

I am really not sure what we could do to fix this. We should probably document the situation in the sd-journal docs, and suggest some mode of operation, but I figure there's no way how we can silently deal with this without requiring explicit app support for catching SIGBUS.
