### ISSUE TITLE
There is a memory leak in systemd

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#23250]
It was found by `dfuzzer` thanks to a new feature @mrc0mmand is working on
```sh
==1==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5521 byte(s) in 10 object(s) allocated from:
    #0 0x7faf155638f7 in strdup (/lib64/libasan.so.6+0x598f7)
    #1 0x7faf1313d06f in strv_extend ../src/basic/strv.c:538
    #2 0x7faf12e4947b in normalize_linked_files ../src/shared/install.c:2839
    #3 0x7faf12e49bc5 in unit_file_reenable ../src/shared/install.c:2872
    #4 0x7faf148e7292 in method_enable_unit_files_generic ../src/core/dbus-manager.c:2332
    #5 0x7faf148e74e6 in method_reenable_unit_files ../src/core/dbus-manager.c:2348
    #6 0x7faf1323c235 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #7 0x7faf13245a38 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1310
    #8 0x7faf132470fa in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1430
    #9 0x7faf132a6585 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2962
    #10 0x7faf132a6a9f in process_running ../src/libsystemd/sd-bus/sd-bus.c:3004
    #11 0x7faf132a9900 in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3224
    #12 0x7faf132a9a9a in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3251
    #13 0x7faf132ad19b in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3602
    #14 0x7faf13465b8c in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3591
    #15 0x7faf1346e3a6 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4175
    #16 0x7faf1346f50a in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4236
    #17 0x7faf14a85dcd in manager_loop ../src/core/manager.c:3068
    #18 0x41c1e3 in invoke_main_loop ../src/core/main.c:1894
    #19 0x42484a in main ../src/core/main.c:2957
    #20 0x7faf1175555f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

Direct leak of 963 byte(s) in 10 object(s) allocated from:
    #0 0x7faf155b891f in __interceptor_malloc (/lib64/libasan.so.6+0xae91f)
    #1 0x7faf1555ee04 in __interceptor_strndup.part.0 (/lib64/libasan.so.6+0x54e04)
    #2 0x7faf130e7119 in path_extract_filename ../src/basic/path-util.c:1053
    #3 0x7faf12e48d16 in normalize_linked_files ../src/shared/install.c:2810
    #4 0x7faf12e49bc5 in unit_file_reenable ../src/shared/install.c:2872
    #5 0x7faf148e7292 in method_enable_unit_files_generic ../src/core/dbus-manager.c:2332
    #6 0x7faf148e74e6 in method_reenable_unit_files ../src/core/dbus-manager.c:2348
    #7 0x7faf1323c235 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #8 0x7faf13245a38 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1310
    #9 0x7faf132470fa in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1430
    #10 0x7faf132a6585 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2962
    #11 0x7faf132a6a9f in process_running ../src/libsystemd/sd-bus/sd-bus.c:3004
    #12 0x7faf132a9900 in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3224
    #13 0x7faf132a9a9a in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3251
    #14 0x7faf132ad19b in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3602
    #15 0x7faf13465b8c in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3591
    #16 0x7faf1346e3a6 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4175
    #17 0x7faf1346f50a in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4236
    #18 0x7faf14a85dcd in manager_loop ../src/core/manager.c:3068
    #19 0x41c1e3 in invoke_main_loop ../src/core/main.c:1894
    #20 0x42484a in main ../src/core/main.c:2957
    #21 0x7faf1175555f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
```

**Comment by yuwata** [comment]
Fix is waiting in #23251.
