### ISSUE TITLE
resolved crashes in specifier_dnssd_hostname

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#23381]
**systemd version the issue has been seen with**
5a6bcbb00134e4f810

```sh
busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager \
    RegisterService sssqqqaa{say} 'H' '%H' _http._udp 65535 65535 65535 0
```
```sh
Assertion 's->manager' failed at src/resolve/resolved-dnssd.c:143, function int specifier_dnssd_hostname(char, const void *, const char *, const void *, char **)(). Aborting.
```
```sh
#0  0x00007ffff532459c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff52d7d86 in raise () from /lib64/libc.so.6
#2  0x00007ffff52aa833 in abort () from /lib64/libc.so.6
#3  0x00007ffff684b811 in log_assert_failed (text=0x7329c0 <str> "s->manager", file=0x731efa "src/resolve/resolved-dnssd.c", line=143,
    func=0x733040 <__PRETTY_FUNCTION__.specifier_dnssd_hostname> "int specifier_dnssd_hostname(char, const void *, const char *, const void *, char **)") at ../src/basic/log.c:870
#4  0x0000000000585b32 in specifier_dnssd_hostname (specifier=72 'H', data=0x0, root=0x0, userdata=0x60700002dc80, ret=0x7fffffffb500) at ../src/resolve/resolved-dnssd.c:143
#5  0x00007ffff661eb06 in specifier_printf (text=0x6020000f0c10 "%H", max_length=63, table=0x732280 <dnssd_render_instance_name.specifier_table>, root=0x0, userdata=0x60700002dc80, ret=0x7fffffffb8e0)
    at ../src/shared/specifier.c:70
#6  0x00000000005850bf in dnssd_render_instance_name (s=0x60700002dc80, ret_name=0x7fffffffbb20) at ../src/resolve/resolved-dnssd.c:173
#7  0x000000000041b2e9 in bus_method_register_service (message=0x618000049880, userdata=0x618000000080, error=0x7fffffffc1e0) at ../src/resolve/resolved-bus.c:1956
#8  0x00007ffff6ac3c43 in method_callbacks_run (bus=0x61c00000b880, m=0x618000049880, c=0x60400007d6d0, require_fallback=false, found_object=0x7fffffffcba0) at ../src/libsystemd/sd-bus/bus-objects.c:406
#9  0x00007ffff6aa332b in object_find_and_run (bus=0x61c00000b880, m=0x618000049880, p=0x611000027658 "/org/freedesktop/resolve1", require_fallback=false, found_object=0x7fffffffcba0)
    at ../src/libsystemd/sd-bus/bus-objects.c:1310
#10 0x00007ffff6aa1944 in bus_process_object (bus=0x61c00000b880, m=0x618000049880) at ../src/libsystemd/sd-bus/bus-objects.c:1430
#11 0x00007ffff6b56cd0 in process_message (bus=0x61c00000b880, m=0x618000049880) at ../src/libsystemd/sd-bus/sd-bus.c:2962
#12 0x00007ffff6b52466 in process_running (bus=0x61c00000b880, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3004
#13 0x00007ffff6b38617 in bus_process_internal (bus=0x61c00000b880, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3224
#14 0x00007ffff6b3089d in sd_bus_process (bus=0x61c00000b880, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3251
#15 0x00007ffff6b3c07b in io_callback (s=0x612000082540, fd=15, revents=1, userdata=0x61c00000b880) at ../src/libsystemd/sd-bus/sd-bus.c:3602
#16 0x00007ffff6e0094e in source_dispatch (s=0x612000082540) at ../src/libsystemd/sd-event/sd-event.c:3591
#17 0x00007ffff6dfea95 in sd_event_dispatch (e=0x617000091f00) at ../src/libsystemd/sd-event/sd-event.c:4175
#18 0x00007ffff6e0433b in sd_event_run (e=0x617000091f00, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4236
#19 0x00007ffff6e052ba in sd_event_loop (e=0x617000091f00) at ../src/libsystemd/sd-event/sd-event.c:4257
#20 0x0000000000642b61 in run (argc=1, argv=0x7fffffffe5d8) at ../src/resolve/resolved.c:92
#21 0x0000000000640c5b in main (argc=1, argv=0x7fffffffe5d8) at ../src/resolve/resolved.c:99
```

**Comment by yuwata** [comment]
Fix is waiting in #23382.
