### ISSUE TITLE
portabled crashes in extract_image_and_extensions

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#23433]
**systemd version the issue has been seen with**
e4885958dc36080aa

```sh
busctl call org.freedesktop.portable1 /org/freedesktop/portable1 org.freedesktop.portable1.Manager GetImageMetadata sas '/' 0
```
or
```sh
busctl call org.freedesktop.portable1 /org/freedesktop/portable1 org.freedesktop.portable1.Manager GetImageMetadataWithExtensions sasast '/' 0 0 0
```

```sh
Assertion 'matches' failed at src/portable/portable.c:533, function extract_image_and_extensions(). Aborting.

Program received signal SIGABRT, Aborted.
0x00007ffff4b6659c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.8-1.fc35.x86_64 glibc-2.34-32.fc35.x86_64 iptables-legacy-libs-1.8.7-13.fc35.x86_64 kmod-libs-29-4.fc35.x86_64 libacl-2.3.1-2.fc35.x86_64 libasan-11.3.1-2.fc35.x86_64 libattr-2.5.1-3.fc35.x86_64 libblkid-2.37.4-1.fc35.x86_64 libcap-2.48-3.fc35.x86_64 libcap-ng-0.8.2-8.fc35.x86_64 libeconf-0.4.0-2.fc35.x86_64 libffi-3.1-29.fc35.x86_64 libgcc-11.3.1-2.fc35.x86_64 libgcrypt-1.9.4-1.fc35.x86_64 libgpg-error-1.43-1.fc35.x86_64 libibverbs-39.0-1.fc35.x86_64 libmount-2.37.4-1.fc35.x86_64 libnl3-3.5.0-8.fc35.x86_64 libseccomp-2.5.3-1.fc35.x86_64 libselinux-3.3-1.fc35.x86_64 libstdc++-11.3.1-2.fc35.x86_64 libubsan-11.3.1-2.fc35.x86_64 libxcrypt-4.4.28-1.fc35.x86_64 libzstd-1.5.2-1.fc35.x86_64 openssl-libs-1.1.1n-1.fc35.x86_64 pcre2-10.39-1.fc35.x86_64 xz-libs-5.2.5-9.fc35.x86_64 zlib-1.2.11-30.fc35.x86_64
(gdb) bt
#0  0x00007ffff4b6659c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff4b19d86 in raise () from /lib64/libc.so.6
#2  0x00007ffff4aec833 in abort () from /lib64/libc.so.6
#3  0x00007ffff64847c9 in log_assert_failed (text=0x432c80 "matches", file=0x4316e3 "src/portable/portable.c", line=533, func=0x435ac0 <__PRETTY_FUNCTION__.38> "extract_image_and_extensions")
    at ../src/basic/log.c:870
#4  0x000000000040eaa1 in extract_image_and_extensions (name_or_path=0x6020000006b0 "/", matches=0x0, extension_image_paths=0x0, validate_sysext=false, ret_image=0x7fffffffd570,
    ret_extension_images=0x7fffffffd4f0, ret_extension_releases=0x7fffffffd510, ret_os_release=0x7fffffffd4d0, ret_unit_files=0x7fffffffd530, ret_valid_prefixes=0x0, error=0x7fffffffd9d0)
    at ../src/portable/portable.c:533
#5  0x0000000000410b5a in portable_extract (name_or_path=0x6020000006b0 "/", matches=0x0, extension_image_paths=0x0, ret_os_release=0x7fffffffd6b0, ret_extension_releases=0x7fffffffd690,
    ret_unit_files=0x7fffffffd710, ret_valid_prefixes=0x0, error=0x7fffffffd9d0) at ../src/portable/portable.c:692
#6  0x00000000004251a1 in bus_image_common_get_metadata (m=0x6060000000e0, message=0x618000003080, name_or_path=0x6110000013d4 "/", image=0x60d000000450, error=0x7fffffffd9d0)
    at ../src/portable/portabled-image-bus.c:160
#7  0x0000000000421f3a in redirect_method_to_image (m=0x6060000000e0, message=0x618000003080, error=0x7fffffffd9d0, method=0x424ad0 <bus_image_common_get_metadata>) at ../src/portable/portabled-bus.c:217
#8  0x0000000000421ff1 in method_get_image_metadata (message=0x618000003080, userdata=0x6060000000e0, error=0x7fffffffd9d0) at ../src/portable/portabled-bus.c:225
#9  0x00007ffff660bb41 in method_callbacks_run (bus=0x61c000000080, m=0x618000003080, c=0x6040000002d0, require_fallback=false, found_object=0x7fffffffdc40) at ../src/libsystemd/sd-bus/bus-objects.c:406
#10 0x00007ffff6615341 in object_find_and_run (bus=0x61c000000080, m=0x618000003080, p=0x611000001318 "/org/freedesktop/portable1", require_fallback=false, found_object=0x7fffffffdc40)
    at ../src/libsystemd/sd-bus/bus-objects.c:1310
#11 0x00007ffff6616a03 in bus_process_object (bus=0x61c000000080, m=0x618000003080) at ../src/libsystemd/sd-bus/bus-objects.c:1430
#12 0x00007ffff6675e2a in process_message (bus=0x61c000000080, m=0x618000003080) at ../src/libsystemd/sd-bus/sd-bus.c:2962
#13 0x00007ffff6676341 in process_running (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3004
#14 0x00007ffff66791a2 in bus_process_internal (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3224
#15 0x00007ffff667933c in sd_bus_process (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3251
#16 0x00007ffff667ca3d in io_callback (s=0x612000000640, fd=5, revents=1, userdata=0x61c000000080) at ../src/libsystemd/sd-bus/sd-bus.c:3602
#17 0x00007ffff68348a9 in source_dispatch (s=0x612000000640) at ../src/libsystemd/sd-event/sd-event.c:3591
#18 0x00007ffff683d0c0 in sd_event_dispatch (e=0x617000000080) at ../src/libsystemd/sd-event/sd-event.c:4175
#19 0x00007ffff683e224 in sd_event_run (e=0x617000000080, timeout=30000000) at ../src/libsystemd/sd-event/sd-event.c:4236
#20 0x00007ffff608480c in bus_event_loop_with_idle (e=0x617000000080, bus=0x61c000000080, name=0x441f00 "org.freedesktop.portable1", timeout=30000000, check_idle=0x42fc42 <check_idle>,
    userdata=0x6060000000e0) at ../src/shared/bus-util.c:122
#21 0x000000000042fde4 in manager_run (m=0x6060000000e0) at ../src/portable/portabled.c:119
#22 0x000000000043055a in run (argc=1, argv=0x7fffffffe608) at ../src/portable/portabled.c:161
#23 0x0000000000430771 in main (argc=1, argv=0x7fffffffe608) at ../src/portable/portabled.c:168
```
It was found with https://github.com/dbus-fuzzer/dfuzzer thanks to yet another feature @mrc0mmand added recently: https://github.com/dbus-fuzzer/dfuzzer/pull/95

**Comment by evverx** [comment]
For the sake of completeness here is another variation on the same issue:
```sh
busctl call org.freedesktop.portable1 /org/freedesktop/portable1 org.freedesktop.portable1.Manager AttachImage sassbs '/' 0 '' 0 ''
```
```sh
Assertion 'matches' failed at src/portable/portable.c:533, function extract_image_and_extensions(). Aborting.

Program received signal SIGABRT, Aborted.
0x00007ffff4b6659c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.8-1.fc35.x86_64 glibc-2.34-32.fc35.x86_64 iptables-legacy-libs-1.8.7-13.fc35.x86_64 kmod-libs-29-4.fc35.x86_64 libacl-2.3.1-2.fc35.x86_64 libasan-11.3.1-2.fc35.x86_64 libattr-2.5.1-3.fc35.x86_64 libblkid-2.37.4-1.fc35.x86_64 libcap-2.48-3.fc35.x86_64 libcap-ng-0.8.2-8.fc35.x86_64 libeconf-0.4.0-2.fc35.x86_64 libffi-3.1-29.fc35.x86_64 libgcc-11.3.1-2.fc35.x86_64 libgcrypt-1.9.4-1.fc35.x86_64 libgpg-error-1.43-1.fc35.x86_64 libibverbs-39.0-1.fc35.x86_64 libmount-2.37.4-1.fc35.x86_64 libnl3-3.5.0-8.fc35.x86_64 libseccomp-2.5.3-1.fc35.x86_64 libselinux-3.3-1.fc35.x86_64 libstdc++-11.3.1-2.fc35.x86_64 libubsan-11.3.1-2.fc35.x86_64 libxcrypt-4.4.28-1.fc35.x86_64 libzstd-1.5.2-1.fc35.x86_64 openssl-libs-1.1.1n-1.fc35.x86_64 pcre2-10.39-1.fc35.x86_64 xz-libs-5.2.5-9.fc35.x86_64 zlib-1.2.11-30.fc35.x86_64
(gdb) bt
#0  0x00007ffff4b6659c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff4b19d86 in raise () from /lib64/libc.so.6
#2  0x00007ffff4aec833 in abort () from /lib64/libc.so.6
#3  0x00007ffff64847c9 in log_assert_failed (text=0x432c80 "matches", file=0x4316e3 "src/portable/portable.c", line=533, func=0x435ac0 <__PRETTY_FUNCTION__.38> "extract_image_and_extensions")
    at ../src/basic/log.c:870
#4  0x000000000040eaa1 in extract_image_and_extensions (name_or_path=0x602000000450 "/", matches=0x0, extension_image_paths=0x0, validate_sysext=true, ret_image=0x7fffffffd450,
    ret_extension_images=0x7fffffffd3f0, ret_extension_releases=0x0, ret_os_release=0x0, ret_unit_files=0x7fffffffd410, ret_valid_prefixes=0x7fffffffd430, error=0x7fffffffd9d0)
    at ../src/portable/portable.c:533
#5  0x0000000000418783 in portable_attach (bus=0x61c000000080, name_or_path=0x602000000450 "/", matches=0x0, profile=0x611000000ed8 "", extension_image_paths=0x0, flags=0, changes=0x7fffffffd730,
    n_changes=0x7fffffffd790, error=0x7fffffffd9d0) at ../src/portable/portable.c:1292
#6  0x0000000000426a2b in bus_image_common_attach (m=0x6060000000e0, message=0x618000001880, name_or_path=0x611000000ecc "/", image=0x60d0000002b0, error=0x7fffffffd9d0)
    at ../src/portable/portabled-image-bus.c:380
#7  0x0000000000421f3a in redirect_method_to_image (m=0x6060000000e0, message=0x618000001880, error=0x7fffffffd9d0, method=0x426156 <bus_image_common_attach>) at ../src/portable/portabled-bus.c:217
#8  0x0000000000422442 in method_attach_image (message=0x618000001880, userdata=0x6060000000e0, error=0x7fffffffd9d0) at ../src/portable/portabled-bus.c:272
#9  0x00007ffff660bb41 in method_callbacks_run (bus=0x61c000000080, m=0x618000001880, c=0x6040000003d0, require_fallback=false, found_object=0x7fffffffdc40) at ../src/libsystemd/sd-bus/bus-objects.c:406
#10 0x00007ffff6615341 in object_find_and_run (bus=0x61c000000080, m=0x618000001880, p=0x611000000e18 "/org/freedesktop/portable1", require_fallback=false, found_object=0x7fffffffdc40)
    at ../src/libsystemd/sd-bus/bus-objects.c:1310
#11 0x00007ffff6616a03 in bus_process_object (bus=0x61c000000080, m=0x618000001880) at ../src/libsystemd/sd-bus/bus-objects.c:1430
#12 0x00007ffff6675e2a in process_message (bus=0x61c000000080, m=0x618000001880) at ../src/libsystemd/sd-bus/sd-bus.c:2962
#13 0x00007ffff6676341 in process_running (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3004
#14 0x00007ffff66791a2 in bus_process_internal (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3224
#15 0x00007ffff667933c in sd_bus_process (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3251
#16 0x00007ffff667ca3d in io_callback (s=0x612000000640, fd=5, revents=1, userdata=0x61c000000080) at ../src/libsystemd/sd-bus/sd-bus.c:3602
#17 0x00007ffff68348a9 in source_dispatch (s=0x612000000640) at ../src/libsystemd/sd-event/sd-event.c:3591
#18 0x00007ffff683d0c0 in sd_event_dispatch (e=0x617000000080) at ../src/libsystemd/sd-event/sd-event.c:4175
#19 0x00007ffff683e224 in sd_event_run (e=0x617000000080, timeout=30000000) at ../src/libsystemd/sd-event/sd-event.c:4236
#20 0x00007ffff608480c in bus_event_loop_with_idle (e=0x617000000080, bus=0x61c000000080, name=0x441f00 "org.freedesktop.portable1", timeout=30000000, check_idle=0x42fc42 <check_idle>,
    userdata=0x6060000000e0) at ../src/shared/bus-util.c:122
#21 0x000000000042fde4 in manager_run (m=0x6060000000e0) at ../src/portable/portabled.c:119
#22 0x000000000043055a in run (argc=1, argv=0x7fffffffe608) at ../src/portable/portabled.c:161
#23 0x0000000000430771 in main (argc=1, argv=0x7fffffffe608) at ../src/portable/portabled.c:168
```
