### ISSUE TITLE
portabled crashes in extension_release_validate when directories are passed to portablectl

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#23448]
**systemd version the issue has been seen with**
https://github.com/systemd/systemd/commit/1ab191b3a95cd511e630e24555ed50205d1ed220

```sh
touch t2/usr/lib/extension-release.d/extension-release.t2
portablectl attach /root/t1 --extension=/root/t2
(Matching unit files with prefix 't1'.)
AttachImageWithExtensions failed: Remote peer disconnected
```
```sh
Assertion '!isempty(host_os_release_id)' failed at src/shared/extension-release.c:21, function extension_release_validate(). Aborting.

Program received signal SIGABRT, Aborted.
0x00007ffff4b9c59c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.8-1.fc35.x86_64 glibc-2.34-32.fc35.x86_64 iptables-legacy-libs-1.8.7-13.fc35.x86_64 kmod-libs-29-4.fc35.x86_64 libacl-2.3.1-2.fc35.x86_64 libasan-11.3.1-2.fc35.x86_64 libattr-2.5.1-3.fc35.x86_64 libblkid-2.37.4-1.fc35.x86_64 libcap-2.48-3.fc35.x86_64 libcap-ng-0.8.2-8.fc35.x86_64 libeconf-0.4.0-2.fc35.x86_64 libffi-3.1-29.fc35.x86_64 libgcc-11.3.1-2.fc35.x86_64 libgcrypt-1.9.4-1.fc35.x86_64 libgpg-error-1.43-1.fc35.x86_64 libibverbs-39.0-1.fc35.x86_64 libmount-2.37.4-1.fc35.x86_64 libnl3-3.5.0-8.fc35.x86_64 libselinux-3.3-1.fc35.x86_64 libstdc++-11.3.1-2.fc35.x86_64 libubsan-11.3.1-2.fc35.x86_64 libxcrypt-4.4.28-1.fc35.x86_64 libzstd-1.5.2-1.fc35.x86_64 openssl-libs-1.1.1n-1.fc35.x86_64 pcre2-10.39-1.fc35.x86_64 xz-libs-5.2.5-9.fc35.x86_64 zlib-1.2.11-30.fc35.x86_64
(gdb) bt
#0  0x00007ffff4b9c59c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff4b4fd86 in raise () from /lib64/libc.so.6
#2  0x00007ffff4b22833 in abort () from /lib64/libc.so.6
#3  0x00007ffff649c67a in log_assert_failed (text=0x7ffff68f4ae0 "!isempty(host_os_release_id)", file=0x7ffff68f4a43 "src/shared/extension-release.c", line=21,
    func=0x7ffff68f5180 <__PRETTY_FUNCTION__.1> "extension_release_validate") at ../src/basic/log.c:870
#4  0x00007ffff61b5c1a in extension_release_validate (name=0x603000000880 "/home/vagrant/systemd/t2", host_os_release_id=0x0, host_os_release_version_id=0x0, host_os_release_sysext_level=0x0,
    host_sysext_scope=0x432e00 "portable", extension_release=0x0) at ../src/shared/extension-release.c:21
#5  0x000000000040f9a1 in extract_image_and_extensions (name_or_path=0x6030000007c0 "/home/vagrant/systemd/t1", matches=0x602000000450, extension_image_paths=0x6020000003f0, validate_sysext=true,
    ret_image=0x7fffffffd460, ret_extension_images=0x7fffffffd400, ret_extension_releases=0x0, ret_os_release=0x0, ret_unit_files=0x7fffffffd420, ret_valid_prefixes=0x7fffffffd440, error=0x7fffffffd9e0)
    at ../src/portable/portable.c:626
#6  0x0000000000418752 in portable_attach (bus=0x61c000000080, name_or_path=0x6030000007c0 "/home/vagrant/systemd/t1", matches=0x602000000450, profile=0x61300000016c "default",
    extension_image_paths=0x6020000003f0, flags=0, changes=0x7fffffffd740, n_changes=0x7fffffffd7a0, error=0x7fffffffd9e0) at ../src/portable/portable.c:1291
#7  0x00000000004269fa in bus_image_common_attach (m=0x6060000000e0, message=0x618000001880, name_or_path=0x61300000011c "/home/vagrant/systemd/t1", image=0x60d0000002b0, error=0x7fffffffd9e0)
    at ../src/portable/portabled-image-bus.c:380
#8  0x0000000000421f09 in redirect_method_to_image (m=0x6060000000e0, message=0x618000001880, error=0x7fffffffd9e0, method=0x426125 <bus_image_common_attach>) at ../src/portable/portabled-bus.c:217
#9  0x0000000000422411 in method_attach_image (message=0x618000001880, userdata=0x6060000000e0, error=0x7fffffffd9e0) at ../src/portable/portabled-bus.c:272
#10 0x00007ffff66239f2 in method_callbacks_run (bus=0x61c000000080, m=0x618000001880, c=0x604000000410, require_fallback=false, found_object=0x7fffffffdc50) at ../src/libsystemd/sd-bus/bus-objects.c:406
#11 0x00007ffff662d1f2 in object_find_and_run (bus=0x61c000000080, m=0x618000001880, p=0x613000000058 "/org/freedesktop/portable1", require_fallback=false, found_object=0x7fffffffdc50)
    at ../src/libsystemd/sd-bus/bus-objects.c:1310
#12 0x00007ffff662e8b4 in bus_process_object (bus=0x61c000000080, m=0x618000001880) at ../src/libsystemd/sd-bus/bus-objects.c:1430
#13 0x00007ffff668dcdb in process_message (bus=0x61c000000080, m=0x618000001880) at ../src/libsystemd/sd-bus/sd-bus.c:2962
#14 0x00007ffff668e1f2 in process_running (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3004
#15 0x00007ffff6691053 in bus_process_internal (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3224
#16 0x00007ffff66911ed in sd_bus_process (bus=0x61c000000080, ret=0x0) at ../src/libsystemd/sd-bus/sd-bus.c:3251
#17 0x00007ffff66948ee in io_callback (s=0x612000000640, fd=5, revents=1, userdata=0x61c000000080) at ../src/libsystemd/sd-bus/sd-bus.c:3602
#18 0x00007ffff684c75a in source_dispatch (s=0x612000000640) at ../src/libsystemd/sd-event/sd-event.c:3591
#19 0x00007ffff6854f71 in sd_event_dispatch (e=0x617000000080) at ../src/libsystemd/sd-event/sd-event.c:4175
#20 0x00007ffff68560d5 in sd_event_run (e=0x617000000080, timeout=30000000) at ../src/libsystemd/sd-event/sd-event.c:4236
#21 0x00007ffff60aa5e5 in bus_event_loop_with_idle (e=0x617000000080, bus=0x61c000000080, name=0x441ec0 "org.freedesktop.portable1", timeout=30000000, check_idle=0x42fc11 <check_idle>,
    userdata=0x6060000000e0) at ../src/shared/bus-util.c:122
#22 0x000000000042fdb3 in manager_run (m=0x6060000000e0) at ../src/portable/portabled.c:119
#23 0x0000000000430529 in run (argc=1, argv=0x7fffffffe618) at ../src/portable/portabled.c:161
#24 0x0000000000430740 in main (argc=1, argv=0x7fffffffe618) at ../src/portable/portabled.c:168
```

**Comment by yuwata** [comment]
Fix is waiting in #23449.
