### ISSUE TITLE
AddressSanitizer: stack-buffer-overflow READ of size 64 in dns_service_split

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#23705]
**systemd version the issue has been seen with**
 3e808e0769799b3efd

```diff
diff --git a/src/test/test-dns-domain.c b/src/test/test-dns-domain.c
index 3a26ecaa70..023ec05a6b 100644
--- a/src/test/test-dns-domain.c
+++ b/src/test/test-dns-domain.c
@@ -540,6 +540,7 @@ TEST(dns_service_split) {
         test_dns_service_split_one("_foo._bar", NULL, "_foo._bar", ".", 0);
         test_dns_service_split_one("_meh._foo._bar", "_meh", "_foo._bar", ".", 0);
         test_dns_service_split_one("Wuff\\032Wuff._foo._bar.waldo.com", "Wuff Wuff", "_foo._bar", "waldo.com", 0);
+        dns_service_split("_Q._Q-------------------------------------------------------------", NULL, NULL, NULL);
 }
```
```sh
./build/test-dns-domain
...
=================================================================
==2382554==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff0259e5df at pc 0x000000467009 bp 0x7fff0259e310 sp 0x7fff0259dac0
READ of size 64 at 0x7fff0259e5df thread T0
    #0 0x467008 in __interceptor_strlen.part.0 asan_interceptors.cpp.o
    #1 0x7ff59bd6b994 in strjoin_real /home/vagrant/systemd/build/../src/basic/string-util.c:97:21
    #2 0x7ff59b9a38fb in dns_service_split /home/vagrant/systemd/build/../src/shared/dns-domain.c:1088:32
    #3 0x50072f in test_dns_service_split /home/vagrant/systemd/build/../src/test/test-dns-domain.c:543:9
    #4 0x501f6d in run_test_table /home/vagrant/systemd/build/../src/shared/tests.h:106:33
    #5 0x501f6d in main /home/vagrant/systemd/build/../src/test/test-dns-domain.c:753:1
    #6 0x7ff59ac4843f in __libc_start_call_main (/lib64/libc.so.6+0x4043f)
    #7 0x7ff59ac484ef in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x404ef)
    #8 0x41d5b4 in _start (/home/vagrant/systemd/build/test-dns-domain+0x41d5b4)

Address 0x7fff0259e5df is located in stack of thread T0 at offset 255 in frame
    #0 0x7ff59b9a323f in dns_service_split /home/vagrant/systemd/build/../src/shared/dns-domain.c:1025

  This frame has 5 object(s):
    [32, 40) 'domain' (line 1026)
    [64, 72) 'p' (line 1027)
    [96, 159) 'a' (line 1028)
    [192, 255) 'b' (line 1028)
    [288, 351) 'c' (line 1028) <== Memory access at offset 255 partially underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow asan_interceptors.cpp.o in __interceptor_strlen.part.0
Shadow bytes around the buggy address:
  0x1000604abc60: 00 00 00 00 f1 f1 f1 f1 00 00 00 f3 f3 f3 f3 f3
  0x1000604abc70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000604abc80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000604abc90: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x1000604abca0: 00 f2 f2 f2 00 f2 f2 f2 00 00 00 00 00 00 00 07
=>0x1000604abcb0: f2 f2 f2 f2 00 00 00 00 00 00 00[07]f2 f2 f2 f2
  0x1000604abcc0: 00 00 00 00 00 00 00 07 f3 f3 f3 f3 00 00 00 00
  0x1000604abcd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000604abce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000604abcf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000604abd00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2382554==ABORTING
```

**Comment by yuwata** [comment]
Fix is waiting in #23707.
