### ISSUE TITLE
systemd segfaults and dumped  core

### ISSUE THREAD

**Issue by prownd** [systemd/systemd#23885]
### systemd version the issue has been seen with

243

### Linux kernel version used

4.19.90

### CPU architectures issue was seen on

aarch64

### Expected behaviour you didn't see

systemd no segfaults 

### Unexpected behaviour you saw

systemd crash , generate segfaults 

### Steps to reproduce the problem

don't know how to reproduce the issue

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
(gdb) bt
#0  0x0000fffe8d3669e8 in kill () from /lib64/libc.so.6
#1  0x0000aaaab0a3ff18 in crash (sig=11) at ../src/core/main.c:212
#2  <signal handler called>
#3  0x0000aaaab0aba750 in device_following_set.lto_priv.165 (u=0xaaaacff18eb0, _set=0xffffca6f3c00) at ../src/core/device.c:787
#4  0x0000aaaab0ad3d24 in transaction_add_job_and_dependencies (tr=tr@entry=0xaaaacfdd2b60, type=type@entry=JOB_START, 
    unit=0xaaaacff18eb0, by=by@entry=0xaaaacfff02d0, matters=matters@entry=true, conflicts=conflicts@entry=false, 
    ignore_requirements=ignore_requirements@entry=false, ignore_order=ignore_order@entry=false, e=<optimized out>, 
    e@entry=0xffffca6f4150) at ../src/core/transaction.c:983
#5  0x0000aaaab0ad4068 in transaction_add_job_and_dependencies (tr=tr@entry=0xaaaacfdd2b60, type=type@entry=JOB_START, 
    unit=<optimized out>, by=by@entry=0xaaaacffbf2a0, matters=matters@entry=true, conflicts=conflicts@entry=false, 
    ignore_requirements=ignore_requirements@entry=false, ignore_order=ignore_order@entry=false, e=<optimized out>, 
    e@entry=0xffffca6f4150) at ../src/core/transaction.c:1011
#6  0x0000aaaab0ad3ffc in transaction_add_job_and_dependencies (tr=tr@entry=0xaaaacfdd2b60, type=type@entry=JOB_START, 
    unit=<optimized out>, by=by@entry=0xaaaacff84920, matters=matters@entry=false, conflicts=conflicts@entry=false, 
    ignore_requirements=ignore_requirements@entry=false, ignore_order=ignore_order@entry=false, e=<optimized out>, 
    e@entry=0xffffca6f4150) at ../src/core/transaction.c:1001
#7  0x0000aaaab0ad40ec in transaction_add_job_and_dependencies (tr=tr@entry=0xaaaacfdd2b60, type=type@entry=JOB_START, 
    unit=<optimized out>, by=by@entry=0xaaaacff82910, matters=matters@entry=true, conflicts=conflicts@entry=false, 
    ignore_requirements=ignore_requirements@entry=false, ignore_order=ignore_order@entry=false, e=<optimized out>, 
    e@entry=0xffffca6f4150) at ../src/core/transaction.c:1021
#8  0x0000aaaab0ad3ffc in transaction_add_job_and_dependencies (tr=0xaaaacfdd2b60, type=JOB_START, unit=<optimized out>, 
    by=<optimized out>, matters=<optimized out>, conflicts=<optimized out>, ignore_requirements=<optimized out>, 
    ignore_order=<optimized out>, e=<optimized out>) at ../src/core/transaction.c:1001
#9  0x0000aaaab0a673e8 in manager_add_job (m=0xaaaacfdd1fd0, type=JOB_START, unit=0xaaaacfeeac30, mode=JOB_REPLACE, 
    affected_jobs=0x0, error=0xffffca6f4150, ret=0x0) at ../src/core/manager.c:1745
#10 0x0000aaaab0aa4410 in timer_enter_running (t=t@entry=0xaaaacfec6e80) at ../src/core/timer.c:574
#11 0x0000aaaab0aa4628 in timer_dispatch (s=<optimized out>, usec=<optimized out>, userdata=<optimized out>)
    at ../src/core/timer.c:737
#12 0x0000fffe8d1b194c in source_dispatch.lto_priv.83 (s=0xaaaacffd2bb0) at ../src/libsystemd/sd-event/sd-event.c:2836
#13 0x0000fffe8d15fa8c in sd_event_dispatch (e=e@entry=0xaaaacfdd2750) at ../src/libsystemd/sd-event/sd-event.c:3241
#14 0x0000fffe8d160ee8 in sd_event_run (e=0xaaaacfdd2750, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3299
#15 0x0000aaaab0a41a14 in manager_loop (m=0xaaaacfdd1fd0) at ../src/core/manager.c:2909
#16 invoke_main_loop (m=0xaaaacfdd1fd0, saved_rlimit_nofile=<optimized out>, saved_rlimit_memlock=<optimized out>, 
    ret_reexecute=<optimized out>, ret_retval=<optimized out>, ret_shutdown_verb=<optimized out>, ret_fds=<optimized out>, 
    ret_switch_root_dir=<optimized out>, ret_switch_root_init=<optimized out>, ret_error_message=<optimized out>)
    at ../src/core/main.c:1703
#17 0x0000aaaab0a2f95c in main (argc=5, argv=0xffffca6f48c8) at ../src/core/main.c:2647




(gdb) info  frame 3
Stack frame at 0xffffca6f3b30:
 pc = 0xaaaab0aba750 in device_following_set.lto_priv.165 (../src/core/device.c:787); saved pc = 0xaaaab0ad3d24
 called by frame at 0xffffca6f3c20, caller of frame at 0xffffca6f2890
 source language c.
 Arglist at 0xffffca6f3af0, args: u=0xaaaacff18eb0, _set=0xffffca6f3c00
 Locals at 0xffffca6f3af0, Previous frame's sp is 0xffffca6f3b30
 Saved registers:
  x19 at 0xffffca6f3b00, x20 at 0xffffca6f3b08, x21 at 0xffffca6f3b10, x22 at 0xffffca6f3b18, x23 at 0xffffca6f3b20,
  x29 at 0xffffca6f3af0, x30 at 0xffffca6f3af8
```

**Comment by yuwata** [comment]
Sorry, v243 is too old here. Please contact to your downstream or try to reproduce the issue with recent releases or the current git HEAD. Closing.
