### ISSUE TITLE
test-network: possible race in test_altname

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#24111]
### systemd version the issue has been seen with

latest main

### Unexpected behaviour you saw

See https://github.com/systemd/systemd-centos-ci/pull/512#issuecomment-1191591008 and https://jenkins-systemd.apps.ocp.ci.centos.org/job/ci-build/1114/artifact/artifacts_all/artifacts_xp9e0luj/testsuite-logs-upstream-ppc64le.RhY/systemd-networkd_sanitizers_FAIL.log

**Comment by mrc0mmand** [comment]
Latest occurrence (from a still existing job): https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-cron-build/682/artifact//systemd-centos-ci/artifacts_all/artifacts_efoka6_d/testsuite-logs-upstream-ppc64le.Yqq/systemd-networkd_sanitizers_FAIL.log

**Comment by mrc0mmand** [comment]
Today's job ended up with a couple more similarly-looking issues:

```
======================================================================
ERROR: test_altname (__main__.NetworkctlTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 927, in test_altname
    copy_network_unit('26-netdev-link-local-addressing-yes.network', '12-dummy.netdev', '12-dummy.link')
  File "test/test-network/systemd-networkd-tests.py", line 312, in copy_network_unit
    udev_reload()
  File "test/test-network/systemd-networkd-tests.py", line 280, in udev_reload
    check_output('udevadm control --reload')
  File "test/test-network/systemd-networkd-tests.py", line 98, in check_output
    return subprocess.run(command, check=True, universal_newlines=text, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs).stdout.rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload']' returned non-zero exit status 2.

======================================================================
ERROR: test_altname (__main__.NetworkctlTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 923, in tearDown
    tear_down_common()
  File "test/test-network/systemd-networkd-tests.py", line 632, in tear_down_common
    clear_network_units()
  File "test/test-network/systemd-networkd-tests.py", line 342, in clear_network_units
    udev_reload()
  File "test/test-network/systemd-networkd-tests.py", line 280, in udev_reload
    check_output('udevadm control --reload')
  File "test/test-network/systemd-networkd-tests.py", line 98, in check_output
    return subprocess.run(command, check=True, universal_newlines=text, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs).stdout.rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload']' returned non-zero exit status 2.

======================================================================
ERROR: test_mtu_link (__main__.NetworkdMTUTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 5266, in test_mtu_link
    copy_network_unit('12-dummy.netdev', '12-dummy-mtu.link', '12-dummy.network', copy_dropins=False)
  File "test/test-network/systemd-networkd-tests.py", line 312, in copy_network_unit
    udev_reload()
  File "test/test-network/systemd-networkd-tests.py", line 280, in udev_reload
    check_output('udevadm control --reload')
  File "test/test-network/systemd-networkd-tests.py", line 98, in check_output
    return subprocess.run(command, check=True, universal_newlines=text, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs).stdout.rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload']' returned non-zero exit status 2.

======================================================================
ERROR: test_mtu_link (__main__.NetworkdMTUTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 5223, in tearDown
    tear_down_common()
  File "test/test-network/systemd-networkd-tests.py", line 632, in tear_down_common
    clear_network_units()
  File "test/test-network/systemd-networkd-tests.py", line 342, in clear_network_units
    udev_reload()
  File "test/test-network/systemd-networkd-tests.py", line 280, in udev_reload
    check_output('udevadm control --reload')
  File "test/test-network/systemd-networkd-tests.py", line 98, in check_output
    return subprocess.run(command, check=True, universal_newlines=text, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs).stdout.rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload']' returned non-zero exit status 2.

======================================================================
ERROR: test_mtu_link_ipv6_mtu (__main__.NetworkdMTUTests)
set ipv6 mtu and set device mtu via link file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 5292, in test_mtu_link_ipv6_mtu
    copy_network_unit('12-dummy.netdev', '12-dummy-mtu.link', '12-dummy.network.d/ipv6-mtu-1550.conf')
  File "test/test-network/systemd-networkd-tests.py", line 312, in copy_network_unit
    udev_reload()
  File "test/test-network/systemd-networkd-tests.py", line 280, in udev_reload
    check_output('udevadm control --reload')
  File "test/test-network/systemd-networkd-tests.py", line 98, in check_output
    return subprocess.run(command, check=True, universal_newlines=text, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs).stdout.rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload']' returned non-zero exit status 2.

======================================================================
ERROR: test_mtu_link_ipv6_mtu (__main__.NetworkdMTUTests)
set ipv6 mtu and set device mtu via link file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 5223, in tearDown
    tear_down_common()
  File "test/test-network/systemd-networkd-tests.py", line 632, in tear_down_common
    clear_network_units()
  File "test/test-network/systemd-networkd-tests.py", line 342, in clear_network_units
    udev_reload()
  File "test/test-network/systemd-networkd-tests.py", line 280, in udev_reload
    check_output('udevadm control --reload')
  File "test/test-network/systemd-networkd-tests.py", line 98, in check_output
    return subprocess.run(command, check=True, universal_newlines=text, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs).stdout.rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload']' returned non-zero exit status 2.

======================================================================
ERROR: test_sriov_udev (__main__.NetworkdSRIOVTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 3896, in tearDown
    tear_down_common()
  File "test/test-network/systemd-networkd-tests.py", line 632, in tear_down_common
    clear_network_units()
  File "test/test-network/systemd-networkd-tests.py", line 342, in clear_network_units
    udev_reload()
  File "test/test-network/systemd-networkd-tests.py", line 280, in udev_reload
    check_output('udevadm control --reload')
  File "test/test-network/systemd-networkd-tests.py", line 98, in check_output
    return subprocess.run(command, check=True, universal_newlines=text, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs).stdout.rstrip()
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['udevadm', 'control', '--reload']' returned non-zero exit status 2.

----------------------------------------------------------------------
Ran 143 tests in 1952.632s

FAILED (errors=7, skipped=1, expected failures=10)
```

Full log: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-cron-build/683/artifact//systemd-centos-ci/artifacts_all/artifacts_u7nmezc6/testsuite-logs-upstream-ppc64le.HKc/systemd-networkd_sanitizers_FAIL.log

**Comment by mrc0mmand** [comment]
This seems to be resolved (or at least the latest run in https://github.com/systemd/systemd-centos-ci/pull/521 passed).
