### ISSUE TITLE
test-oomd-util fails on CentOS CI Arch Linux

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#24357]
### systemd version the issue has been seen with

main

### Used distribution

Arch Linux

### Linux kernel version used

5.18.16-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-oomd

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
11:58:06 [coredumpctl_collect] Trying to run gdb with 'file /systemd-meson-build/test-oomd-util\nthread apply all bt\nbt full\nquit' for '/usr/lib/systemd/tests/test-oomd-util'
11:58:06 GNU gdb (GDB) 12.1
11:58:06 Copyright (C) 2022 Free Software Foundation, Inc.
11:58:06 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
11:58:06 This is free software: you are free to change and redistribute it.
11:58:06 There is NO WARRANTY, to the extent permitted by law.
11:58:06 Type "show copying" and "show warranty" for details.
11:58:06 This GDB was configured as "x86_64-pc-linux-gnu".
11:58:06 Type "show configuration" for configuration details.
11:58:06 For bug reporting instructions, please see:
11:58:06 <https://www.gnu.org/software/gdb/bugs/>.
11:58:06 Find the GDB manual and other documentation resources online at:
11:58:06     <http://www.gnu.org/software/gdb/documentation/>.
11:58:06 
11:58:06 For help, type "help".
11:58:06 Type "apropos word" to search for commands related to "word"...
11:58:06 Reading symbols from /usr/lib/systemd/tests/test-oomd-util...
11:58:06 [New LWP 1038]
11:58:06 [Thread debugging using libthread_db enabled]
11:58:06 Using host libthread_db library "/usr/lib/libthread_db.so.1".
11:58:06 Core was generated by `/usr/lib/systemd/tests/test-oomd-util'.
11:58:06 Program terminated with signal SIGABRT, Aborted.
11:58:06 #0  0x00007ff1752a14dc in ?? () from /usr/lib/libc.so.6
11:58:06 (gdb) Load new symbol table from "/systemd-meson-build/test-oomd-util"? (y or n) [answered Y; input not from terminal]
11:58:06 Reading symbols from /systemd-meson-build/test-oomd-util...
11:58:06 (gdb) 
11:58:06 Thread 1 (Thread 0x7ff174a2c580 (LWP 1038)):
11:58:06 #0  0x00007ff1752a14dc in ?? () from /usr/lib/libc.so.6
11:58:06 #1  0x00007ff175251998 in raise () from /usr/lib/libc.so.6
11:58:06 #2  0x00007ff17523b53d in abort () from /usr/lib/libc.so.6
11:58:06 #3  0x00007ff17558ea93 in log_assert_failed (text=text@entry=0x562e7ed644b5 "ctx->pgscan == 0", file=file@entry=0x562e7ed64531 "src/oom/test-oomd-util.c", line=line@entry=137, func=func@entry=0x562e7ed65b60 <__PRETTY_FUNCTION__.0> "test_oomd_cgroup_context_acquire_and_insert") at ../build/src/basic/log.c:856
11:58:06 #4  0x0000562e7ed60d35 in test_oomd_cgroup_context_acquire_and_insert () at ../build/src/oom/test-oomd-util.c:137
11:58:06 #5  0x0000562e7ed610a9 in main () at ../build/src/oom/test-oomd-util.c:472
11:58:06 (gdb) #0  0x00007ff1752a14dc in ?? () from /usr/lib/libc.so.6
11:58:06 No symbol table info available.
11:58:06 #1  0x00007ff175251998 in raise () from /usr/lib/libc.so.6
11:58:06 No symbol table info available.
11:58:06 #2  0x00007ff17523b53d in abort () from /usr/lib/libc.so.6
11:58:06 No symbol table info available.
11:58:06 #3  0x00007ff17558ea93 in log_assert_failed (
11:58:06     text=text@entry=0x562e7ed644b5 "ctx->pgscan == 0", 
11:58:06     file=file@entry=0x562e7ed64531 "src/oom/test-oomd-util.c", 
11:58:06     line=line@entry=137, 
11:58:06     func=func@entry=0x562e7ed65b60 <__PRETTY_FUNCTION__.0> "test_oomd_cgroup_context_acquire_and_insert") at ../build/src/basic/log.c:856
11:58:06 No locals.
11:58:06 #4  0x0000562e7ed60d35 in test_oomd_cgroup_context_acquire_and_insert ()
11:58:06     at ../build/src/oom/test-oomd-util.c:137
11:58:06         h1 = 0x0
11:58:06         h2 = 0x0
11:58:06         ctx = 0x562e7fdd3440
11:58:06         cgroup = 0x562e7fdd1bc0 "/system.slice/test-oomd-util-593580fa5284e68a.scope"
11:58:06         root_pref = <optimized out>
11:58:06         c1 = <optimized out>
11:58:06         c2 = <optimized out>
11:58:06         mask = CGROUP_MASK_V2
11:58:06         test_xattrs = <optimized out>
11:58:06         root_xattrs = <optimized out>
11:58:06         r = <optimized out>
11:58:06         __PRETTY_FUNCTION__ = "test_oomd_cgroup_context_acquire_and_insert"
11:58:06 #5  0x0000562e7ed610a9 in main () at ../build/src/oom/test-oomd-util.c:472
11:58:06         r = <optimized out>
11:58:06 (gdb) 
```
```

**Comment by DaanDeMeyer** [comment]
cc @anitazha
