### ISSUE TITLE
systemd-resolved takes a lot of time to switch to another DNS server

### ISSUE THREAD

**Issue by gitzdnex** [systemd/systemd#25294]
### systemd version the issue has been seen with

249.11-0ubuntu3.6

### Used distribution

ubuntu 22.04

### Linux kernel version used

5.15

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

I expect that systemd-resolved will check responses from more servers without failing with Temporary failure in name resolution, when network seems to work. Dnsmasq or simple /etc/resolv.conf with  option rotate and timeout looks to work correctly.  I wanted to set some specific timeout (low value/retry) for systemd-resolved, but I did not find an option for it?

### Unexpected behaviour you saw

I see that systemd-resolved takes a lot of time to fail and switch to another DNS server. Log from journal shows that timeout takes around 26s and then actually switches to another server and gets result and stores it to cache. But meanwhile application already fails. 

### Steps to reproduce the problem

Just run resolution against DNS server which seems to have problems. 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Nov 07 18:19:31 systemd-resolved: Regular transaction 19686 for <google.com IN AAAA> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
Nov 07 18:19:31 systemd-resolved: Sending response packet with id 1707 on interface 1/AF_INET of size 67.
Nov 07 18:19:31 systemd-resolved: Freeing transaction 19686.
Nov 07 18:20:02 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:02 systemd-resolved: Got DNS stub UDP query packet for id 12902
Nov 07 18:20:02 systemd-resolved: Looking up RR for instance.example.com IN A.
Nov 07 18:20:02 systemd-resolved: Cache miss for instance.example.com IN A
Nov 07 18:20:02 systemd-resolved: Firing regular transaction 51449 for <instance.example.com IN A> scope dns on */* (validate=yes).
Nov 07 18:20:02 systemd-resolved: Using feature level UDP+EDNS0 for transaction 51449.
Nov 07 18:20:02 systemd-resolved: Using DNS server 37.1.1.1 for transaction 51449.
Nov 07 18:20:02 systemd-resolved: Announcing packet size 1472 in egress EDNS(0) packet.
Nov 07 18:20:02 systemd-resolved: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Nov 07 18:20:02 systemd-resolved: Sending query packet with id 51449 of size 46.
Nov 07 18:20:02 systemd-resolved: Processing query...
Nov 07 18:20:02 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:28 systemd-resolved: Cache miss for instance.example.com IN AAAA
Nov 07 18:20:28 systemd-resolved: Firing regular transaction 5346 for <instance.example.com IN AAAA> scope dns on */* (validate=yes).
Nov 07 18:20:28 systemd-resolved: Using feature level UDP+EDNS0 for transaction 5346.
Nov 07 18:20:28 systemd-resolved: Using DNS server 37.1.1.1 for transaction 5346.
Nov 07 18:20:28 systemd-resolved: Announcing packet size 1472 in egress EDNS(0) packet.
Nov 07 18:20:28 systemd-resolved: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Nov 07 18:20:28 systemd-resolved: Sending query packet with id 5346 of size 46.
Nov 07 18:20:28 systemd-resolved: Processing query...
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:28 systemd-resolved: Got DNS stub UDP query packet for id 12902
Nov 07 18:20:28 systemd-resolved: Got repeat packet from client, ignoring.
Nov 07 18:20:28 systemd-resolved: Timeout reached on transaction 5346.
Nov 07 18:20:28 systemd-resolved: Retrying transaction 5346, after switching servers.
Nov 07 18:20:28 systemd-resolved: Switching to system DNS server 37.1.1.2.
Nov 07 18:20:28 systemd-resolved: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/resolve1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 07 18:20:28 systemd-resolved: Cache miss for instance.example.com IN AAAA
Nov 07 18:20:28 systemd-resolved: Firing regular transaction 5346 for <instance.example.com IN AAAA> scope dns on */* (validate=yes).
Nov 07 18:20:28 systemd-resolved: Using feature level UDP+EDNS0 for transaction 5346.
Nov 07 18:20:28 systemd-resolved: Using DNS server 37.1.1.2 for transaction 5346.
Nov 07 18:20:28 systemd-resolved: Added socket 18 to graveyard
Nov 07 18:20:28 systemd-resolved: Announcing packet size 1472 in egress EDNS(0) packet.
Nov 07 18:20:28 systemd-resolved: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Nov 07 18:20:28 systemd-resolved: Sending query packet with id 5346 of size 46.
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 62, ifindex=6, ttl=0, fragsize=0
Nov 07 18:20:28 systemd-resolved: Processing incoming packet of size 62 on transaction 51449 (rcode=SUCCESS).
Nov 07 18:20:28 systemd-resolved: Added positive unauthenticated non-confidential cache entry for instance.example.com IN A 1500s on venet0/INET/37.1.1.1
Nov 07 18:20:28 systemd-resolved: Regular transaction 51449 for <instance.example.com IN A> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
Nov 07 18:20:28 systemd-resolved: Sending response packet with id 12902 on interface 1/AF_INET of size 62.
Nov 07 18:20:28 systemd-resolved: Freeing transaction 51449.
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:28 systemd-resolved: Got DNS stub UDP query packet for id 14319
Nov 07 18:20:28 systemd-resolved: Got repeat packet from client, ignoring.
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:28 systemd-resolved: Got DNS stub UDP query packet for id 29893
Nov 07 18:20:28 systemd-resolved: Looking up RR for instance.example.com IN A.
Nov 07 18:20:28 systemd-resolved: Positive cache hit for instance.example.com IN A
Nov 07 18:20:28 systemd-resolved: Regular transaction 36156 for <instance.example.com IN A> on scope dns on */* now complete with <success> from cache (unsigned; non-confidential).
Nov 07 18:20:28 systemd-resolved: Freeing transaction 36156.
Nov 07 18:20:28 systemd-resolved: Sending response packet with id 29893 on interface 1/AF_INET of size 62.
Nov 07 18:20:28 systemd-resolved: Processing query...
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:28 systemd-resolved: Got DNS stub UDP query packet for id 28466
Nov 07 18:20:28 systemd-resolved: Looking up RR for instance.example.com IN AAAA.
Nov 07 18:20:28 systemd-resolved: Processing query...
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:28 systemd-resolved: Got DNS stub UDP query packet for id 29893
Nov 07 18:20:28 systemd-resolved: Looking up RR for instance.example.com IN A.
Nov 07 18:20:28 systemd-resolved: Positive cache hit for instance.example.com IN A
Nov 07 18:20:28 systemd-resolved: Regular transaction 2727 for <instance.example.com IN A> on scope dns on */* now complete with <success> from cache (unsigned; non-confidential).
Nov 07 18:20:28 systemd-resolved: Freeing transaction 2727.
Nov 07 18:20:28 systemd-resolved: Sending response packet with id 29893 on interface 1/AF_INET of size 62.
Nov 07 18:20:28 systemd-resolved: Processing query...
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 46, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:28 systemd-resolved: Got DNS stub UDP query packet for id 28466
Nov 07 18:20:28 systemd-resolved: Got repeat packet from client, ignoring.
Nov 07 18:20:28 systemd-resolved: Closing graveyard socket fd 18
Nov 07 18:20:28 systemd-resolved: Received dns UDP packet of size 106, ifindex=6, ttl=0, fragsize=0
Nov 07 18:20:28 systemd-resolved: Processing incoming packet of size 106 on transaction 5346 (rcode=SUCCESS).
Nov 07 18:20:28 systemd-resolved: Verified we get a response at feature level UDP+EDNS0 from DNS server 37.1.1.2.
Nov 07 18:20:28 systemd-resolved: Not caching negative entry for: instance.example.com IN AAAA, cache mode set to no-negative
Nov 07 18:20:28 systemd-resolved: Regular transaction 5346 for <instance.example.com IN AAAA> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
Nov 07 18:20:28 systemd-resolved: Sending response packet with id 14319 on interface 1/AF_INET of size 106.
Nov 07 18:20:28 systemd-resolved: Sending response packet with id 28466 on interface 1/AF_INET of size 106.
Nov 07 18:20:28 systemd-resolved: Freeing transaction 5346.
Nov 07 18:20:52 systemd-resolved: Received dns UDP packet of size 45, ifindex=0, ttl=64, fragsize=0
Nov 07 18:20:52 systemd-resolved: Got DNS stub UDP query packet for id 4971
Nov 07 18:20:52 systemd-resolved: Looking up RR for instance1.example.com IN A.
Nov 07 18:20:52 systemd-resolved: Cache miss for instance1.example.com IN A

$ systemctl --version
systemd 249 (249.11-0ubuntu3.6)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
$ resolvectl status
Global
           Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
  Current DNS Server: 37.1.1.1
         DNS Servers: 37.1.1.1 37.1.1.2 1.1.1.1
Fallback DNS Servers: 1.1.1.1

Link 2 (tunl0)  
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (gre0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (gretap0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (erspan0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 6 (venet0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported


Actual error message from app ---
----
2022-11-07 18:20:04,692:INFO:tornado.access:200 GET /check_online (ip) 0.30ms
2022-11-07 18:20:22,046:ERROR:root:Cannot connect to instance.example.com
Traceback (most recent call last):
  File "tornado.py", line 218, in check_network
    connect(host=net,url=url,method="GET")
  File "connect.py", line 41, in connect
    conn.request(method, url, data, headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by gitzdnex** [comment]
As this did not happen anymore, we have added more servers and enabled better cache it is quite okay. I would still like to be able specify timemout or conditions for server switch, but it seems to be quite okay now.
