### ISSUE TITLE
There are memory leaks in ndisc_router_process_onlink_prefix and ndisc_router_process_route

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#25891]
I'm not sure whether they are related to https://github.com/systemd/systemd/issues/25883 or not but since the backtraces and packets triggering them are different I think it would make sense to track them separately
```sh
[38767.863720] systemd-networkd[485]: =================================================================
[38767.865188] systemd-networkd[485]: ==485==ERROR: LeakSanitizer: detected memory leaks
[38767.866384] systemd-networkd[485]: Direct leak of 28304 byte(s) in 122 object(s) allocated from:
[38767.867455] systemd-networkd[485]:     #0 0x7f1cbaeba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
[38767.868566] systemd-networkd[485]:     #1 0x48207c in malloc_multiply ../src/basic/alloc-util.h:119
[38767.869846] systemd-networkd[485]:     #2 0x483a87 in route_new ../src/network/networkd-route.c:27
[38767.871191] systemd-networkd[485]:     #3 0x673d3a in ndisc_router_process_onlink_prefix ../src/network/networkd-ndisc.c:452
[38767.872363] systemd-networkd[485]:     #4 0x67545c in ndisc_router_process_prefix ../src/network/networkd-ndisc.c:508
[38767.873875] systemd-networkd[485]:     #5 0x67af9d in ndisc_router_process_options ../src/network/networkd-ndisc.c:819
[38767.875348] systemd-networkd[485]:     #6 0x67eaff in ndisc_router_handler ../src/network/networkd-ndisc.c:1053
[38767.876863] systemd-networkd[485]:     #7 0x67f08e in ndisc_handler ../src/network/networkd-ndisc.c:1083
[38767.878864] systemd-networkd[485]:     #8 0x7bb733 in ndisc_callback ../src/libsystemd-network/sd-ndisc.c:42
[38767.880406] systemd-networkd[485]:     #9 0x7bdebb in ndisc_handle_datagram ../src/libsystemd-network/sd-ndisc.c:197
[38767.882379] systemd-networkd[485]:     #10 0x7bf054 in ndisc_recv ../src/libsystemd-network/sd-ndisc.c:251
[38767.884860] systemd-networkd[485]:     #11 0x7f1cb9e37fd0 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3665
[38767.886409] systemd-networkd[485]:     #12 0x7f1cb9e40a62 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4249
[38767.888365] systemd-networkd[485]:     #13 0x7f1cb9e41b6d in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4310
[38767.889444] systemd-networkd[485]:     #14 0x7f1cb9e41eee in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4331
[38767.890282] systemd-networkd[485]:     #15 0x41312e in run ../src/network/networkd.c:114
[38767.891416] systemd-networkd[485]:     #16 0x41338e in main ../src/network/networkd.c:121
[38767.892386] systemd-networkd[485]:     #17 0x7f1cb802950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)
[38767.893467] systemd-networkd[485]: SUMMARY: AddressSanitizer: 28304 byte(s) leaked in 122 allocation(s).
```
```sh
[45604.584389] systemd-networkd[838]: =================================================================
[45604.586209] systemd-networkd[838]: ==838==ERROR: LeakSanitizer: detected memory leaks
[45604.587457] systemd-networkd[838]: Direct leak of 7424 byte(s) in 32 object(s) allocated from:
[45604.589222] systemd-networkd[838]:     #0 0x7eff772ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
[45604.590538] systemd-networkd[838]:     #1 0x48207c in malloc_multiply ../src/basic/alloc-util.h:119
[45604.591936] systemd-networkd[838]:     #2 0x483a87 in route_new ../src/network/networkd-route.c:27
[45604.593097] systemd-networkd[838]:     #3 0x676f77 in ndisc_router_process_route ../src/network/networkd-ndisc.c:583
[45604.594171] systemd-networkd[838]:     #4 0x67afda in ndisc_router_process_options ../src/network/networkd-ndisc.c:825
[45604.595421] systemd-networkd[838]:     #5 0x67eaff in ndisc_router_handler ../src/network/networkd-ndisc.c:1053
[45604.596790] systemd-networkd[838]:     #6 0x67f08e in ndisc_handler ../src/network/networkd-ndisc.c:1083
[45604.598300] systemd-networkd[838]:     #7 0x7bb733 in ndisc_callback ../src/libsystemd-network/sd-ndisc.c:42
[45604.600460] systemd-networkd[838]:     #8 0x7bdebb in ndisc_handle_datagram ../src/libsystemd-network/sd-ndisc.c:197
[45604.601853] systemd-networkd[838]:     #9 0x7bf054 in ndisc_recv ../src/libsystemd-network/sd-ndisc.c:251
[45604.603089] systemd-networkd[838]:     #10 0x7eff76237fd0 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3665
[45604.604817] systemd-networkd[838]:     #11 0x7eff76240a62 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4249
[45604.607979] systemd-networkd[838]:     #12 0x7eff76241b6d in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4310
[45604.611385] systemd-networkd[838]:     #13 0x7eff76241eee in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4331
[45604.614422] systemd-networkd[838]:     #14 0x41312e in run ../src/network/networkd.c:114
[45604.617208] systemd-networkd[838]:     #15 0x41338e in main ../src/network/networkd.c:121
[45604.619155] systemd-networkd[838]:     #16 0x7eff7442950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)
[45604.620577] systemd-networkd[838]: SUMMARY: AddressSanitizer: 7424 byte(s) leaked in 32 allocation(s).
```

**Comment by evverx** [comment]
Interestingly with `UseDomains` enabled interfaces go to the failed mode on receiving bogus DNSSLs. That appears to explain why my fuzzer hasn't gotten far in the last two days
```sh
host0: Failed to get DNSSL addresses: Bad message
host0: Failed
host0: State changed: configured -> failed
host0: DHCPv4 client: STOPPED
host0: LLDP Rx: Stopping LLDP client
host0: DHCPv6 client: State changed: solicitation -> stopped
host0: NDISC: Stopping IPv6 Router Solicitation client
```
Anyway according to RFC 8106
> If the DNS options are valid, the host SHOULD copy the values of
      the options into the DNS Repository and the Resolver Repository in
      order.  Otherwise, the host MUST discard the options.
