### ISSUE TITLE
test-time-util::test_format_timestamp is flakey

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#26172]
### systemd version the issue has been seen with

git

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

I saw the following in CI:

https://autopkgtest.ubuntu.com/results/autopkgtest-jammy-upstream-systemd-ci-systemd-ci/jammy/arm64/s/systemd-upstream/20230124_012733_11a6e@/log.gz
```
/* test_map_clock_usec */
/* test_in_utc_timezone */
/* test_usec_shift_clock */
/* test_deserialize_dual_timestamp */
/* test_format_timestamp_range */
/* test_format_timestamp_relative */
/* test_FORMAT_TIMESTAMP */
/* test_format_timestamp */
Assertion 'y > usec_sub_unsigned(x, 2 * USEC_PER_DAY) && y < usec_add(x, 2* USEC_PER_DAY)' failed at src/test/test-time-util.c:371, function test_format_timestamp(). Aborting.
```

Locally, if I change the loop to run infinitely instead of just 100 times, it crashes fairly quickly too:
```
(gdb) bt
#0  0x00007ff45b6afe5c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ff45b65fa76 in raise () from /lib64/libc.so.6
#2  0x00007ff45b6497fc in abort () from /lib64/libc.so.6
#3  0x00007ff45ba50a7f in log_assert_failed (text=0x409eb1 "parse_timestamp(buf, &y) >= 0", 
    file=0x4080e2 "src/test/test-time-util.c", line=370, func=0x40abe0 <__func__.12> "test_format_timestamp")
    at ../src/basic/log.c:888
#4  0x0000000000405247 in test_format_timestamp () at ../src/test/test-time-util.c:370
#5  0x0000000000401906 in run_test_table () at ../src/shared/tests.h:106
#6  0x0000000000407281 in main (argc=1, argv=0x7fff68272f18) at ../src/test/test-time-util.c:654
(gdb) up 3
#3  0x00007ff45ba50a7f in log_assert_failed (text=0x409eb1 "parse_timestamp(buf, &y) >= 0", 
    file=0x4080e2 "src/test/test-time-util.c", line=370, func=0x40abe0 <__func__.12> "test_format_timestamp")
    at ../src/basic/log.c:888
888	        abort();
(gdb) up
#4  0x0000000000405247 in test_format_timestamp () at ../src/test/test-time-util.c:370
370	                assert_se(parse_timestamp(buf, &y) >= 0);
(gdb) p buf
$1 = "Thu 1970-01-01\000\060\064:39:24.384197 UTC\000\000\377\177\000\000\334\024@\000\000\000\000\000\b\000\000\000\000\000\000\000@\256@\000\000\000\000"
(gdb) p (const char*) buf
$2 = 0x7fff68272d40 "Thu 1970-01-01"
```

This is not related to #26159, and I don't have time to look into this now.

Also, we should figure out how to print the seed that causes a crash, so that it's visible in logs.

### Steps to reproduce the problem

```diff
diff --git src/test/test-time-util.c src/test/test-time-util.c
index 33d5b89729..902fe603b4 100644
--- src/test/test-time-util.c
+++ src/test/test-time-util.c
@@ -334,7 +334,7 @@ TEST(usec_sub_signed) {
 }
 
 TEST(format_timestamp) {
-        for (unsigned i = 0; i < 100; i++) {
+        for (unsigned i = 0; ; i++) {
                 char buf[CONST_MAX(FORMAT_TIMESTAMP_MAX, FORMAT_TIMESPAN_MAX)];
                 usec_t x, y;
 
```

**Comment by medhefgo** [comment]
@poettering broke it with 64f3419ec1f56a93b6dd48137ca40c945fc06c59. Use this seed to reproduce: 30587605529.
