### ISSUE TITLE
Cannot run eBPF programs from a privileged nspawn container

### ISSUE THREAD

**Issue by torrefatto** [systemd/systemd#26572]
### systemd version the issue has been seen with

252

### Used distribution

Arch Linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

machinectl, systemd-nspawn

### Expected behaviour you didn't see

I expected to be able to run an eBPF program from inside a nspawn container.

### Unexpected behaviour you saw

I received a Permission Denied error.

### Steps to reproduce the problem

I created a container with `debootstrap` in `/var/lib/machines/mycontainer`. I then created a unit at `/etc/systemd/nspawn/mycontainer.nspawn` with this config

```ini
[Exec]
Capability=all
PrivateUsers=false

[Files]
Bind=/sys/kernel/debug:/sys/kernel/debug
Bind=/sys/kernel/tracing:/sys/kernel/tracing
Bind=/sys/fs/bpf:/sys/fs/bpf
BindReadOnly=/usr/lib/modules/6.1.12-arch1-1/build:/usr/src/linux-headers-6.1.12-arch1-1
BindReadOnly=/usr/lib/modules/6.1.12-arch1-1:/lib/modules/6.1.12-arch1-1

[Network]
VirtualEthernet=yes
```

Lastly, I installed `python3-bpfcc` and tried to run the following program as root
 
```python
#!/usr/bin/python
from bcc import BPF

prog = """
int hello(void *ctx) {
    bpf_trace_printk("Hello world\\n");
    return 0;
}
"""

b = BPF(text=prog)
clone = b.get_syscall_fnname("clone")
b.attach_kprobe(event=clone, fn_name="hello")
b.trace_print()
```

but I got a permission denied:

```
# python3 hello_ebpf.py 
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:94:
include/linux/compiler-clang.h:41:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:94:
include/linux/compiler-clang.h:42:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:94:
include/linux/compiler-clang.h:43:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
3 warnings generated.
bpf: Failed to load program: Operation not permitted

Traceback (most recent call last):
  File "hello_ebpf.py", line 13, in <module>
    b.attach_kprobe(event=clone, fn_name="hello")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 654, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 391, in load_func
    raise Exception("Need super-user privileges to run")
Exception: Need super-user privileges to run
```

 I tried, on the same host, to run it from a docker container and managed to do it successfully with this `Dockerfile`

```Dockerfile
FROM ubuntu:focal

USER root
WORKDIR /root

RUN apt update && apt install -y python3-bpfcc
COPY ./hello_ebpf.py .

ENTRYPOINT ["python3", "/root/hello_ebpf.py"]
```

building the image

```
docker build -t test_ebpf .
```

and running a container with 

```
docker run --rm --privileged \
    -v /usr/lib/modules/6.1.12-arch1-1/:/lib/modules/6.1.12-arch1-1/ \
    -v /sys/kernel/debug:/sys/kernel/debug \
    -v /sys/kernel/tracing:/sys/kernel/tracing \
    -ti test_ebpf
```

I get

```
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:94:
include/linux/compiler-clang.h:41:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:94:
include/linux/compiler-clang.h:42:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:5:
In file included from include/linux/compiler_types.h:94:
include/linux/compiler-clang.h:43:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
3 warnings generated.
b'    tmux: server-31549   [001] d..31 28326.437335: bpf_trace_printk: Hello world'
b''
b'           <...>-125788  [003] d..31 28361.390257: bpf_trace_printk: Hello world'
b''
b'   ECStateEngine-144277  [002] d..31 28361.391213: bpf_trace_printk: Hello world'
b''
b' event_collector-144278  [006] d..31 28361.395866: bpf_trace_printk: Hello world'
b''
b' event_collector-144278  [006] d..31 28361.395936: bpf_trace_printk: Hello world'
b''
b' event_collector-144278  [006] d..31 28361.396006: bpf_trace_printk: Hello world'
b''
b' event_collector-144281  [001] d..31 28361.396124: bpf_trace_printk: Hello world'
b''
b'           <...>-1400    [004] d..31 28361.894574: bpf_trace_printk: Hello world'
b''
b'         systemd-1400    [004] d..31 28361.928076: bpf_trace_printk: Hello world'
b''
b'    tmux: server-31549   [002] d..31 28361.945986: bpf_trace_printk: Hello world'
b''
b'    tmux: server-31549   [002] d..31 28361.947615: bpf_trace_printk: Hello world'
b''
b'    tmux: server-31549   [003] d..31 28363.286771: bpf_trace_printk: Hello world'
b''
b'    tmux: server-31549   [003] d..31 28363.287960: bpf_trace_printk: Hello world'
b''
b'    tmux: server-31549   [003] d..31 28363.948256: bpf_trace_printk: Hello world'
b''
b'    tmux: server-31549   [003] d..31 28363.949603: bpf_trace_printk: Hello world'
b''
b'         systemd-1400    [002] d..31 28364.145413: bpf_trace_printk: Hello world'
b''
b'         systemd-1400    [002] d..31 28364.178826: bpf_trace_printk: Hello world'
b''
^CTraceback (most recent call last):
  File "/root/hello_ebpf.py", line 14, in <module>
    b.trace_print()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1199, in trace_print
    line = self.trace_readline(nonblocking=False)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1179, in trace_readline
    line = trace.readline(1024).rstrip()
KeyboardInterrupt
```

**Comment by poettering** [comment]
We also filter the bpf syscall via seccomp. i.e. use --system-call-filter= to unlock that.

**Comment by torrefatto** [comment]
Thanks for the clarification! And thanks for you work (I love `systemd`). I just wanted to add, for [future reference](https://xkcd.com/979/), that what I needed in the end was this set of configuration in my `.nspawn`, under `[Exec]`:

```
PrivateUsers=false
SystemCallFilter=@privileged @debug @mount
```

> We also filter the bpf syscall via seccomp. i.e. use --system-call-filter= to unlock that.

One never knows how deep the rabbit hole is. Thanks again!
