### ISSUE TITLE
Ukify : ModuleNotFoundError: No module named 'pefile'

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#26634]
### systemd version the issue has been seen with

253-1

### Used distribution

Arch linux

### Linux kernel version used

6.2.1-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

UKI generation fails with ```No module named 'pefile'```

### Unexpected behaviour you saw

```
Host arch 'x86_64', EFI arch 'x64'
Kernel version not specified, starting autodetection 😖.
Found uname version: 6.1.14-hardened1-1-hardened
Traceback (most recent call last):
  File "/usr/lib/systemd/ukify", line 784, in <module>
    main()
  File "/usr/lib/systemd/ukify", line 780, in main
    make_uki(opts)
  File "/usr/lib/systemd/ukify", line 519, in make_uki
    uki = UKI(opts.stub)
  File "<string>", line 5, in __init__
  File "/usr/lib/systemd/ukify", line 276, in __post_init__
    self.offset = round_up(pe_next_section_offset(self.executable))
  File "/usr/lib/systemd/ukify", line 81, in pe_next_section_offset
    import pefile
ModuleNotFoundError: No module named 'pefile'
```

### Steps to reproduce the problem

```
# /usr/lib/systemd/ukify /lib/modules/6.1.14-hardened1-1-hardened/vmlinuz /boot/initramfs-linux-hardened.img --cmdline='quiet rw'
```

**Comment by DaanDeMeyer** [comment]
This means the python-pefile dependency is missing. Please report this to your distro instead.

**Comment by YHNdnzj** [comment]
Downstream bug report is at
https://bugs.archlinux.org/task/77529 :)
