### ISSUE TITLE
systemd-resolved:  "Assertion 'e->key == i->next_key' failed" after resume

### ISSUE THREAD

**Issue by marckleinebudde** [systemd/systemd#2676]
I'm using debian's systemd-229 with enabled systemd-resolved. After resume, the following assertion sometimes triggers:

```
Feb 20 09:07:10 hardanger systemd-resolved[898]: Switching to DNS server 8.8.8.8 for interface wlan0.
Feb 20 09:07:10 hardanger systemd-resolved[898]: Detected conflict on hardanger4. IN AAAA  2001:6f8:105b:1122:5e51:4fff:fed6:c770
Feb 20 09:07:10 hardanger systemd-resolved[898]: Hostname conflict, changing published hostname from 'hardanger4' to 'hardanger11'.
Feb 20 09:07:10 hardanger systemd-resolved[898]: Assertion 'e->key == i->next_key' failed at ../src/basic/hashmap.c:634, function hashmap_iterate_in_internal_order(). Aborting.
```

**Comment by keszybz** [comment]
Most likely the assertion is hit after the memory corruption happens, and it would be great to catch instead the moment when the actual corruption happens. Any chance you could (in the order of effort involved):
1. do the same with debugging enabled (use `systemctl edit systemd-resolved.service` and insert `[Service] Environment=SYSTEMD_LOG_LEVEL=debug`) and post the log output
2. recompile with `--enable-address-sanitizer` (only install `systemd-resolved` to /usr/lib/systemd/), and let it run and post the output when it crashes.

**Comment by marckleinebudde** [comment]
Don't this it's a memory corruption due to the suspend. I think the problem is that wlan0 and eth0 are both in the same network. OK, why this happened here is a separate problem. I've an avai-daemon running, too. Otherwise my HP printer isn't detected via mdns.

I've switched on SYSTEMD_LOG_LEVEL=debug, but not the address sanitizer, yet. For output see attached file.

[systemd-resolved-20160220-1.txt](https://github.com/systemd/systemd/files/139214/systemd-resolved-20160220-1.txt)

**Comment by keszybz** [comment]
Thanks. I looked the code in this area over and don't see anything wrong. Most likely one of the callbacks frees something that should is not protected by an increased refcount somewhere, but I have no idea where.

**Comment by poettering** [comment]
Any chance you can get the coredump for this? This should normally result in a coredump collected by systemd-coredump, which you can look at via "coredumpctl". Just get us the stacktrace.

**Comment by marckleinebudde** [comment]
Sure, but systemd doesn't create a coredump when `/lib/systemd/systemd-resolved` crashes (or I kill with with ABRT), while the core is dumped for other daemons like sshd. (note: running debian).

**Comment by poettering** [comment]
is "systemd-coredump" available on Debian and enabled?

**Comment by marckleinebudde** [comment]
Seems to be working for me on sshd:

```
➜ (pts/20) frogger@hardanger:~ (master) ✗ sudo pkill -ABRT sshd 
➜ (pts/20) frogger@hardanger:~ (master) ✗ sudo pkill -ABRT systemd-resolved
➜ (pts/20) frogger@hardanger:~ (master) ✗ sudo pkill -ABRT sshd            
➜ (pts/20) frogger@hardanger:~ (master) ✗ sudo coredumpctl 
TIME                            PID   UID   GID SIG PRESENT EXE
Sun 2016-02-21 23:42:01 CET   24948     0     0   6 * /usr/sbin/sshd
Sun 2016-02-21 23:42:06 CET   25013     0     0   6 * /usr/sbin/sshd
```

**Comment by marckleinebudde** [comment]
Better use `killall` - now it's really killed - but still no coredump for systemd-resolved.

**Comment by marckleinebudde** [comment]
No coredump for `systemd-networkd` either. Is this come kind of special debian setting or a layer8 problem? :)

**Comment by marckleinebudde** [comment]
gdb says:

```
>>> bt
#0  0x00007fc12924d507 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fc12924e8da in __GI_abort () at abort.c:89
#2  0x0000559fc20d7b85 in log_assert_failed (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ../src/basic/log.c:788
#3  0x0000559fc20eb63f in hashmap_iterate_in_internal_order (i=0x7ffe5ea4d500, h=0x559fc22a6d10) at ../src/basic/hashmap.c:634
#4  hashmap_iterate_entry.lto_priv.330 (h=0x559fc22a6d10, i=0x7ffe5ea4d500) at ../src/basic/hashmap.c:678
#5  0x0000559fc20db982 in internal_hashmap_iterate (h=0x559fc22a6d10, i=<optimized out>, value=0x7ffe5ea4d4f0, key=0x0) at ../src/basic/hashmap.c:686
#6  0x0000559fc20a682b in dns_transaction_complete (t=t@entry=0x559fc2292f80, state=state@entry=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:334
#7  0x0000559fc20a6e55 in dns_transaction_process_dnssec.lto_priv.376 (t=<optimized out>) at ../src/resolve/resolved-dns-transaction.c:722
#8  0x0000559fc20d08f8 in dns_transaction_process_reply (t=0x559fc2292f80, p=<optimized out>) at ../src/resolve/resolved-dns-transaction.c:1004
#9  0x0000559fc20dc11c in on_llmnr_packet (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>) at ../src/resolve/resolved-llmnr.c:111
#10 0x0000559fc20a5d93 in source_dispatch.lto_priv.472 (s=0x559fc2268150) at ../src/libsystemd/sd-event/sd-event.c:2265
#11 0x0000559fc20911dd in sd_event_dispatch (e=0x559fc2262350) at ../src/libsystemd/sd-event/sd-event.c:2625
#12 sd_event_run (timeout=18446744073709551615, e=0x559fc2262350) at ../src/libsystemd/sd-event/sd-event.c:2684
#13 sd_event_loop (e=0x559fc2262350) at ../src/libsystemd/sd-event/sd-event.c:2704
#14 main (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:98
>>> bt full
#0  0x00007fc12924d507 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 15884
        selftid = 15884
#1  0x00007fc12924e8da in __GI_abort () at abort.c:89
        save_stage = 2
        act = {
          __sigaction_handler = {
            sa_handler = 0x559fc2262370, 
            sa_sigaction = 0x559fc2262370
          }, 
          sa_mask = {
            __val = {[0] = 94144643852165, [1] = 94144645433808, [2] = 0, [3] = 140730486281240, [4] = 94144643840386, [5] = 94144645432976, [6] = 140730486281248, [7] = 140730486281240, [8] = 94144643872124, [9] = 94144645432976, [10] = 94144643826496, [11] = 94144643983560, [12] = 12737311629953595904, [13] = 94144644041344, [14] = 94144645721360, [15] = 140730486281472}
          }, 
          sa_flags = 1, 
          sa_restorer = 0x7ffe5ea4d4f0
        }
        sigs = {
          __val = {[0] = 32, [1] = 0 <repeats 15 times>}
        }
#2  0x0000559fc20d7b85 in log_assert_failed (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ../src/basic/log.c:788
No locals.
#3  0x0000559fc20eb63f in hashmap_iterate_in_internal_order (i=0x7ffe5ea4d500, h=0x559fc22a6d10) at ../src/basic/hashmap.c:634
        idx = <optimized out>
#4  hashmap_iterate_entry.lto_priv.330 (h=0x559fc22a6d10, i=0x7ffe5ea4d500) at ../src/basic/hashmap.c:678
No locals.
#5  0x0000559fc20db982 in internal_hashmap_iterate (h=0x559fc22a6d10, i=<optimized out>, value=0x7ffe5ea4d4f0, key=0x0) at ../src/basic/hashmap.c:686
        idx = <optimized out>
#6  0x0000559fc20a682b in dns_transaction_complete (t=t@entry=0x559fc2292f80, state=state@entry=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:334
        c = 0x0
        z = 0x559fc2282980
        d = 0x559fc228b480
        i = {
          idx = 1, 
          next_key = 0x559fc226b710
        }
        st = <optimized out>
        __PRETTY_FUNCTION__ = "dns_transaction_complete"
        __func__ = "dns_transaction_complete"
#7  0x0000559fc20a6e55 in dns_transaction_process_dnssec.lto_priv.376 (t=<optimized out>) at ../src/resolve/resolved-dns-transaction.c:722
        r = <optimized out>
        __PRETTY_FUNCTION__ = "dns_transaction_process_dnssec"
#8  0x0000559fc20d08f8 in dns_transaction_process_reply (t=0x559fc2292f80, p=<optimized out>) at ../src/resolve/resolved-dns-transaction.c:1004
        ts = 173688028163
        r = <optimized out>
        __PRETTY_FUNCTION__ = "dns_transaction_process_reply"
        __func__ = "dns_transaction_process_reply"
#9  0x0000559fc20dc11c in on_llmnr_packet (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>) at ../src/resolve/resolved-llmnr.c:111
        p = 0x559fc22760f0
        t = <optimized out>
        m = <optimized out>
        scope = 0x559fc22938f0
        r = <optimized out>
        __func__ = "on_llmnr_packet"
#10 0x0000559fc20a5d93 in source_dispatch.lto_priv.472 (s=0x559fc2268150) at ../src/libsystemd/sd-event/sd-event.c:2265
        r = <optimized out>
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
#11 0x0000559fc20911dd in sd_event_dispatch (e=0x559fc2262350) at ../src/libsystemd/sd-event/sd-event.c:2625
        p = <optimized out>
        r = <optimized out>
#12 sd_event_run (timeout=18446744073709551615, e=0x559fc2262350) at ../src/libsystemd/sd-event/sd-event.c:2684
        r = <optimized out>
#13 sd_event_loop (e=0x559fc2262350) at ../src/libsystemd/sd-event/sd-event.c:2704
        r = <optimized out>
#14 main (argc=<optimized out>, argv=<optimized out>) at ../src/resolve/resolved.c:98
        m = 0x559fc2260690
        user = <optimized out>
        uid = <optimized out>
        gid = <optimized out>
```

**Comment by poettering** [comment]
ok, that was very helpful, found the bug.

**Comment by marckleinebudde** [comment]
\o/

**Comment by poettering** [comment]
Could you please check if #2702 fixes the issue for you?

**Comment by marckleinebudde** [comment]
I was testing the patched resolved and I failed to crash the system. Tested about 30 minutes, it usually fails after ~5.
