### ISSUE TITLE
Segmentation fault in `journalctl`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#26822]
### systemd version the issue has been seen with

latest main

### Used distribution

CentOS Stream 8

### CPU architectures issue was seen on

None

### Component

journalctl

### Unexpected behaviour you saw

One recent CentOS CI job reported a seemingly random segmentation fault when gathering journals from one of the test VMs, and given the stack trace it might be a fallout from https://github.com/systemd/systemd/pull/26355 (cc @poettering):

```
Core was generated by `/root/systemd/build/journalctl -o export -D /var/tmp/systemd-test-TEST-13-NSPAW'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8d7a38360a in journal_file_read_tail_timestamp (
    j=j@entry=0x1708a40, f=0x1715ee0)
    at ../src/libsystemd/sd-journal/sd-journal.c:2440
2440	                        id = o->entry.boot_id;
```

```gdb
#0  0x00007f8d7a38360a in journal_file_read_tail_timestamp (
    j=j@entry=0x1708a40, f=0x1715ee0)
    at ../src/libsystemd/sd-journal/sd-journal.c:2440
        offset = <optimized out>
        mo = <optimized out>
        rt = <optimized out>
        id = <optimized out>
        type = <optimized out>
        o = 0x0
        r = <optimized out>
        __func__ = "journal_file_read_tail_timestamp"
#1  0x00007f8d7a3866e0 in add_any_file (j=j@entry=0x1708a40, fd=16, 
    fd@entry=-1, 
    path=path@entry=0x1714440 "/var/tmp/systemd-test-TEST-13-NSPAWN-SMOKE_1/root/var/log/journal/d7c3074ee5d04e8ebca0dbabd2e73fd6/user-1794572288@0005f6e21f4f00a9-a3d2369cbf6000b3.journal~")
    at ../src/libsystemd/sd-journal/sd-journal.c:1471
        our_fd = -9
        f = 0x1715ee0
        st = {st_dev = 66310, st_ino = 3978, st_nlink = 1, st_mode = 33184, 
          st_uid = 0, st_gid = 190, __pad0 = 0, st_rdev = 0, 
          st_size = 8388608, st_blksize = 4096, st_blocks = 16392, st_atim = {
            tv_sec = 1678825931, tv_nsec = 861186951}, st_mtim = {
            tv_sec = 1678825538, tv_nsec = 660312251}, st_ctim = {
            tv_sec = 1678825931, tv_nsec = 863187206}, __glibc_reserved = {0, 
            0, 0}}
        r = 1
        __func__ = "add_any_file"
#2  0x00007f8d7a3868dd in add_file_by_name (j=j@entry=0x1708a40, 
    prefix=0x1712dc0 "/var/tmp/systemd-test-TEST-13-NSPAWN-SMOKE_1/root/var/log/journal/d7c3074ee5d04e8ebca0dbabd2e73fd6", 
    filename=filename@entry=0x170b19b "user-1794572288@0005f6e21f4f00a9-a3d2369cbf6000b3.journal~") at ../src/libsystemd/sd-journal/sd-journal.c:1505
        path = 0x1714440 "/var/tmp/systemd-test-TEST-13-NSPAWN-SMOKE_1/root/var/log/journal/d7c3074ee5d04e8ebca0dbabd2e73fd6/user-1794572288@0005f6e21f4f00a9-a3d2369cbf6000b3.journal~"
        __func__ = "add_file_by_name"
#3  0x00007f8d7a387097 in directory_enumerate (j=j@entry=0x1708a40, 
    m=m@entry=0x1712da0, d=0x170ad60)
    at ../src/libsystemd/sd-journal/sd-journal.c:1683
        de = 0x170b188
        __func__ = "directory_enumerate"
#4  0x00007f8d7a3874fb in add_root_directory (j=j@entry=0x1708a40, 
    p=p@entry=0x7ffe4d966118 "/var/tmp/systemd-test-TEST-13-NSPAWN-SMOKE_1/root/var/log/journal/d7c3074ee5d04e8ebca0dbabd2e73fd6", 
    missing_ok=missing_ok@entry=false)
    at ../src/libsystemd/sd-journal/sd-journal.c:1904
        d = 0x170ad60
        m = 0x1712da0
        r = <optimized out>
        k = <optimized out>
        __func__ = "add_root_directory"
#5  0x00007f8d7a389686 in sd_journal_open_directory (
    ret=ret@entry=0x7ffe4d9644b8, 
    path=0x7ffe4d966118 "/var/tmp/systemd-test-TEST-13-NSPAWN-SMOKE_1/root/var/log/journal/d7c3074ee5d04e8ebca0dbabd2e73fd6", flags=0)
    at ../src/libsystemd/sd-journal/sd-journal.c:2136
        j = 0x1708a40
        r = <optimized out>
        __func__ = "sd_journal_open_directory"
        _pvar_ = <optimized out>
        _var_ = <optimized out>
        _nullvalue_ = <optimized out>
#6  0x000000000040b5a8 in run (argc=5, argv=0x7ffe4d964a98)
    at ../src/journal/journalctl.c:2212
        loop_device = 0x0
        unlink_dir = 0x0
        previous_boot_id_valid = false
        first_line = true
        ellipsized = false
        need_seek = false
        since_seeked = false
        use_cursor = false
        after_cursor = false
        j = 0x0
        previous_boot_id = <optimized out>
        previous_boot_id_output = {bytes = '\000' <repeats 15 times>, 
          qwords = {0, 0}}
        previous_ts_output = {realtime = 0, monotonic = 0}
        machine_fd = -9
        n_shown = 0
        r = <optimized out>
        poll_fd = -9
        __func__ = "run"
#7  0x000000000040d76b in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/journal/journalctl.c:2728
        r = <optimized out>
        __func__ = "main"
```

Unfortunately, that's all I got, as the journal didn't get properly archived (for obvious reasons).

**Comment by evverx** [comment]
I saw that one too. Under ASan it looks like
```sh
../src/libsystemd/sd-journal/sd-journal.c:2440:33: runtime error: member access within null pointer of type 'Object' (aka 'union Object')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/libsystemd/sd-journal/sd-journal.c:2440:33 in
../src/libsystemd/sd-journal/sd-journal.c:2440:33: runtime error: member access within null pointer of type 'EntryObject' (aka 'struct EntryObject')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/libsystemd/sd-journal/sd-journal.c:2440:33 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==21463==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x7fc854e958e2 bp 0x7ffcece8f470 sp 0x7ffcece8ebb8 T0)
==21463==The signal is caused by a READ memory access.
==21463==Hint: address points to the zero page.
    #0 0x7fc854e958e2 in __memmove_avx_unaligned_erms (/lib64/libc.so.6+0x1528e2) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #1 0x7fc856dfe2aa in journal_file_read_tail_timestamp /home/vagrant/systemd/build/../src/libsystemd/sd-journal/sd-journal.c:2440:39
    #2 0x7fc856dc4586 in add_any_file /home/vagrant/systemd/build/../src/libsystemd/sd-journal/sd-journal.c:1471:16
    #3 0x7fc856dbfe5e in sd_journal_open_files /home/vagrant/systemd/build/../src/libsystemd/sd-journal/sd-journal.c:2156:21
    #4 0x51e6ae in run /home/vagrant/systemd/build/../src/journal/journalctl.c:2218:21
    #5 0x51bc0a in main /home/vagrant/systemd/build/../src/journal/journalctl.c:2728:1
    #6 0x7fc854d6a50f in __libc_start_call_main (/lib64/libc.so.6+0x2750f) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #7 0x7fc854d6a5c8 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x275c8) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #8 0x4230f4 in _start (/home/vagrant/systemd/build/journalctl+0x4230f4) (BuildId: 3581c6200569fae2a2c2618666ad0d82f606ee31)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libc.so.6+0x1528e2) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136) in __memmove_avx_unaligned_erms
==21463==ABORTING
```

```
cat <<'EOF' | xxd -r -p >CRASH
4c504b534848524800003800000000000000000000000000000000000000
00000000000000000000000000000000000000003f000000000000000000
000000000000000000000000000000000000000000000000000000000001
00000000000000000000000000000008000000fcffffff00000000000200
000000002d34303035000000000000008000000000000000000000000000
000000006060606060606060606060606060606060606060606060606060
606060606060606060606060606060606060606060606060606060606060
606060606060606060606060606060606060606060ff38000000000060ff
380000000a00000000000000c543bcbae128d70000000000000000000000
000000ff00000000030000000000000000000000000000f3bd0000000000
000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
0000000049dd000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000002d3334300000000000
000000000009000000000000000000000000000000000000000000000000
0000000000000000006367727000000071f1000000000000000000000000
000000000000000000000000000000000000000000000000000000000000
EOF

./build/journalctl --file CRASH
...
==21551==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x7f79c6c628e2 bp 0x7fff8df6a3d0 sp 0x7fff8df69b18 T0)
...
```
