### ISSUE TITLE
systemd-networkd DHCPServer segmentation fault at ../src/basic/hashmap.h:176

### ISSUE THREAD

**Issue by makhomed** [systemd/systemd#27293]
### systemd version the issue has been seen with

systemd-networkd-250.3-1.el9.x86_64

### Used distribution

Rocky Linux release 9.1

### Linux kernel version used

5.14.0-162.23.1.el9_1.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Expected what systemd-networkd work without errors ```systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV```

### Unexpected behaviour you saw

```
# coredumpctl
TIME                          PID UID GID SIG     COREFILE EXE                                SIZE
Sun 2023-04-16 02:49:45 UTC  2970 192 192 SIGSEGV present  /usr/lib/systemd/systemd-networkd 97.4K
Sun 2023-04-16 04:20:46 UTC  9335 192 192 SIGSEGV present  /usr/lib/systemd/systemd-networkd 97.9K
Sun 2023-04-16 05:51:46 UTC 10075 192 192 SIGSEGV present  /usr/lib/systemd/systemd-networkd 97.7K
Sun 2023-04-16 07:22:47 UTC 28404 192 192 SIGSEGV present  /usr/lib/systemd/systemd-networkd 97.8K
Sun 2023-04-16 08:53:48 UTC 28826 192 192 SIGSEGV present  /usr/lib/systemd/systemd-networkd 97.5K
Sun 2023-04-16 10:24:49 UTC 29546 192 192 SIGSEGV present  /usr/lib/systemd/systemd-networkd 97.4K
```
```
# coredumpctl debug
Core was generated by `/usr/lib/systemd/systemd-networkd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  hashmap_get (key=0x556d1d03eca8, h=<error reading variable: Cannot access memory at address 0x55684bd2af16>) at ../src/basic/hashmap.h:176
176             return _hashmap_get(HASHMAP_BASE(h), key);
(gdb) bt
#0  hashmap_get (key=0x556d1d03eca8, h=<error reading variable: Cannot access memory at address 0x55684bd2af16>) at ../src/basic/hashmap.h:176
#1  dhcp_lease_free (lease=0x556d1d03eca0) at ../src/libsystemd-network/sd-dhcp-server.c:34
#2  0x0000556d1b326d06 in dhcp_server_cleanup_expired_leases (server=0x556d1d03e6f0) at ../src/libsystemd-network/sd-dhcp-server.c:874
#3  dhcp_server_handle_message (length=<optimized out>, message=0x556d1d03b3d0, server=0x556d1d03e6f0) at ../src/libsystemd-network/sd-dhcp-server.c:921
#4  server_receive_message (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>) at ../src/libsystemd-network/sd-dhcp-server.c:1245
#5  0x0000556d1b2e4281 in source_dispatch (s=0x556d1d03e820) at ../src/libsystemd/sd-event/sd-event.c:3598
#6  0x0000556d1b21f062 in sd_event_dispatch (e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:4183
#7  sd_event_run (timeout=18446744073709551615, e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:4244
#8  sd_event_loop (e=0x556d1cff6320) at ../src/libsystemd/sd-event/sd-event.c:4265
#9  run (argc=<optimized out>, argv=<optimized out>) at ../src/network/networkd.c:114
#10 0x0000556d1b215bea in main (argc=<optimized out>, argv=<optimized out>) at ../src/network/networkd.c:121
(gdb)
```

### Steps to reproduce the problem

0. use bare metal server with two ipv4 addresses assigned by hosting provider, first ip used by bare metal server, second ip routed to bridge br0 for using inside router virtual machine.
1. create bridges br0 and br101
[br0.netdev.TXT](https://github.com/systemd/systemd/files/11242143/br0.netdev.TXT)
[br0.network.TXT](https://github.com/systemd/systemd/files/11242144/br0.network.TXT)
[br101.netdev.TXT](https://github.com/systemd/systemd/files/11242145/br101.netdev.TXT)
[br101.network.TXT](https://github.com/systemd/systemd/files/11242146/br101.network.TXT)
2. create two virtual machines using Virtual Machine Manager and System Rescue from https://www.system-rescue.org/Download/
router virtual machine - with two interfaces with manually configured MAC addresses:
``` xml
    <interface type='bridge'>
      <mac address='52:54:00:13:65:00'/>
      <source bridge='br0'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
    <interface type='bridge'>
      <mac address='52:54:00:13:65:01'/>
      <source bridge='br101'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
    </interface>
```
application virtual machine - with one interface with manually configured MAC address:
``` xml
    <interface type='bridge'>
      <mac address='52:54:00:13:65:02'/>
      <source bridge='br101'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
```
3. boot these two virtual machines and leave its booted up for 24h
4. see what ```systemd-networkd``` has segmentation fault in DHCPServer.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  hashmap_get (key=0x556d1d03eca8, h=<error reading variable: Cannot access memory at address 0x55684bd2af16>) at ../src/basic/hashmap.h:176
176             return _hashmap_get(HASHMAP_BASE(h), key);
(gdb) bt
#0  hashmap_get (key=0x556d1d03eca8, h=<error reading variable: Cannot access memory at address 0x55684bd2af16>) at ../src/basic/hashmap.h:176
#1  dhcp_lease_free (lease=0x556d1d03eca0) at ../src/libsystemd-network/sd-dhcp-server.c:34
#2  0x0000556d1b326d06 in dhcp_server_cleanup_expired_leases (server=0x556d1d03e6f0) at ../src/libsystemd-network/sd-dhcp-server.c:874
#3  dhcp_server_handle_message (length=<optimized out>, message=0x556d1d03b3d0, server=0x556d1d03e6f0) at ../src/libsystemd-network/sd-dhcp-server.c:921
#4  server_receive_message (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>) at ../src/libsystemd-network/sd-dhcp-server.c:1245
#5  0x0000556d1b2e4281 in source_dispatch (s=0x556d1d03e820) at ../src/libsystemd/sd-event/sd-event.c:3598
#6  0x0000556d1b21f062 in sd_event_dispatch (e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:4183
#7  sd_event_run (timeout=18446744073709551615, e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:4244
#8  sd_event_loop (e=0x556d1cff6320) at ../src/libsystemd/sd-event/sd-event.c:4265
#9  run (argc=<optimized out>, argv=<optimized out>) at ../src/network/networkd.c:114
#10 0x0000556d1b215bea in main (argc=<optimized out>, argv=<optimized out>) at ../src/network/networkd.c:121
(gdb)
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# /usr/lib/systemd/systemd-networkd --version
systemd 250 (v250.3-1.el9)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 +PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Comment by evverx** [comment]
I think this segfault was fixed in https://github.com/systemd/systemd/pull/22254.

**Comment by makhomed** [comment]
@evverx Ok, thank you! If this problem already resolved in the ```systemd-networkd``` - I should close this issue.

BTW, I found workaround for my case:
```
[DHCPServer]
# workaround for https://github.com/systemd/systemd/issues/27293
DefaultLeaseTimeSec=1y
MaxLeaseTimeSec=1y
```
after this workaround enabled - no more ```systemd-networkd``` crashes.
```
# coredumpctl list
No coredumps found.
```
