### ISSUE TITLE
Pid 1 crash during shutdown on watchdog error

### ISSUE THREAD

**Issue by pothos** [systemd/systemd#27491]
### systemd version the issue has been seen with

252

### Used distribution

Flatcar 3510.2.0

### Linux kernel version used

5.15.98

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

The reboot on the affected machine normally works without problems

### Unexpected behaviour you saw

The machine froze during reboot when dealing with the hardware watchdog.

### Steps to reproduce the problem

Unknown, this was on Equinix Metal c3.small.x86

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Apr 25 16:31:35 hostname systemd[1]: Reached target reboot.target.
Apr 25 16:31:35 hostname systemd[1]: Shutting down.
Apr 25 16:31:35 hostname audit: BPF prog-id=20 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=19 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=25 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=24 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=23 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=18 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=17 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=16 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=28 op=UNLOAD
Apr 25 16:31:35 hostname audit: BPF prog-id=27 op=UNLOAD
Apr 25 16:31:35 hostname kernel: watchdog: watchdog0: watchdog did not stop!
Apr 25 16:31:35 hostname systemd[1]: Using hardware watchdog 'iTCO_wdt', version 0, device /dev/watchdog0
Apr 25 16:31:35 hostname systemd[1]: Failed to set timeout to 10min: Bad file descriptor
Apr 25 16:31:35 hostname systemd[1]: Failed to disable hardware watchdog, ignoring: Bad file descriptor
Apr 25 16:31:35 hostname systemd[1]: Failed to disarm watchdog timer, ignoring: Bad file descriptor
Apr 25 16:31:35 hostname systemd[1]: Assertion 'close_nointr(fd) != -EBADF' failed at src/basic/fd-util.c:77, function safe_close(). Aborting.
Apr 25 16:31:35 hostname audit[227942]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:kernel_t:s0 pid=227942 comm="systemd" exe="/usr/lib/systemd/sy>
Apr 25 16:31:35 hostname systemd[1]: Caught <ABRT> from our own process.
Apr 25 16:31:35 hostname systemd-coredump[227943]: Due to PID 1 having crashed coredump collection will now be turned off.
Apr 25 16:31:35 hostname systemd-coredump[227943]: elfutils disabled, parsing ELF objects not supported
Apr 25 16:31:35 hostname systemd-coredump[227943]: [🡕] Process 227942 (systemd) of user 0 dumped core.
Apr 25 16:31:35 hostname systemd[1]: Caught <ABRT>, dumped core as pid 227942.
Apr 25 16:31:35 hostname systemd[1]: Freezing execution.
Apr 25 16:32:56 hostname systemd-journald[932]: Failed to send WATCHDOG=1 notification message: Connection refused
Apr 25 16:34:46 hostname systemd-journald[932]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
Apr 25 16:35:56 hostname systemd-journald[932]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
Apr 25 16:37:46 hostname systemd-journald[932]: Failed to send WATCHDOG=1 notification message: Transport endpoint is not connected
[… These messages were going on forever …]
```

**Comment by pothos** [comment]
No, the coredump file doesn't exist (anymore? I don't know what would have cleaned it up…)

**Comment by yuwata** [comment]
> #11 0x00007fefbba0deb9 in open_watchdog () at ../systemd-stable-252.5/src/shared/watchdog.c:345
> #12 0x00007fefbba0e069 in open_watchdog () at ../systemd-stable-252.5/src/shared/watchdog.c:308

Hmm??? Why `open_watchdog()` is listed twice?

https://github.com/systemd/systemd/blob/e8dc52766e1fdb4f8c09c3ab654d1270e1090c8d/src/shared/watchdog.c#L308-L309

https://github.com/systemd/systemd/blob/e8dc52766e1fdb4f8c09c3ab654d1270e1090c8d/src/shared/watchdog.c#L343-L345

**Comment by poettering** [comment]
So this is in an error path, somehow updating the timeout via ioctl fails, and then our codepath gets confused.

WOuld love to see an strace of this. Any chance you can get me that? Would probably mean doing something like:

```
systemd-run -p DefaultDependencies=no strace -p 1 -s 500 -y -o log /tmp/mytrace
```

(this will start strace as detached service that won't be terminated during the shutdown). If you can reproduce the issue this should then generate the trace file for you that tells us what syscalls actually fail that trigger this.

**Comment by mrc0mmand** [comment]
> So this is in an error path, somehow updating the timeout via ioctl fails, and then our codepath gets confused.
> 
> WOuld love to see an strace of this. Any chance you can get me that? Would probably mean doing something like:
> 
> ```
> systemd-run -p DefaultDependencies=no strace -p 1 -s 500 -y -o log /tmp/mytrace
> ```

Probably best to use `/var/tmp/mytrace` as `/tmp` is usually tmpfs nowadays and we're dealing with reboots here.

**Comment by pothos** [comment]
Thanks!
Here the last lines (I've ran it with `-o /var/tmp/mytrace`):
```
$ tail -n 75 mytrace 
statx(7</run/systemd/generator.late>, "local-fs.target.wants", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW|AT_NO_AUTOMOUNT, STATX_TYPE, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=60, ...}) = 0
openat(7</run/systemd/generator.late>, "local-fs.target.wants", O_RDONLY|O_NONBLOCK|O_NOFOLLOW|O_NOATIME|O_CLOEXEC|O_DIRECTORY) = 8</run/systemd/generator.late/local-fs.target.wants>
newfstatat(8</run/systemd/generator.late/local-fs.target.wants>, "", {st_mode=S_IFDIR|0755, st_size=60, ...}, AT_EMPTY_PATH) = 0
fcntl(8</run/systemd/generator.late/local-fs.target.wants>, F_GETFL) = 0x78800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW|O_NOATIME|O_DIRECTORY)
fcntl(8</run/systemd/generator.late/local-fs.target.wants>, F_SETFD, FD_CLOEXEC) = 0
getdents64(8</run/systemd/generator.late/local-fs.target.wants>, 0x56286bf9f170 /* 3 entries */, 32768) = 88
unlinkat(8</run/systemd/generator.late/local-fs.target.wants>, "boot.automount", 0) = 0
getdents64(8</run/systemd/generator.late/local-fs.target.wants>, 0x56286bf9f170 /* 0 entries */, 32768) = 0
close(8</run/systemd/generator.late/local-fs.target.wants>) = 0
unlinkat(7</run/systemd/generator.late>, "local-fs.target.wants", AT_REMOVEDIR) = 0
unlinkat(7</run/systemd/generator.late>, "boot.automount", 0) = 0
unlinkat(7</run/systemd/generator.late>, "boot.mount", 0) = 0
getdents64(7</run/systemd/generator.late>, 0x56286bfd3df0 /* 0 entries */, 32768) = 0
close(7</run/systemd/generator.late>)   = 0
rmdir("/run/systemd/generator.late")    = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 17<socket:[27864]>, NULL) = 0
close(17<socket:[27864]>)               = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 44<socket:[8273]>, NULL) = 0
close(44<socket:[8273]>)                = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 41<socket:[8274]>, NULL) = 0
close(41<socket:[8274]>)                = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 6<anon_inode:[signalfd]>, NULL) = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 29<socket:[8268]>, NULL) = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 20<anon_inode:[timerfd]>, NULL) = 0
close(20<anon_inode:[timerfd]>)         = 0
inotify_rm_watch(12<anon_inode:inotify>, 1) = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 12<anon_inode:inotify>, NULL) = 0
close(12<anon_inode:inotify>)           = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 34<socket:[8269]>, NULL) = 0
close(6<anon_inode:[signalfd]>)         = 0
close(29<socket:[8268]>)                = 0
close(34<socket:[8269]>)                = 0
close(35<socket:[8270]>)                = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 86<anon_inode:inotify>, NULL) = 0
close(86<anon_inode:inotify>)           = 0
epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 82<pipe:[1651203]>, NULL) = 0
close(23<pipe:[1651202]>)               = 0
close(81<pipe:[1651202]>)               = 0
close(82<pipe:[1651203]>)               = 0
close(85<pipe:[1651203]>)               = 0
munmap(0x7f08c8423000, 237568)          = 0
munmap(0x7f08c9278000, 8446)            = 0
munmap(0x7f08c8499000, 476235)          = 0
munmap(0x7f08c927b000, 4096)            = 0
close(4<socket:[32522]>)                = 0
openat(AT_FDCWD</>, "/dev/watchdog0", O_WRONLY|O_CLOEXEC) = 4</dev/watchdog0>
ioctl(4</dev/watchdog0>, WDIOC_GETSUPPORT, 0x7fff13b13940) = 0
gettid()                                = 1
sendmsg(4</dev/watchdog0>, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="PRIORITY=6\nSYSLOG_FACILITY=3\nTID=1\nCODE_FILE=src/shared/watchdog.c\nCODE_LINE=338\nCODE_FUNC=open_watchdog\nSYSLOG_IDENTIFIER=systemd\n", iov_len=131}, {iov_base="MESSAGE=", iov_len=8}, {iov_base="Using hardware watchdog 'iTCO_wdt', version 0, device /dev/watchdog0", iov_len=68}, {iov_base="\n", iov_len=1}], msg_iovlen=4, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENOTSOCK (Socket operation on non-socket)
close(4</dev/watchdog0>)                = 0
writev(3</dev/kmsg>, [{iov_base="<30>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Using hardware watchdog 'iTCO_wdt', version 0, device /dev/watchdog0", iov_len=68}, {iov_base="\n", iov_len=1}], 5) = 85
ioctl(4, WDIOC_SETTIMEOUT, [600])       = -1 EBADF (Bad file descriptor)
writev(3</dev/kmsg>, [{iov_base="<27>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Failed to set timeout to 10min: Bad file descriptor", iov_len=51}, {iov_base="\n", iov_len=1}], 5) = 68
ioctl(4, WDIOC_SETOPTIONS, 0x7fff13b13884) = -1 EBADF (Bad file descriptor)
writev(3</dev/kmsg>, [{iov_base="<28>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Failed to disable hardware watchdog, ignoring: Bad file descriptor", iov_len=66}, {iov_base="\n", iov_len=1}], 5) = 83
write(4, "V", 1)                        = -1 EBADF (Bad file descriptor)
writev(3</dev/kmsg>, [{iov_base="<28>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Failed to disarm watchdog timer, ignoring: Bad file descriptor", iov_len=62}, {iov_base="\n", iov_len=1}], 5) = 79
close(4)                                = -1 EBADF (Bad file descriptor)
writev(3</dev/kmsg>, [{iov_base="<26>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Assertion 'close_nointr(fd) != -EBADF' failed at src/basic/fd-util.c:77, function safe_close(). Aborting.", iov_len=105}, {iov_base="\n", iov_len=1}], 5) = 122
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
gettid()                                = 1
getpid()                                = 1
tgkill(1, 1, SIGABRT)                   = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=1, si_uid=0} ---
rt_sigaction(SIGCHLD, {sa_handler=0x7f08c9416f70, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_NOCLDSTOP, sa_restorer=0x7f08c90cc660}, NULL, 8) = 0
clone(child_stack=NULL, flags=SIGCHLD)  = 188811
writev(3</dev/kmsg>, [{iov_base="<24>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Caught <ABRT> from our own process.", iov_len=35}, {iov_base="\n", iov_len=1}], 5) = 52
waitid(P_PID, 188811, {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=188811, si_uid=0, si_status=SIGABRT, si_utime=0, si_stime=0}, WEXITED, NULL) = 0
writev(3</dev/kmsg>, [{iov_base="<24>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Caught <ABRT>, dumped core as pid 188811.", iov_len=41}, {iov_base="\n", iov_len=1}], 5) = 58
rt_sigaction(SIGCHLD, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_NOCLDSTOP|SA_NOCLDWAIT, sa_restorer=0x7f08c90cc660}, NULL, 8) = 0
writev(3</dev/kmsg>, [{iov_base="<24>", iov_len=4}, {iov_base="systemd", iov_len=7}, {iov_base="[1]: ", iov_len=5}, {iov_base="Freezing execution.", iov_len=19}, {iov_base="\n", iov_len=1}], 5) = 36
sync()                                  = 0
close(3</dev/kmsg>)                     = 0
close_range(3, 4294967295, 0)           = 0
waitid(P_ALL, 0, 
```

**Comment by poettering** [comment]
apparently something closed the logging fd behind the back of the logging logic, hence the logging logic tries to log into the closed fd, which however is now taken by the watchdog fd. which will fail with ENOTSOCK, which then causes the logging logic to close the socket, which isn't the socket but the watchdog fd, and then things go bad.

big question: how come the logging fd was closed. It's the close() immediately before the first attempt that's the culprit. Question is, where does that come from?

could be the fdset_free() in the main function or manager_free(). might be worth sprinkling `(void) access("before", F_OK)` and `(void) access("after", F_OK)` and similar in the shutdown code to see where precisely the close() comes from. (the access serves no purpose but placing arbitrary marker strings in the strace log).

**Comment by poettering** [comment]
so lemme guess, this is an selinux system, right? if you turn off selinux entirely (i.e. selinux=0 – permissive mode does not suffice!) then things start working correctly, right?

**Comment by poettering** [comment]
i prepped a fix in #27754. It's a "dry" implementation, I don't actually have selinux around. It's plainly the result of some hard thinking and a look at your strace and one from @bluca that was very similar. I think it will fix the issue at hand, but please report back if that's really the case.

**Comment by poettering** [comment]
also, lemme guess your libselinux version is ancient? can that be?

i.e. doesn't carry this: https://github.com/SELinuxProject/selinux/commit/da4829d0beb13104c7f88b099d40a24ea541f581

**Comment by pothos** [comment]
Thank you, I'll try to reproduce this with a backport on systemd 252.

> also, lemme guess your libselinux version is ancient? can that be?
> 
> i.e. doesn't carry this: [SELinuxProject/selinux@da4829d](https://github.com/SELinuxProject/selinux/commit/da4829d0beb13104c7f88b099d40a24ea541f581)

Yes! I had hopes that the 3.2 package was used but no, 3.1 from a tag that doesn't have this.
