### ISSUE TITLE
test-async is unstable

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#27833]
### systemd version the issue has been seen with

latest main

### Used distribution

Arch Linux

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

Disclaimer: I'm still not completely sure if this is our bug or meson's since I've yet to come up with a reliable reproducer.

For the past couple of months there's been an uprising of timeouts while running `test-async`. However, after a closer look, this doesn't look like a "standard" test timeout, but there's something wrong with process "babysitting":

The output from `meson test:`
```
Summary of Failures:

 506/1515 systemd:test / test-async                                                              TIMEOUT         360.39s

Ok:                 1509
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            5   
Timeout:            1   

Full log written to /systemd-meson-build/meson-logs/testlog.txt
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f5efc8ec7c0>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 558, in close
    self._close(None)
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 582, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Relevant stuff from `testlog.txt`:
```
...
PID 9496: /systemd-meson-build/test-async
      /systemd-meson-build/test-async
      /systemd-meson-build/test-async
      /systemd-meson-build/test-async
      /systemd-meson-build/test-async
      /systemd-meson-build/test-async
      "/systemd-meson-build/test-async"
      "/systemd-meson-build/test-async"
PID 9549: (sd-sync)
      (sd-sync)
      "(sd-sync)"
      "(sd-sync)"
      $'(sd-sync)'
      $'(sd-sync)'
      "(sd-sync)"
      "(sd-sync)"
...
==============================================================================

================================== 506/1515 ==================================
test:         systemd:test / test-async
start time:   11:46:35
duration:     360.39s
result:       exit status 0
command:      LD_LIBRARY_PATH=/systemd-meson-build/src/shared SYSTEMD_LANGUAGE_FALLBACK_MAP=/build/src/locale/language-fallback-map PATH=/systemd-meson-build:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl PROJECT_BUILD_ROOT=/systemd-meson-build MALLOC_PERTURB_=196 /systemd-meson-build/test-async
----------------------------------- stderr -----------------------------------
/* test_test_async */
Successfully forked off '(sd-sync)' as PID 9549.
==============================================================================
```

The [test itself](https://github.com/systemd/systemd/blob/main/src/test/test-async.c) is quite simple and it creates two threads (`asynchronous_close()` and `asynchronous_job()`) and does one fork (`asynchronous_sync()`).

Given the asyncio stack trace I'd say this is a bug in meson (/cc @eli-schwartz) and I found a somewhat similar-ish issue (https://github.com/mesonbuild/meson/issues/3967), but maybe we're doing something weird with the threads. Also, in case of `asynchronous_sync()` we don't wait for the child process, so that's another thing that may confuse meson?

Also, another notable thing - I can seem to reproduce this only with sanitizers - not sure if because it's a timing issue or the ASan/UBSan interceptors doing something fishy.

And now for a very unreliable reproducer:

```
# meson build-san -Db_sanitize=address,undefined
...
# while meson test -C build-san --print-errorlogs test-async; do :; done
...
<... grab a coffee, this might take a while ...>
...
ninja: no work to do.
ninja: Entering directory `/build/build-san'
[1/8] Generating version.h with a custom command
1/1 systemd:test / test-async        OK               1.06s

Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /build/build-san/meson-logs/testlog.txt
ninja: no work to do.
ninja: Entering directory `/build/build-san'
[1/8] Generating version.h with a custom command
1/1 systemd:test / test-async        OK               1.05s

Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /build/build-san/meson-logs/testlog.txt
ninja: no work to do.
ninja: Entering directory `/build/build-san'
[1/8] Generating version.h with a custom command
systemd:test / test-async time out (After 120 seconds)
1/1 systemd:test / test-async        TIMEOUT        120.01s
>>> SYSTEMD_LANGUAGE_FALLBACK_MAP=/build/src/locale/language-fallback-map PROJECT_BUILD_ROOT=/build/build-san PATH=/build/build-san:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl MALLOC_c
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stderr:
/* test_test_async */
Successfully forked off '(sd-sync)' as PID 598910.
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

1/1 systemd:test / test-async TIMEOUT        120.01s

Ok:                 0   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            1   

Full log written to /build/build-san/meson-logs/testlog.txt
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7ff1e311c720>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 558, in close
    self._close(None)
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 582, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by eli-schwartz** [comment]
What version of meson are you using? This code did change a bit in meson 1.1.0, so it might be interesting to try bisecting meson before/after https://github.com/mesonbuild/meson/compare/9aff189e315ccbe3444c75aef412d311fa95fcd2...c5e766af75369009ab9de82baf6c7c7e18f66857.

**Comment by mrc0mmand** [comment]
> What version of meson are you using? This code did change a bit in meson 1.1.0, so it might be interesting to try bisecting meson before/after [mesonbuild/meson@9aff189...c5e766a](https://github.com/mesonbuild/meson/compare/9aff189e315ccbe3444c75aef412d311fa95fcd2...c5e766af75369009ab9de82baf6c7c7e18f66857).

Ah, interesting, that would explain why I could reproduce it only on Arch (with meson 1.1.0) and not locally on my Fedora 37 (with meson 1.0.0).

**Comment by eli-schwartz** [comment]
After running the unreliable reproducer from meson git master for an hour I still haven't hit it locally.

**Comment by eli-schwartz** [comment]
I killed the loop after 6.5 hours -- hopefully a more reliable reproducer can be found.

**Comment by mrc0mmand** [comment]
Thanks for the debugging, I'll play around with meson's master and try to reproduce it (or fail to) with it during today.

**Comment by mrc0mmand** [comment]
This is... weird. I can't reproduce it on Fedora with any meson version, but I can reproduce it on Arch quite _reliably_ (< 100 iterations) with 1.1.99, 1.1.1, 1.0.0, and 0.64.1 (the only change with meson <1.1.1 is that it doesn't throw the "Event loop is closed" exception, but it still fails due to a timeout).

```
$ podman run -it --rm archlinux:latest
# pacman --needed --noconfirm -Sy base base-devel bpf btrfs-progs acl audit bash-completion clang compiler-rt docbook-xsl ethtool gdm git gnu-efi-libs gperf intltool iptables kexec-tools kmod libbpf libcap libelf libfido2 libgcrypt libidn2 libmicrohttpd libpwquality libseccomp libutil-linux libxkbcommon libxslt linux-api-headers llvm llvm-libs lvm2 lz4 meson multipath-tools ninja p11-kit pam pcre2 python-jinja python-lxml qrencode quota-tools rust tpm2-pkcs11 xz
# git clone https://github.com/systemd/systemd --depth=1
# cd systemd
# meson build-san -Db_sanitize=address,undefined
# i=0; while meson test -C build-san test-async; do echo $((i++)); done
...
60
ninja: no work to do.
ninja: Entering directory `/root/systemd/build-san'
[1/8] Generating version.h with a custom command
1/1 systemd:test / test-async        OK               1.03s

Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /root/systemd/build-san/meson-logs/testlog.txt
61
ninja: no work to do.
ninja: Entering directory `/root/systemd/build-san'
[1/8] Generating version.h with a custom command
1/1 systemd:test / test-async        TIMEOUT        120.01s
>>> PATH=/root/systemd/build-san:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PROJECT_BUILD_ROOT=/root/systemd/build-san SYSTEMD_LANGUAGE_FALLBACK_MAP=/root/systemd/src/locale/language-fallback-map MALLOC_PERTURB_=167 LD_LIBRARY_PATH=/root/systemd/build-san/src/shared /root/systemd/build-san/test-async


Ok:                 0   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            1   

Full log written to /root/systemd/build-san/meson-logs/testlog.txt
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f5593824720>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 558, in close
    self._close(None)
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 582, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

And it does seem to be caused by the forked-off-and-not-waited-for `(sd-sync)` process:

```
# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   5272  4132 pts/0    Ss   12:13   0:00 /usr/bin/bash
root        4381  0.0  0.0 21474957932 20960 ?   S    12:24   0:00 (sd-sync)
root        5264  0.0  0.0 21474957932 21000 ?   S    12:29   0:00 (sd-sync)
root        5267  0.0  0.0   7696  2968 pts/0    R+   12:33   0:00 ps aux
```

(there are two of them, since I managed to reproduce it twice in that container so far).

Both of them are stuck in a futex() call:

```
# strace -p 4381
strace: Process 4381 attached
futex(0x640000001208, FUTEX_WAIT_PRIVATE, 0, NULL

# strace -p 5264
strace: Process 5264 attached
futex(0x640000001208, FUTEX_WAIT_PRIVATE, 0, NULL
```

and don't respond to SIGINT/SIGTERM, only SIGKILL. So I guess meson is innocent there, since it's waiting for all process in the process group to finish, which obviously doesn't happen.
```

**Comment by mrc0mmand** [comment]
Hah, a looking at one of the `(sd-sync)` processes closer, it looks like it's the same issue as in #27287:

```
# eu-stack -p 12149
PID 12149 - process
TID 12149:
#0  0x00007fad696fe90e __sanitizer::FutexWait(__sanitizer::atomic_uint32_t*, unsigned int)
#1  0x00007fad697018cb __sanitizer::Semaphore::Wait()
#2  0x00007fad6962da2e __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::GetFromAllocator(__sanitizer::AllocatorStats*, unsigned long, unsigned int*, unsigned long)
#3  0x00007fad6962db8f __sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::Refill(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::PerClass*, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >*, unsigned long)
#4  0x00007fad6962de69 __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Allocate(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >*, unsigned long, unsigned long)
#5  0x00007fad6962ab52 __asan::Allocator::QuarantineChunk(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) [clone .isra.0]
#6  0x00007fad696dfd82 __interceptor_free.part.0
#7  0x00007fad695c9a46 cap_free
#8  0x00007fad6829c675 cap_freep
#9  0x00007fad6829ca70 have_effective_cap
#10 0x00007fad68293c3a update_argv
#11 0x00007fad68294e1c rename_process
#12 0x00007fad68397ec8 safe_fork_full
#13 0x00007fad6829663d safe_fork
#14 0x00007fad682969f9 asynchronous_sync
#15 0x000055a343fc6596 test_test_async
#16 0x000055a343fc6329 run_test_table
#17 0x000055a343fc6826 main
#18 0x00007fad67239850
#19 0x00007fad6723990a __libc_start_main
#20 0x000055a343fc5255 _start
```
