### ISSUE TITLE
Build failure with DT_RELR (-Wl,-z,pack-relative-relocs)

### ISSUE THREAD

**Issue by thesamesam** [systemd/systemd#28520]
### systemd version the issue has been seen with

sys-apps/systemd-254_rc2

### Used distribution

Gentoo

### Linux kernel version used

6.4.6

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

Successful build.

### Unexpected behaviour you saw

Build failure when building `linuxx64.efi.stub` with `RuntimeError: Unknown section .relr.dyn, refusing.`.

### Steps to reproduce the problem

Build systemd with `LDFLAGS="-Wl,-z,pack-relative-relocs"` to use `DT_RELR`.

### Additional program output to the terminal or log subsystem illustrating the issue

Full build log: [build.log.gz](https://github.com/systemd/systemd/files/12167684/build.log.gz)

```sh
[661/2632] /var/tmp/portage/sys-apps/systemd-254_rc3/work/systemd-254-rc3/tools/elf2efi.py --version-major=254 --version-minor=0 --efi-major=1 --efi-minor=1 --subsystem=10 --minimum-sections=0 src/boot/efi/li
nuxx64.elf.stub src/boot/efi/linuxx64.efi.stub
FAILED: src/boot/efi/linuxx64.efi.stub
/var/tmp/portage/sys-apps/systemd-254_rc3/work/systemd-254-rc3/tools/elf2efi.py --version-major=254 --version-minor=0 --efi-major=1 --efi-minor=1 --subsystem=10 --minimum-sections=0 src/boot/efi/linuxx64.elf.
stub src/boot/efi/linuxx64.efi.stub
Traceback (most recent call last):
  File "/var/tmp/portage/sys-apps/systemd-254_rc3/work/systemd-254-rc3/tools/elf2efi.py", line 593, in <module>
    main()
  File "/var/tmp/portage/sys-apps/systemd-254_rc3/work/systemd-254-rc3/tools/elf2efi.py", line 589, in main
    elf2efi(parser.parse_args())
  File "/var/tmp/portage/sys-apps/systemd-254_rc3/work/systemd-254-rc3/tools/elf2efi.py", line 492, in elf2efi
    sections = copy_sections(elf, opt)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/sys-apps/systemd-254_rc3/work/systemd-254-rc3/tools/elf2efi.py", line 288, in copy_sections
    if not use_section(elf_s):
           ^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/sys-apps/systemd-254_rc3/work/systemd-254-rc3/tools/elf2efi.py", line 256, in use_section
    raise RuntimeError(f"Unknown section {elf_s.name}, refusing.")
RuntimeError: Unknown section .relr.dyn, refusing.
```

**Comment by bluca** [comment]
@medhefgo any idea about this flag?
