### ISSUE TITLE
test-bpf-lsm FAIL

### ISSUE THREAD

**Issue by iam-TJ** [systemd/systemd#28685]
### systemd version the issue has been seen with

master (commit 04bce24d4ef2dc1)

### Used distribution

Debian 12

### Linux kernel version used

6.5.0-rc4+debian+tj+

### CPU architectures issue was seen on

x86_64

### Component

tests

### Expected behaviour you didn't see

test would report `OK` or `SKIP`

### Unexpected behaviour you saw

```
 800/1205 systemd:core / test-bpf-lsm                                      FAIL             1.81s   killed by signal 6 SIGABRT
 ```

### Steps to reproduce the problem

Build using (latest) `mkosi`
```
mkosi --distribution=debian --release=bookworm --secure-boot=no
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
800/1205 systemd:core / test-bpf-lsm                                      FAIL             1.81s   killed by signal 6 SIGABRT
>>> PATH=/work/build:/work/build:/usr/bin:/usr/sbin LD_LIBRARY_PATH=/work/build/src/shared:/work/build/src/core PROJECT_BUILD_ROOT=/work/build MALLOC_PERTURB_=219 EFI_ADDO
N=/work/build/src/boot/efi/addonx64.efi.stub SYSTEMD_LANGUAGE_FALLBACK_MAP=/work/src/src/locale/language-fallback-map /work/build/test-bpf-lsm
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
Listing only the last 100 lines from a long log.
-.mount: Changed dead -> mounted
system.slice changed dead -> active
-.slice changed dead -> active
Invoking unit catchup() handlers…
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-fs-bpf.mount: Changed dead -> mounted
proc-irq.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-fs-pstore.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-kernel-tracing.mount: Changed dead -> mounted
proc-bus.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev-zero.mount: Changed dead -> mounted
work-dest.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-fs-fuse-connections.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-proc-irq.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-var-tmp.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-firmware-efi-efivars.mount: Changed dead -> mounted
dev-zero.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-proc-bus.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev-null.mount: Changed dead -> mounted
sys-kernel-debug.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev-tty.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-kernel-security.mount: Changed dead -> mounted
work-src-mkosi.output.mount: Changed dead -> mounted
work-out.mount: Changed dead -> mounted
dev-null.mount: Changed dead -> mounted
dev-tty.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev-pts.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root.mount: Changed dead -> mounted
sys-kernel-tracing.mount: Changed dead -> mounted
work-src.mount: Changed dead -> mounted
var-tmp-root.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-proc.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev-random.mount: Changed dead -> mounted
sys-kernel-debug-tracing.mount: Changed dead -> mounted
dev-urandom.mount: Changed dead -> mounted
sys-kernel-config.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-kernel-debug-tracing.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-proc-sysrq\x2dtrigger.mount: Changed dead -> mounted
dev-full.mount: Changed dead -> mounted
etc-machine\x2did.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-run.mount: Changed dead -> mounted
work-src-mkosi.cache-debian\x7ebookworm.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-tmp.mount: Changed dead -> mounted
dev-random.mount: Changed dead -> mounted
work-build\x2dscript.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-kernel-config.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-kernel-debug.mount: Changed dead -> mounted
work-build.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev.mount: Changed dead -> mounted
tmp.mount: Changed dead -> mounted
proc-sysrq\x2dtrigger.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev-urandom.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-etc-machine\x2did.mount: Changed dead -> mounted
work-src-mkosi.builddir-debian\x7ebookworm.mount: Changed dead -> mounted
var-tmp.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys-fs-cgroup.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-sys.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-var-tmp-root.mount: Changed dead -> mounted
sys-fs-fuse-connections.mount: Changed dead -> mounted
work-src-.mkosi\x2dtmp1w96w9xu-root-dev-full.mount: Changed dead -> mounted
restrict_filesystems_test.service: Will spawn child (service_enter_start): cat
restrict_filesystems_test.service: Failed to create cgroup /restrict_filesystems_test.service: Read-only file system
restrict_filesystems_test.service: Passing 0 fds to service
restrict_filesystems_test.service: About to execute: cat /sys/kernel/tracing/printk_formats
restrict_filesystems_test.service: Forked cat as 12335
restrict_filesystems_test.service: Changed dead -> start
restrict_filesystems_test.service: Failed to attach to cgroup /restrict_filesystems_test.service: No such file or directory
restrict_filesystems_test.service: Failed at step CGROUP spawning cat: No such file or directory
Received SIGCHLD from PID 12335 ((cat)).
Child 12335 ((cat)) died (code=exited, status=219/CGROUP)
restrict_filesystems_test.service: Child 12335 belongs to restrict_filesystems_test.service.
restrict_filesystems_test.service: Main process exited, code=exited, status=219/CGROUP
restrict_filesystems_test.service: Failed with result 'exit-code'.
restrict_filesystems_test.service: Service will not restart (restart setting)
restrict_filesystems_test.service: Changed start -> failed
restrict_filesystems_test.service: bpf-lsm: Failed to delete cgroup entry from LSM BPF map: No such file or directory
Failed to trim cgroup /restrict_filesystems_test.service: Read-only file system
restrict_filesystems_test.service: Failed to destroy cgroup /restrict_filesystems_test.service, ignoring: Read-only file system
restrict_filesystems_test.service: Unit entered failed state.
Service is not dead
restrict_filesystems_test.service: Will spawn child (service_enter_start): cat
restrict_filesystems_test.service: Failed to create cgroup /restrict_filesystems_test.service: Read-only file system
restrict_filesystems_test.service: Passing 0 fds to service
restrict_filesystems_test.service: About to execute: cat /sys/kernel/tracing/printk_formats
restrict_filesystems_test.service: Forked cat as 12336
restrict_filesystems_test.service: Changed dead -> start
restrict_filesystems_test.service: Failed to attach to cgroup /restrict_filesystems_test.service: No such file or directory
restrict_filesystems_test.service: Failed at step CGROUP spawning cat: No such file or directory
Received SIGCHLD from PID 12336 ((cat)).
Child 12336 ((cat)) died (code=exited, status=219/CGROUP)
restrict_filesystems_test.service: Child 12336 belongs to restrict_filesystems_test.service.
restrict_filesystems_test.service: Main process exited, code=exited, status=219/CGROUP
restrict_filesystems_test.service: Failed with result 'exit-code'.
restrict_filesystems_test.service: Service will not restart (restart setting)
restrict_filesystems_test.service: Changed start -> failed
restrict_filesystems_test.service: bpf-lsm: Failed to delete cgroup entry from LSM BPF map: No such file or directory
Failed to trim cgroup /restrict_filesystems_test.service: Read-only file system
restrict_filesystems_test.service: Failed to destroy cgroup /restrict_filesystems_test.service, ignoring: Read-only file system
restrict_filesystems_test.service: Unit entered failed state.
Service is not dead
Assertion 'test_restrict_filesystems(m, "restrict_filesystems_test.service", "/sys/kernel/tracing/printk_formats", STRV_MAKE("tracefs", "@common-block")) >= 0' failed at s
rc/test/test-bpf-lsm.c:95, function main(). Aborting.

Python/mkosi debug logging was on and shows:

‣ "/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.presets/00-base/mkosi.build" returned non-zero exit code 1.
‣ + umount --no-mtab /srv/NAS/Sunny/SourceCode/systemd/systemd/.mkosi-tmp1w96w9xu/root
‣    (Cleaning up overlayfs)
‣     (Removing overlay whiteout files…)
Traceback (most recent call last):
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 19, in propagate_failed_return
    yield
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 49, in main
    run_verb(args, presets)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2211, in run_verb
    build_image(args, config)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 1799, in build_image
    run_build_script(state)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 292, in run_build_script
    bwrap(
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 311, in bwrap
    raise e
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 305, in bwrap
    result = run([*cmdline, *cmd], env=env, log=False, stdin=stdin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 212, in run
    raise e
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 193, in run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwrap', '--dev-bind', '/', '/', '--remount-ro', '/', '--ro-bind', '/root', '/root', '--ro-bind', '/home', '/home', '--ro-bind', '/var', '/var', '--ro-bind', '/run', '/run', '--bind', '/var/tmp', '/var/tmp', '--bind', '/srv/NAS/Sunny/SourceCode/systemd/systemd', '/srv/NAS/Sunny/SourceCode/systemd/sys
temd', '--chdir', '/srv/NAS/Sunny/SourceCode/systemd/systemd', '--unshare-pid', '--unshare-ipc', '--unshare-cgroup', '--die-with-parent', '--proc', '/proc', '--dev', '/dev
', '--ro-bind', '/sys', '/sys', '--tmpfs', '/tmp', '--bind', '/srv/NAS/Sunny/SourceCode/systemd/systemd', '/srv/NAS/Sunny/SourceCode/systemd/systemd', '--bind', '/srv/NAS/
Sunny/SourceCode/systemd/systemd/mkosi.cache/debian~bookworm', '/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.cache/debian~bookworm', '--bind', '/srv/NAS/Sunny/SourceCod
e/systemd/systemd/mkosi.output', '/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.output', '--bind', '/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.builddir/debian~bookworm', '/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.builddir/debian~bookworm', '--setenv', 'PATH', '/srv/NAS/Sunny/SourceCode/systemd/systemd/.mkosi-tmp1w96w9xu/mkosi-s
cripts6900y75y:/tmp/mkosi.pathrjmh0le6:/srv/NAS/Sunny/SourceCode/systemd/systemd/build:/usr/my/sbin:/usr/my/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bi
n', 'sh', '-c', 'chmod 1777 /tmp /dev/shm && exec $0 "$@"', '/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.presets/00-base/mkosi.build']' returned non-zero exit status 1
.
```

**Comment by mrc0mmand** [comment]
This is something I've seen in CentOS CI as well, i.e. https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-cron-build/154/artifact//systemd-centos-ci/artifacts_all/artifacts_jlnsklq7/vagrant-logs.97d/vagrant-arch-coverage-testsuite.JL0/ninja-test_FAIL.log

**Comment by iam-TJ** [comment]
I forgot to add that this was reported in issue #22287 some time ago

**Comment by chenglongtang1** [comment]
+1 I am having the exact same problems in ubuntu, debian and fedora.

**Comment by iam-TJ** [comment]
I can't even build it now! With `mkosi --distribution=debian --release=bookworm --secure-boot=no`  it ignores the command-line and reports:
```
‣ UEFI SecureBoot enabled, but couldn't find the certificate and private key. 
```
The churn in `mkosi` behaviour, adding/removing/changing functionality without warning or documentation drives me crazy!

**Comment by DaanDeMeyer** [comment]
@iam-TJ #29140 will fix that problem

**Comment by iam-TJ** [comment]
@DaanDeMeyer  Thanks - that is EXACTLY what I did already

**Comment by DaanDeMeyer** [comment]
@iam-TJ systemd in bookworm is too old, we need systemd-repart and ukify from v254 to build disk images. Try with --tools-tree=default from the latest mkosi release, it'll download a debian testing image and use that to build the other images.

**Comment by iam-TJ** [comment]
@DaanDeMeyer  Does that mean latest systemd cannot be built for use with Bookworm (as opposed to built ON Bookworm)? That would be a problem since I was doing it to dig into an apparent bug in `systemd-resolved` and need to test mainline systemd to be sure it still occurs.

**Comment by iam-TJ** [comment]
Well - it gets past the reason for this bug report:
```
809/1231 systemd:core / test-bpf-lsm                                 SKIP             0.04s   exit status 77
```
  but is hitting other `systemd-repart` related failures now:
```
‣  Running finalize script…
‣ + bwrap --dev-bind / / --remount-ro / --ro-bind /root /root --ro-bind /home /home --ro-bind /var /var --ro-bind /run /run --bind /var/tmp /var/tmp --tmpfs /tmp --bind /
srv/NAS/Sunny/SourceCode/systemd/systemd /srv/NAS/Sunny/SourceCode/systemd/systemd --chdir /srv/NAS/Sunny/SourceCode/systemd/systemd --unshare-pid --unshare-ipc --unshare
-cgroup --unshare-net --die-with-parent --proc /proc --dev /dev --ro-bind /sys /sys --setenv SYSTEMD_OFFLINE 0 --setenv PATH /srv/NAS/Sunny/SourceCode/systemd/systemd/.mk
osi-tmpxgf9lh_w/mkosi-scriptsg0ygaamy:/usr/bin:/usr/sbin --bind /srv/NAS/Sunny/SourceCode/systemd/systemd /srv/NAS/Sunny/SourceCode/systemd/systemd --bind '/srv/NAS/Sunny
/SourceCode/systemd/systemd/mkosi.builddir/debian~bookworm' '/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.builddir/debian~bookworm' --bind '/srv/NAS/Sunny/SourceCode/s
ystemd/systemd/mkosi.cache/debian~bookworm' '/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.cache/debian~bookworm' --bind /srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi
.output /srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.output sh -c 'chmod 1777 /tmp /dev/shm && exec $0 "$@"' /srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.presets/sy
stem/mkosi.finalize
‣ + grep --recursive '--include=*.conf' Subvolumes= /srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.presets/system/mkosi.repart
‣  Generating disk image
‣ + systemd-repart --empty=allow --size=auto --dry-run=no --json=pretty --no-pager --offline=yes --root /srv/NAS/Sunny/SourceCode/systemd/systemd/.mkosi-tmpxgf9lh_w/root 
--seed random /srv/NAS/Sunny/SourceCode/systemd/systemd/.mkosi-tmpxgf9lh_w/staging/system.raw --empty=create --defer-partitions esp,xbootldr --definitions /srv/NAS/Sunny/
SourceCode/systemd/systemd/mkosi.presets/system/mkosi.repart
/srv/NAS/Sunny/SourceCode/systemd/systemd/mkosi.presets/system/mkosi.repart/12-usr-verity-sig.conf:1: Verity signature partition requested but no private key provided (--
private-key=)
‣ "systemd-repart --empty=allow --size=auto --dry-run=no --json=pretty --no-pager --offline=yes --root /srv/NAS/Sunny/SourceCode/systemd/systemd/.mkosi-tmpxgf9lh_w/root -
-seed random /srv/NAS/Sunny/SourceCode/systemd/systemd/.mkosi-tmpxgf9lh_w/staging/system.raw --empty=create --defer-partitions esp,xbootldr --definitions /srv/NAS/Sunny/S
ourceCode/systemd/systemd/mkosi.presets/system/mkosi.repart" returned non-zero exit code 1.
```
Should I open a new bug report for this?

**Comment by DaanDeMeyer** [comment]
No this is expected, systemd's config builds with verity partitions and those need a private key. You can just run mkosi genkey in the systemd repository and then you don't need to disable secure boot btw

**Comment by chenglongtang1** [comment]
Now running mkosi shows Unkown setting Presets in the latest changes:
```
$ meson setup build -Danalyze=true -Drepart=true -Defi=true -Dbootloader=true -Dukify=true
$ ninja -C build
$ mkosi
‣ Unknown setting Presets
```

**Comment by iam-TJ** [comment]
> Now running mkosi shows Unkown setting Presets in the latest changes:
> 
> ```
> $ meson setup build -Danalyze=true -Drepart=true -Defi=true -Dbootloader=true -Dukify=true
> $ ninja -C build
> $ mkosi
> ‣ Unknown setting Presets
> ```

Are you using latest `mkosi`?

**Comment by chenglongtang1** [comment]
Hi, yeah the mkosi version is the root cause. I updated it and now it works. But the test-bpf-lsm issue still exists.
```
restrict_filesystems_test.service: Child 2767 belongs to restrict_filesystems_test.service.
restrict_filesystems_test.service: Main process exited, code=exited, status=219/CGROUP
restrict_filesystems_test.service: Failed with result 'exit-code'.
restrict_filesystems_test.service: Service will not restart (restart setting)
restrict_filesystems_test.service: Changed start -> failed
restrict_filesystems_test.service: bpf-lsm: Failed to delete cgroup entry from LSM BPF map: No such file or directory
Failed to trim cgroup /restrict_filesystems_test.service: Read-only file system
restrict_filesystems_test.service: Failed to destroy cgroup /restrict_filesystems_test.service, ignoring: Read-only file system
restrict_filesystems_test.service: Unit entered failed state.
Service is not dead
restrict_filesystems_test.service: Will spawn child (service_enter_start): cat
restrict_filesystems_test.service: Failed to create cgroup /restrict_filesystems_test.service: Read-only file system
restrict_filesystems_test.service: Passing 0 fds to service
restrict_filesystems_test.service: About to execute: cat /sys/kernel/tracing/printk_formats
restrict_filesystems_test.service: Forked cat as 2768
restrict_filesystems_test.service: Changed dead -> start
restrict_filesystems_test.service: Failed to attach to cgroup /restrict_filesystems_test.service: No such file or directory
restrict_filesystems_test.service: Failed at step CGROUP spawning cat: No such file or directory
Received SIGCHLD from PID 2768 ((cat)).
Child 2768 ((cat)) died (code=exited, status=219/CGROUP)
restrict_filesystems_test.service: Child 2768 belongs to restrict_filesystems_test.service.
restrict_filesystems_test.service: Main process exited, code=exited, status=219/CGROUP
restrict_filesystems_test.service: Failed with result 'exit-code'.
restrict_filesystems_test.service: Service will not restart (restart setting)
restrict_filesystems_test.service: Changed start -> failed
restrict_filesystems_test.service: bpf-lsm: Failed to delete cgroup entry from LSM BPF map: No such file or directory
Failed to trim cgroup /restrict_filesystems_test.service: Read-only file system
restrict_filesystems_test.service: Failed to destroy cgroup /restrict_filesystems_test.service, ignoring: Read-only file system
restrict_filesystems_test.service: Unit entered failed state.
Service is not dead
Assertion 'test_restrict_filesystems(m, "restrict_filesystems_test.service", "/sys/kernel/tracing/printk_formats", STRV_MAKE("tracefs", "@common-block")) >= 0' failed at src/test/test-bpf-lsm.c:95, function main(). Aborting.
```

**Comment by DaanDeMeyer** [comment]
@chenglongtang1 Can you run again with https://github.com/systemd/systemd/pull/35557? That should give us a better error message.
