### ISSUE TITLE
There is a memory leak in sd-radv caused by PREF64

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#28985]
```sh
=================================================================
==42675==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 63872 byte(s) in 998 object(s) allocated from:
    #0 0x7f2fd78d92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: e5f0a0d511a659fbc47bf41072869139cb2db47f)
    #1 0x7e15bb in malloc_multiply ../src/basic/alloc-util.h:120
    #2 0x7fb204 in sd_radv_pref64_prefix_new ../src/libsystemd-network/sd-radv.c:1068
    #3 0x4709b9 in radv_set_pref64_prefix ../src/network/networkd-radv.c:361
    #4 0x475215 in radv_configure ../src/network/networkd-radv.c:588
    #5 0x476829 in radv_process_request ../src/network/networkd-radv.c:691
    #6 0x468d60 in manager_process_requests ../src/network/networkd-queue.c:223
    #7 0x7f2fd6785fa0 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4223
    #8 0x7f2fd678ecf2 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
    #9 0x7f2fd678fe29 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
    #10 0x7f2fd67901b0 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
    #11 0x4137df in run ../src/network/networkd.c:112
    #12 0x413a3f in main ../src/network/networkd.c:119
    #13 0x7f2fd5249b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #14 0x7f2fd5249c0a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #15 0x411754 in _start (/home/vagrant/systemd/build/systemd-networkd+0x411754) (BuildId: 32d76e70f1208bdc2ad24b82cf6b8e2450fac193)
SUMMARY: AddressSanitizer: 63872 byte(s) leaked in 998 allocation(s).
run-rb57aa2fb7ec349a7a432b06ea860864c.service: Main process exited, code=exited, status=1/FAILURE
```
It was introduced in https://github.com/systemd/systemd/pull/28565 as far as I can see

**Comment by ssahani** [comment]
I have added a fix . https://github.com/systemd/systemd/pull/28992
