### ISSUE TITLE
Build error: ValueError: failed to process man/busctl.xml

### ISSUE THREAD

**Issue by bluecmd** [systemd/systemd#2904]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229 tagged rev

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Custom

Please note that there are patches applied to allow building in the custom environment that I am unable to remove. After reading through the diff I don't see anything obvious that would impact the build process. Full diff is available on https://gist.github.com/bluecmd/787fbd181b32c77cdc16.
### In case of bug report: Expected behaviour you didn't see

> Make builds everything without error
### In case of bug report: Unexpected behaviour you saw

> Make fails on man/systemd.directives.xml:

```
| ValueError: failed to process /home/bluecmd/openswitch/ops-build/build/tmp/work/core2-64-openswitch-linux/systemd/1_229+gitAUTOINC+714c62b463-r0_openswitch/git/man/busctl.xml
```

Modifying make-directive-index.py to emit the real exception:

```
diff --git a/tools/make-directive-index.py b/tools/make-directive-index.py
index 8091683..b371834 100755
--- a/tools/make-directive-index.py
+++ b/tools/make-directive-index.py
@@ -313,7 +313,7 @@ def make_page(*xml_files):
         try:
             _extract_directives(directive_groups, formatting, page)
         except Exception:
-            raise ValueError("failed to process " + page)
+            raise

     return _make_page(template, directive_groups, formatting)

```

Output:

```
..
Traceback (most recent call last):
  File "/home/bluecmd/openswitch/ops-build/build/tmp/work/core2-64-openswitch-linux/systemd/1_229+gitAUTOINC+714c62b463-r0_openswitch/git/tools/make-directive-index.py", line 322, in <module>
    f.write(xml_print(make_page(*sys.argv[2:])))
  File "/home/bluecmd/openswitch/ops-build/build/tmp/work/core2-64-openswitch-linux/systemd/1_229+gitAUTOINC+714c62b463-r0_openswitch/git/tools/make-directive-index.py", line 314, in make_page
    _extract_directives(directive_groups, formatting, page)
  File "/home/bluecmd/openswitch/ops-build/build/tmp/work/core2-64-openswitch-linux/systemd/1_229+gitAUTOINC+714c62b463-r0_openswitch/git/tools/make-directive-index.py", line 191, in _extract_directives
    t = xml_parse(page)
  File "/home/bluecmd/openswitch/ops-build/build/tmp/work/core2-64-openswitch-linux/systemd/1_229+gitAUTOINC+714c62b463-r0_openswitch/git/tools/xml_helper.py", line 31, in xml_parse
    doc.xinclude()
  File "src/lxml/lxml.etree.pyx", line 2342, in lxml.etree._ElementTree.xinclude (src/lxml/lxml.etree.c:71345)
  File "src/lxml/xinclude.pxi", line 61, in lxml.etree.XInclude.__call__ (src/lxml/lxml.etree.c:160123)
lxml.etree.XIncludeError: Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
Makefile:21803: recipe for target 'man/systemd.directives.xml' failed
make[3]: *** [man/systemd.directives.xml] Error 1
make[3]: *** Deleting file 'man/systemd.directives.xml'
make[3]: *** Waiting for unfinished jobs....
```
### In case of bug report: Steps to reproduce the problem

```
./configure && make
```

As for the details: Not sure. This is inside a Yocto build environment.
Seems like this might be a problem with too old libxml2 shipping without some used XML entities. Alternatively, tuning lxml to allow fetching (or ignoring) entities might be required.

**Comment by keszybz** [comment]
You need to install the necessary docbook files. In Fedora this is the `docbook-dtds` package.
