### ISSUE TITLE
Intermittent DNS name resolution failure, likely IPv6-related

### ISSUE THREAD

**Issue by schams-net** [systemd/systemd#29069]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-10-cloud-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

DNS look-ups with a constant 100% success rate for IPv4 and IPv6 addresses.

### Unexpected behaviour you saw

Intermittent DNS name resolution failures with a success rate of approx. 90% (approx. 10 errors out of 100 queries), likely IPv6-related.

Official Debian v12 AMIs on AWS show intermittent DNS name resolution failures when they perform DNS look-ups of an RDS Aurora endpoint. The instances use the Amazon-provided DNS server (VPC.2). While approx. 90 percent of the DNS queries succeed, 10 percent fail (name or service not known).

The issue occurs on Debian v12 but doesn't occur on Debian v11 or Amazon Linux 2 systems (same environment). No error occurs if the "systemd-resolved" service is disabled or bypassed on Debian v12. No error occurs if IPv6 is disabled on the Debian v12 system.

### Steps to reproduce the problem

Please find a detailed problem description including analysis, steps how to reproduce the problem, and a Terraform plan to provision a test infrastructure in the following Git repository: <https://github.com/schams-net/aws-ec2-rds-dns-lookup-issue>

**Comment by wjsc** [comment]
Hi! Any update on this issue? any new workaround?

**Comment by jackarias** [comment]
Hello! Same problem here. It would be nice to have a workaround on this asap.

**Comment by schams-net** [comment]
As documented [here](https://github.com/schams-net/aws-ec2-rds-dns-lookup-issue/blob/main/docs/disable-systemd-resolved.md), the workaround across our server fleet is a small change to the file `/etc/nsswitch.conf`. Locate this line:
```
hosts: files resolve [!UNAVAIL=return] dns
```
...and remove the "resolve" service. After the change, the line reads:
```
hosts: files dns
```
Note that this is not the final solution but only a workaround.

**Comment by levinse** [comment]
We are experiencing this since upgrading to Debian 12 AMIs

**Comment by ahmgithubahm** [comment]
We're affected by this, using Debian 12 AWS EC2 AMIs.  As well as agreeing that it is somehow IPv6 related, it also seems to only cause resolution failures for CNAMEs.  At least in my testing with A and CNAME lookups, only CNAMEs exhibit the intermittent failures.

Our workaround has been to simply purge the systemd-resolved package entirely, which has the effect of sorting out nsswitch on its way out of the door.

`apt purge --auto-remove systemd-resolved`

Thanks to @schams-net for the detailed repro details.  I shamelessly grabbed the bash fragment [1] to easily reproduce the issue.  Using the script to resolve a CNAME produced intermittent failures.  Pointing it at an A record gave no failures.  Telling netcat to use IPv4 (nc -4) also meant no failures, for A or CNAME lookups.

[1] https://github.com/schams-net/aws-ec2-rds-dns-lookup-issue/blob/main/docs/how-to-reproduce-the-issue.md

**Comment by nmeyerhans** [comment]
@ahmgithubahm You don't need to remove all of systemd-resolved. Just removing libnss-resolve will accomplish what you need without disabling resolv.conf management altogether.  Debian 12.6 images, when they're published, will make this the default.

**Comment by ahmgithubahm** [comment]
Thanks @nmeyerhans, that's good to know.  I've edited my post now I realise that my workaround leaves you with no working /etc/resolv.conf after a reboot.  Oops. 🤡

**Comment by nmeyerhans** [comment]
@schams-net @ahmgithubahm @jackarias @levinse @wjsc Be aware that the Debian 12 cloud images just released (version 20240415-1718) no longer enable `libnss-resolve` by default.  So this issue should be mitigated in instances launched from these and future images.

If somebody who has encountered this issue on Debian 12 would be able to test the Debian `sid` images, that would help the systemd maintainers understand if the issue is still present.

**Comment by kuzminets** [comment]
Thanks @nmeyerhans! Is the problem somehow specific to AWS? I can't reproduce it from a local VM with `libnss-resolve` being enabled.

**Comment by nmeyerhans** [comment]
I don't see any reason to think it'd be specific to AWS, but it's possible. As the problem is intermittent, it could be that something about the AWS DNS infrastructure triggers it more frequently, but that's just speculation.

**Comment by schams-net** [comment]
I can confirm that I'm unable reproduce the issue with the latest AMIs at AWS anymore 🥳  
I tested `debian-12-amd64-20240429-1732` (for example AMI ID `ami-02175b0058d3ce245` in us-east-1). The file `/etc/nsswitch.conf` contains the following configuration in the old vs. new image.

Previously (with "resolve"):
```
hosts: files resolve [!UNAVAIL=return] dns
```

New(er) images (without "resolve"):
```
hosts: files dns myhostname
```

(As @nmeyerhans pointed out).

I haven't had the chance to test the Debian sid images yet.

**Comment by Pentium4User** [comment]
This issue still seems to affect Debian 13 and is only happening when using libnss_resolve.

**Comment by gbe** [comment]
Hi there, I also face the issue when using `libnss_resolve`.

### Description

`systemd-resolved` successfully resolves AAAA records, but hostname resolution through the NSS resolve module fails for IPv6-only domains.

My client host has IPv6 connectivity through NAT66 and only has ULA addresses configured locally.

The same lookup succeeds when using the `dns` NSS module instead of `resolve`.

### Environment
Distribution: Fedora 44
glibc: 2.43
systemd-resolved enabled
IPv6 connectivity provided through NAT66
Host has no global IPv6 address assigned locally
Host only has:
ULA address (fd00::/8)
link-local address (fe80::/10)

I do not have any `/etc/gai.conf` file.

### NSS configuration

Default configuration in `/etc/nsswitch.conf`:

```
hosts: files myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
```

### Reproduction steps

Use an IPv6-only public hostname: `thiswebsiteisipv6only.com`

The AAAA record is correctly returned:

```shell
$ dig +short AAAA thiswebsiteisipv6only.com
2a0d:f302:146:a596::1
```

`systemd-resolved` also returns the AAAA record:

```shell
$ resolvectl query -t AAAA thiswebsiteisipv6only.com

thiswebsiteisipv6only.com IN AAAA 2a0d:f302:146:a596::1
```

However, NSS resolution fails:

```shell
$ getent ahosts thiswebsiteisipv6only.com

(no output)
```

Applications using `getaddrinfo()` fail as well:

```shell
$ curl https://thiswebsiteisipv6only.com/
curl: (6) Could not resolve host: thiswebsiteisipv6only.com
```

The same request succeeds when forcing IPv6:

```shell
$ curl -6 https://thiswebsiteisipv6only.com/

[...]
```

### Additional tests

IPv6-only lookup through NSS succeeds:

```shell
$ getent ahostsv6 thiswebsiteisipv6only.com

2a0d:f302:146:a596::1 STREAM thiswebsiteisipv6only.com
2a0d:f302:146:a596::1 DGRAM
2a0d:f302:146:a596::1 RAW
```

Using Python:
```shell
strace -f -e trace=network,getrandom,recvfrom,sendto python3 -c 'import socket; socket.getaddrinfo("thiswebsiteisipv6only.com",443)'

getrandom("\x1a\xc4\x7f\x47\x20\x1a\x12\xcf", 8, GRND_NONBLOCK) = 8
getrandom("\x57\x1d\xe2\xa1\x2f\xd3\x4b\xdf\xa8\x73\xe2\xe3\x27\xcb\x97\x54\x5f\xfb\x00\x62\xa5\xc0\x29\x5b\x8c\xe9\xdc\x1d\x6b\x04\x2d\x25", 32, GRND_NONBLOCK) = 32
getrandom("\xd2\xb3\x03\x4f\xc4\x81\x6f\x04\x85\x99\x8f\x02\x27\xfe\x15\xc9\xdd\xeb\x64\x37\x39\xb9\x2d\xd1\xc4\x39\x9b\xa7\xf5\x1e\x4d\x39", 32, 0) = 32
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/run/systemd/resolve/io.systemd.Resolve"}, 42) = 0
sendto(3, "{\"method\":\"io.systemd.Resolve.Re"..., 108, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 108
recvfrom(3, 0x55fbbd1ef3c0, 131080, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(3, "{\"error\":\"io.systemd.Resolve.NoS"..., 131080, MSG_DONTWAIT, NULL, NULL) = 52
socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 3
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [8388608], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_SNDBUFFORCE, [8388608], 4) = -1 EPERM (Operation not permitted)
sendmsg(3, {msg_name={sa_family=AF_UNIX, sun_path="/run/systemd/journal/socket"}, msg_namelen=30, msg_iov=[{iov_base="MESSAGE=detected unhandled Pytho"..., iov_len=81}, {iov_base="\n", iov_len=1}, {iov_base="CODE_FILE=/usr/lib/python3.14/si"..., iov_len=70}, {iov_base="\n", iov_len=1}, {iov_base="CODE_LINE=33", iov_len=12}, {iov_base="\n", iov_len=1}, {iov_base="CODE_FUNC=syslog", iov_len=16}, {iov_base="\n", iov_len=1}, {iov_base="SYSLOG_IDENTIFIER=", iov_len=18}, {iov_base="python3", iov_len=7}, {iov_base="\n", iov_len=1}], msg_iovlen=11, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 209
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import socket; socket.getaddrinfo("thiswebsiteisipv6only.com",443)
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/socket.py", line 987, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] No address associated with hostname
+++ exited with 1 +++
```

returns `socket.gaierror: [Errno -5] No address associated with hostname`.

Tracing shows that `glibc` uses the `systemd-resolved` NSS module:

```
connect(3, {sa_family=AF_UNIX, sun_path="/run/systemd/resolve/io.systemd.Resolve"}, ...)
```

and receives: `io.systemd.Resolve.NoSuchRR`

### Workaround

I changed `/etc/nsswitch.conf` from:

```
hosts: files myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
```

to:

```
hosts: files myhostname mdns4_minimal [NOTFOUND=return] resolve dns
```

After a `sudo systemctl restart systemd-resolved`, it made the lookup work and the website could be reached with `curl` without forcing IPv6:

```shell
$ getent ahosts thiswebsiteisipv6only.com

2a0d:f302:146:a596::1 STREAM thiswebsiteisipv6only.com
2a0d:f302:146:a596::1 DGRAM
2a0d:f302:146:a596::1 RAW

$ curl https://thiswebsiteisipv6only.com/
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>This Site Is IPv6-Only</title>
[...]
```
