### ISSUE TITLE
There is a memory leak in networkd caused by router advertisements with PREF64s

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#29062]
```sh
=================================================================
==210==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 267480 byte(s) in 743 object(s) allocated from:
    #0 0x7f35338d92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: e5f0a0d511a659fbc47bf41072869139cb2db47f)
    #1 0x7f35320e18fd in malloc_multiply ../src/basic/alloc-util.h:120
    #2 0x7f35320e94eb in json_variant_new_object ../src/shared/json.c:714
    #3 0x7f353210876d in json_buildv ../src/shared/json.c:3877
    #4 0x7f353210cadf in json_build ../src/shared/json.c:4262
    #5 0x641828 in pref64_append_json ../src/network/networkd-json.c:936
    #6 0x64548d in link_build_json ../src/network/networkd-json.c:1176
    #7 0x645db4 in links_append_json ../src/network/networkd-json.c:1224
    #8 0x6460ea in manager_build_json ../src/network/networkd-json.c:1243
    #9 0x415cb1 in bus_method_describe ../src/network/networkd-manager-bus.c:233
    #10 0x7f35325575e4 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #11 0x7f3532560f25 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1319
    #12 0x7f35325625d4 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1439
    #13 0x7f35325c433e in process_message ../src/libsystemd/sd-bus/sd-bus.c:3007
    #14 0x7f35325c48c8 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3049
    #15 0x7f35325c771e in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3269
    #16 0x7f35325c78bb in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3296
    #17 0x7f35325cb029 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3638
    #18 0x7f3532794547 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4187
    #19 0x7f353279dcd8 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
    #20 0x7f353279ee0f in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
    #21 0x7f353279f196 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
    #22 0x41385f in run ../src/network/networkd.c:112
    #23 0x413abf in main ../src/network/networkd.c:119
    #24 0x7f3531249b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #25 0x7f3531249c0a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #26 0x4117d4 in _start (/usr/lib/systemd/systemd-networkd+0x4117d4) (BuildId: 7b6bd6e6a7fd1ad75a92fe7bca412793f2883880)
Indirect leak of 1010480 byte(s) in 1486 object(s) allocated from:
    #0 0x7f35338d92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: e5f0a0d511a659fbc47bf41072869139cb2db47f)
    #1 0x7f35320e18fd in malloc_multiply ../src/basic/alloc-util.h:120
    #2 0x7f35320e77f4 in json_variant_new_array_bytes ../src/shared/json.c:616
    #3 0x7f353210ac05 in json_buildv ../src/shared/json.c:4120
    #4 0x7f353210cadf in json_build ../src/shared/json.c:4262
    #5 0x641828 in pref64_append_json ../src/network/networkd-json.c:936
    #6 0x64548d in link_build_json ../src/network/networkd-json.c:1176
    #7 0x645db4 in links_append_json ../src/network/networkd-json.c:1224
    #8 0x6460ea in manager_build_json ../src/network/networkd-json.c:1243
    #9 0x415cb1 in bus_method_describe ../src/network/networkd-manager-bus.c:233
    #10 0x7f35325575e4 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #11 0x7f3532560f25 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1319
    #12 0x7f35325625d4 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1439
    #13 0x7f35325c433e in process_message ../src/libsystemd/sd-bus/sd-bus.c:3007
    #14 0x7f35325c48c8 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3049
    #15 0x7f35325c771e in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3269
    #16 0x7f35325c78bb in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3296
    #17 0x7f35325cb029 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3638
    #18 0x7f3532794547 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4187
    #19 0x7f353279dcd8 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
    #20 0x7f353279ee0f in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
    #21 0x7f353279f196 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
    #22 0x41385f in run ../src/network/networkd.c:112
    #23 0x413abf in main ../src/network/networkd.c:119
    #24 0x7f3531249b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #25 0x7f3531249c0a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #26 0x4117d4 in _start (/usr/lib/systemd/systemd-networkd+0x4117d4) (BuildId: 7b6bd6e6a7fd1ad75a92fe7bca412793f2883880)
Indirect leak of 34921 byte(s) in 743 object(s) allocated from:
    #0 0x7f35338d8cc7 in calloc (/lib64/libasan.so.8+0xd8cc7) (BuildId: e5f0a0d511a659fbc47bf41072869139cb2db47f)
    #1 0x7f35320e3ce4 in json_variant_new ../src/shared/json.c:291
    #2 0x7f35320e4c97 in json_variant_new_stringn ../src/shared/json.c:412
    #3 0x7f35320e298d in json_variant_new_string ../src/shared/json.h:81
    #4 0x7f353210abd0 in json_buildv ../src/shared/json.c:4116
    #5 0x7f353210cadf in json_build ../src/shared/json.c:4262
    #6 0x641828 in pref64_append_json ../src/network/networkd-json.c:936
    #7 0x64548d in link_build_json ../src/network/networkd-json.c:1176
    #8 0x645db4 in links_append_json ../src/network/networkd-json.c:1224
    #9 0x6460ea in manager_build_json ../src/network/networkd-json.c:1243
    #10 0x415cb1 in bus_method_describe ../src/network/networkd-manager-bus.c:233
    #11 0x7f35325575e4 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #12 0x7f3532560f25 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1319
    #13 0x7f35325625d4 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1439
    #14 0x7f35325c433e in process_message ../src/libsystemd/sd-bus/sd-bus.c:3007
    #15 0x7f35325c48c8 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3049
    #16 0x7f35325c771e in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3269
    #17 0x7f35325c78bb in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3296
    #18 0x7f35325cb029 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3638
    #19 0x7f3532794547 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4187
    #20 0x7f353279dcd8 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
    #21 0x7f353279ee0f in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
    #22 0x7f353279f196 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
    #23 0x41385f in run ../src/network/networkd.c:112
    #24 0x413abf in main ../src/network/networkd.c:119
    #25 0x7f3531249b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #26 0x7f3531249c0a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #27 0x4117d4 in _start (/usr/lib/systemd/systemd-networkd+0x4117d4) (BuildId: 7b6bd6e6a7fd1ad75a92fe7bca412793f2883880)
Indirect leak of 33435 byte(s) in 743 object(s) allocated from:
    #0 0x7f35338d8cc7 in calloc (/lib64/libasan.so.8+0xd8cc7) (BuildId: e5f0a0d511a659fbc47bf41072869139cb2db47f)
    #1 0x7f35320e3ce4 in json_variant_new ../src/shared/json.c:291
    #2 0x7f35320e4c97 in json_variant_new_stringn ../src/shared/json.c:412
    #3 0x7f35320e298d in json_variant_new_string ../src/shared/json.h:81
    #4 0x7f3532109749 in json_buildv ../src/shared/json.c:3979
    #5 0x7f353210cadf in json_build ../src/shared/json.c:4262
    #6 0x641828 in pref64_append_json ../src/network/networkd-json.c:936
    #7 0x64548d in link_build_json ../src/network/networkd-json.c:1176
    #8 0x645db4 in links_append_json ../src/network/networkd-json.c:1224
    #9 0x6460ea in manager_build_json ../src/network/networkd-json.c:1243
    #10 0x415cb1 in bus_method_describe ../src/network/networkd-manager-bus.c:233
    #11 0x7f35325575e4 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #12 0x7f3532560f25 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1319
    #13 0x7f35325625d4 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1439
    #14 0x7f35325c433e in process_message ../src/libsystemd/sd-bus/sd-bus.c:3007
    #15 0x7f35325c48c8 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3049
    #16 0x7f35325c771e in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3269
    #17 0x7f35325c78bb in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3296
    #18 0x7f35325cb029 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3638
    #19 0x7f3532794547 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4187
    #20 0x7f353279dcd8 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
    #21 0x7f353279ee0f in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
    #22 0x7f353279f196 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
    #23 0x41385f in run ../src/network/networkd.c:112
    #24 0x413abf in main ../src/network/networkd.c:119
    #25 0x7f3531249b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #26 0x7f3531249c0a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #27 0x4117d4 in _start (/usr/lib/systemd/systemd-networkd+0x4117d4) (BuildId: 7b6bd6e6a7fd1ad75a92fe7bca412793f2883880)
Indirect leak of 33435 byte(s) in 743 object(s) allocated from:
    #0 0x7f35338d8cc7 in calloc (/lib64/libasan.so.8+0xd8cc7) (BuildId: e5f0a0d511a659fbc47bf41072869139cb2db47f)
    #1 0x7f35320e3ce4 in json_variant_new ../src/shared/json.c:291
    #2 0x7f35320e4c97 in json_variant_new_stringn ../src/shared/json.c:412
    #3 0x7f35320e298d in json_variant_new_string ../src/shared/json.h:81
    #4 0x7f3532108a0d in json_buildv ../src/shared/json.c:3900
    #5 0x7f353210cadf in json_build ../src/shared/json.c:4262
    #6 0x641828 in pref64_append_json ../src/network/networkd-json.c:936
    #7 0x64548d in link_build_json ../src/network/networkd-json.c:1176
    #8 0x645db4 in links_append_json ../src/network/networkd-json.c:1224
    #9 0x6460ea in manager_build_json ../src/network/networkd-json.c:1243
    #10 0x415cb1 in bus_method_describe ../src/network/networkd-manager-bus.c:233
    #11 0x7f35325575e4 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #12 0x7f3532560f25 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1319
    #13 0x7f35325625d4 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1439
    #14 0x7f35325c433e in process_message ../src/libsystemd/sd-bus/sd-bus.c:3007
    #15 0x7f35325c48c8 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3049
    #16 0x7f35325c771e in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3269
    #17 0x7f35325c78bb in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3296
    #18 0x7f35325cb029 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3638
    #19 0x7f3532794547 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:4187
    #20 0x7f353279dcd8 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4808
    #21 0x7f353279ee0f in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4869
    #22 0x7f353279f196 in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:4891
    #23 0x41385f in run ../src/network/networkd.c:112
    #24 0x413abf in main ../src/network/networkd.c:119
    #25 0x7f3531249b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #26 0x7f3531249c0a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #27 0x4117d4 in _start (/usr/lib/systemd/systemd-networkd+0x4117d4) (BuildId: 7b6bd6e6a7fd1ad75a92fe7bca412793f2883880)
SUMMARY: AddressSanitizer: 1379751 byte(s) leaked in 4458 allocation(s).
```

**Comment by ssahani** [comment]
@evverx could you try with https://github.com/systemd/systemd/pull/29064
