### ISSUE TITLE
Systemd-journal-remote crash observed

### ISSUE THREAD

**Issue by Sribharath27** [systemd/systemd#29164]
### systemd version the issue has been seen with

250

### Linux kernel version used

Linux 5.15.71-yocto-standard #1 SMP Fri Mar 9 12:34:56 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

### CPU architectures issue was seen on

aarch64

### Component

journalctl

### Expected behaviour you didn't see

Not seen systemd journal remote crash in an earlier release systemd version. 

### Unexpected behaviour you saw

systemd journal remote crash - segmentation fault

Core was generated by `/lib/systemd/systemd-journal-remote --listen-http=19532 --output=/run/log/journ'.
Program terminated with signal SIGSEGV, Segmentation fault.

### Steps to reproduce the problem

During soak runs multiple systemd-journal-remote core files observed

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Back trace:

(gdb) bt
#0  0x0000000000406d88 in writer_write (w=0x43dbd0, iovw=iovw@entry=0x442160, ts=ts@entry=0x442178, boot_id=boot_id@entry=0x442188, compress=compress@entry=true,
    seal=seal@entry=false) at ../git/src/journal-remote/journal-remote-write.c:71
#1  0x000000000040698c in process_source (source=0x442120, source@entry=0x442160, compress=true, seal=false) at ../git/src/journal-remote/journal-remote-parse.c:71
#2  0x0000000000403c74 in process_http_upload (source=0x442160, upload_data_size=<optimized out>, upload_data=<optimized out>, connection=0x442410)
    at ../git/src/journal-remote/journal-remote-main.c:226
#3  request_handler (cls=<optimized out>, connection=0x442410, url=<optimized out>, method=<optimized out>, version=<optimized out>, upload_data=<optimized out>,
    upload_data_size=<optimized out>, connection_cls=<optimized out>) at ../git/src/journal-remote/journal-remote-main.c:285
#4  0x0000ffff82783f2c in process_request_body (connection=0x0) at ../../../libmicrohttpd-0.9.66/src/microhttpd/connection.c:2790
#5  MHD_connection_handle_idle (connection=0x0, connection@entry=0x442410) at ../../../libmicrohttpd-0.9.66/src/microhttpd/connection.c:3765
#6  0x0000ffff827852f0 in call_handlers (con=con@entry=0x442410, read_ready=<optimized out>, write_ready=true, force_close=<optimized out>)
    at ../../../libmicrohttpd-0.9.66/src/microhttpd/daemon.c:1206
#7  0x0000ffff827897e4 in MHD_epoll (daemon=0x43d220, may_block=<optimized out>, may_block@entry=0) at ../../../libmicrohttpd-0.9.66/src/microhttpd/daemon.c:4536
#8  0x0000ffff8278a894 in MHD_run (daemon=0x43d220) at ../../../libmicrohttpd-0.9.66/src/microhttpd/daemon.c:4622
#9  0x00000000004039cc in dispatch_http_event (event=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x43b860)
    at ../git/src/journal-remote/journal-remote-main.c:541
#10 0x0000ffff82994760 in ?? () from mm/rootfs/lib/systemd/libsystemd-shared-250.so
#11 0x0000ffff82994d68 in sd_event_dispatch () from mm/rootfs/lib/systemd/libsystemd-shared-250.so
#12 0x0000ffff8299548c in sd_event_run () from mm/rootfs/lib/systemd/libsystemd-shared-250.so
#13 0x0000000000405bc8 in run (argc=<optimized out>, argv=<optimized out>) at ../git/src/journal-remote/journal-remote-main.c:1160
#14 0x00000000004035e8 in main (argc=<optimized out>, argv=<optimized out>) at ../git/src/journal-remote/journal-remote-main.c:1175
```

**Comment by poettering** [comment]
please provide a full backtrae with debug symbols, otherwise not actionable for us.

**Comment by poettering** [comment]
also 250 is too old to be tracked here. please reproduce with a current version.
