### ISSUE TITLE
Build failure on CentOS Stream 8 (Hyperscale SIG)

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#29406]
### systemd version the issue has been seen with

main

### Used distribution

CentOS Stream 8

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

Build succeeds

### Unexpected behaviour you saw

```
[647/2689] /builddir/build/BUILD/systemd-hs-254.999/tools/elf2efi.py --version-major=254 --version-minor=0 --efi-major=1 --efi-minor=1 --subsystem=10 --minimum-sections=15 --copy-sections=.sbat,.sdmagic,.osrel src/boot/efi/addonx64.elf.stub src/boot/efi/addonx64.efi.stub
FAILED: src/boot/efi/addonx64.efi.stub 
/builddir/build/BUILD/systemd-hs-254.999/tools/elf2efi.py --version-major=254 --version-minor=0 --efi-major=1 --efi-minor=1 --subsystem=10 --minimum-sections=15 --copy-sections=.sbat,.sdmagic,.osrel src/boot/efi/addonx64.elf.stub src/boot/efi/addonx64.efi.stub
Traceback (most recent call last):
  File "/builddir/build/BUILD/systemd-hs-254.999/tools/elf2efi.py", line 699, in <module>
    main()
  File "/builddir/build/BUILD/systemd-hs-254.999/tools/elf2efi.py", line 695, in main
    elf2efi(parser.parse_args())
  File "/builddir/build/BUILD/systemd-hs-254.999/tools/elf2efi.py", line 601, in elf2efi
    copy_sections(elf, opt, args.copy_sections, sections)
  File "/builddir/build/BUILD/systemd-hs-254.999/tools/elf2efi.py", line 365, in copy_sections
    pe_s.VirtualAddress = next_section_address(sections)
  File "/builddir/build/BUILD/systemd-hs-254.999/tools/elf2efi.py", line 250, in next_section_address
    sections[-1].VirtualAddress + sections[-1].VirtualSize, SECTION_ALIGNMENT
IndexError: list index out of range
```

**Comment by medhefgo** [comment]
This is another episode in the horror movie series: "The Linker LTOed My Entry Point"

Here's a reproducer: `cc -xc <(echo "int _start(void) { return 0; }") -o/tmp/bug -O1 -flto -fvisibility=hidden -nostdlib; readelf -WS /tmp/bug | grep .text`. If it reports a .text section you're not affected.

You can either not build with LTO, remove the `-fvisibility=hidden` or switch to a newer toolchain (gcc-toolset-9 seems to have fixed this).

This actually only worked by accident with the previous linker script based build. The addon only contains the `.sdmagic` section and a 0 entry point address, yay.

**Comment by poettering** [comment]
Let's close this as this appears to be a problem with a too old toolchain.
