### ISSUE TITLE
Possible double free in sd-executor

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#29610]
### systemd version the issue has been seen with

latest main

### Used distribution

Arch Linux

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

As discussed on telegram, There seems to be a double free somewhere in the sd-executor stuff. So far I haven't been able to pinpoint the root cause, even with a fuzzer (coming soon™), but maybe the details I collected along the way might help someone else.

Symptoms:
```
[   29.636267] testsuite-50.sh[1378]: + systemd-run -P -p 'MountImages=/tmp/tmp.bYyFnz/minimal_0.gpt:/run/img1:root:nosuid /tmp/tmp.bYyFnz/minimal_0.raw:/run/img2:home:suid' mount
[   29.638279] testsuite-50.sh[1379]: + grep -F squashfs
[   29.639333] testsuite-50.sh[1380]: + grep -q -F nosuid
[   29.752142] kernel:  loop3: p1 p2 p3
[   30.201651] systemd[1]: Started run-u20.service.
[   30.302963] kernel: device-mapper: verity: sha256 using implementation "sha256-generic"
[   30.302985] kernel: device-mapper: table: 254:1: verity: Root hash verification failed (-ENOKEY)
[   30.302987] kernel: device-mapper: ioctl: error adding target to table
[   30.305903] kernel: device-mapper: verity: sha256 using implementation "sha256-generic"
[   30.234974] (mount)[1381]: device-mapper: reload ioctl on 4ff873d154e92e1aff1b60fb4c485fa01999d38f5ddd8865b6740e39899b703e-verity (254:1) failed: Required key not available
[   30.257940] (mount)[1381]: Device 4ff873d154e92e1aff1b60fb4c485fa01999d38f5ddd8865b6740e39899b703e-verity already exists.
[   30.258340] (mount)[1381]: Device 4ff873d154e92e1aff1b60fb4c485fa01999d38f5ddd8865b6740e39899b703e-verity already exists.
[   30.261802] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.262562] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.265124] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.267365] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.269459] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.269983] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.271411] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.272038] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.272893] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.273823] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.275578] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.276199] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.278027] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.278535] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.280247] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.281039] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.281629] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.282317] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.283317] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.284124] (mount)[1381]: Cannot use device /dev/loop3p1 which is in use (already mapped or mounted).
[   30.500838] testsuite-50.sh[1381]: free(): double free detected in tcache 2
[   30.503825] (mount)[1381]: run-u20.service: Failed to set up mount namespacing: /run/img1: Device or resource busy
[   30.518319] systemd[1]: Created slice system-systemd\x2dcoredump.slice.
[   30.541578] systemd[1]: Started systemd-coredump@0-1397-0.service.
[   30.792697] systemd-coredump[1398]: [🡕] Process 1381 ((mount)) of user 0 dumped core.
                                       
                                       Stack trace of thread 1381:
                                       #0  0x00007fcb60aac83c n/a (libc.so.6 + 0x8e83c)
                                       #1  0x00007fcb60a5c668 raise (libc.so.6 + 0x3e668)
                                       #2  0x00007fcb60a444b8 abort (libc.so.6 + 0x264b8)
                                       #3  0x00007fcb60a45390 n/a (libc.so.6 + 0x27390)
                                       #4  0x00007fcb60ab67b7 n/a (libc.so.6 + 0x987b7)
                                       #5  0x00007fcb60ab8c59 n/a (libc.so.6 + 0x9ac59)
                                       #6  0x00007fcb60abb353 free (libc.so.6 + 0x9d353)
                                       #7  0x00007fcb60ce4bca mount_options_free_all (libsystemd-shared-254.so + 0xe4bca)
                                       #8  0x00007fcb6110b4ce mount_image_free_many (libsystemd-core-254.so + 0x10b4ce)
                                       #9  0x00007fcb610b8368 exec_context_done (libsystemd-core-254.so + 0xb8368)
                                       #10 0x000055e3bd63ad8a main (systemd-executor + 0x7d8a)
                                       #11 0x00007fcb60a45cd0 n/a (libc.so.6 + 0x27cd0)
                                       #12 0x00007fcb60a45d8a __libc_start_main (libc.so.6 + 0x27d8a)
                                       #13 0x000055e3bd63a255 _start (systemd-executor + 0x7255)
                                       ELF object binary architecture: AMD x86-64
[   30.811627] systemd[1]: run-u20.service: Main process exited, code=dumped, status=6/ABRT
[   30.870464] systemd[1]: run-u20.service: Failed with result 'core-dump'.
```
<details>
<summary>Full stack trace</summary>

```gdb
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fcb60aac83c in ?? () from /usr/lib/libc.so.6
(gdb) (gdb) #0  0x00007fcb60aac83c in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007fcb60a5c668 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007fcb60a444b8 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007fcb60a45390 in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x00007fcb60ab67b7 in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#5  0x00007fcb60ab8c59 in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#6  0x00007fcb60abb353 in free () from /usr/lib/libc.so.6
No symbol table info available.
#7  0x00007fcb60ce4bca in mount_options_free_all (options=0x0) at ../build/src/shared/dissect-image.c:3783
        m = 0x55e3bd69e7b0
#8  0x00007fcb6110b4ce in mount_image_free_many (m=0x55e3bd69e970, n=n@entry=0x7ffc5595f8c8) at ../build/src/core/namespace.c:2590
        i = 0
        __func__ = "mount_image_free_many"
#9  0x00007fcb610b8368 in exec_context_done (c=c@entry=0x7ffc5595f650) at ../build/src/core/execute.c:542
        __func__ = "exec_context_done"
#10 0x000055e3bd63ad8a in main (argc=<optimized out>, argv=<optimized out>) at ../build/src/core/executor.c:179
        fdset = 0x0
        exit_status = 226
        r = <optimized out>
        cgroup_context = {
          cpu_accounting = true,
          io_accounting = false,
          blockio_accounting = false,
          memory_accounting = true,
          tasks_accounting = true,
          ip_accounting = false,
          memory_oom_group = false,
          delegate = false,
          delegate_controllers = 0,
          disable_controllers = 0,
          delegate_subgroup = 0x0,
          cpu_weight = 18446744073709551615,
          startup_cpu_weight = 18446744073709551615,
          cpu_quota_per_sec_usec = 18446744073709551615,
          cpu_quota_period_usec = 18446744073709551615,
          cpuset_cpus = {
            set = 0x0,
            allocated = 0
          },
          startup_cpuset_cpus = {
            set = 0x0,
            allocated = 0
          },
          cpuset_mems = {
            set = 0x0,
            allocated = 0
          },
          startup_cpuset_mems = {
            set = 0x0,
            allocated = 0
          },
          io_weight = 18446744073709551615,
          startup_io_weight = 18446744073709551615,
          io_device_weights = 0x0,
          io_device_limits = 0x0,
          io_device_latencies = 0x0,
          default_memory_min = 0,
          default_memory_low = 0,
          default_startup_memory_low = 0,
          memory_min = 0,
          memory_low = 0,
          startup_memory_low = 0,
          memory_high = 18446744073709551615,
          startup_memory_high = 18446744073709551615,
          memory_max = 18446744073709551615,
          startup_memory_max = 18446744073709551615,
          memory_swap_max = 18446744073709551615,
          startup_memory_swap_max = 18446744073709551615,
          memory_zswap_max = 18446744073709551615,
          startup_memory_zswap_max = 18446744073709551615,
          default_memory_min_set = false,
          default_memory_low_set = false,
          default_startup_memory_low_set = false,
          memory_min_set = false,
          memory_low_set = false,
          startup_memory_low_set = false,
          startup_memory_high_set = false,
          startup_memory_max_set = false,
          startup_memory_swap_max_set = false,
          startup_memory_zswap_max_set = false,
          ip_address_allow = 0x0,
          ip_address_deny = 0x0,
          ip_address_allow_reduced = true,
          ip_address_deny_reduced = true,
          ip_filters_ingress = 0x0,
          ip_filters_egress = 0x0,
          bpf_foreign_programs = 0x0,
          restrict_network_interfaces = 0x0,
          restrict_network_interfaces_is_allow_list = false,
          cpu_shares = 18446744073709551615,
          startup_cpu_shares = 18446744073709551615,
          blockio_weight = 18446744073709551615,
          startup_blockio_weight = 18446744073709551615,
          blockio_device_weights = 0x0,
          blockio_device_bandwidths = 0x0,
          memory_limit = 18446744073709551615,
          device_policy = CGROUP_DEVICE_POLICY_AUTO,
          device_allow = 0x0,
          socket_bind_allow = 0x0,
          socket_bind_deny = 0x0,
          tasks_max = {
            value = 15,
            scale = 100
          },
          moom_swap = MANAGED_OOM_AUTO,
          moom_mem_pressure = MANAGED_OOM_AUTO,
          moom_mem_pressure_limit = 0,
          moom_preference = MANAGED_OOM_PREFERENCE_NONE,
          memory_pressure_watch = CGROUP_PRESSURE_WATCH_AUTO,
          memory_pressure_threshold_usec = 200000,
          nft_set_context = {
            sets = 0x0,
            n_sets = 0
          },
          coredump_receive = false
        }
        context = {
          environment = 0x0,
          environment_files = 0x0,
          pass_environment = 0x0,
          unset_environment = 0x0,
          rlimit = {0x0 <repeats 16 times>},
          working_directory = 0x0,
          root_directory = 0x0,
          root_image = 0x0,
          root_verity = 0x0,
          root_hash_path = 0x0,
          root_hash_sig_path = 0x0,
          root_hash = 0x0,
          root_hash_sig = 0x0,
          root_hash_size = 0,
          root_hash_sig_size = 0,
          root_image_options = 0x0,
          root_ephemeral = false,
          working_directory_missing_ok = false,
          working_directory_home = false,
          oom_score_adjust_set = false,
          coredump_filter_set = false,
          nice_set = false,
          missing_ioprio_set = false,
          cpu_sched_set = false,
          mount_apivfs_set = false,
          same_pgrp = false,
          cpu_sched_reset_on_fork = false,
          non_blocking = false,
          umask = 18,
          oom_score_adjust = 0,
          nice = 0,
          ioprio = 16388,
          cpu_sched_policy = 0,
          cpu_sched_priority = 0,
          coredump_filter = 0,
          cpu_set = {
            set = 0x0,
            allocated = 0
          },
          numa_policy = {
            type = -1,
            nodes = {
              set = 0x0,
              allocated = 0
            }
          },
          cpu_affinity_from_numa = false,
          std_input = EXEC_INPUT_NULL,
          std_output = EXEC_OUTPUT_JOURNAL,
          std_error = EXEC_OUTPUT_INHERIT,
          stdio_as_fds = true,
          stdio_fdname = {0x0, 0x0, 0x0},
          stdio_file = {0x0, 0x0, 0x0},
          stdin_data = 0x0,
          stdin_data_size = 0,
          timer_slack_nsec = 18446744073709551615,
          tty_path = 0x0,
          tty_reset = false,
          tty_vhangup = false,
          tty_vt_disallocate = false,
          tty_rows = 4294967295,
          tty_cols = 4294967295,
          ignore_sigpipe = true,
          keyring_mode = EXEC_KEYRING_PRIVATE,
          user = 0x0,
          group = 0x0,
          supplementary_groups = 0x0,
          set_login_environment = -1,
          pam_name = 0x0,
          utmp_id = 0x0,
          utmp_mode = EXEC_UTMP_INIT,
          no_new_privileges = false,
          selinux_context_ignore = false,
          apparmor_profile_ignore = false,
          smack_process_label_ignore = false,
          selinux_context = 0x0,
          apparmor_profile = 0x0,
          smack_process_label = 0x0,
          read_write_paths = 0x0,
          read_only_paths = 0x0,
          inaccessible_paths = 0x0,
          exec_paths = 0x0,
          no_exec_paths = 0x0,
          exec_search_path = 0x0,
          mount_propagation_flag = 0,
          bind_mounts = 0x0,
          n_bind_mounts = 0,
          temporary_filesystems = 0x0,
          n_temporary_filesystems = 0,
          mount_images = 0x55e3bd69e970,
          n_mount_images = 2,
          extension_images = 0x0,
          n_extension_images = 0,
          extension_directories = 0x0,
          capability_bounding_set = 18446744073709551615,
          capability_ambient_set = 0,
          secure_bits = 0,
          syslog_priority = 30,
          syslog_level_prefix = true,
          syslog_identifier = 0x0,
          log_extra_fields = 0x0,
          n_log_extra_fields = 0,
          log_filter_allowed_patterns = 0x0,
          log_filter_denied_patterns = 0x0,
          log_ratelimit_interval_usec = 0,
          log_ratelimit_burst = 0,
          log_level_max = -1,
          log_namespace = 0x0,
          protect_proc = PROTECT_PROC_DEFAULT,
          proc_subset = PROC_SUBSET_ALL,
          private_mounts = -1,
          memory_ksm = -1,
          private_tmp = false,
          private_network = false,
          private_devices = false,
          private_users = false,
          private_ipc = false,
          protect_kernel_tunables = false,
          protect_kernel_modules = false,
          protect_kernel_logs = false,
          protect_clock = false,
          protect_control_groups = false,
          protect_system = PROTECT_SYSTEM_NO,
          protect_home = PROTECT_HOME_NO,
          protect_hostname = false,
          mount_apivfs = false,
          dynamic_user = false,
          remove_ipc = false,
          memory_deny_write_execute = false,
          restrict_realtime = false,
          restrict_suid_sgid = false,
          lock_personality = false,
          personality = 4294967295,
          restrict_namespaces = 18446744073709551615,
          restrict_filesystems = 0x0,
          restrict_filesystems_allow_list = false,
          syscall_filter = 0x0,
          syscall_archs = 0x0,
          syscall_errno = 2147483646,
          syscall_allow_list = false,
          syscall_log = 0x0,
          syscall_log_allow_list = false,
          address_families_allow_list = false,
          address_families = 0x0,
          network_namespace_path = 0x0,
          ipc_namespace_path = 0x0,
          directories = {{
              mode = 493,
              n_items = 0,
              items = 0x0
            }, {
              mode = 493,
              n_items = 0,
              items = 0x0
            }, {
              mode = 493,
              n_items = 0,
              items = 0x0
            }, {
              mode = 493,
              n_items = 0,
              items = 0x0
            }, {
              mode = 493,
              n_items = 0,
              items = 0x0
            }},
          runtime_directory_preserve_mode = EXEC_PRESERVE_NO,
          timeout_clean_usec = 18446744073709551615,
          set_credentials = 0x0,
          load_credentials = 0x0,
          import_credentials = 0x0,
          root_image_policy = 0x0,
          mount_image_policy = 0x0,
          extension_image_policy = 0x0
        }
        command = {
          path = 0x0,
          argv = 0x0,
          exec_status = {
            start_timestamp = {
              realtime = 0,
              monotonic = 0
            },
            exit_timestamp = {
              realtime = 0,
              monotonic = 0
            },
            pid = 0,
            code = 0,
            status = 0
          },
          flags = 0,
          command_next = 0x0,
          command_prev = 0x0
        }
        params = {
          runtime_scope = RUNTIME_SCOPE_SYSTEM,
          environment = 0x0,
          fds = 0x0,
          fd_names = 0x0,
          n_socket_fds = 0,
          n_storage_fds = 0,
          flags = (EXEC_APPLY_SANDBOXING | EXEC_APPLY_CHROOT | EXEC_APPLY_TTY_STDIN | EXEC_PASS_LOG_UNIT | EXEC_CHOWN_DIRECTORIES | EXEC_WRITE_CREDENTIALS | EXEC_PASS_FDS | EXEC_SET_WATCHDOG | EXEC_SETENV_MONITOR_RESULT),
          selinux_context_net = false,
          cgroup_supported = 8109,
          cgroup_path = 0x0,
          cgroup_id = 2861,
          prefix = 0x0,
          received_credentials_directory = 0x0,
          received_encrypted_credentials_directory = 0x0,
          confirm_spawn = 0x0,
          shall_confirm_spawn = false,
          watchdog_usec = 0,
          idle_pipe = 0x0,
          stdin_fd = -9,
          stdout_fd = -9,
          stderr_fd = -9,
          exec_fd = -9,
          notify_socket = 0x0,
          open_files = 0x0,
          fallback_smack_process_label = 0x0,
          files_env = 0x0,
          user_lookup_fd = -9,
          bpf_outer_map_fd = -9,
          unit_id = 0x0,
          invocation_id = {
            bytes = '\000' <repeats 15 times>,
            qwords = {0, 0}
          },
          invocation_id_string = "\000c4cfbbb2ba64502aaf700a211d67a27"
        }
        shared = {
          n_ref = 0,
          manager = 0x0,
          id = 0x0,
          tmp_dir = 0x0,
          var_tmp_dir = 0x0,
          netns_storage_socket = {-9, -9},
          ipcns_storage_socket = {-9, -9}
        }
        dynamic_creds = {
          user = 0x0,
          group = 0x0
        }
        runtime = {
          shared = 0x7ffc5595f510,
          dynamic_creds = 0x7ffc5595f280,
          ephemeral_copy = 0x0,
          ephemeral_storage_socket = {-9, -9}
        }
        __func__ = "main"
```
</details>

It looks like there's indeed something going really wrong on with the `mount_images` stuff:
```gdb
(gdb) p c->mount_images[0]
$1 = {
  source = 0x55e3bd69e760 "\276&R\343\346U",
  destination = 0x55e3bd69e790 "\2160R\343\346U",
  mount_options = 0x55e3bd69e7b0,
  ignore_enoent = false,
  type = MOUNT_IMAGE_DISCRETE
}
(gdb) p c->mount_images[1]
$2 = {
  source = 0x55e3bd69e8d0 "/tmp/tmp.bYyFnz/minimal_0.raw",
  destination = 0x55e3bd69e900 "/run/img2",
  mount_options = 0x55e3bd69e920,
  ignore_enoent = false,
  type = MOUNT_IMAGE_DISCRETE
}
...
(gdb) p *c->mount_images[0].mount_options
$5 = {
  partition_designator = -481153554,
  options = 0x55e3bd69e7e0 "\256\222U\343\346U",
  mount_options_next = 0x0,
  mount_options_prev = 0x0
}
(gdb) p *c->mount_images[1].mount_options
$6 = {
  partition_designator = -481152706,
  options = 0x55e3bd69e950 "n7R\343\346U",
  mount_options_next = 0x0,
  mount_options_prev = 0x0
}
```

/cc @bluca

**Comment by mrc0mmand** [comment]
Forgot to mention - I can finally reproduce this quite reliably even on my Fedora machine, using this state of art reproducer:

```diff
diff --git a/test/units/testsuite-50.sh b/test/units/testsuite-50.sh
index 4142e1ebbc..30432c13ef 100755
--- a/test/units/testsuite-50.sh
+++ b/test/units/testsuite-50.sh
@@ -316,15 +316,20 @@ grep -F "squashfs" "${image_dir}/result/b" | grep -q -F "noatime"
 busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/testservice_2d50b_2eservice org.freedesktop.systemd1.Service RootImageOptions | grep -F "nosuid,dev,%foo"
 
 # Now do some checks with MountImages, both by itself, with options and in combination with RootImage, and as single FS or GPT image
-systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img1/usr/lib/os-release | grep -q -F "MARKER=1"
-systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img2/usr/lib/os-release | grep -q -F "MARKER=1"
-systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2:nosuid,dev" mount | grep -F "squashfs" | grep -q -F "nosuid"
-systemd-run -P -p MountImages="${image}.gpt:/run/img1:root:nosuid ${image}.raw:/run/img2:home:suid" mount | grep -F "squashfs" | grep -q -F "nosuid"
-systemd-run -P -p MountImages="${image}.raw:/run/img2\:3" cat /run/img2:3/usr/lib/os-release | grep -q -F "MARKER=1"
-systemd-run -P -p MountImages="${image}.raw:/run/img2\:3:nosuid" mount | grep -F "squashfs" | grep -q -F "nosuid"
-systemd-run -P -p TemporaryFileSystem=/run -p RootImage="${image}.raw" -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /usr/lib/os-release | grep -q -F "MARKER=1"
-systemd-run -P -p TemporaryFileSystem=/run -p RootImage="${image}.raw" -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img1/usr/lib/os-release | grep -q -F "MARKER=1"
-systemd-run -P -p TemporaryFileSystem=/run -p RootImage="${image}.gpt" -p RootHash="${roothash}" -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img2/usr/lib/os-release | grep -q -F "MARKER=1"
+while :; do
+       set +e
+       systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img1/usr/lib/os-release | grep -q -F "MARKER=1"
+       systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img2/usr/lib/os-release | grep -q -F "MARKER=1"
+       systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2:nosuid,dev" mount | grep -F "squashfs" | grep -q -F "nosuid"
+       systemd-run -P -p MountImages="${image}.gpt:/run/img1:root:nosuid ${image}.raw:/run/img2:home:suid" mount | grep -F "squashfs" | grep -q -F "nosuid"
+       systemd-run -P -p MountImages="${image}.raw:/run/img2\:3" cat /run/img2:3/usr/lib/os-release | grep -q -F "MARKER=1"
+       systemd-run -P -p MountImages="${image}.raw:/run/img2\:3:nosuid" mount | grep -F "squashfs" | grep -q -F "nosuid"
+       systemd-run -P -p TemporaryFileSystem=/run -p RootImage="${image}.raw" -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /usr/lib/os-release | grep -q -F "MARKER=1"
+       systemd-run -P -p TemporaryFileSystem=/run -p RootImage="${image}.raw" -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img1/usr/lib/os-release | grep -q -F "MARKER=1"
+       systemd-run -P -p TemporaryFileSystem=/run -p RootImage="${image}.gpt" -p RootHash="${roothash}" -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img2/usr/lib/os-release | grep -q -F "MARKER=1"
+       journalctl --sync
+       if journalctl -b --grep "double free"; then exit 1; fi
+done
 cat >/run/systemd/system/testservice-50c.service <<EOF
 [Service]
 MountAPIVFS=yes
```

```
$ make -C test/TEST-50-DISSECT clean setup run BUILD_DIR=$PWD/build
...
[   18.206347] testsuite-50.sh[1170]: Bus n/a: changing state RUNNING → CLOSED
[   18.207464] testsuite-50.sh[648]: + journalctl --sync
[   18.223049] testsuite-50.sh[648]: + journalctl -b --grep 'double free'
[   18.920929] testsuite-50.sh[1194]: -- Journal begins at Wed 2023-10-18 23:21:46 CEST, ends at Wed 2023-10-18 23:22:03 CEST. --
[   18.921933] testsuite-50.sh[1194]: Oct 18 23:22:01 H testsuite-50.sh[1066]: free(): double free detected in tcache 2
[   18.922652] testsuite-50.sh[1194]: Oct 18 23:22:03 H testsuite-50.sh[648]: + journalctl -b --grep 'double free'
[   18.923115] testsuite-50.sh[648]: + exit 1
[   18.923519] testsuite-50.sh[648]: + cleanup
[   18.924206] testsuite-50.sh[1195]: + set +ex
[   18.928486] testsuite-50.sh[1196]: umount: /tmp/tmp.Qf6WmN/app0: no mount point specified.
[   18.931788] testsuite-50.sh[1197]: umount: /tmp/tmp.Qf6WmN/app1: no mount point specified.
[   18.934710] testsuite-50.sh[1198]: umount: /tmp/tmp.Qf6WmN/app-nodistro: no mount point specified.
[   18.936356] testsuite-50.sh[1199]: umount: /tmp/tmp.Qf6WmN/service-scoped-test: no mount point specified.
[   19.497426] reboot: Power down
Spawning getter /home/mrc0mmand/repos/@systemd/systemd/build/journalctl -o export -D /var/tmp/systemd-tests/systemd-test.Ffoisx/root/var/log/journal/2489e470aa8d40d48a2880c97ca762d9...
Finishing after writing 43732 entries
Spawning getter /home/mrc0mmand/repos/@systemd/systemd/build/journalctl -o export -D /var/tmp/systemd-tests/systemd-test.Ffoisx/root/var/log/journal/remote...
Finishing after writing 0 entries
TEST-50-DISSECT: (failed; see logs)
-rw-r----- 1 root root 41943040 Oct 18 23:22 /var/tmp/systemd-tests/systemd-test.Ffoisx/system.journal
qemu test failed
make: *** [Makefile:4: run] Error 1
make: Leaving directory '/home/mrc0mmand/repos/@systemd/systemd/test/TEST-50-DISSECT'
```

**Comment by mrc0mmand** [comment]
```diff
diff --git a/test/units/testsuite-50.sh b/test/units/testsuite-50.sh
index 4142e1ebbc..3710107342 100755
--- a/test/units/testsuite-50.sh
+++ b/test/units/testsuite-50.sh
@@ -316,6 +316,22 @@ grep -F "squashfs" "${image_dir}/result/b" | grep -q -F "noatime"
 busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/testservice_2d50b_2eservice org.freedesktop.systemd1.Service RootImageOptions | grep -F "nosuid,dev,%foo"
 
 # Now do some checks with MountImages, both by itself, with options and in combination with RootImage, and as single FS or GPT image
+systemctl log-level info
+i=0
+while :; do
+    set +e
+
+    systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img1/usr/lib/os-release | grep -q -F "MARKER=1"
+    systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img2/usr/lib/os-release | grep -q -F "MARKER=1"
+    systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2:nosuid,dev" mount | grep -F "squashfs" | grep -q -F "nosuid"
+    systemd-run -P -p MountImages="${image}.gpt:/run/img1:root:nosuid ${image}.raw:/run/img2:home:suid" mount | grep -F "squashfs" | grep -q -F "nosuid"
+    systemd-run -P -p MountImages="${image}.raw:/run/img2\:3:nosuid" mount | grep -F "squashfs" | grep -q -F "nosuid"
+    if ((i++ % 10 == 0)); then
+        journalctl --sync
+        journalctl -b --grep "[d]ouble free" && exit 1
+    fi
+done
+
 systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img1/usr/lib/os-release | grep -q -F "MARKER=1"
 systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2" cat /run/img2/usr/lib/os-release | grep -q -F "MARKER=1"
 systemd-run -P -p MountImages="${image}.gpt:/run/img1 ${image}.raw:/run/img2:nosuid,dev" mount | grep -F "squashfs" | grep -q -F "nosuid"
```

may be a slightly better version. Also, I take back `quite reliably` and replace it with `somewhat` reliably, as it seems to be very... temperamental, and it might take a couple of minutes in some cases.

**Comment by bluca** [comment]
Thanks I can reproduce it too with that snippet, looking

**Comment by bluca** [comment]
When starting fails and sd-executor exits instead of execvp, then there's the exec-context cleanup, which is where the double free happens - so somehow the mount images objects get cleaned up twice on error
