### ISSUE TITLE
Coredump occurs on systemd.

### ISSUE THREAD

**Issue by hongjinghao** [systemd/systemd#29752]
### systemd version the issue has been seen with

249

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

No coredump occurs on systemd.

### Unexpected behaviour you saw

Coredump occurs on systemd.

### Steps to reproduce the problem

NA

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
(gdb)bt
#0  0x00007fa98df4a2eb in kill () at ../sysdeps/unix/syscall-template.S:120
#1  0x000055a80669341d in crash (sig=6, siginfo=0x7fff96238b70, context=<optimized out>) at ../src/core/main.c:264
#2  <signal handler called>
#3  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#4  0x00007fa98df964ae in __pthread_kill_internal (signo=<optimized out>, threadid=<optimized out>) at pthread_kill.c:78
#5  0x00007fa98df4a006 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#6  0x00007fa98df354f7 in __GI_abort () at abort.c:79
#7  0x00007fa98df8a597 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fa98e0c4120 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#8  0x00007fa98df9ff6c in malloc_printerr (str=str@entry=0x7fa98e0c21d4 "malloc(): corrupted top size") at malloc.c:5671
#9  0x00007fa98dfa340a in _int_malloc (av=av@entry=0x7fa98e0faaa0 <main_arena>, bytes=bytes@entry=1800) at malloc.c:4375
#10 0x00007fa98dfa3d09 in __GI___libc_malloc (bytes=bytes@entry=1800) at malloc.c:3331
#11 0x00007fa98e3b3a4a in malloc_multiply (need=1, size=1800) at ../src/basic/alloc-util.h:103
#12 sd_bus_new (ret=ret@entry=0x7fff96239418) at ../src/libsystemd/sd-bus/sd-bus.c:236
#13 0x000055a8066acc0a in bus_on_connection (s=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x55a806bf1660) at ../src/core/dbus.c:690
#14 0x00007fa98e40ca69 in source_dispatch (s=s@entry=0x55a806d498c0) at ../src/libsystemd/sd-event/sd-event.c:3630
#15 0x00007fa98e40cd6d in dispatch_exit (e=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:3790
#16 sd_event_dispatch (e=e@entry=0x55a806bf1d20) at ../src/libsystemd/sd-event/sd-event.c:4218
#17 0x00007fa98e40e330 in sd_event_run (e=0x55a806bf1d20, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4286
#18 0x000055a8066daf50 in manager_loop (m=0x55a806bf1660) at ../src/core/manager.c:3017
#19 0x000055a806691c3a in invoke_main_loop (ret_error_message=<optimized out>, ret_switch_root_init=<optimized out>, ret_switch_root_dir=<optimized out>, ret_fds=<optimized out>, ret_shutdown_verb=<optimized out>, 
    ret_retval=<optimized out>, ret_reexecute=<optimized out>, saved_rlimit_memlock=<optimized out>, saved_rlimit_nofile=<optimized out>, m=<optimized out>) at ../src/core/main.c:1966
#20 main (argc=5, argv=<optimized out>) at ../src/core/main.c:2994
(gdb)
(gdb)x/500xg 0x7fa98e0faa00 
0x7fa98e0faa00 <_IO_wide_data_0+96>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa10 <_IO_wide_data_0+112>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa20 <_IO_wide_data_0+128>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa30 <_IO_wide_data_0+144>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa40 <_IO_wide_data_0+160>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa50 <_IO_wide_data_0+176>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa60 <_IO_wide_data_0+192>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa70 <_IO_wide_data_0+208>:	0x0000000000000000	0x0000000000000000
0x7fa98e0faa80 <_IO_wide_data_0+224>:	0x00007fa98e0fbe60	0x0000000000000000
0x7fa98e0faa90:	0x0000000000000000	0x0000000000000000
0x7fa98e0faaa0 <main_arena>:	0x0000000000000001	0x0000000000000000
0x7fa98e0faab0 <main_arena+16>:	0x000055a806d37510	0x000055a806d1e000
0x7fa98e0faac0 <main_arena+32>:	0x000055a806d56840	0x000055a806b09c50
0x7fa98e0faad0 <main_arena+48>:	0x000055a806d26f20	0x000055a806d57af0
0x7fa98e0faae0 <main_arena+64>:	0x000055a806b3e7c0	0x0000000000000000
0x7fa98e0faaf0 <main_arena+80>:	0x0000000000000000	0x0000000000000000
0x7fa98e0fab00 <main_arena+96>:	0x00007fa98e0fab00	0x000055a806d4ae20
0x7fa98e0fab10 <main_arena+112>:	0x00007fa98e0fab00	0x00007fa98e0fab00
0x7fa98e0fab20 <main_arena+128>:	0x00007fa98e0fab10	0x00007fa98e0fab10
0x7fa98e0fab30 <main_arena+144>:	0x00007fa98e0fab20	0x00007fa98e0fab20
0x7fa98e0fab40 <main_arena+160>:	0x00007fa98e0fab30	0x00007fa98e0fab30
0x7fa98e0fab50 <main_arena+176>:	0x00007fa98e0fab40	0x00007fa98e0fab40
0x7fa98e0fab60 <main_arena+192>:	0x00007fa98e0fab50	0x00007fa98e0fab50
0x7fa98e0fab70 <main_arena+208>:	0x00007fa98e0fab60	0x00007fa98e0fab60
0x7fa98e0fab80 <main_arena+224>:	0x00007fa98e0fab70	0x00007fa98e0fab70
0x7fa98e0fab90 <main_arena+240>:	0x00007fa98e0fab80	0x00007fa98e0fab80
0x7fa98e0faba0 <main_arena+256>:	0x00007fa98e0fab90	0x00007fa98e0fab90
0x7fa98e0fabb0 <main_arena+272>:	0x00007fa98e0faba0	0x00007fa98e0faba0
0x7fa98e0fabc0 <main_arena+288>:	0x00007fa98e0fabb0	0x00007fa98e0fabb0
0x7fa98e0fabd0 <main_arena+304>:	0x00007fa98e0fabc0	0x00007fa98e0fabc0
0x7fa98e0fabe0 <main_arena+320>:	0x00007fa98e0fabd0	0x00007fa98e0fabd0
0x7fa98e0fabf0 <main_arena+336>:	0x00007fa98e0fabe0	0x00007fa98e0fabe0
0x7fa98e0fac00 <main_arena+352>:	0x00007fa98e0fabf0	0x00007fa98e0fabf0
0x7fa98e0fac10 <main_arena+368>:	0x00007fa98e0fac00	0x00007fa98e0fac00
0x7fa98e0fac20 <main_arena+384>:	0x00007fa98e0fac10	0x00007fa98e0fac10
0x7fa98e0fac30 <main_arena+400>:	0x00007fa98e0fac20	0x00007fa98e0fac20
0x7fa98e0fac40 <main_arena+416>:	0x00007fa98e0fac30	0x00007fa98e0fac30
0x7fa98e0fac50 <main_arena+432>:	0x00007fa98e0fac40	0x00007fa98e0fac40
0x7fa98e0fac60 <main_arena+448>:	0x00007fa98e0fac50	0x00007fa98e0fac50
0x7fa98e0fac70 <main_arena+464>:	0x00007fa98e0fac60	0x00007fa98e0fac60
0x7fa98e0fac80 <main_arena+480>:	0x00007fa98e0fac70	0x00007fa98e0fac70
0x7fa98e0fac90 <main_arena+496>:	0x00007fa98e0fac80	0x00007fa98e0fac80
0x7fa98e0faca0 <main_arena+512>:	0x00007fa98e0fac90	0x00007fa98e0fac90
0x7fa98e0facb0 <main_arena+528>:	0x00007fa98e0faca0	0x00007fa98e0faca0
0x7fa98e0facc0 <main_arena+544>:	0x00007fa98e0facb0	0x00007fa98e0facb0
0x7fa98e0facd0 <main_arena+560>:	0x00007fa98e0facc0	0x00007fa98e0facc0
0x7fa98e0face0 <main_arena+576>:	0x00007fa98e0facd0	0x00007fa98e0facd0
0x7fa98e0facf0 <main_arena+592>:	0x00007fa98e0face0	0x00007fa98e0face0
0x7fa98e0fad00 <main_arena+608>:	0x00007fa98e0facf0	0x00007fa98e0facf0
0x7fa98e0fad10 <main_arena+624>:	0x00007fa98e0fad00	0x00007fa98e0fad00
(gdb)
(gdb)x/400cb 0x000055a806d4ad90
0x55a806d4ad90:	-48 '\320'	-114 '\216'	-66 '\276'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4ad98:	80 'P'	-100 '\234'	-80 '\260'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4ada0:	120 'x'	-80 '\260'	118 'v'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4ada8:	72 'H'	-83 '\255'	-44 '\324'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4adb0:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4adb8:	-40 '\330'	79 'O'	125 '}'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4adc0:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4adc8:	-127 '\201'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4add0:	-48 '\320'	-114 '\216'	-66 '\276'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4add8:	113 'q'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ade0:	74 'J'	109 'm'	-128 '\200'	90 'Z'	5 '\005'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ade8:	2 '\002'	0 '\000'	0 '\000'	0 '\000'	60 '<'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4adf0:	5 '\005'	1 '\001'	117 'u'	0 '\000'	2 '\002'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4adf8:	7 '\a'	1 '\001'	115 's'	0 '\000'	24 '\030'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae00:	111 'o'	114 'r'	103 'g'	46 '.'	102 'f'	114 'r'	101 'e'	101 'e'
0x55a806d4ae08:	100 'd'	101 'e'	115 's'	107 'k'	116 't'	111 'o'	112 'p'	46 '.'
0x55a806d4ae10:	115 's'	121 'y'	115 's'	116 't'	101 'e'	109 'm'	100 'd'	49 '1'
0x55a806d4ae18:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae20:	8 '\b'	1 '\001'	103 'g'	0 '\000'	6 '\006'	97 'a'	40 '('	115 's'
0x55a806d4ae28:	117 'u'	115 's'	41 ')'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae30:	0 '\000'	-85 '\253'	15 '\017'	-114 '\216'	-87 '\251'	127 '\177'	0 '\000'	0 '\000'
0x55a806d4ae38:	0 '\000'	-85 '\253'	15 '\017'	-114 '\216'	-87 '\251'	127 '\177'	0 '\000'	0 '\000'
0x55a806d4ae40:	32 ' '	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae48:	65 'A'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae50:	48 '0'	-90 '\246'	-36 '\334'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4ae58:	80 'P'	-63 '\301'	-55 '\311'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4ae60:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae68:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae70:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae78:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae80:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae88:	33 '!'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4ae90:	121 'y'	101 'e'	115 's'	0 '\000'	-83 '\255'	85 'U'	0 '\000'	0 '\000'
0x55a806d4ae98:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aea0:	99 'c'	101 'e'	0 '\000'	107 'k'	101 'e'	116 't'	0 '\000'	0 '\000'
0x55a806d4aea8:	81 'Q'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aeb0:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aeb8:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aec0:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aec8:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aed0:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aed8:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aee0:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aee8:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4aef0:	-64 '\300'	72 'H'	-40 '\330'	6 '\006'	-88 '\250'	85 'U'	0 '\000'	0 '\000'
0x55a806d4aef8:	97 'a'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4af00:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4af08:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4af10:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x55a806d4af18:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
(gdb)
(gdb)frame 14
(gdb)p *s
$12 = {wakeup = WAKEUP_EVENT_SOURCE, n_ref = 1, event = 0x55a806bf1d20, userdata = 0x55a806bf1660, prepare = 0x0, description = 0x55a806d3df30 "bus-connection", type = SOURCE_IO, enabled = 1, pending = false, dispatching = true, 
  floating = false, exit_on_failure = false, ratelimited = false, priority = 0, pending_index = 0, prepare_index = 4294967295, pending_iteration = 55922, prepare_iteration = 0, preempted_iteration = 0, pending_count = 0, 
  dispatched_count = 0, preempt_dispatch_count = 10, destroy_callback = 0x0, ratelimit_expire_callback = 0x0, sources_next = 0x55a806b1db20, sources_prev = 0x55a806d49bd0, rate_limit = {interval = 0, burst = 0, num = 0, begin = 0}, 
  earliest_index = 0, latest_index = 0, {io = {callback = 0x55a8066acb10 <bus_on_connection>, fd = 15, events = 1, revents = 1, registered = true, owned = false}, time = {callback = 0x55a8066acb10 <bus_on_connection>, 
      next = 4294967311, accuracy = 4294967297}, signal = {callback = 0x55a8066acb10 <bus_on_connection>, siginfo = {ssi_signo = 15, ssi_errno = 1, ssi_code = 1, ssi_pid = 1, ssi_uid = 0, ssi_fd = 0, ssi_tid = 0, ssi_band = 0, 
        ssi_overrun = 0, ssi_trapno = 0, ssi_status = 0, ssi_int = 0, ssi_ptr = 0, ssi_utime = 0, ssi_stime = 0, ssi_addr = 0, ssi_addr_lsb = 0, __pad2 = 0, ssi_syscall = 0, ssi_call_addr = 0, ssi_arch = 0, 
        __pad = '\000' <repeats 27 times>}, sig = 0}, child = {callback = 0x55a8066acb10 <bus_on_connection>, siginfo = {si_signo = 15, si_errno = 1, si_code = 1, __pad0 = 1, _sifields = {_pad = {0 <repeats 28 times>}, _kill = {
            si_pid = 0, si_uid = 0}, _timer = {si_tid = 0, si_overrun = 0, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _rt = {si_pid = 0, si_uid = 0, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _sigchld = {si_pid = 0, 
            si_uid = 0, si_status = 0, si_utime = 0, si_stime = 0}, _sigfault = {si_addr = 0x0, si_addr_lsb = 0, _bounds = {_addr_bnd = {_lower = 0x0, _upper = 0x0}, _pkey = 0}}, _sigpoll = {si_band = 0, si_fd = 0}, _sigsys = {
            _call_addr = 0x0, _syscall = 0, _arch = 0}}}, pid = 0, options = 0, pidfd = 0, registered = false, pidfd_owned = false, process_owned = false, exited = false, waited = false}, defer = {
      callback = 0x55a8066acb10 <bus_on_connection>}, post = {callback = 0x55a8066acb10 <bus_on_connection>}, exit = {callback = 0x55a8066acb10 <bus_on_connection>, prioq_index = 15}, inotify = {
      callback = 0x55a8066acb10 <bus_on_connection>, mask = 15, inode_data = 0x100000001, by_inode_data_next = 0x0, by_inode_data_prev = 0x0}}}
```

**Comment by mrc0mmand** [comment]
Sorry, but v249 is just too old. Can you reproduce this on v253/v254? Or, alternatively, is this reproducible somehow?

**Comment by hongjinghao** [comment]
> Sorry, but v249 is just too old. Can you reproduce this on v253/v254? Or, alternatively, is this reproducible somehow?

I don't have a stable reproduction, so I can't provide information on the v253/v254

**Comment by poettering** [comment]
Sorry, but this is not actionable to us then. Please contact your OS vendor for help. Here, upstream we only track issues in current systemd versions, 249 is too old for that. Sorry.
