### ISSUE TITLE
DHCPv6: enterprise id is downgraded from uint32_t to uint16_t

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#29800]
Looks like the following DHCPv6 option
```sh
    Vendor-specific Information
        Option: Vendor-specific Information (17)
        Length: 8
        Enterprise ID: Unknown (4294967295)
        option
            Option code: 0
            Option length: 0
            Option data: <MISSING>
```
turns into `65535` and I'm not sure it's intentional.
```sh
../src/libsystemd-network/sd-dhcp6-lease.c:660:85: runtime error: implicit conversion from type 'uint32_t' (aka 'unsigned int') of value 4294967295 (32-bit, unsigned) to type 'uint16_t' (aka 'unsigned short') changed the value to 65535 (16-bit, unsigned)
    #0 0x8c7c6c in dhcp6_lease_add_vendor_option src/libsystemd-network/sd-dhcp6-lease.c:660:85
    #1 0x8c5881 in dhcp6_lease_parse_message src/libsystemd-network/sd-dhcp6-lease.c:854:29
    #2 0x8be9f9 in dhcp6_lease_new_from_message src/libsystemd-network/sd-dhcp6-lease.c:958:13
    #3 0x8ae63b in client_process_advertise_or_rapid_commit_reply src/libsystemd-network/sd-dhcp6-client.c:1241:13
    #4 0x8a9599 in client_receive_message src/libsystemd-network/sd-dhcp6-client.c:1368:21
    #5 0x7ff8ff3c9bd6 in source_dispatch src/libsystemd/sd-event/sd-event.c:4187:21
    #6 0x7ff8ff3c870f in sd_event_dispatch src/libsystemd/sd-event/sd-event.c:4808:21
    #7 0x7ff8ff3ccb79 in sd_event_run src/libsystemd/sd-event/sd-event.c:4869:21
    #8 0x7ff8ff3cd6cc in sd_event_loop src/libsystemd/sd-event/sd-event.c:4891:21
    #9 0x43e679 in run src/network/networkd.c:112:13
    #10 0x43ba05 in main src/network/networkd.c:119:1
    #11 0x7ff8fe049b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: 7026fe8c129a523e07856d7c96306663ceab6e24)
    #12 0x7ff8fe049c4a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x27c4a) (BuildId: 7026fe8c129a523e07856d7c96306663ceab6e24)
    #13 0x4138f4 in _start (/usr/lib/systemd/systemd-networkd+0x4138f4) (BuildId: cfc58c381fc2bb8ae2ca2f64bb208538bc57aab6)
```

**Comment by yuwata** [comment]
Ouch. Fix is waiting in #29802.
