### ISSUE TITLE
Operations on NFT sets appear to be racy

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#30427]
There's a one fail in `systemd-networkd-tests.py` that's currently plaguing the CI:

```
======================================================================
FAIL: test_address_static (__main__.NetworkdNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 2616, in test_address_static
    self.check_nftset('ifindex', 'dummy98')
  File "./test/test-network/systemd-networkd-tests.py", line 1057, in check_nftset
    self.assertRegex(output, r'.*elements = { [^}]*' + contents + r'[^}]* }.*')
AssertionError: Regex didn't match: '.*elements = { [^}]*dummy98[^}]* }.*' not found in 'table inet sd_test {\n\tset ifindex {\n\t\ttype iface_index\n\t}\n}'
```

I did some debugging and I can reliably reproduce the issue by running the failing test twice in a row:
```
# test/test-network/systemd-networkd-tests.py --debug -- NetworkdNetworkTests.test_address_static
...
10.8.1.0/24 proto kernel scope link src 10.8.1.1 metric 128
2001:db8:0:f105::/64 proto kernel metric 128 pref medium
accept:on interface:dummy98,address:10.10.1.0/24,label:"system_u:object_r:root_t:s0"
table inet sd_test {
        set addr4 {
                type ipv4_addr
                elements = { 10.10.1.1 }
        }
}
table inet sd_test {
        set network4 {
                type ipv4_addr
                flags interval
                elements = { 10.10.1.0/24 }
        }
}
table inet sd_test {
        set ifindex {
                type iface_index
                elements = { "dummy98" }
        }
}

----------------------------------------------------------------------
Ran 1 test in 5.338s

OK

# test/test-network/systemd-networkd-tests.py --debug -- NetworkdNetworkTests.test_address_static10.8.1.0/24 proto kernel scope link ...
10.8.1.0/24 proto kernel scope link src 10.8.1.1 metric 128
2001:db8:0:f105::/64 proto kernel metric 128 pref medium
accept:on interface:dummy98,address:10.10.1.0/24,label:"system_u:object_r:root_t:s0"
table inet sd_test {
        set addr4 {
                type ipv4_addr
                elements = { 10.10.1.1 }
        }
}
table inet sd_test {
        set network4 {
                type ipv4_addr
                flags interval
        }
}
...
======================================================================
FAIL: test_address_static (__main__.NetworkdNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-network/systemd-networkd-tests.py", line 2615, in test_address_static
    self.check_nftset('network4', r'10\.10\.1\.0/24')
  File "test/test-network/systemd-networkd-tests.py", line 1057, in check_nftset
    self.assertRegex(output, r'.*elements = { [^}]*' + contents + r'[^}]* }.*')
AssertionError: Regex didn't match: '.*elements = { [^}]*10\\.10\\.1\\.0/24[^}]* }.*' not found in 'table inet sd_test {\n\tset network4 {\n\t\ttype ipv4_addr\n\t\tflags interval\n\t}\n}'

----------------------------------------------------------------------
Ran 1 test in 2.331s

FAILED (failures=1)
```

I sprinkled some printfs here and there, and the error seems to come from kernel, so it's (imo) not a test issue:

```
# journalctl -b -o short-monotonic --no-hostname
...
[251989.853563] systemd-networkd[67335]: dummy98: Received updated static address (configured): 10.10.1.1/24 broadcast 10.10.1.255 (valid forever, preferred forever), flags: permanent, scope: global, label: n/a
[251989.853741] systemd-networkd[67335]: dummy98: Adding NetLabel system_u:object_r:root_t:s0 for IP address 10.10.1.1/24
[251989.853817] audit: MAC_UNLBL_STCADD netlabel: auid=4294967295 ses=4294967295 subj=system_u:system_r:systemd_networkd_t:s0 netif=dummy98 src=10.10.1.0 src_prefixlen=24 sec_obj=system_u:object_r:root_t:s0 res=0
[251989.866139] systemd-networkd[67335]: Got -2 errno from netlink
[251989.866235] systemd-networkd[67335]: Got -2 errno from netlink
[251989.866267] systemd-networkd[67335]: Failed to add NFT set: family inet, table sd_test, set addr4, IP address 10.10.1.1/24, ignoring: No such file or directory
[251989.872091] systemd-networkd[67335]: Got -2 errno from netlink
[251989.872143] systemd-networkd[67335]: Got -2 errno from netlink
[251989.872180] systemd-networkd[67335]: Failed to add NFT set: family inet, table sd_test, set network4, IP address 10.10.1.1/24, ignoring: No such file or directory
[251989.878088] systemd-networkd[67335]: Got -2 errno from netlink
[251989.878136] systemd-networkd[67335]: Got -2 errno from netlink
[251989.878183] systemd-networkd[67335]: Failed to add NFT set: family inet, table sd_test, set ifindex, IP address 10.10.1.1/24, ignoring: No such file or directory
[251989.878213] systemd-networkd[67335]: dummy98: link_check_ready(): static addresses are not configured.
```

I reproduced this both on Fedora Rawhide (`6.7.0-0.rc3.20231201git994d5c58e50e.32.fc40.x86_64`) and CentOS Stream 8 (`4.18.0-521.el8.x86_64`). Sometimes it fails to create all three NFT sets, sometimes only some of them, but the error is always the same.

/cc @topimiettinen

**Comment by mrc0mmand** [comment]
Note: revert e4a80de119c5ce022396b436690f6321f4bb626b once this gets fixed.

**Comment by topimiettinen** [comment]
It looks like the kernel rejects the same operation which it accepts earlier. The netlink messages seem to be the same except for sequence numbers:

accepted: "Added NFT set: family inet, table sd_test, set addr4, IP address 10.10.1.1/24"

\x14\x00\x00\x00\x10\x00\x05\x00\x0c\xe6\xce\x59\x00\x00\x00\x00\x00\x00\x00\x0a\x40\x00\x00\x00\x0c\x0a\x05\x04\x0d\xe6\xce\x59\x00\x00\x00\x00\x01\x00\xe6\x0c\x0c\x00\x01\x00\x73\x64\x5f\x74\x65\x73\x74\x00\x0a\x00\x02\x00\x61\x64\x64\x72\x34\x00\x00\x00\x14\x00\x03\x80\x10\x00\x00\x80\x0c\x00\x01\x80\x08\x00\x01\x00\x0a\x0a\x01\x01\x14\x00\x00\x00\x11\x00\x05\x00\x0e\xe6\xce\x59\x00\x00\x00\x00\x00\x00\x00\x0a

rejected with ENOENT: "Failed to add NFT set: family inet, table sd_test, set addr4, IP address 10.10.1.1/24, ignoring"

\x14\x00\x00\x00\x10\x00\x05\x00\x15\xe6\xce\x59\x00\x00\x00\x00\x00\x00\x00\x0a\x40\x00\x00\x00\x0c\x0a\x05\x04\x16\xe6\xce\x59\x00\x00\x00\x00\x01\x00\xe6\x15\x0c\x00\x01\x00\x73\x64\x5f\x74\x65\x73\x74\x00\x0a\x00\x02\x00\x61\x64\x64\x72\x34\x00\x00\x00\x14\x00\x03\x80\x10\x00\x00\x80\x0c\x00\x01\x80\x08\x00\x01\x00\x0a\x0a\x01\x01\x14\x00\x00\x00\x11\x00\x05\x00\x17\xe6\xce\x59\x00\x00\x00\x00\x00\x00\x00\x0a

**Comment by topimiettinen** [comment]
The operations by `nft` and `networkd` seem to be interleaved in the bad test run as seen by `nft monitor`:

Good:
```
add table inet sd_test
# new generation 55 by process 4551 (nft)
add set inet sd_test addr4 { type ipv4_addr; } 
# new generation 56 by process 4552 (nft)
add set inet sd_test network4 { type ipv4_addr; flags interval; } 
# new generation 57 by process 4555 (nft)
add set inet sd_test ifindex { type iface_index; } 
# new generation 58 by process 4557 (nft)
add element inet sd_test addr4 { 10.10.1.1 }
# new generation 59 by process 4545 (systemd-network)
add element inet sd_test network4 { 10.10.1.0/24 }
# new generation 60 by process 4545 (systemd-network)
add element inet sd_test ifindex { 33 }
# new generation 61 by process 4545 (systemd-network)
delete set inet sd_test addr4
# new generation 62 by process 4575 (nft)
delete set inet sd_test network4
# new generation 63 by process 4576 (nft)
delete set inet sd_test ifindex
# new generation 64 by process 4577 (nft)
delete table inet sd_test
# new generation 65 by process 4578 (nft)
```

Bad:
```
add table inet sd_test
# new generation 66 by process 4990 (nft)
add set inet sd_test addr4 { type ipv4_addr; } 
# new generation 67 by process 4991 (nft)
add set inet sd_test network4 { type ipv4_addr; flags interval; } 
# new generation 68 by process 4993 (nft)
add element inet sd_test addr4 { 10.10.1.1 }
# new generation 69 by process 4984 (systemd-network)
add element inet sd_test network4 { 10.10.1.0/24 }
# new generation 70 by process 4984 (systemd-network)
add set inet sd_test ifindex { type iface_index; } 
# new generation 71 by process 4995 (nft)
delete element inet sd_test addr4 { 10.10.1.1 }
# new generation 72 by process 4984 (systemd-network)
delete element inet sd_test network4 { 10.10.1.0/24 }
# new generation 73 by process 4984 (systemd-network)
```
Notice how in the bad run the set `ifindex` is added _after_ `networkd` has already added elements to the other sets!
