### ISSUE TITLE
ninja -C build update-man-rules is borked on git main

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#30715]
### systemd version the issue has been seen with

git main

### Offending output:

```
FAILED: man/update-man-rules 
/home/lennart/projects/systemd/tools/update-man-rules.py '/home/lennart/projects/systemd/man/*.xml' /home/lennart/projects/systemd/man/rules/meson.build
Failed to process /home/lennart/projects/systemd/man/standard-conf.xml
Traceback (most recent call last):
  File "/home/lennart/projects/systemd/tools/update-man-rules.py", line 101, in <module>
    main()
  File "/home/lennart/projects/systemd/tools/update-man-rules.py", line 92, in main
    rules = create_rules(pages)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/lennart/projects/systemd/tools/update-man-rules.py", line 42, in create_rules
    add_rules(rules, name)
  File "/home/lennart/projects/systemd/tools/update-man-rules.py", line 24, in add_rules
    title = refmeta.find('./refentrytitle').text
            ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
ninja: build stopped: subcommand failed.
```

**Comment by poettering** [comment]
@dtardon a little bird told me you touched that last?

**Comment by DaanDeMeyer** [comment]
Specifically https://github.com/systemd/systemd/pull/30616 broke it

**Comment by mrc0mmand** [comment]
-> https://github.com/systemd/systemd/pull/30732
