### ISSUE TITLE
logind: Assertion '!m->action_job' failed at src/login/logind-dbus.c:1879 function bus_manager_shutdown_or_sleep_now_or_later()

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#30917]
As far as I can tell it happens when `RebootWithFlags` is called two times in a row:
```sh
Got message type=method_call sender=:1.58 destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=RebootWithFlags  cookie=3 reply_cookie=0 signature=t error-name=n/a error-message=n/a
...
The system will reboot now!
...
System userspace is rebooting.
...
Got message type=method_call sender=:1.57 destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=RebootWithFlags  cookie=3 reply_cookie=0 signature=t error-name=n/a error-message=n/a
...
The system will reboot now!
Assertion '!m->action_job' failed at src/login/logind-dbus.c:1879, function bus_manager_shutdown_or_sleep_now_or_later(). Aborting.
systemd-logind.service: Main process exited, code=dumped, status=6/ABRT
systemd-logind.service: Failed with result 'core-dump'.
```
```sh
(gdb) bt                                                                                                                                                      
#0  0x00007f9b018b0884 in __pthread_kill_implementation ()                                                                                                    
   from target:/lib64/libc.so.6                                                                                                                               
#1  0x00007f9b0185fafe in raise () from target:/lib64/libc.so.6                                                                                               
#2  0x00007f9b0184887f in abort () from target:/lib64/libc.so.6                                                                                               
#3  0x00007f9b02c95911 in log_assert_failed (                                                                                                                 
    text=0x531a60 <str> "!m->action_job",                                                                                                                     
    file=0x53b8a6 "src/login/logind-dbus.c", line=1879,                                                                                                       
    func=0x5319e0 <__func__.bus_manager_shutdown_or_sleep_now_or_later> "bus_manager_shutdown_or_sleep_now_or_later") at ../src/basic/log.c:968               
#4  0x000000000045a56b in bus_manager_shutdown_or_sleep_now_or_later (                                                                                        
    m=0x617000000080, a=0x55d510 <handle_action_data_table+400>,                                                                                              
    error=0x7f9afef33b20) at ../src/login/logind-dbus.c:1879                                                                                                  
#5  0x000000000048fa27 in method_do_shutdown_or_sleep (m=0x617000000080,                                                                                      
    message=0x61800002b480, action=HANDLE_REBOOT, with_flags=true,                                                                                            
    error=0x7f9afef33b20) at ../src/login/logind-dbus.c:2137                                                                                                  
#6  0x000000000047e142 in method_reboot (message=0x61800002b480,                                                                                              
    userdata=0x617000000080, error=0x7f9afef33b20)                                                                                                            
    at ../src/login/logind-dbus.c:2157                                                                                                                        
#7  0x00007f9b02f3b2b0 in method_callbacks_run (bus=0x61d000000080,                                                                                           
    m=0x61800002b480, c=0x604000001590, require_fallback=false,                                                                                               
    found_object=0x7f9aff0d0540) at ../src/libsystemd/sd-bus/bus-objects.c:406                                                                                
#8  0x00007f9b02f1a65b in object_find_and_run (bus=0x61d000000080,                                                                                            
    m=0x61800002b480, p=0x60f000001318 "/org/freedesktop/login1",                                                                                             
    require_fallback=false, found_object=0x7f9aff0d0540)                                                                                                      
    at ../src/libsystemd/sd-bus/bus-objects.c:1319
#9  0x00007f9b02f18c77 in bus_process_object (bus=0x61d000000080, 
    m=0x61800002b480) at ../src/libsystemd/sd-bus/bus-objects.c:1439
#10 0x00007f9b02fd42d6 in process_message (bus=0x61d000000080, 
    m=0x61800002b480) at ../src/libsystemd/sd-bus/sd-bus.c:3010
#11 0x00007f9b02fcf896 in process_running (bus=0x61d000000080, ret=0x0)
    at ../src/libsystemd/sd-bus/sd-bus.c:3052
#12 0x00007f9b02fb3287 in bus_process_internal (bus=0x61d000000080, ret=0x0)
    at ../src/libsystemd/sd-bus/sd-bus.c:3272
#13 0x00007f9b02fab2fd in sd_bus_process (bus=0x61d000000080, ret=0x0)
    at ../src/libsystemd/sd-bus/sd-bus.c:3299
#14 0x00007f9b02fbbeb9 in time_callback (s=0x60f000000400, usec=0, 
    userdata=0x61d000000080) at ../src/libsystemd/sd-bus/sd-bus.c:3654
#15 0x00007f9b032968b8 in source_dispatch (s=0x60f000000400)
    at ../src/libsystemd/sd-event/sd-event.c:4195
#16 0x00007f9b032945b5 in sd_event_dispatch (e=0x617000000400)
    at ../src/libsystemd/sd-event/sd-event.c:4808
#17 0x00007f9b0329a0ae in sd_event_run (e=0x617000000400, 
    timeout=18446744073709551615)
    at ../src/libsystemd/sd-event/sd-event.c:4869
#18 0x0000000000410d35 in manager_run (m=0x617000000080)
    at ../src/login/logind.c:1212
#19 0x000000000040be67 in run (argc=1, argv=0x7ffee9404d28)
    at ../src/login/logind.c:1260
#20 0x000000000040ae8e in main (argc=1, argv=0x7ffee9404d28)
    at ../src/login/logind.c:1263
```

**Comment by yuwata** [comment]
cc @YHNdnzj
