### ISSUE TITLE
systemd-measure failure to sign: Could not calculate PolicyPCR digest: Operation not supported

### ISSUE THREAD

**Issue by Itxaka** [systemd/systemd#31390]
### systemd version the issue has been seen with

255

### Used distribution

leap 15.5

### Linux kernel version used

6.7.4-arch1-1 (container)

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

`ukify build --linux vmlinuz --initrd initrd --measure --pcr-private-key /keys/tpm2-pcr-private.pem` produces a measured efi file with systemd-measure

### Unexpected behaviour you saw

systemd-measure failing to calculate the policyPCR

```
+ /usr/lib/systemd/systemd-measure sign --linux=vmlinuz --osrel=/etc/os-release --uname=/tmp/tmp.unamepbyyuc2y --pcrpkey=/tmp/tmp.pcrpkeyrg6iltva --initrd=initrd --sbat=/tmp/tmp.sbatk3w6itld --private-key=/keys/tpm2-pcr-private.pem
Could not calculate PolicyPCR digest: Operation not supported
Traceback (most recent call last):
  File "/usr/bin/ukify", line 1659, in <module>
    main()
  File "/usr/bin/ukify", line 1648, in main
    make_uki(opts)
  File "/usr/bin/ukify", line 821, in make_uki
    call_systemd_measure(uki, linux, opts=opts)
  File "/usr/bin/ukify", line 501, in call_systemd_measure
    pcrsig = subprocess.check_output(cmd + extra, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/systemd/systemd-measure', 'sign', '--linux=vmlinuz', '--osrel=/etc/os-release', '--uname=/tmp/tmp.unamepbyyuc2y', '--pcrpkey=/tmp/tmp.pcrpkeyrg6iltva', '--initrd=initrd', '--sbat=/tmp/tmp.sbatk3w6itld', '--private-key=/keys/tpm2-pcr-private.pem']' returned non-zero exit status 1.
```

### Steps to reproduce the problem

This is a very specific build. I picked 255 from master and build the minimal target possible to get systemd-measure and ukify working so I could use them in an older system.

Running from a container as its a container tool, which its used to create and sign efis only.

Still, evne if its user problem, I would like to be able to pinpoint WHY its not able to calculate the policyPCR properly as I think all the deps and build options are there to be able to do so.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
/usr/lib/systemd/systemd-measure --version
systemd 255 (255)
-PAM -AUDIT +SELINUX -APPARMOR +IMA +SMACK -SECCOMP -GCRYPT -GNUTLS +OPENSSL -ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC -KMOD -LIBCRYPTSETUP -LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE +TPM2 -BZIP2 -LZ4 -XZ -ZLIB -ZSTD -BPF_FRAMEWORK -XKBCOMMON -UTMP -SYSVINIT default-hierarchy=unified


Build options for systemd:

-Dmode=release -Dbootloader=true -Defi=true -Dukify=true -Dblkid=true -Dopenssl=true -Dshared-lib-tag=${PACKAGE_VERSION}-kairos -Dsbat-distro="Kairos" -Dsbat-distro-url="kairos.io" -Dsbat-distro-summary="Kairos" -Dsbat-distro-version="kairos-${PACKAGE_VERSION}" -Ddns-servers='' -Dsysvinit-path= -Dsysvrcnd-path= -Dtpm=false -Dinstall-tests=false -Dnss-resolve=disabled -Dlogind=false -Dcoredump=false -Dhomed=disabled -Dfirstboot=false -Dhostnamed=false -Dhibernate=false -Dinitrd=false -Dimportd=false -Dkernel-install=false -Dlocaled=false -Dmachined=false -Dnetworkd=false -Dnss-myhostname=false -Dnss-mymachines=false -Dnss-systemd=false -Doomd=false -Dportabled=false -Dhwdb=false -Dpstore=false -Dquotacheck=false -Drandomseed=false -Drepart=false -Dresolve=false -Drfkill=false -Dsysext=false -Danalyze=false -Dsysupdate=false -Dsysusers=false -Dstoragetm=false -Dtimedated=false -Dtimesyncd=false -Dtmpfiles=false -Duserdb=false -Dvconsole=false -Dxdg-autostart=false -Didn=false -Dpolkit=false -Dnscd=false -Dkmod=false -Ddbus=false -Dglib=false -Dbacklight=false -Dldconfig=false -Dgshadow=false -Dwheel-group=false -Dadm-group=false -Dxkbcommon=false -Dzstd=false -Dlz4=false -Dutmp=false -Dlink-udev-shared=false -Dlink-systemctl-shared=false -Dlink-networkd-shared=false -Dlink-timesyncd-shared=false -Dlink-journalctl-shared=false -Dlink-boot-shared=false -Dlink-portabled-shared=false -Denvironment-d=false -Dqrencode=false -Dpwquality=false -Dlibcurl=false -Dfdisk=false -Dlibidn2=false -Dlibiptc=false -Ddns-over-tls=false -Didn=false -Dgnutls=false -Dp11kit=false -Dlibidn=false -Dlibidn2=false -Dgcrypt=false -Dxz=false -Dzlib=false -Dbzip2=false
```

**Comment by Itxaka** [comment]
well just after finally hitting send after 2 hours of having this issue created and ready to be submitted I just thougth about looking at the code that was calling this which seems to be using tpm2 libs and I wondering if that meant having tp2-* packages installed for runtime calculation...


Yes Im dumb.

You need those tpm2 package on runtime to be able to talk or calculate the tpm stuff.... closing and sorry for the inconvenience.
