### ISSUE TITLE
journalctl: cuts off log messages when invoked with -u

### ISSUE THREAD

**Issue by Tasssadar** [systemd/systemd#3277]
**Systemd version:** 229-4
**Distribution**: [Debian testing](https://packages.debian.org/stretch/systemd)

I have a unit for program written in Go that logs into journald, as per default settings:

``` [Unit]
Description=Awesome generic name app
Requires=postgresql@9.5-main.service

[Service]
WorkingDirectory=/mnt/store/server/
ExecStart=/mnt/store/server/server
IgnoreSIGPIPE=false
KillSignal=SIGINT
Restart=always
RestartSec=30
User=tassadar

[Install]
WantedBy=multi-user.target
```

The program has crashed on a golang panic.  This is what I can see with `journalctl -u awesome-server`:

```
...
May 17 13:37:48 sunfyre server[25933]: panic: runtime error: slice bounds out of range
May 17 13:37:48 sunfyre server[25933]: goroutine 45 [running]:
May 17 13:37:48 sunfyre server[25933]: panic(0xda80e0, 0xc82000a070)
May 17 13:37:48 sunfyre systemd[1]: awesome-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 17 13:37:48 sunfyre systemd[1]: awesome-server.service: Unit entered failed state.
May 17 13:37:48 sunfyre systemd[1]: awesome-server.service: Failed with result 'exit-code'.
May 17 13:38:18 sunfyre systemd[1]: awesome-server.service: Service hold-off time over, scheduling restart.
May 17 13:38:18 sunfyre systemd[1]: Stopped Awesome generic name app.
May 17 13:38:18 sunfyre systemd[1]: Started Awesome generic name app.
May 17 13:38:19 sunfyre server[31604]: [May 17 13:38:19.258] I: server: awesome-server starting
...
```

Not very useful, the whole stack trace is missing (golang automatically generates stack traces to stderr on panic)!

But, when I invoke just `journalctl` with no arguments:

```
...
May 17 13:37:48 sunfyre server[25933]: panic: runtime error: slice bounds out of range
May 17 13:37:48 sunfyre server[25933]: goroutine 45 [running]:
May 17 13:37:48 sunfyre server[25933]: panic(0xda80e0, 0xc82000a070)
May 17 13:37:48 sunfyre server[25933]:         /home/tassadar/go-linux-amd64-bootstrap/src/runtime/panic.go:481 +0x3e6
May 17 13:37:48 sunfyre server[25933]: server/backend.(*ioTraceParser).parseLine(0xc873db2370, 0xc87b687740, 0xb1, 0x733, 0xc8864afb40)
May 17 13:37:48 sunfyre server[25933]:         <filepath>
May 17 13:37:48 sunfyre server[25933]: server/backend.(*ioTraceParser).parseFile(0xc873db2370, 0xc89e551920, 0x55, 0xc8864afb40, 0x0, 0x0)
May 17 13:37:48 sunfyre server[25933]:         <filepath>
May 17 13:37:48 sunfyre server[25933]: server/backend.(*analysisContext).analyzeIo(0xc888db4c30, 0x0, 0x0)
May 17 13:37:48 sunfyre server[25933]:         <filepath>
May 17 13:37:48 sunfyre server[25933]: server/backend.(*apStageStatic).doAnalysis(0xc821270160, 0x2a0cd, 0x0, 0x0)
May 17 13:37:48 sunfyre server[25933]:         <filepath>
May 17 13:37:48 sunfyre server[25933]: server/backend.(*apStageStatic).analysisRoutine(0xc821270160)
May 17 13:37:48 sunfyre server[25933]:         <filepath>
May 17 13:37:48 sunfyre server[25933]: created by server/backend.newStageStatic
May 17 13:37:48 sunfyre server[25933]:         <filepath>
May 17 13:37:48 sunfyre systemd[1]: awesome-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 17 13:37:48 sunfyre systemd[1]: awesome-server.service: Unit entered failed state.
May 17 13:37:48 sunfyre systemd[1]: awesome-server.service: Failed with result 'exit-code'.
May 17 13:38:04 sunfyre ntpd[972]: Soliciting pool server 81.27.192.20
May 17 13:38:18 sunfyre systemd[1]: awesome-server.service: Service hold-off time over, scheduling restart.
May 17 13:38:18 sunfyre systemd[1]: Stopped Awesome generic name app.
May 17 13:38:18 sunfyre systemd[1]: Started Awesome generic name app.
May 17 13:38:19 sunfyre server[31604]: [May 17 13:38:19.258] I: server: awesome-server starting
...
```

**The whole stack trace is in journald, but it is not visibile when filtered by unit name.**

When I look at the messages with journald -o verbose, I can see that the messages not shown with -u are missing _SYSTEMD_UNIT field for some reason. Maybe the golang program dies before journald can eat the whole trace?

```
Tue 2016-05-17 13:37:48.372014 CEST [s=7d57116cc2414e8183a404d56a9c8c6d;i=5ec3f;b=90efd1ca2b144ab0bf8d6ad4b6d488b8;m=12f45651816;t=533082ba2682e;x=d3b3f25d64b6bd91]
    ...  
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=server
    _PID=25933
    _UID=1000
    _GID=1000
    _COMM=server
    _EXE=/mnt/store/server/server
    _CMDLINE=/mnt/store/server/server
    _CAP_EFFECTIVE=400
    _SYSTEMD_CGROUP=/system.slice/awesome-server.service
    _SYSTEMD_UNIT=awesome-server.service
    MESSAGE=panic(0xda80e0, 0xc82000a070)
Tue 2016-05-17 13:37:48.414297 CEST [s=7d57116cc2414e8183a404d56a9c8c6d;i=5ec40;b=90efd1ca2b144ab0bf8d6ad4b6d488b8;m=12f4565bd42;t=533082ba30d59;x=7a4db6ec3bc3b67a]
   ...
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=server
    _PID=25933
    _UID=1000
    _GID=1000
    _COMM=server
    _EXE=/mnt/store/server/server
    _CMDLINE=/mnt/store/server/server
    _CAP_EFFECTIVE=400
    _SYSTEMD_CGROUP=/
    _SYSTEMD_SLICE=-.slice
    MESSAGE=    /home/tassadar/go-linux-amd64-bootstrap/src/runtime/panic.go:481 +0x3e6
```

Let me know if there's more logs I can provide.

EDIT: Can be reproduced even with a very simple program, except with this one journald usually misses the whole trace:

``` go
package main

import "fmt"

func foo() {
    bar()
}

func bar() {
    baz()
}

func baz() {
    teststr := "Hello world"
    fmt.Println(teststr[213213:])
}

func main() {
    fmt.Println("Starting!")
    foo()
    return
}

```

**Comment by michich** [comment]
Known race, issue #2913
