### ISSUE TITLE
[256-rc3] test-systemd-tmpfiles fails

### ISSUE THREAD

**Issue by konstruktoid** [systemd/systemd#33006]
### systemd version the issue has been seen with

256-rc3

### Used distribution

Ubuntu 24.04 LTS

### Linux kernel version used

6.8.0-31-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

Completed build of 256-rc3

### Unexpected behaviour you saw

`systemd:tmpfiles / test-systemd-tmpfiles                                                  FAIL              0.38s   exit status 1`

### Steps to reproduce the problem

Build script: https://github.com/konstruktoid/nosu-project/blob/main/scripts/build_systemd.sh
`bash build_systemd.sh`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
----------------------------------- stderr -----------------------------------
Generating a test journal
Reserving 333 entries in field hash table.
Reserving 2047 entries in data hash table.
Journal effective settings seal=no keyed_hash=yes compress=ZSTD compress_threshold_bytes=512B
Verifying with key: n/a
Toggling bits 307584 to 308096
0095f0: Invalid hash (9649edf674085414 vs. cba006920e56444e)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 446cb33c4c89f82c)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. d99d062de937b6cd)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 32c007ea2309b812)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 9668e0a3c6d9d7d3)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 5ab24bd53e469b2b)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 39bdabedb5fe7d20)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 3a68733f30fd6ca3)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. a7651a2ab71c78cc)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 2309f7b1f9c3ce6d)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 71759991c636741c)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 670ae26d027ea85d)
0095f0: Invalid object contents: Bad message
File corruption detected at test.journal:38384 (of 8388608 bytes, 0%).
0095f0: Invalid hash (9649edf674085414 vs. 3271ec16c7baa12b)
0095f0: Invalid object contents: Bad message
[...]
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. e0f704a3370bec33)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. f9eb64d3cf66101b)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 57b055701c324fbb)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. cc7fd608128a51ad)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 4c56b7975bb7d80c)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 3e84d42c01547c80)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 3757a0189b72b052)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. f4621935077cb7c8)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 683ee68d865c1741)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 1e8a5c66c0b091c8)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 7afe2abd7f4fcd6e)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. d004370a6e8b146a)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 7247c85537294f44)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 871251bc2b109c2d)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 4459edd3e6b18f33)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. a7fd2919816d6b9c)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 223474117b578376)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. e7ebe99bd450a402)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. d6885463229c3a9f)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. c7e395b7ba33c1af)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. e70fd826511021d9)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 6fb372abcc4d80bc)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. c64677a9556e391c)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. d885b0435d5cf9cc)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 471453a80598bfaa)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 24f1f08f4528bb44)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 7b42f2f96c3087a1)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 7484003d88eb2906)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 7d790d797eedab2b)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. dfe583382df445b2)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 95c1447e14f45479)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 1971a597e2911dfc)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
009640: Invalid hash (d6c38a6e3eef6572 vs. 8e6a89977c314118)
009640: Invalid object contents: Bad message
File corruption detected at test.journal:38464 (of 8388608 bytes, 0%).
==============================================================================


Summary of Failures:

1189/1590 systemd:tmpfiles / test-systemd-tmpfiles                                                  FAIL              0.38s   exit status 1

Ok:                 1471
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            118
Timeout:            0
```

**Comment by bluca** [comment]
Environment? Compiler version?

**Comment by konstruktoid** [comment]
The error was a result of `/tmp/user/` having to restrictive permissions, `run0 chmod 0755 /tmp/user/` solved it.
Feel free to close.

```sh
$ stat -c "%a %A %n" /tmp/user/
711 drwx--x--x /tmp/user/
```
```
================================= 1189/1590 ==================================
test:         systemd:tmpfiles / test-systemd-tmpfiles
start time:   12:34:07
duration:     0.38s
result:       exit status 1
command:      LD_LIBRARY_PATH=/tmp/build-systemd-v256-rc3/systemd-256-rc3/build/src/shared MALLOC_PERTURB_=199 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_
on_error=1:print_summary=1:print_stacktrace=1 /tmp/build-systemd-v256-rc3/systemd-256-rc3/test/test-systemd-tmpfiles.py /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles
----------------------------------- stdout -----------------------------------
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'asdfa'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f "open quote'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f closed quote""'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'Y /unknown/letter'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'w non/absolute/path'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 's'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f!! /too/many/bangs'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f++ /too/many/plusses'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f+!+ /too/many/plusses'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f!+! /too/many/bangs'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f== /too/many/equals'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'w /unresolved/argument - - - - "%Y"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'w /unresolved/argument/sandwich - - - - "%v%Y%v"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'w /unresolved/filename/%Y - - - - "whatever"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'w /unresolved/filename/sandwich/%v%Y%v - - - - "whatever"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'w - - - - - "no file specified"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'C - - - - - "no file specified"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'C non/absolute/path - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'b - - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'b 1234 - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'c - - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'c 1234 - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 't - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'T - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'a - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'A - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'h - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'H - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'asdfa'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f "open quote'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f closed quote""'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'Y /unknown/letter'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'w non/absolute/path'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 's'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f!! /too/many/bangs'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f++ /too/many/plusses'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f+!+ /too/many/plusses'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f!+! /too/many/bangs'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f== /too/many/equals'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'w /unresolved/argument - - - - "%Y"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'w /unresolved/argument/sandwich - - - - "%v%Y%v"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'w /unresolved/filename/%Y - - - - "whatever"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'w /unresolved/filename/sandwich/%v%Y%v - - - - "whatever"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'w - - - - - "no file specified"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'C - - - - - "no file specified"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'C non/absolute/path - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'b - - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'b 1234 - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'c - - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'c 1234 - - - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 't - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'T - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'a - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'A - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'h - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'H - - -'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'w /foo - - - - "specifier for --user %t"'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.338ln42_/arg - - - - two words'
expect: 'two words'
actual: 'two words'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.d5c39yod/arg - - - - %H'
expect: 'gungnir'
actual: 'gungnir'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.jb8nsbg3/arg - - - - %v'
expect: '6.8.0-31-generic'
actual: '6.8.0-31-generic'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.ee7czrgn/arg - - - - %U'
expect: '0'
actual: '0'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.c5560qhc/arg - - - - %G'
expect: '0'
actual: '0'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.mbyupw9d/arg - - - - %u'
expect: 'root'
actual: 'root'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.0qtk2odp/arg - - - - %g'
expect: 'root'
actual: 'root'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.2ruhv4hi/arg - - - - %h'
expect: '/home/tsj'
actual: '/home/tsj'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.chbhqmd_/arg - - - - %t'
expect: '/run'
actual: '/run'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.67ozayql/arg - - - - %S'
expect: '/var/lib'
actual: '/var/lib'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.3ylp3cdx/arg - - - - %C'
expect: '/var/cache'
actual: '/var/cache'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.hl1arjm6/arg - - - - %L'
expect: '/var/log'
actual: '/var/log'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.bn9nekzz/arg - - - - %%'
expect: '%'
actual: '%'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.gveiqahj/arg - - - - two words'
expect: 'two words'
actual: 'two words'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.vkh_zwgt/arg - - - - %H'
expect: 'gungnir'
actual: 'gungnir'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.nurl5nir/arg - - - - %v'
expect: '6.8.0-31-generic'
actual: '6.8.0-31-generic'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.f99kg3x5/arg - - - - %U'
expect: '1000'
actual: '1000'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.l112cdp0/arg - - - - %G'
expect: '1000'
actual: '1000'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.g18ub8e4/arg - - - - %u'
expect: 'tsj'
actual: 'tsj'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.qjw6xv51/arg - - - - %g'
expect: 'tsj'
actual: 'tsj'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.yblw_tl0/arg - - - - %h'
expect: '/home/tsj'
actual: '/home/tsj'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.lrbgi89v/arg - - - - %t'
expect: '/run/user/1000'
actual: '/run/user/1000'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.8p72ygq9/arg - - - - %S'
expect: '/home/tsj/.local/state'
actual: '/home/tsj/.local/state'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.4sbkw38w/arg - - - - %C'
expect: '/home/tsj/.cache'
actual: '/home/tsj/.cache'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.sjebnlb5/arg - - - - %L'
expect: '/home/tsj/.local/state/log'
actual: '/home/tsj/.local/state/log'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles --user on 'f /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.sv828864/arg - - - - %%'
expect: '%'
actual: '%'
Running /tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles on 'f= /tmp/user/1000/test-systemd-tmpfiles.j9h8ai0c/test-content.rgp26c5y/shallow - - - - None-shallow'
----------------------------------- stderr -----------------------------------
<stdin>:1: Syntax error.
<stdin>:1: Failed to parse line: Invalid argument
<stdin>:1: Path 'closed' not absolute.
<stdin>:1: Unknown command type 'Y'.
<stdin>:1: Path 'non/absolute/path' not absolute.
<stdin>:1: Syntax error.
<stdin>:1: Unknown modifiers in command 'f!!'.
<stdin>:1: Unknown modifiers in command 'f++'.
<stdin>:1: Unknown modifiers in command 'f+!+'.
<stdin>:1: Unknown modifiers in command 'f!+!'.
<stdin>:1: Unknown modifiers in command 'f=='.
<stdin>:1: Failed to substitute specifiers in argument: Invalid slot
<stdin>:1: Failed to substitute specifiers in argument: Invalid slot
<stdin>:1: Failed to replace specifiers in '/unresolved/filename/%Y': Invalid slot
<stdin>:1: Failed to replace specifiers in '/unresolved/filename/sandwich/%v%Y%v': Invalid slot
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path 'non/absolute/path' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '1234' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '1234' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Syntax error.
<stdin>:1: Failed to parse line: Invalid argument
<stdin>:1: Path 'closed' not absolute.
<stdin>:1: Unknown command type 'Y'.
<stdin>:1: Path 'non/absolute/path' not absolute.
<stdin>:1: Syntax error.
<stdin>:1: Unknown modifiers in command 'f!!'.
<stdin>:1: Unknown modifiers in command 'f++'.
<stdin>:1: Unknown modifiers in command 'f+!+'.
<stdin>:1: Unknown modifiers in command 'f!+!'.
<stdin>:1: Unknown modifiers in command 'f=='.
<stdin>:1: Failed to substitute specifiers in argument: Invalid slot
<stdin>:1: Failed to substitute specifiers in argument: Invalid slot
<stdin>:1: Failed to replace specifiers in '/unresolved/filename/%Y': Invalid slot
<stdin>:1: Failed to replace specifiers in '/unresolved/filename/sandwich/%v%Y%v': Invalid slot
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path 'non/absolute/path' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '1234' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '1234' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Path '-' not absolute.
<stdin>:1: Failed to resolve specifier: Required $XDG_... variable not defined, skipping.
All rules containing unresolvable specifiers will be skipped.
Failed to open "user" at "/tmp": Permission denied
Traceback (most recent call last):
  File "/tmp/build-systemd-v256-rc3/systemd-256-rc3/test/test-systemd-tmpfiles.py", line 244, in <module>
    test_hard_cleanup(user=False)
  File "/tmp/build-systemd-v256-rc3/systemd-256-rc3/test/test-systemd-tmpfiles.py", line 206, in test_hard_cleanup
    test_content('f= {} - - - - ' + label, label, user=user, subpath=subpath, path_cb=type_cb)
  File "/tmp/build-systemd-v256-rc3/systemd-256-rc3/test/test-systemd-tmpfiles.py", line 93, in test_content
    test_line(spec, user=user, returncode=0, extra=extra)
  File "/tmp/build-systemd-v256-rc3/systemd-256-rc3/test/test-systemd-tmpfiles.py", line 48, in test_line
    assert c.returncode == returncode, c
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: CompletedProcess(args=['/tmp/build-systemd-v256-rc3/systemd-256-rc3/build/systemd-tmpfiles', '--create', '-'], returncode=73, stdout='')
```

**Comment by konstruktoid** [comment]
Setting `0755` on `/tmp/user` is however reverted after a reboot, now running 256~rc3.

```
$ uptime && systemd --version && stat -c "%a %A %n" /tmp/user/
 14:14:07 up 2 min,  4 users,  load average: 0.20, 0.23, 0.09
systemd 256~rc3 (256~rc3)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT -LIBARCHIVE
711 drwx--x--x /tmp/user/
```

**Comment by konstruktoid** [comment]
`libpam-tmpdir` was the culprit.
