### ISSUE TITLE
dynamic-stack-buffer-overflow in test-async

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#33150]
### systemd version the issue has been seen with

main

### Used distribution

opensuse tumbleweed

### CPU architectures issue was seen on

None

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
957/1625 systemd:test / test-async                                                   FAIL             2.57s   killed by signal 6 SIGABRT
>>> EFI_ADDON=/work/build/src/boot/efi/addonx64.efi.stub SYSTEMD_SLOW_TESTS=0 MALLOC_PERTURB_=175 SYSTEMD_LANGUAGE_FALLBACK_MAP=/work/src/src/locale/language-fallback-map UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 PATH=/work/build:/work/scripts:/usr/bin:/usr/sbin LD_LIBRARY_PATH=/work/build/src/shared PROJECT_BUILD_ROOT=/work/build /work/build/test-async
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stderr:
/* test_asynchronous_sync */
Successfully forked off intermediary '(sd-sync)' as PID 1835363.
/* test_asynchronous_close */
=================================================================
==1835365==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffe58df2f00 at pc 0x7fa8bd07ccfc bp 0x7ffe58df0e70 sp 0x7ffe58df0640
WRITE of size 12288 at 0x7ffe58df2f00 thread T0 ((sd-close))
PR_SET_MM_ARG_START failed: Operation not permitted
    #0 0x7fa8bd07ccfb in __asan_memset (/usr/lib64/clang/18/lib/linux/libclang_rt.asan-x86_64.so+0x104cfb) (BuildId: 7fea6ed19f057640d1a38f3d162980f937efadca)
    #1 0x7fa8bc2ede34 in clone_with_nested_stack /work/build/../src/src/basic/process-util.c:1427:19
    #2 0x7fa8bb9026db in close_func /work/build/../src/src/shared/async.c:57:23
    #3 0x7fa8bad0edf3 in __clone (/lib64/libc.so.6+0x113df3) (BuildId: a2c0942c27fb9483b47886a1b937337a797bbceb)

Address 0x7ffe58df2f00 is located in stack of thread T0 ((sd-close))
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow /work/build/../src/src/basic/process-util.c:1427:19 in clone_with_nested_stack
Shadow bytes around the buggy address:
  0x7ffe58df2c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df2d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df2d80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df2e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df2e80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7ffe58df2f00:[ca]ca ca ca 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df2f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df3000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df3080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df3100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffe58df3180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1835365==ABORTING
src/test/test-async.c:30: Assertion failed: expected "fcntl(fd, F_GETFD) == -1", but "1 != -1"
```

**Comment by yuwata** [comment]
-> #33154.
