### ISSUE TITLE
systemd fails to build with libxml2 2.13.0

### ISSUE THREAD

**Issue by fishilico** [systemd/systemd#33302]
### systemd version the issue has been seen with

256 and master

### Used distribution

Arch Linux

### Linux kernel version used

not applicable

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Building systemd with `-Dman=enabled` works with libxml2 2.13.0.

### Unexpected behaviour you saw

Multiple failure when generating documentation files, such as:
```text
[42/2054] Generating man/systemd.directives.xml with a custom command
FAILED: man/systemd.directives.xml 
/tmp/git/systemd/tools/make-directive-index.py man/systemd.directives.xml ../man/directives-template.xml ../man/binfmt.d.xml ../man/bootctl.xml ../man/bootup.xml ../man/busctl.xml ../man/capsule@.service.xml ../man/coredump.conf.xml ../man/coredumpctl.xml ../man/crypttab.xml ../man/daemon.xml ../man/dnssec-trust-anchors.d.xml ../man/environment.d.xml ../man/file-hierarchy.xml ../man/homectl.xml ../man/homed.conf.xml ../man/hostname.xml ../man/hostnamectl.xml ../man/hwdb.xml ../man/importctl.xml ../man/integritytab.xml ../man/iocost.conf.xml ../man/journal-remote.conf.xml ../man/journal-upload.conf.xml ../man/journalctl.xml ../man/journald.conf.xml ../man/kernel-command-line.xml ../man/kernel-install.xml ../man/libsystemd.xml ../man/libudev.xml ../man/loader.conf.xml ../man/locale.conf.xml ../man/localectl.xml ../man/localtime.xml ../man/loginctl.xml ../man/logind.conf.xml ../man/machine-id.xml ../man/machine-info.xml ../man/machinectl.xml ../man/modules-load.d.xml ../man/networkctl.xml ../man/networkd.conf.xml ../man/nss-myhostname.xml ../man/nss-mymachines.xml ../man/nss-resolve.xml ../man/nss-systemd.xml ../man/oomctl.xml ../man/oomd.conf.xml ../man/org.freedesktop.LogControl1.xml ../man/org.freedesktop.home1.xml ../man/org.freedesktop.hostname1.xml ../man/org.freedesktop.import1.xml ../man/org.freedesktop.locale1.xml ../man/org.freedesktop.login1.xml ../man/org.freedesktop.machine1.xml ../man/org.freedesktop.network1.xml ../man/org.freedesktop.oom1.xml ../man/org.freedesktop.portable1.xml ../man/org.freedesktop.resolve1.xml ../man/org.freedesktop.systemd1.xml ../man/org.freedesktop.timedate1.xml ../man/os-release.xml ../man/pam_systemd.xml ../man/pam_systemd_home.xml ../man/pam_systemd_loadkey.xml ../man/portablectl.xml ../man/poweroff.xml ../man/pstore.conf.xml ../man/repart.d.xml ../man/resolvectl.xml ../man/resolved.conf.xml ../man/run0.xml ../man/runlevel.xml ../man/sd-bus-errors.xml ../man/sd-bus.xml ../man/sd-daemon.xml ../man/sd-device.xml ../man/sd-event.xml ../man/sd-hwdb.xml ../man/sd-id128.xml ../man/sd-journal.xml ../man/sd-json.xml ../man/sd-login.xml ../man/sd_booted.xml ../man/sd_bus_add_match.xml ../man/sd_bus_add_node_enumerator.xml ../man/sd_bus_add_object.xml ../man/sd_bus_add_object_manager.xml ../man/sd_bus_attach_event.xml ../man/sd_bus_call.xml ../man/sd_bus_call_method.xml ../man/sd_bus_can_send.xml ../man/sd_bus_close.xml ../man/sd_bus_creds_get_pid.xml ../man/sd_bus_creds_new_from_pid.xml ../man/sd_bus_default.xml ../man/sd_bus_emit_signal.xml ../man/sd_bus_enqueue_for_read.xml ../man/sd_bus_error.xml ../man/sd_bus_error_add_map.xml ../man/sd_bus_get_current_handler.xml ../man/sd_bus_get_fd.xml ../man/sd_bus_get_n_queued_read.xml ../man/sd_bus_get_name_creds.xml ../man/sd_bus_get_name_machine_id.xml ../man/sd_bus_interface_name_is_valid.xml ../man/sd_bus_is_open.xml ../man/sd_bus_list_names.xml ../man/sd_bus_message_append.xml ../man/sd_bus_message_append_array.xml ../man/sd_bus_message_append_basic.xml ../man/sd_bus_message_append_string_memfd.xml ../man/sd_bus_message_append_strv.xml ../man/sd_bus_message_at_end.xml ../man/sd_bus_message_copy.xml ../man/sd_bus_message_dump.xml ../man/sd_bus_message_get_cookie.xml ../man/sd_bus_message_get_monotonic_usec.xml ../man/sd_bus_message_get_signature.xml ../man/sd_bus_message_get_type.xml ../man/sd_bus_message_new.xml ../man/sd_bus_message_new_method_call.xml ../man/sd_bus_message_new_method_error.xml ../man/sd_bus_message_new_signal.xml ../man/sd_bus_message_open_container.xml ../man/sd_bus_message_read.xml ../man/sd_bus_message_read_array.xml ../man/sd_bus_message_read_basic.xml ../man/sd_bus_message_read_strv.xml ../man/sd_bus_message_rewind.xml ../man/sd_bus_message_seal.xml ../man/sd_bus_message_sensitive.xml ../man/sd_bus_message_set_destination.xml ../man/sd_bus_message_set_expect_reply.xml ../man/sd_bus_message_skip.xml ../man/sd_bus_message_verify_type.xml ../man/sd_bus_negotiate_fds.xml ../man/sd_bus_new.xml ../man/sd_bus_path_encode.xml ../man/sd_bus_pending_method_calls.xml ../man/sd_bus_process.xml ../man/sd_bus_query_sender_creds.xml ../man/sd_bus_reply_method_error.xml ../man/sd_bus_reply_method_return.xml ../man/sd_bus_request_name.xml ../man/sd_bus_send.xml ../man/sd_bus_set_address.xml ../man/sd_bus_set_close_on_exit.xml ../man/sd_bus_set_connected_signal.xml ../man/sd_bus_set_description.xml ../man/sd_bus_set_exit_on_disconnect.xml ../man/sd_bus_set_fd.xml ../man/sd_bus_set_method_call_timeout.xml ../man/sd_bus_set_property.xml ../man/sd_bus_set_sender.xml ../man/sd_bus_set_server.xml ../man/sd_bus_set_watch_bind.xml ../man/sd_bus_slot_get_bus.xml ../man/sd_bus_slot_ref.xml ../man/sd_bus_slot_set_description.xml ../man/sd_bus_slot_set_destroy_callback.xml ../man/sd_bus_slot_set_floating.xml ../man/sd_bus_slot_set_userdata.xml ../man/sd_bus_start.xml ../man/sd_bus_track_add_name.xml ../man/sd_bus_track_new.xml ../man/sd_bus_wait.xml ../man/sd_device_get_syspath.xml ../man/sd_device_ref.xml ../man/sd_event_add_child.xml ../man/sd_event_add_defer.xml ../man/sd_event_add_inotify.xml ../man/sd_event_add_io.xml ../man/sd_event_add_memory_pressure.xml ../man/sd_event_add_signal.xml ../man/sd_event_add_time.xml ../man/sd_event_exit.xml ../man/sd_event_get_fd.xml ../man/sd_event_new.xml ../man/sd_event_now.xml ../man/sd_event_run.xml ../man/sd_event_set_signal_exit.xml ../man/sd_event_set_watchdog.xml ../man/sd_event_source_get_event.xml ../man/sd_event_source_get_pending.xml ../man/sd_event_source_set_description.xml ../man/sd_event_source_set_destroy_callback.xml ../man/sd_event_source_set_enabled.xml ../man/sd_event_source_set_exit_on_failure.xml ../man/sd_event_source_set_floating.xml ../man/sd_event_source_set_prepare.xml ../man/sd_event_source_set_priority.xml ../man/sd_event_source_set_ratelimit.xml ../man/sd_event_source_set_userdata.xml ../man/sd_event_source_unref.xml ../man/sd_event_wait.xml ../man/sd_get_seats.xml ../man/sd_hwdb_get.xml ../man/sd_hwdb_new.xml ../man/sd_id128_get_machine.xml ../man/sd_id128_randomize.xml ../man/sd_id128_to_string.xml ../man/sd_is_fifo.xml ../man/sd_journal_add_match.xml ../man/sd_journal_enumerate_fields.xml ../man/sd_journal_get_catalog.xml ../man/sd_journal_get_cursor.xml ../man/sd_journal_get_cutoff_realtime_usec.xml ../man/sd_journal_get_data.xml ../man/sd_journal_get_fd.xml ../man/sd_journal_get_realtime_usec.xml ../man/sd_journal_get_seqnum.xml ../man/sd_journal_get_usage.xml ../man/sd_journal_has_runtime_files.xml ../man/sd_journal_next.xml ../man/sd_journal_open.xml ../man/sd_journal_print.xml ../man/sd_journal_query_unique.xml ../man/sd_journal_seek_head.xml ../man/sd_journal_stream_fd.xml ../man/sd_listen_fds.xml ../man/sd_login_monitor_new.xml ../man/sd_machine_get_class.xml ../man/sd_notify.xml ../man/sd_path_lookup.xml ../man/sd_pid_get_owner_uid.xml ../man/sd_seat_get_active.xml ../man/sd_session_is_active.xml ../man/sd_uid_get_state.xml ../man/sd_watchdog_enabled.xml ../man/shutdown.xml ../man/smbios-type-11.xml ../man/sysctl.d.xml ../man/systemctl.xml ../man/systemd-ac-power.xml ../man/systemd-analyze.xml ../man/systemd-ask-password-console.service.xml ../man/systemd-ask-password.xml ../man/systemd-backlight@.service.xml ../man/systemd-battery-check.service.xml ../man/systemd-binfmt.service.xml ../man/systemd-bless-boot-generator.xml ../man/systemd-bless-boot.service.xml ../man/systemd-boot-check-no-failures.service.xml ../man/systemd-boot-random-seed.service.xml ../man/systemd-boot.xml ../man/systemd-bsod.service.xml ../man/systemd-cat.xml ../man/systemd-cgls.xml ../man/systemd-cgtop.xml ../man/systemd-coredump.xml ../man/systemd-creds.xml ../man/systemd-cryptenroll.xml ../man/systemd-cryptsetup-generator.xml ../man/systemd-cryptsetup.xml ../man/systemd-debug-generator.xml ../man/systemd-delta.xml ../man/systemd-detect-virt.xml ../man/systemd-dissect.xml ../man/systemd-environment-d-generator.xml ../man/systemd-escape.xml ../man/systemd-firstboot.xml ../man/systemd-fsck@.service.xml ../man/systemd-fstab-generator.xml ../man/systemd-getty-generator.xml ../man/systemd-gpt-auto-generator.xml ../man/systemd-hibernate-resume-generator.xml ../man/systemd-hibernate-resume.service.xml ../man/systemd-homed.service.xml ../man/systemd-hostnamed.service.xml ../man/systemd-hwdb.xml ../man/systemd-id128.xml ../man/systemd-importd.service.xml ../man/systemd-inhibit.xml ../man/systemd-initctl.service.xml ../man/systemd-integritysetup-generator.xml ../man/systemd-integritysetup@.service.xml ../man/systemd-journal-gatewayd.service.xml ../man/systemd-journal-remote.service.xml ../man/systemd-journal-upload.service.xml ../man/systemd-journald.service.xml ../man/systemd-localed.service.xml ../man/systemd-logind.service.xml ../man/systemd-machine-id-commit.service.xml ../man/systemd-machine-id-setup.xml ../man/systemd-machined.service.xml ../man/systemd-makefs@.service.xml ../man/systemd-measure.xml ../man/systemd-modules-load.service.xml ../man/systemd-mount.xml ../man/systemd-mountfsd.service.xml ../man/systemd-network-generator.service.xml ../man/systemd-networkd-wait-online.service.xml ../man/systemd-networkd.service.xml ../man/systemd-notify.xml ../man/systemd-nspawn.xml ../man/systemd-nsresourced.service.xml ../man/systemd-oomd.service.xml ../man/systemd-path.xml ../man/systemd-pcrlock.xml ../man/systemd-pcrphase.service.xml ../man/systemd-portabled.service.xml ../man/systemd-poweroff.service.xml ../man/systemd-pstore.service.xml ../man/systemd-quotacheck.service.xml ../man/systemd-random-seed.service.xml ../man/systemd-rc-local-generator.xml ../man/systemd-remount-fs.service.xml ../man/systemd-repart.xml ../man/systemd-resolved.service.xml ../man/systemd-rfkill.service.xml ../man/systemd-run-generator.xml ../man/systemd-run.xml ../man/systemd-sleep.conf.xml ../man/systemd-socket-activate.xml ../man/systemd-socket-proxyd.xml ../man/systemd-soft-reboot.service.xml ../man/systemd-ssh-generator.xml ../man/systemd-ssh-proxy.xml ../man/systemd-stdio-bridge.xml ../man/systemd-storagetm.service.xml ../man/systemd-stub.xml ../man/systemd-suspend.service.xml ../man/systemd-sysctl.service.xml ../man/systemd-sysext.xml ../man/systemd-system-update-generator.xml ../man/systemd-system.conf.xml ../man/systemd-sysupdate.xml ../man/systemd-sysusers.xml ../man/systemd-sysv-generator.xml ../man/systemd-time-wait-sync.service.xml ../man/systemd-timedated.service.xml ../man/systemd-timesyncd.service.xml ../man/systemd-tmpfiles.xml ../man/systemd-tpm2-generator.xml ../man/systemd-tpm2-setup.service.xml ../man/systemd-tty-ask-password-agent.xml ../man/systemd-udev-settle.service.xml ../man/systemd-udevd.service.xml ../man/systemd-update-done.service.xml ../man/systemd-update-utmp.service.xml ../man/systemd-user-sessions.service.xml ../man/systemd-userdbd.service.xml ../man/systemd-vconsole-setup.service.xml ../man/systemd-veritysetup-generator.xml ../man/systemd-veritysetup@.service.xml ../man/systemd-vmspawn.xml ../man/systemd-volatile-root.service.xml ../man/systemd-vpick.xml ../man/systemd-xdg-autostart-generator.xml ../man/systemd.xml ../man/systemd.automount.xml ../man/systemd.device.xml ../man/systemd.dnssd.xml ../man/systemd.environment-generator.xml ../man/systemd.exec.xml ../man/systemd.generator.xml ../man/systemd.image-policy.xml ../man/systemd.journal-fields.xml ../man/systemd.kill.xml ../man/systemd.link.xml ../man/systemd.mount.xml ../man/systemd.net-naming-scheme.xml ../man/systemd.netdev.xml ../man/systemd.network.xml ../man/systemd.nspawn.xml ../man/systemd.offline-updates.xml ../man/systemd.path.xml ../man/systemd.pcrlock.xml ../man/systemd.preset.xml ../man/systemd.resource-control.xml ../man/systemd.scope.xml ../man/systemd.service.xml ../man/systemd.slice.xml ../man/systemd.socket.xml ../man/systemd.special.xml ../man/systemd.swap.xml ../man/systemd.syntax.xml ../man/systemd.system-credentials.xml ../man/systemd.target.xml ../man/systemd.time.xml ../man/systemd.timer.xml ../man/systemd.unit.xml ../man/systemd.v.xml ../man/sysupdate.d.xml ../man/sysusers.d.xml ../man/telinit.xml ../man/timedatectl.xml ../man/timesyncd.conf.xml ../man/tmpfiles.d.xml ../man/udev.xml ../man/udev.conf.xml ../man/udev_device_get_syspath.xml ../man/udev_device_has_tag.xml ../man/udev_device_new_from_syspath.xml ../man/udev_enumerate_add_match_subsystem.xml ../man/udev_enumerate_new.xml ../man/udev_enumerate_scan_devices.xml ../man/udev_list_entry.xml ../man/udev_monitor_filter_update.xml ../man/udev_monitor_new_from_netlink.xml ../man/udev_monitor_receive_device.xml ../man/udev_new.xml ../man/udevadm.xml ../man/ukify.xml ../man/user@.service.xml ../man/userdbctl.xml ../man/varlinkctl.xml ../man/vconsole.conf.xml ../man/veritytab.xml
Traceback (most recent call last):
  File "/tmp/git/systemd/tools/make-directive-index.py", line 164, in make_page
    _extract_directives(directive_groups, formatting, page)
  File "/tmp/git/systemd/tools/make-directive-index.py", line 17, in _extract_directives
    t = xml_parse(page)
        ^^^^^^^^^^^^^^^
  File "/tmp/git/systemd/tools/xml_helper.py", line 22, in xml_parse
    doc.xinclude()
  File "src/lxml/etree.pyx", line 2432, in lxml.etree._ElementTree.xinclude
  File "src/lxml/xinclude.pxi", line 64, in lxml.etree.XInclude.__call__
lxml.etree.XIncludeError: XPointer evaluation failed: #xpointer(//varlistentry[@id='option-P']/listitem/para), line 280

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/git/systemd/tools/make-directive-index.py", line 174, in <module>
    _xml = make_page(_template_path, _xml_files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/git/systemd/tools/make-directive-index.py", line 166, in make_page
    raise ValueError("failed to process " + page) from e
ValueError: failed to process ../man/machinectl.xml
```

### Steps to reproduce the problem

1. Launch a "clean" Arch Linux container. I am using: `podman run --rm -it docker.io/archlinux/archlinux`

2. Install build dependencies in the container, using the list from the official Arch Linux package (https://gitlab.archlinux.org/archlinux/packaging/packages/systemd/-/blob/baf4803252a7e1803642423cb2ef302144327287/PKGBUILD#L18):
```sh
pacman -Syu pacman -Syu base-devel git acl cryptsetup docbook-xsl gperf lz4 xz pam libelf intltool iptables kmod libcap libidn2 libgcrypt libmicrohttpd libxcrypt libxslt util-linux linux-api-headers python-jinja python-lxml quota-tools shadow git meson libseccomp pcre2 audit kexec-tools libxkbcommon bash-completion p11-kit systemd libfido2 tpm2-tss rsync bpf libbpf clang llvm curl gnutls python-pyelftools libpwquality qrencode lib32-gcc-libs python-pefile
```

3. Download systemd (at the time of writing, this cloned branch `main` at commit 7811864b08393eda5ff92145ea2776180d9b28ee):
```sh
cd /tmp && git clone https://github.com/systemd/systemd.git
```

4. Configure the build with man pages
```sh
cd systemd && meson build -Dman=enabled
```

5. Compile with one job, to make things more reproducible:
```sh
meson compile -C build -j1
```

This fails in `Generating man/systemd.directives.xml with a custom command` with:

```text
Traceback (most recent call last):
  File "/tmp/systemd/tools/make-directive-index.py", line 164, in make_page
    _extract_directives(directive_groups, formatting, page)
  File "/tmp/systemd/tools/make-directive-index.py", line 17, in _extract_directives
    t = xml_parse(page)
        ^^^^^^^^^^^^^^^
  File "/tmp/systemd/tools/xml_helper.py", line 22, in xml_parse
    doc.xinclude()
  File "src/lxml/etree.pyx", line 2432, in lxml.etree._ElementTree.xinclude
  File "src/lxml/xinclude.pxi", line 64, in lxml.etree.XInclude.__call__
lxml.etree.XIncludeError: XPointer evaluation failed: #xpointer(//varlistentry[@id='option-P']/listitem/para), line 280

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/systemd/tools/make-directive-index.py", line 174, in <module>
    _xml = make_page(_template_path, _xml_files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/systemd/tools/make-directive-index.py", line 166, in make_page
    raise ValueError("failed to process " + page) from e
ValueError: failed to process ../man/machinectl.xml
ninja: build stopped: subcommand failed.
```

6. As `libxml2` was updated yesterday, downgrade it from `2.13.0-1` to `2.12.7-1`:
```sh
curl -sSO https://archive.archlinux.org/packages/l/libxml2/libxml2-2.12.7-1-x86_64.pkg.tar.zst
pacman -U libxml2-2.12.7-1-x86_64.pkg.tar.zst
meson compile -C build -j1
```

... with this, building continues and succeeds.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Problematic `libxml2` version on Arch Linux:

$ pacman -Qi libxml2
Name            : libxml2
Version         : 2.13.0-1
Description     : XML C parser and toolkit
Architecture    : x86_64
URL             : https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home
Licenses        : MIT
Groups          : None
Provides        : libxml2.so=2-64
Depends On      : glibc  icu  ncurses  readline  xz  zlib
Optional Deps   : python: Python bindings [installed]
Required By     : docbook-xml  docbook-xsl  gettext  libarchive  libxkbcommon  libxslt  llvm-libs
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 3.45 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Wed Jun 12 19:55:19 2024
Install Date    : Thu Jun 13 08:33:37 2024
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by keszybz** [comment]
I see two problems with the updated libxml2:
- includes like `<xi:include href="standard-options.xml" xpointer="xpointer(//varlistentry[@id='option-P']/listitem/para)" />` stopped working.
- loading of files from path is broken: 
```
$ /usr/bin/xsltproc -o man/systemd.link.5 --nonet --xinclude --maxdepth 9000 --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 --stringparam systemd.version '257~devel' --path /home/zbyszek/src/systemd/build-rawhide/man:/home/zbyszek/src/systemd/man:/home/zbyszek/src/systemd/build-rawhide/src/shared ../man/custom-man.xsl ../man/systemd.link.xml
I/O error : failed to load "../man/ethtool-link-mode.xml": No such file or directory
I/O error : failed to load "/home/zbyszek/src/systemd/build-rawhide/man/ethtool-link-mode.xml": No such file or directory
I/O error : failed to load "/home/zbyszek/src/systemd/man/ethtool-link-mode.xml": No such file or directory
../man/systemd.link.xml:888: element include: XInclude error : could not load ../man/ethtool-link-mode.xml, and no fallback was found
```
But the file is there:
```
$ file /home/zbyszek/src/systemd/build-rawhide/src/shared/ethtool-link-mode.xml
/home/zbyszek/src/systemd/build-rawhide/src/shared/ethtool-link-mode.xml: ASCII text
```

**Comment by poettering** [comment]
What does strace say?

**Comment by keszybz** [comment]
[libxml2-2.13.0-xslt-strace.log](https://github.com/user-attachments/files/15836854/libxml2-2.13.0-xslt-strace.log)

The log is … surprising.

**Comment by mrc0mmand** [comment]
Looking at https://gitlab.gnome.org/GNOME/libxml2/-/commit/669bd3499399b3a44b7788ce943e7194d7a48c3f it looks like the `xpointer` stuff is not in the latest Arch's libxml2, since it's not built with `--with-xptr-locs `.

**Comment by keszybz** [comment]
> Hmmm, maybe this?
> 
> > Support for FTP and xpointer() XPath extensions will be removed in the next release.
> 
> https://github.com/GNOME/libxml2/blob/master/NEWS#L33C1-L35C1

That talks about the next release, so it's not clear.



> not built with `--with-xptr-locs`.

I rebuilt the Fedora package with `--with-xptr-locs` and the first error went away. But the second error remains.

**Comment by mrc0mmand** [comment]
> > Hmmm, maybe this?
> > > Support for FTP and xpointer() XPath extensions will be removed in the next release.
> > 
> > 
> > https://github.com/GNOME/libxml2/blob/master/NEWS#L33C1-L35C1
> 
> That talks about the next release, so it's not clear.
> 
> > not built with `--with-xptr-locs`.
> 
> I rebuilt the Fedora package with `--with-xptr-locs` and the first error went away. But the second error remains.

I did a bisect and it points to https://gitlab.gnome.org/GNOME/libxml2/-/commit/78eab7a1301fc56481aac37602310034fd0bec05 - if I revert it, the error disappears, at least for me. I guess the new error propagation is way too eager.

**Comment by xry111** [comment]
I opened https://gitlab.gnome.org/GNOME/libxml2/-/issues/733

**Comment by keszybz** [comment]
Everything works fine with libxml2-2.13.0 built with the two patches applied. Nothing for us to fix here.
