### ISSUE TITLE
Assertion failure in systemd-user-runtime-dir

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#33388]
```
06:46:08 [coredumpctl_collect] Collecting coredumps for '/usr/lib/systemd/systemd-user-runtime-dir'
06:46:08            PID: 86517 (4)
06:46:08            UID: 0 (root)
06:46:08            GID: 0 (root)
06:46:08         Signal: 6 (ABRT)
06:46:08      Timestamp: Tue 2024-06-18 05:15:50 UTC (30min ago)
06:46:08   Command Line: /usr/lib/systemd/systemd-user-runtime-dir start 4711
06:46:08     Executable: /usr/lib/systemd/systemd-user-runtime-dir
06:46:08  Control Group: /machine.slice/TEST-05-RLIMITS.scope/payload/user.slice/user-4711.slice/user-runtime-dir@4711.service
06:46:08           Unit: TEST-05-RLIMITS.scope
06:46:08          Slice: machine.slice
06:46:08        Boot ID: b1a58a71b49a461d908b74d7f0a0b6ee
06:46:08     Machine ID: be6cb34bafe44505be1bbd095bc17ed7
06:46:08       Hostname: H
06:46:08        Storage: /var/lib/systemd/coredump/core.4.0.b1a58a71b49a461d908b74d7f0a0b6ee.86517.1718687750000000.zst (present)
06:46:08   Size on Disk: 146.5K
06:46:08        Message: Process 86517 (4) of user 0 dumped core.
06:46:08                 
06:46:08                 Stack trace of thread 46:
06:46:08                 #0  0x00007aea906a8e44 n/a (libc.so.6 + 0x94e44)
06:46:08                 #1  0x00007aea90650a30 raise (libc.so.6 + 0x3ca30)
06:46:08                 #2  0x00007aea906384c3 abort (libc.so.6 + 0x244c3)
06:46:08                 #3  0x00007aea90a1ab93 log_assert_failed (libsystemd-shared-257.so + 0x21ab93)
06:46:08                 #4  0x00007aea90a1bf67 log_assert_failed_return (libsystemd-shared-257.so + 0x21bf67)
06:46:08                 #5  0x00007aea90a94a7b sd_bus_call (libsystemd-shared-257.so + 0x294a7b)
06:46:08                 #6  0x00007aea90a637ee sd_bus_call_methodv (libsystemd-shared-257.so + 0x2637ee)
06:46:08                 #7  0x00007aea90a63885 sd_bus_call_method (libsystemd-shared-257.so + 0x263885)
06:46:08                 #8  0x00007aea90a647f1 sd_bus_get_property_trivial (libsystemd-shared-257.so + 0x2647f1)
06:46:08                 #9  0x00007aea908a76a2 bus_get_property_trivial (libsystemd-shared-257.so + 0xa76a2)
06:46:08                 #10 0x00005d583eb055d3 acquire_runtime_dir_properties (systemd-user-runtime-dir + 0x25d3)
06:46:08                 #11 0x00005d583eb05db0 do_mount (systemd-user-runtime-dir + 0x2db0)
06:46:08                 #12 0x00005d583eb06404 run (systemd-user-runtime-dir + 0x3404)
06:46:08                 #13 0x00005d583eb0651f main (systemd-user-runtime-dir + 0x351f)
06:46:08                 #14 0x00007aea90639c88 n/a (libc.so.6 + 0x25c88)
06:46:08                 #15 0x00007aea90639d4c __libc_start_main (libc.so.6 + 0x25d4c)
06:46:08                 #16 0x00005d583eb052a5 _start (systemd-user-runtime-dir + 0x22a5)
06:46:08                 ELF object binary architecture: AMD x86-64
06:46:08 [coredumpctl_collect] $BUILD_DIR is set and 'systemd-user-runtime-dir' was found in it
06:46:08 [coredumpctl_collect] Overriding the executable to '/systemd-meson-build/systemd-user-runtime-dir' and gdb command to 'file /systemd-meson-build/systemd-user-runtime-dir\nthread apply all bt\nset print pretty on\nbt full'
06:46:08 
06:46:08 
06:46:08 [coredumpctl_collect] Trying to run gdb with 'file /systemd-meson-build/systemd-user-runtime-dir\nthread apply all bt\nset print pretty on\nbt full' for '/usr/lib/systemd/systemd-user-runtime-dir'
06:46:08 GNU gdb (GDB) 14.2
06:46:08 Copyright (C) 2023 Free Software Foundation, Inc.
06:46:08 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
06:46:08 This is free software: you are free to change and redistribute it.
06:46:08 There is NO WARRANTY, to the extent permitted by law.
06:46:08 Type "show copying" and "show warranty" for details.
06:46:08 This GDB was configured as "x86_64-pc-linux-gnu".
06:46:08 Type "show configuration" for configuration details.
06:46:08 For bug reporting instructions, please see:
06:46:08 <https://www.gnu.org/software/gdb/bugs/>.
06:46:08 Find the GDB manual and other documentation resources online at:
06:46:08     <http://www.gnu.org/software/gdb/documentation/>.
06:46:08 
06:46:08 For help, type "help".
06:46:08 Type "apropos word" to search for commands related to "word"...
06:46:08 Reading symbols from /usr/lib/systemd/systemd-user-runtime-dir...
06:46:08 [New LWP 46]
06:46:08 
06:46:08 This GDB supports auto-downloading debuginfo from the following URLs:
06:46:08   <https://debuginfod.archlinux.org/>
06:46:08 Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
06:46:08 Debuginfod has been disabled.
06:46:08 To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
06:46:08 [Thread debugging using libthread_db enabled]
06:46:08 Using host libthread_db library "/usr/lib/libthread_db.so.1".
06:46:08 Core was generated by `/usr/lib/systemd/systemd-user-runtime-dir start 4711'.
06:46:08 Program terminated with signal SIGABRT, Aborted.
06:46:08 #0  0x00007aea906a8e44 in ?? () from /usr/lib/libc.so.6
06:46:08 (gdb) Load new symbol table from "/systemd-meson-build/systemd-user-runtime-dir"? (y or n) [answered Y; input not from terminal]
06:46:08 Reading symbols from /systemd-meson-build/systemd-user-runtime-dir...
06:46:08 (gdb) 
06:46:08 Thread 1 (Thread 0x7aea90c8c940 (LWP 46)):
06:46:08 #0  0x00007aea906a8e44 in ?? () from /usr/lib/libc.so.6
06:46:08 #1  0x00007aea90650a30 in raise () from /usr/lib/libc.so.6
06:46:08 #2  0x00007aea906384c3 in abort () from /usr/lib/libc.so.6
06:46:08 #3  0x00007aea90a1ab93 in log_assert_failed (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ../build/src/basic/log.c:992
06:46:08 #4  0x00007aea90a1bf67 in log_assert_failed_return (text=text@entry=0x7aea90b5f4e9 "!bus_error_is_dirty(error)", file=file@entry=0x7aea90b3cba9 "src/libsystemd/sd-bus/sd-bus.c", line=line@entry=2428, func=func@entry=0x7aea90b85940 <__func__.69> "sd_bus_call") at ../build/src/basic/log.c:1011
06:46:08 #5  0x00007aea90a94a7b in sd_bus_call (bus=bus@entry=0x5d5848df5eb0, _m=<optimized out>, usec=usec@entry=0, error=error@entry=0x7ffe0fa86420, reply=reply@entry=0x7ffe0fa86398) at ../build/src/libsystemd/sd-bus/sd-bus.c:2428
06:46:08 #6  0x00007aea90a637ee in sd_bus_call_methodv (bus=0x5d5848df5eb0, destination=0x7aea90b47c2c "org.freedesktop.login1", path=0x7aea90b47c43 "/org/freedesktop/login1", interface=0x7aea90b081c0 "org.freedesktop.DBus.Properties", member=0x7aea90b5df4a "Get", error=0x7ffe0fa86420, reply=0x7ffe0fa86398, types=0x7aea90b56236 "ss", ap=0x7ffe0fa86270) at ../build/src/libsystemd/sd-bus/bus-convenience.c:183
06:46:08 #7  0x00007aea90a63885 in sd_bus_call_method (bus=bus@entry=0x5d5848df5eb0, destination=destination@entry=0x7aea90b47c2c "org.freedesktop.login1", path=path@entry=0x7aea90b47c43 "/org/freedesktop/login1", interface=interface@entry=0x7aea90b081c0 "org.freedesktop.DBus.Properties", member=member@entry=0x7aea90b5df4a "Get", error=error@entry=0x7ffe0fa86420, reply=0x7ffe0fa86398, types=0x7aea90b56236 "ss") at ../build/src/libsystemd/sd-bus/bus-convenience.c:203
06:46:08 #8  0x00007aea90a647f1 in sd_bus_get_property_trivial (bus=0x5d5848df5eb0, destination=0x7aea90b47c2c "org.freedesktop.login1", path=0x7aea90b47c43 "/org/freedesktop/login1", interface=<optimized out>, member=member@entry=0x5d583eb07516 "RuntimeDirectoryInodesMax", error=error@entry=0x7ffe0fa86420, type=116 't', ptr=0x7ffe0fa868a8) at ../build/src/libsystemd/sd-bus/bus-convenience.c:462
06:46:08 #9  0x00007aea908a76a2 in bus_get_property_trivial (bus=<optimized out>, locator=locator@entry=0x7aea90c17130 <__compound_literal.3>, member=member@entry=0x5d583eb07516 "RuntimeDirectoryInodesMax", error=error@entry=0x7ffe0fa86420, type=type@entry=116 't', ptr=ptr@entry=0x7ffe0fa868a8) at ../build/src/shared/bus-locator.c:149
06:46:08 #10 0x00005d583eb055d3 in acquire_runtime_dir_properties (size=size@entry=0x7ffe0fa868a0, inodes=inodes@entry=0x7ffe0fa868a8) at ../build/src/login/user-runtime-dir.c:43
06:46:08 #11 0x00005d583eb05db0 in do_mount (user=<optimized out>) at ../build/src/login/user-runtime-dir.c:157
06:46:08 #12 0x00005d583eb06404 in run (argc=argc@entry=3, argv=argv@entry=0x7ffe0fa86a68) at ../build/src/login/user-runtime-dir.c:209
06:46:08 #13 0x00005d583eb0651f in main (argc=3, argv=0x7ffe0fa86a68) at ../build/src/login/user-runtime-dir.c:215
06:46:08 (gdb) (gdb) #0  0x00007aea906a8e44 in ?? () from /usr/lib/libc.so.6
06:46:08 No symbol table info available.
06:46:08 #1  0x00007aea90650a30 in raise () from /usr/lib/libc.so.6
06:46:08 No symbol table info available.
06:46:08 #2  0x00007aea906384c3 in abort () from /usr/lib/libc.so.6
06:46:08 No symbol table info available.
06:46:08 #3  0x00007aea90a1ab93 in log_assert_failed (text=<optimized out>, 
06:46:08     file=<optimized out>, line=<optimized out>, func=<optimized out>)
06:46:08     at ../build/src/basic/log.c:992
06:46:08 No locals.
06:46:08 #4  0x00007aea90a1bf67 in log_assert_failed_return (
06:46:08     text=text@entry=0x7aea90b5f4e9 "!bus_error_is_dirty(error)", 
06:46:08     file=file@entry=0x7aea90b3cba9 "src/libsystemd/sd-bus/sd-bus.c", 
06:46:08     line=line@entry=2428, 
06:46:08     func=func@entry=0x7aea90b85940 <__func__.69> "sd_bus_call")
06:46:08     at ../build/src/basic/log.c:1011
06:46:08         _saved_errno_ = 32766
06:46:08 #5  0x00007aea90a94a7b in sd_bus_call (bus=bus@entry=0x5d5848df5eb0, 
06:46:08     _m=<optimized out>, usec=usec@entry=0, error=error@entry=0x7ffe0fa86420, 
06:46:08     reply=reply@entry=0x7ffe0fa86398)
06:46:08     at ../build/src/libsystemd/sd-bus/sd-bus.c:2428
06:46:08         m = 0x5d5848dfa0b0
06:46:08         timeout = <optimized out>
06:46:08         cookie = 0
06:46:08         i = <optimized out>
06:46:08         r = <optimized out>
06:46:08         __func__ = "sd_bus_call"
06:46:08 #6  0x00007aea90a637ee in sd_bus_call_methodv (bus=0x5d5848df5eb0, 
06:46:08     destination=0x7aea90b47c2c "org.freedesktop.login1", 
06:46:08     path=0x7aea90b47c43 "/org/freedesktop/login1", 
06:46:08     interface=0x7aea90b081c0 "org.freedesktop.DBus.Properties", 
06:46:08     member=0x7aea90b5df4a "Get", error=0x7ffe0fa86420, reply=0x7ffe0fa86398, 
06:46:08     types=0x7aea90b56236 "ss", ap=0x7ffe0fa86270)
06:46:08     at ../build/src/libsystemd/sd-bus/bus-convenience.c:183
06:46:08         m = 0x5d5848dfa0b0
06:46:08         r = <optimized out>
06:46:08         __func__ = "sd_bus_call_methodv"
06:46:08 #7  0x00007aea90a63885 in sd_bus_call_method (bus=bus@entry=0x5d5848df5eb0, 
06:46:08     destination=destination@entry=0x7aea90b47c2c "org.freedesktop.login1", 
06:46:08     path=path@entry=0x7aea90b47c43 "/org/freedesktop/login1", 
06:46:08     interface=interface@entry=0x7aea90b081c0 "org.freedesktop.DBus.Properties", member=member@entry=0x7aea90b5df4a "Get", error=error@entry=0x7ffe0fa86420, 
06:46:08     reply=0x7ffe0fa86398, types=0x7aea90b56236 "ss")
06:46:08     at ../build/src/libsystemd/sd-bus/bus-convenience.c:203
06:46:08         ap = {{
06:46:08             gp_offset = 48,
06:46:08             fp_offset = 48,
06:46:08             overflow_arg_area = 0x7ffe0fa86370,
06:46:08             reg_save_area = 0x7ffe0fa86290
06:46:08           }}
06:46:08         r = <optimized out>
06:46:08 #8  0x00007aea90a647f1 in sd_bus_get_property_trivial (bus=0x5d5848df5eb0, 
06:46:08     destination=0x7aea90b47c2c "org.freedesktop.login1", 
06:46:08     path=0x7aea90b47c43 "/org/freedesktop/login1", interface=<optimized out>, 
06:46:08     member=member@entry=0x5d583eb07516 "RuntimeDirectoryInodesMax", 
06:46:08     error=error@entry=0x7ffe0fa86420, type=116 't', ptr=0x7ffe0fa868a8)
06:46:08     at ../build/src/libsystemd/sd-bus/bus-convenience.c:462
06:46:08         reply = 0x0
06:46:08         r = <optimized out>
06:46:08         __func__ = "sd_bus_get_property_trivial"
06:46:08 #9  0x00007aea908a76a2 in bus_get_property_trivial (bus=<optimized out>, 
06:46:08     locator=locator@entry=0x7aea90c17130 <__compound_literal.3>, 
06:46:08     member=member@entry=0x5d583eb07516 "RuntimeDirectoryInodesMax", 
06:46:08     error=error@entry=0x7ffe0fa86420, type=type@entry=116 't', 
06:46:08     ptr=ptr@entry=0x7ffe0fa868a8) at ../build/src/shared/bus-locator.c:149
06:46:08         __func__ = "bus_get_property_trivial"
06:46:08 #10 0x00005d583eb055d3 in acquire_runtime_dir_properties (
06:46:08     size=size@entry=0x7ffe0fa868a0, inodes=inodes@entry=0x7ffe0fa868a8)
06:46:08     at ../build/src/login/user-runtime-dir.c:43
06:46:08         error = {
06:46:08           name = 0x5d5848df9c60 "org.freedesktop.DBus.Error.NameHasNoOwner",
06:46:08           message = 0x5d5848df6a20 "Could not activate remote peer 'org.freedesktop.login1': startup job failed",
06:46:08           _need_free = 1
06:46:08         }
06:46:08         bus = 0x5d5848df5eb0
06:46:08         r = -6
06:46:08         __func__ = "acquire_runtime_dir_properties"
06:46:08 #11 0x00005d583eb05db0 in do_mount (user=<optimized out>)
06:46:08     at ../build/src/login/user-runtime-dir.c:157
06:46:08         runtime_path = "\320h\250\017\376\177\000\000o铐\352z\000\000\320h\250\017\376"
06:46:08         runtime_dir_size = 13505048576
06:46:08         runtime_dir_inodes = 135147866873345
06:46:08         uid = 4711
06:46:08         gid = 4711
06:46:08         r = <optimized out>
06:46:08         __func__ = "do_mount"
06:46:08 #12 0x00005d583eb06404 in run (argc=argc@entry=3, 
06:46:08     argv=argv@entry=0x7ffe0fa86a68)
06:46:08     at ../build/src/login/user-runtime-dir.c:209
06:46:08         r = <optimized out>
06:46:08         __func__ = "run"
06:46:08 #13 0x00005d583eb0651f in main (argc=3, argv=0x7ffe0fa86a68)
06:46:08     at ../build/src/login/user-runtime-dir.c:215
06:46:08         r = <optimized out>
06:46:08         __func__ = "main"
```

https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux/15145/console

**Comment by bluca** [comment]
@mrc0mmand this looks new to me? Have you seen it before?

**Comment by mrc0mmand** [comment]
This indeed looks new, I haven't seen this before.
