### ISSUE TITLE
test-network: test_route_static randomly fails

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#34057]
https://autopkgtest.ubuntu.com/results/autopkgtest-noble-upstream-systemd-ci-systemd-ci/noble/amd64/s/systemd-upstream/20240821_054403_4603e@/log.gz
```
======================================================================
7292s [  187.396660] systemd-networkd-tests.py[441]: FAIL: test_route_static (__main__.NetworkdNetworkTests.test_route_static) (manage_foreign_routes=True)
7292s [  187.400920] systemd-networkd-tests.py[441]: ----------------------------------------------------------------------
7292s [  187.404671] systemd-networkd-tests.py[441]: Traceback (most recent call last):
7292s [  187.405520] systemd-networkd-tests.py[441]:   File "/usr/lib/systemd/tests/testdata/test-network/systemd-networkd-tests.py", line 3607, in test_route_static
7292s [  187.407324] systemd-networkd-tests.py[441]:     self._test_route_static(manage_foreign_routes)
7292s [  187.408740] systemd-networkd-tests.py[441]:   File "/usr/lib/systemd/tests/testdata/test-network/systemd-networkd-tests.py", line 3488, in _test_route_static
7292s [  187.409788] systemd-networkd-tests.py[441]:     self.assertIn('via 2001:1234:5:8fff:ff:ff:ff:ff dev dummy98', output)
7292s [  187.410497] systemd-networkd-tests.py[441]: AssertionError: 'via 2001:1234:5:8fff:ff:ff:ff:ff dev dummy98' not found in '2001:1234:5:bfff:ff:ff:ff:ff proto static metric 1024 pref medium\n\tnexthop via 2001:1234:5:9fff:ff:ff:ff:ff dev dummy98 weight 5 \n\tnexthop via 2001:1234:5:6fff:ff:ff:ff:ff dev test1 weight 20 \n\tnexthop via 2001:1234:5:7fff:ff:ff:ff:ff dev test1 weight 30'
7292s [  187.414682] systemd-networkd-tests.py[441]: ----------------------------------------------------------------------
```

**Comment by yuwata** [comment]
Duplicat of #34167 and fixed by c8dbf9acc10939f2d6c4bdd8cdee1d2ff9a4204e (#34213).
