### ISSUE TITLE
systemd-machined can be crashed by calling the List varlink method

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#34764]
### systemd version the issue has been seen with

2053182bd10c9c1cff0af6ec70c42e1aad321e09

### Used distribution

Fedora 40

### Linux kernel version used

Linux version 6.10.12-200.fc40.x86_64

### CPU architectures issue was seen on

None

### Component

systemd-machined

### Unexpected behaviour you saw

```sh
varlink: New incoming connection.
varlink: Connections of user 1000: 0 (of 576 max)
varlink-14-14: Setting state idle-server
varlink-14-14: Received message: {"method":"io.systemd.Machine.List","parameters":{"name":""}}
varlink-14-14: Changing state idle-server → processing-method
varlink-14-14: Sending message: {"error":"org.varlink.service.InvalidParameter","parameters":{"parameter":"name"}}
varlink-14-14: Changing state processing-method → processed-method
Assertion 'm' failed at src/machine/machined-varlink.c:397, function list_machine_one(). Aborting.
```
```sh
Assertion 'm' failed at src/machine/machined-varlink.c:397, function list_machine_one(). Aborting.
#0  0x00007f8ef7dc4664 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f8ef7d6bc4e in raise () from /lib64/libc.so.6
#2  0x00007f8ef7d53902 in abort () from /lib64/libc.so.6
#3  0x00007f8ef8993b1a in log_assert_failed (text=<optimized out>, file=<optimized out>, line=line@entry=397, func=<optimized out>) at ../src/basic/log.c:996
#4  0x000000000052a643 in list_machine_one (link=0x51300000d400, m=<optimized out>, more=<optimized out>) at ../src/machine/machined-varlink.c:397
#5  0x000000000052963d in vl_method_list (link=<optimized out>, parameters=<error reading variable: Cannot access memory at address 0x0>, 
    flags=<optimized out>, userdata=0x50c000000040) at ../src/machine/machined-varlink.c:454
#6  0x00007f8ef8ccb27c in varlink_dispatch_method (v=0x51300000d400) at ../src/libsystemd/sd-varlink/sd-varlink.c:1383
#7  sd_varlink_process (v=0x51300000d400) at ../src/libsystemd/sd-varlink/sd-varlink.c:1456
#8  0x00007f8ef8ce50f6 in defer_callback (s=s@entry=0x50e00000dda0, userdata=0x1709) at ../src/libsystemd/sd-varlink/sd-varlink.c:2880
#9  0x00007f8ef8b58b30 in source_dispatch (s=0x50e00000dda0) at ../src/libsystemd/sd-event/sd-event.c:4260
#10 0x00007f8ef8b5703a in sd_event_dispatch (e=e@entry=0x517000000080) at ../src/libsystemd/sd-event/sd-event.c:4849
#11 0x00007f8ef8b5af9a in sd_event_run (e=0x517000000080, timeout=<optimized out>) at ../src/libsystemd/sd-event/sd-event.c:4910
#12 0x00007f8ef8606a86 in bus_event_loop_with_idle (e=0x517000000080, bus=<optimized out>, name=<optimized out>, timeout=<optimized out>, 
    check_idle=<optimized out>, userdata=<optimized out>) at ../src/shared/bus-util.c:147
#13 0x000000000050ab4a in run (argc=<optimized out>, argv=<optimized out>) at ../src/machine/machined.c:346
#14 main (argc=<optimized out>, argv=<optimized out>) at ../src/machine/machined.c:358
```

### Steps to reproduce the problem

```sh
printf '{"method":"io.systemd.Machine.List","parameters":{"name":""}}\0' | ncat -U /run/systemd/machine/io.systemd.Machine
```

**Comment by mrc0mmand** [comment]
There's also https://github.com/systemd/systemd/pull/34623#issuecomment-2411157739

**Comment by evverx** [comment]
As far as I can see the MachineImage interface can't be introspected either for some reason (and it kind of makes it harder to discover and poke those methods automatically).
