### ISSUE TITLE
Assertion failure in on_stream_io()

### ISSUE THREAD

**Issue by pfactum** [systemd/systemd#34956]
### systemd version the issue has been seen with

256.7-1

### Used distribution

Arch Linux

### Linux kernel version used

6.11.0-pf3

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Unexpected behaviour you saw

At some point, on my VPS, `systemd-resolved` restarted abruptly:

```
systemd-resolved[316]: Assertion 's->read_packet->family == AF_INET6' failed at src/resolve/resolved-dns-stream.c:405, function on_stream_io(). Aborting.

(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007a69c48a5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007a69c484c120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007a69c48334c3 in __GI_abort () at abort.c:79
#4  0x00007a69c5278339 in log_assert_failed (text=text@entry=0x56451c3247b8 "s->read_packet->family == AF_INET6",
    file=file@entry=0x56451c323133 "src/resolve/resolved-dns-stream.c", line=line@entry=405, func=func@entry=0x56451c330248 <__func__.7.lto_priv.4> "on_stream_io")
    at ../systemd/src/basic/log.c:995
#5  0x000056451c2d9991 in on_stream_io (es=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>)
    at ../systemd/src/resolve/resolved-dns-stream.c:405
#6  0x00007a69c550c562 in source_dispatch (s=0x56452dd8ad70) at ../systemd/src/libsystemd/sd-event/sd-event.c:4223
#7  0x00007a69c550fcce in sd_event_dispatch (e=<optimized out>, e@entry=0x56452d8ff880) at ../systemd/src/libsystemd/sd-event/sd-event.c:4844
#8  0x00007a69c55103a1 in sd_event_run (e=<optimized out>, e@entry=0x56452d8ff880, timeout=timeout@entry=18446744073709551615)
    at ../systemd/src/libsystemd/sd-event/sd-event.c:4905
#9  0x00007a69c5510588 in sd_event_loop (e=<optimized out>) at ../systemd/src/libsystemd/sd-event/sd-event.c:4927
#10 0x000056451c301750 in run (argc=<optimized out>, argv=<optimized out>) at ../systemd/src/resolve/resolved.c:92
#11 0x000056451c2c02b4 in main (argc=<optimized out>, argv=<optimized out>) at ../systemd/src/resolve/resolved.c:99
```

### Steps to reproduce the problem

I do not know how to reproduce this. It happened with no intervention from my side.

**Comment by poettering** [comment]
Hmm, uh. is this some weird setup with ipv4 over ipv6 or so?

it seems as if we got an ipv4 peer address on an ipv6 socket in your case? that is super strange?

**Comment by pfactum** [comment]
> Hmm, uh. is this some weird setup with ipv4 over ipv6 or so?

I would not expect anything weird from this setup. It's dual-stack, yes, with client getting addresses via DHCPv4 and DHCPv6, but no tunnelling involved.

> it seems as if we got an ipv4 peer address on an ipv6 socket in your case? that is super strange?

Anything specific I can check and/or provide here?

**Comment by poettering** [comment]
I am pretty sure #36597 should fix your issue

**Comment by pfactum** [comment]
Applied on top of 257.3, observing now.

**Comment by pfactum** [comment]
No crash so far with this commit applied.
