### ISSUE TITLE
FSPRG_state can be initialised to 0, leading to segmentation faults on null pointer dereference

### ISSUE THREAD

**Issue by matthewruffell** [systemd/systemd#34952]
### systemd version the issue has been seen with

systemd 255.4-1ubuntu8.4

### Used distribution

Ubuntu 24.04

### Linux kernel version used

Linux 6.8.0-1014-aws x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Unexpected behaviour you saw

On initial instance boot, systemd-journald crashes during startup when trying to prepare journal sealing through FSS.

### Steps to reproduce the problem

I haven't found a reproducer just yet. I will keep trying.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
System log:

    2024-09-09T09:35:41.438953+00:00 ip-172-31-31-77 kernel: systemd-journal[126]: segfault at 0 ip 000077ddc2689444 sp 00007fff7a61e598 error 4 in libsystemd-shared-255.so[77ddc246a000+247000] likely on CPU 0 (core 0, socket 0)
    2024-09-09T09:35:41.438971+00:00 ip-172-31-31-77 kernel: Code: 00 00 00 48 8d 35 ef 64 07 00 48 8d 3d 99 04 04 00 48 89 e5 e8 0d 11 f4 ff 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa <0f> b7 07 66 c1 c0 08 83 c0 01 c1 e0 04 0f b7 c0 c1 f8 02 83 c0 02
    2024-09-09T09:35:42.915050+00:00 ip-172-31-31-77 kernel: systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
    2024-09-09T09:35:42.921951+00:00 ip-172-31-31-77 kernel: systemd[1]: Starting systemd-journald.service - Journal Service...
    2024-09-09T09:35:42.934967+00:00 ip-172-31-31-77 kernel: systemd-journald[2116]: Collecting audit messages is disabled.
    2024-09-09T09:35:42.942184+00:00 ip-172-31-31-77 systemd[1]: systemd-journald.service: Main process exited, code=dumped, status=11/SEGV
    2024-09-09T09:35:42.942337+00:00 ip-172-31-31-77 systemd[1]: systemd-journald.service: Failed with result 'core-dump'.
    2024-09-09T09:35:42.942960+00:00 ip-172-31-31-77 kernel: systemd[1]: Started systemd-journald.service - Journal Service.

gdb:
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  read_secpar (buf=<optimized out>) at ../src/libsystemd/sd-journal/fsprg.c:331
     
    (gdb) bt
    #0  read_secpar (buf=<optimized out>) at ../src/libsystemd/sd-journal/fsprg.c:331
    #1  FSPRG_GetEpoch (state=0x0) at ../src/libsystemd/sd-journal/fsprg.c:330
    #2  0x000077ddc2689546 in journal_file_next_evolve_usec (f=0x583599e2cbd0, u=u@entry=0x7fff7a61e5d0) at ../src/libsystemd/sd-journal/journal-authenticate.c:520
    #3  0x00005835986c086f in main (argc=<optimized out>, argv=<optimized out>) at ../src/journal/journald.c:105

A quick look at code:

    src/libsystemd/sd-journal/journal-authenticate.c:520
    511 bool journal_file_next_evolve_usec(JournalFile *f, usec_t *u) {
    512         uint64_t epoch;
    513 
    514         assert(f);
    515         assert(u);
    516 
    517         if (!JOURNAL_HEADER_SEALED(f->header))
    518                 return false;
    519 
    520         epoch = FSPRG_GetEpoch(f->fsprg_state);
    521 
    522         *u = (usec_t) (f->fss_start_usec + f->fss_interval_usec * epoch + f->fss_interval_usec);
    523 
    524         return true;
    525 }

We do some validation, ensuring we have a non-null journalfile, non-null usec count, and that sealed is enabled.

We then call FSPRG_GetEpoch(f->fsprg_state); with the pseudo random number generator state.

    src/libsystemd/sd-journal/fsprg.c:330
    328 uint64_t FSPRG_GetEpoch(const void *state) {
    329         uint16_t secpar;
    330         secpar = read_secpar(state + 0);
    331         return uint64_import(state + 2 + 2 * secpar / 8, 8);
    332 }

*state is just f->fsprg_state, we add 0 to the pointer, and call read_secpar(),

with effectively read_secpar(f->fsprg_state):

    240 static uint16_t read_secpar(const void *buf) {
    241         uint16_t secpar;
    242         secpar =
    243                 (uint16_t)(((uint8_t*) buf)[0]) << 8 |
    244                 (uint16_t)(((uint8_t*) buf)[1]) << 0;
    245         return 16 * (secpar + 1);
    246 }

Looking closer at the backtrace again:

    (gdb) bt
    #0  read_secpar (buf=<optimized out>) at ../src/libsystemd/sd-journal/fsprg.c:331
    #1  FSPRG_GetEpoch (state=0x0) at ../src/libsystemd/sd-journal/fsprg.c:330

state=0x0. Well, what do we have here? A null pointer. So buf=0x0.

So for some reason, the journal file f->fsprg_state hasn't been initialised.

Do we need to ensure that f->fsprg_state is not 0, and is seeded properly?
```

**Comment by poettering** [comment]
My educated guess is that this is fallout from 8707c9b24465ad2d45c1093a431a0597d8341077

**Comment by poettering** [comment]
Does that system have gcrypt around?

**Comment by matthewruffell** [comment]
Hi @poettering,

Yes, the system has gcrypt:
```
232:ii  libgcrypt20:amd64               1.10.3-2build1                          amd64        LGPL Crypto library - runtime library
```

The systemd package 255.4-1ubuntu8.4 does not have 8707c9b though, that landed in 256 and hasn't been backported.
