### ISSUE TITLE
Fix ASAN integration tests for PrivatePIDs=

### ISSUE THREAD

**Issue by ryantimwilson** [systemd/systemd#34992]
### systemd version the issue has been seen with

257

### Used distribution

Centos 10

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Integration tests should pass

### Unexpected behaviour you saw

https://github.com/systemd/systemd/pull/34940#issuecomment-2452672533

Currently, when running tests with ASAN, systemd services spawned with PrivatePIDs=yes hang with the parent systemd-executor process stuck at __lsan::DoLeakCheck and constantly running sched_yield(). As a result, the child process is stuck in a zombie state.

Stack trace:
```
#0  0x00007fde66314dbb in sched_yield () from /lib64/libc.so.6
#1  0x00007fde66d28165 in __sanitizer::StopTheWorld(void (*)(__sanitizer::SuspendedThreadsList const&, void*), void*) ()
   from /lib64/libasan.so.8
#2  0x00007fde66d3a0ce in __lsan::LockStuffAndStopTheWorldCallback(dl_phdr_info*, unsigned long, void*) () from /lib64/libasan.so.8
#3  0x00007fde663796bb in dl_iterate_phdr () from /lib64/libc.so.6
#4  0x00007fde66d3a470 in __lsan::LockStuffAndStopTheWorld(void (*)(__sanitizer::SuspendedThreadsList const&, void*), __lsan::CheckForLeaksParam*) () from /lib64/libasan.so.8
#5  0x00007fde66d37479 in __lsan::CheckForLeaks() [clone .part.0] () from /lib64/libasan.so.8
#6  0x00007fde66d37bef in __lsan::DoLeakCheck() () from /lib64/libasan.so.8
#7  0x00007fde6626bb51 in __cxa_finalize () from /lib64/libc.so.6
#8  0x00007fde66c3b977 in __do_global_dtors_aux () from /lib64/libasan.so.8
#9  0x00007fde67371160 in ?? ()
#10 0x00007fde6737a0e2 in _dl_call_fini (closure_map=0x7ffe48220d50, closure_map@entry=0x7fde67371160) at dl-call_fini.c:43
#11 0x00007fde6737e22e in _dl_fini () at dl-fini.c:114
#12 0x00007fde6626c091 in __run_exit_handlers () from /lib64/libc.so.6
#13 0x00007fde6626c150 in exit () from /lib64/libc.so.6
#14 0x00007fde66253315 in __libc_start_call_main () from /lib64/libc.so.6
#15 0x00007fde662533c9 in __libc_start_main_impl () from /lib64/libc.so.6
#16 0x0000560b91286bd5 in _start ()
```

Unit state for service running readlink binary:
```
systemctl status run-p745-i1045.service
● run-p745-i1045.service - [systemd-run] /usr/bin/readlink /proc/self
     Loaded: loaded (/run/systemd/transient/run-p745-i1045.service; transient)
  Transient: yes
     Active: active (running) since Sat 2024-11-02 06:31:17 PDT; 55s ago
 Invocation: 74fbebfd56044bde88eb18075f16e631
   Main PID: 747 (readlink)
      Tasks: 3 (limit: 2159)
     Memory: 68.2M (peak: 75M)
        CPU: 20.659s
     CGroup: /system.slice/run-p745-i1045.service
             ├─746 "(readlink)"
             └─747 "[readlink]"
```

### Steps to reproduce the problem

Add the following to mkosi.local.conf:
```
[Content]
Environment=SANITIZERS=address,undefined
```

Then run integration tests:
```
SYSTEMD_INTEGRATION_TESTS=1 meson test -C build --no-rebuild -v TEST-07-PID1
```

**Comment by yuwata** [comment]
cc @mrc0mmand

**Comment by ryantimwilson** [comment]
This is fixed with @poettering's latest suggestion to exit immediately and not run destructors twice (once in parent, another in child) and only once in child
