### ISSUE TITLE
Assertion failure on v232 with unicode partlabel

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#4747]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

v232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

System boots.

### In case of bug report: Unexpected behaviour you saw

```
Assertion 'u' failed at src/core/unit.c:519, function unit_free(). Aborting.
Aborted (core dumped)
```

### In case of bug report: Steps to reproduce the problem

- Format a partition with ntfs
- Set the partition label to †††††††††††††††††††††††††††††††††††

systemd will immediately core dump.

I've bisected this to a581e45ae8f9bb5c6693c23c78bc070aa15d0c8a.

downstream bug: https://bugs.archlinux.org/task/51950

**Comment by falconindy** [comment]
Backtrace from the assert

```
#0  0x00007ffff6b8304f in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff6b8447a in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff7cd9392 in log_assert_failed (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at src/basic/log.c:795
No locals.
#3  0x00005555555f0f31 in unit_free (u=<optimized out>) at src/core/unit.c:521
        i = {idx = 1432760672, next_key = 0x555555673350}
        t = 0x555555663160 "\360\067fUUU"
        __PRETTY_FUNCTION__ = "unit_free"
#4  0x00005555555c7490 in device_setup_unit.lto_priv.276 (m=m@entry=0x555555663160, dev=dev@entry=0x555555682580,
    path=path@entry=0x5555556729a0 "/dev/disk/by-partlabel/￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ", main=main@entry=false) at src/core/device.c:369
        e = 0x555555673170 "dev-disk-by\\x2dpartlabel-\\xef\\xbf\\xa2\\xef\\xbe\\x80\\xef\\xbe\\xa0\\xef\\xbf\\xa2\\xef\\xbe\\x80\\xef\\xbe\\xa0\\xef\\xbf\\xa2\\xef\\xbe\\x80\\xef\\xbe\\xa0\\xef\\xbf\\xa2\\xef\\xbe\\x80\\xef\\xbe\\xa0\\xef\\xbf\\xa2\\xef\\xbe\\x80\\xef\\xb"...
        sysfs = <optimized out>
        u = 0x0
        delete = true
        r = -22
        __PRETTY_FUNCTION__ = "device_setup_unit"
        __func__ = "device_setup_unit"
#5  0x00005555555c7c10 in device_process_new.lto_priv.278 (m=0x555555663160, dev=0x555555682580) at src/core/device.c:420
        p = 0x5555556729a0 "/dev/disk/by-partlabel/￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ￢ﾀﾠ"
        st = {st_dev = 6, st_ino = 16094, st_nlink = 1, st_mode = 25008, st_uid = 0, st_gid = 6, __pad0 = 0, st_rdev = 65073, st_size = 0, st_blksize = 4096, st_blocks = 0, st_atim = {tv_sec = 1480185909, tv_nsec = 35280815},
          st_mtim = {tv_sec = 1480181944, tv_nsec = 467580189}, st_ctim = {tv_sec = 1480181944, tv_nsec = 467580189}, __glibc_reserved = {0, 0, 0}}
        sysfs = 0x55555567f480 "/sys/devices/pci0000:00/0000:00:07.0/virtio4/block/vdd/vdd1"
        dn = <optimized out>
        alias = <optimized out>
        item = 0x555555672960
        first = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "device_process_new"
        __func__ = "device_process_new"
#6  0x00005555555decc5 in device_enumerate.lto_priv.151 (m=0x555555663160) at src/core/device.c:689
        dev = 0x555555682580
        sysfs = 0x55555566a520 "/sys/devices/pci0000:00/0000:00:07.0/virtio4/block/vdd/vdd1"
        e = 0x555555665750
        item = 0x55555566ce90
        first = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "device_enumerate"
        __func__ = "device_enumerate"
#7  0x00005555555d813f in manager_enumerate (m=<optimized out>) at src/core/manager.c:1141
        c = <optimized out>
#8  0x00005555555880a5 in manager_startup (fds=<optimized out>, serialization=<optimized out>, m=0x555555663160) at src/core/manager.c:1269
        r = 0
        q = <optimized out>
#9  main (argc=3, argv=0x7fffffffe518) at src/core/main.c:1814
        m = 0x555555663160
        r = <optimized out>
        retval = 1
        before_startup = 7010343119
        after_startup = <optimized out>
        timespan = "\340\212\356\366\377\177\000\000\060", '\000' <repeats 15 times>, "\031μ\366\377\177\000\000\000\000\000\000\000\000\000\000\365\210\274\366\377\177", '\000' <repeats 11 times>, "\060fUUU\000"
        fds = 0x5555556637c0
        reexecute = false
        shutdown_verb = 0x0
        initrd_timestamp = <optimized out>
        userspace_timestamp = {realtime = 1480187966322380, monotonic = 7010341832}
        kernel_timestamp = {realtime = 0, monotonic = 0}
        security_start_timestamp = {realtime = 0, monotonic = 0}
        security_finish_timestamp = {realtime = 0, monotonic = 0}
        systemd = "systemd"
        skip_setup = <optimized out>
        j = <optimized out>
        loaded_policy = false
        arm_reboot_watchdog = false
        queue_default_job = true
        empty_etc = <optimized out>
        switch_root_dir = 0x0
        switch_root_init = 0x0
        saved_rlimit_nofile = {rlim_cur = 1024, rlim_max = 4096}
        error_message = 0x0
        __func__ = "main"
        __PRETTY_FUNCTION__ = "main"
```
