### ISSUE TITLE
systemctl segfault when told to cat a non-existent template unit

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#4912]
```
Core was generated by `systemctl cat test@.target test@.service'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strrchr () at ../sysdeps/x86_64/strrchr.S:32
32              movdqu  (%rdi), %xmm0
(gdb) bt
#0  strrchr () at ../sysdeps/x86_64/strrchr.S:32
#1  0x00007f3da9b357fe in __GI___basename (filename=0x0) at basename.c:24
#2  0x0000557b3df2fd91 in unit_find_paths (bus=0x557b3e9d6a90, unit_name=0x557b3e9d6740 "test@.target", lp=0x7ffccb170830, fragment_path=0x7ffccb170810, dropin_paths=0x7ffccb170818) at src/systemctl/systemctl.c:2584
#3  0x0000557b3df3aae5 in cat (argc=3, argv=0x7ffccb170aa0, userdata=0x0) at src/systemctl/systemctl.c:5324
#4  0x00007f3daa111c6b in dispatch_verb (argc=4, argv=0x7ffccb170a98, verbs=0x557b3df50c60 <verbs>, userdata=0x0) at src/basic/verbs.c:92
#5  0x0000557b3df4377f in systemctl_main (argc=4, argv=0x7ffccb170a98) at src/systemctl/systemctl.c:8141
#6  0x0000557b3df44572 in main (argc=4, argv=0x7ffccb170a98) at src/systemctl/systemctl.c:8412
```

Regression introduced in c6dd36b65caa9acc03a8e77b7db752574cf36eb4.

@fsateler

**Comment by fsateler** [comment]
Ooops. Will take a look.

Saludos,
Felipe Sateler
