### ISSUE TITLE
get_files_in_directory segfaults on the error path

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5056]
[`get_files_in_directory`](https://github.com/systemd/systemd/blob/8fb3f0099787a5b48213c4e2aa42d8ff61b0c7f1/src/basic/fs-util.c#L446) contains something like
```c
size_t n = 0;
_cleanup_strv_free_ char **l = NULL;
...
FOREACH(i, ...) {
    if (!GREEDY_REALLOC(l, bufsize, n + 2))
        return -ENOMEM;

    l[n] = strdup(i);
    if (!l[n]) // <- this is wrong. l[n+1] should be NULL
        return -ENOMEM;

    l[++n] = NULL;
}
```

```
ASAN:DEADLYSIGNAL
=================================================================
==9026==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fb49d5b38f7 bp 0x7ffc618d70b0 sp 0x7ffc618d6820 T0)
    #0 0x7fb49d5b38f6  (/lib64/libasan.so.3+0x238f6)
    #1 0x7fb49d656acb in free (/lib64/libasan.so.3+0xc6acb)
    #2 0x7fb49d125cbe in strv_clear src/basic/strv.c:83
    #3 0x7fb49d125d39 in strv_free src/basic/strv.c:89
    #4 0x7fb49d0f551a in strv_freep src/basic/strv.h:37
    #5 0x7fb49d0f8654 in get_files_in_directory src/basic/fs-util.c:450
    #6 0x55f16dbe9824 in test_get_files_in_directory src/test/test-fs-util.c:239
    #7 0x55f16dbea115 in main src/test/test-fs-util.c:300
    #8 0x7fb49ca08400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #9 0x55f16dbe5329 in _start (/home/vagrant/systemd-asan/.libs/lt-test-fs-util+0x3329)
```
```
==28067==
==28067== Conditional jump or move depends on uninitialised value(s)
==28067==    at 0x4EA51B4: strv_clear (strv.c:82)
==28067==    by 0x4EA51DD: strv_free (strv.c:89)
==28067==    by 0x4E8D2E2: strv_freep (strv.h:37)
==28067==    by 0x4E8E8C7: get_files_in_directory (fs-util.c:450)
==28067==    by 0x10BC49: test_get_files_in_directory (test-fs-util.c:239)
==28067==    by 0x10C2E1: main (test-fs-util.c:300)
==28067==  Uninitialised value was created by a heap allocation
==28067==    at 0x4C2DADE: malloc (vg_replace_malloc.c:298)
==28067==    by 0x4C2FC91: realloc (vg_replace_malloc.c:785)
==28067==    by 0x4ED933C: greedy_realloc (alloc-util.c:57)
==28067==    by 0x4E8E83C: get_files_in_directory (fs-util.c:470)
==28067==    by 0x10BC49: test_get_files_in_directory (test-fs-util.c:239)
==28067==    by 0x10C2E1: main (test-fs-util.c:300)
==28067==
```
`GREEDY_REALLOC0` fixes the issue

Seems like `config_parse_exec` segfaults too

**Comment by evverx** [comment]
Sorry, I was wrong. I injected a failure incorrectly. Closing.
