### ISSUE TITLE
test-env-util, test-fileio: LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5405]
https://github.com/systemd/systemd/pull/5131#issuecomment-281314198
```
FAIL: test-env-util
===================


=================================================================
==17489==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fd06fa1de60 in malloc (/lib64/libasan.so.3+0xc6e60)
    #1 0x7fd06ef1c5ec in malloc_multiply src/basic/alloc-util.h:70
    #2 0x7fd06ef1dc76 in strnappend src/basic/string-util.c:206
    #3 0x7fd06ef7efb0 in replace_env_n src/basic/env-util.c:694
    #4 0x55a386b954a7 in replace_env src/basic/env-util.h:42
    #5 0x55a386b978ba in test_replace_env src/test/test-env-util.c:160
    #6 0x55a386b99b24 in main src/test/test-env-util.c:324
    #7 0x7fd06d7e5400 in __libc_start_main (/lib64/libc.so.6+0x20400)

Direct leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0x7fd06fa1de60 in malloc (/lib64/libasan.so.3+0xc6e60)
    #1 0x7fd06ef1c5ec in malloc_multiply src/basic/alloc-util.h:70
    #2 0x7fd06ef1dc76 in strnappend src/basic/string-util.c:206
    #3 0x7fd06ef7efb0 in replace_env_n src/basic/env-util.c:694
    #4 0x55a386b954a7 in replace_env src/basic/env-util.h:42
    #5 0x55a386b978ba in test_replace_env src/test/test-env-util.c:160
    #6 0x55a386b99b2e in main src/test/test-env-util.c:325
    #7 0x7fd06d7e5400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 25 byte(s) leaked in 2 allocation(s).
FAIL test-env-util (exit status: 1)
FAIL: test-fileio
=================
...
==18689==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f181a73e210 in realloc (/lib64/libasan.so.3+0xc7210)
    #1 0x7f1819d20c23 in greedy_realloc src/basic/alloc-util.c:57
    #2 0x7f1819cd7431 in parse_env_file_internal src/basic/fileio.c:415
    #3 0x7f1819cd93ae in merge_env_file src/basic/fileio.c:807
    #4 0x5634db7dc370 in test_merge_env_file_invalid src/test/test-fileio.c:308
    #5 0x5634db7e0af8 in main src/test/test-fileio.c:674
    #6 0x7f1818505400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
FAIL test-fileio (exit status: 1)
```

**Comment by poettering** [comment]
btw, please always mark leak errors and segfaults and such obviously wrong bugs always with the next milestone so that we fix them before the next release. I think for such obvious bugs there's little excuse to release with them in place.

**Comment by evverx** [comment]
oh, I forgot to mark this issue. My bad. Sorry.

> I think for such obvious bugs there's little excuse to release with them in place

Sure
