### ISSUE TITLE
--disable-manpages fails

### ISSUE THREAD

**Issue by phomes** [systemd/systemd#5854]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

master

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

fedora 25

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

build fails when configured with --disable-manpages

### In case of bug report: Steps to reproduce the problem

./autogen.sh && ./configure CFLAGS='-g -O0 -ftrapv' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 --disable-manpages && make

...
Traceback (most recent call last):
  File "tools/make-man-index.py", line 137, in <module>
    f.write(xml_print(make_page(*sys.argv[2:])))
  File "tools/make-man-index.py", line 126, in make_page
    index = make_index(xml_files)
  File "tools/make-man-index.py", line 81, in make_index
    t = xml_parse(p)
  File "/home/phomes/systemd/tools/xml_helper.py", line 31, in xml_parse
    doc = tree.parse(page, _parser)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:117848)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118195)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117107)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:111653)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "man/systemctl.xml", line 486
lxml.etree.XMLSyntaxError: Entity 'MOUNT_PATH' not defined, line 486, column 33
Makefile:26529: recipe for target 'man/systemd.index.xml' failed
make[2]: *** [man/systemd.index.xml] Error 1
make[2]: *** Deleting file 'man/systemd.index.xml'
Makefile:22663: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:10172: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mbiebl** [comment]
I guess you don't have a man/custom-entities.ent file? In case of --disable-manpages it seems we are missing a rule which triggers the creation of that file.

**Comment by mbiebl** [comment]
Do we need something like maybe?
```
diff --git a/Makefile.am b/Makefile.am
index f5f2793f5..a9f1513ba 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -768,7 +768,7 @@ update-man-list: $(top_srcdir)/tools/make-man-rules.py $(XML_GLOB) man/custom-en
        $(AM_V_at)mv $(top_srcdir)/Makefile-man.tmp $(top_srcdir)/Makefile-man.am
        @echo "Makefile-man.am has been regenerated"
 
-man/systemd.index.xml: $(top_srcdir)/tools/make-man-index.py $(NON_INDEX_XML_FILES)
+man/systemd.index.xml: $(top_srcdir)/tools/make-man-index.py man/custom-entities.ent $(NON_INDEX_XML_FILES)
        $(AM_V_at)$(MKDIR_P) $(dir $@)
        $(AM_V_GEN)$(PYTHON) $< $@ $(filter-out $<,$^)
```

**Comment by phomes** [comment]
With that patch it fails with:

Traceback (most recent call last):
  File "tools/make-man-index.py", line 137, in <module>
    f.write(xml_print(make_page(*sys.argv[2:])))
  File "tools/make-man-index.py", line 126, in make_page
    index = make_index(xml_files)
  File "tools/make-man-index.py", line 81, in make_index
    t = xml_parse(p)
  File "/home/phomes/systemd/tools/xml_helper.py", line 31, in xml_parse
    doc = tree.parse(page, _parser)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:117848)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118195)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117107)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:111653)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "man/custom-entities.ent", line 2
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 2, column 2
Makefile:26529: recipe for target 'man/systemd.index.xml' failed
make[2]: *** [man/systemd.index.xml] Error 1
make[2]: *** Deleting file 'man/systemd.index.xml'
Makefile:22663: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:10172: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by keszybz** [comment]
A different question is why it's trying to build systemd.index.xml if man pages are disabled.

**Comment by mbiebl** [comment]
@keszybz I had a similar thought. Afacis, this rules is triggered via man/index.html.

**Comment by mbiebl** [comment]
@keszybz I guess we can avoid the generation of systemd.index.html simply by something like #5865.
That said, there is still something fishy with the dependencies of 
```man/systemd.index.xml```. An even simpler reproducer is

```
$ ./autogen.sh && ./configure
make man/systemd.index.xml 
```

**Comment by mbiebl** [comment]
I compared a failing build from a successful build. If you make sure custom-entities.ent exists, the man/systemd.index.xml rule for the failing build passed a different set of files, i.e. ```$(NON_INDEX_XML_FILES)``` is different for the failing and successful build. 
```
--- good	2017-04-30 13:58:13.395333724 +0200
+++ fail	2017-04-30 13:58:24.879531478 +0200
@@ -1,281 +1,248 @@
+man/binfmt.d.xml
+man/bootctl.xml
 man/bootup.xml
 man/busctl.xml
-man/busctl.xml
+man/coredump.conf.xml
+man/coredumpctl.xml
+man/crypttab.xml
 man/custom-entities.ent
 man/daemon.xml
-man/daemon.xml
+man/dnssec-trust-anchors.d.xml
+man/environment.d.xml
 man/file-hierarchy.xml
-man/file-hierarchy.xml
-man/halt.xml
 man/halt.xml
+man/hostnamectl.xml
 man/hostname.xml
-man/hostname.xml
-man/journalctl.xml
+man/hwdb.xml
 man/journalctl.xml
 man/journald.conf.xml
-man/journald.conf.xml
-man/kernel-command-line.xml
+man/journal-remote.conf.xml
+man/journal-upload.conf.xml
 man/kernel-command-line.xml
 man/kernel-install.xml
-man/kernel-install.xml
-man/libudev.xml
 man/libudev.xml
 man/locale.conf.xml
-man/locale.conf.xml
-man/localtime.xml
+man/localectl.xml
 man/localtime.xml
+man/loginctl.xml
+man/logind.conf.xml
+man/machinectl.xml
 man/machine-id.xml
-man/machine-id.xml
-man/machine-info.xml
 man/machine-info.xml
+man/modules-load.d.xml
+man/networkctl.xml
+man/networkd.conf.xml
+man/nss-myhostname.xml
+man/nss-mymachines.xml
+man/nss-resolve.xml
 man/nss-systemd.xml
-man/nss-systemd.xml
-man/os-release.xml
 man/os-release.xml
-man/sbootup.xml
+man/pam_systemd.xml
+man/resolved.conf.xml
+man/runlevel.xml
 man/sd_booted.xml
-man/sd_booted.xml
-man/sd_bus_add_match.xml
 man/sd_bus_add_match.xml
 man/sd_bus_creds_get_pid.xml
-man/sd_bus_creds_get_pid.xml
-man/sd_bus_creds_new_from_pid.xml
 man/sd_bus_creds_new_from_pid.xml
 man/sd_bus_default.xml
-man/sd_bus_default.xml
-man/sd_bus_error_add_map.xml
 man/sd_bus_error_add_map.xml
 man/sd-bus-errors.xml
-man/sd-bus-errors.xml
-man/sd_bus_error.xml
 man/sd_bus_error.xml
 man/sd_bus_get_fd.xml
-man/sd_bus_get_fd.xml
-man/sd_bus_message_append_array.xml
 man/sd_bus_message_append_array.xml
 man/sd_bus_message_append_basic.xml
-man/sd_bus_message_append_basic.xml
-man/sd_bus_message_append_string_memfd.xml
 man/sd_bus_message_append_string_memfd.xml
 man/sd_bus_message_append_strv.xml
-man/sd_bus_message_append_strv.xml
-man/sd_bus_message_append.xml
 man/sd_bus_message_append.xml
 man/sd_bus_message_get_cookie.xml
-man/sd_bus_message_get_cookie.xml
-man/sd_bus_message_get_monotonic_usec.xml
 man/sd_bus_message_get_monotonic_usec.xml
 man/sd_bus_message_read_basic.xml
-man/sd_bus_message_read_basic.xml
-man/sd_bus_negotiate_fds.xml
 man/sd_bus_negotiate_fds.xml
 man/sd_bus_new.xml
-man/sd_bus_new.xml
-man/sd_bus_path_encode.xml
 man/sd_bus_path_encode.xml
 man/sd_bus_process.xml
-man/sd_bus_process.xml
-man/sd_bus_request_name.xml
 man/sd_bus_request_name.xml
 man/sd_bus_track_add_name.xml
-man/sd_bus_track_add_name.xml
-man/sd_bus_track_new.xml
 man/sd_bus_track_new.xml
 man/sd-bus.xml
-man/sd-bus.xml
-man/sd-daemon.xml
 man/sd-daemon.xml
 man/sd_event_add_child.xml
-man/sd_event_add_child.xml
-man/sd_event_add_defer.xml
 man/sd_event_add_defer.xml
 man/sd_event_add_io.xml
-man/sd_event_add_io.xml
-man/sd_event_add_signal.xml
 man/sd_event_add_signal.xml
 man/sd_event_add_time.xml
-man/sd_event_add_time.xml
-man/sd_event_exit.xml
 man/sd_event_exit.xml
 man/sd_event_get_fd.xml
-man/sd_event_get_fd.xml
-man/sd_event_new.xml
 man/sd_event_new.xml
 man/sd_event_now.xml
-man/sd_event_now.xml
-man/sd_event_run.xml
 man/sd_event_run.xml
 man/sd_event_set_watchdog.xml
-man/sd_event_set_watchdog.xml
-man/sd_event_source_get_event.xml
 man/sd_event_source_get_event.xml
 man/sd_event_source_get_pending.xml
-man/sd_event_source_get_pending.xml
-man/sd_event_source_set_description.xml
 man/sd_event_source_set_description.xml
 man/sd_event_source_set_enabled.xml
-man/sd_event_source_set_enabled.xml
-man/sd_event_source_set_prepare.xml
 man/sd_event_source_set_prepare.xml
 man/sd_event_source_set_priority.xml
-man/sd_event_source_set_priority.xml
-man/sd_event_source_set_userdata.xml
 man/sd_event_source_set_userdata.xml
 man/sd_event_source_unref.xml
-man/sd_event_source_unref.xml
-man/sd_event_wait.xml
 man/sd_event_wait.xml
 man/sd-event.xml
-man/sd-event.xml
+man/sd_get_seats.xml
 man/sd_id128_get_machine.xml
-man/sd_id128_get_machine.xml
-man/sd_id128_randomize.xml
 man/sd_id128_randomize.xml
 man/sd_id128_to_string.xml
-man/sd_id128_to_string.xml
-man/sd-id128.xml
 man/sd-id128.xml
 man/sd_is_fifo.xml
-man/sd_is_fifo.xml
-man/sd_journal_add_match.xml
 man/sd_journal_add_match.xml
 man/sd_journal_enumerate_fields.xml
-man/sd_journal_enumerate_fields.xml
-man/sd_journal_get_catalog.xml
 man/sd_journal_get_catalog.xml
 man/sd_journal_get_cursor.xml
-man/sd_journal_get_cursor.xml
-man/sd_journal_get_cutoff_realtime_usec.xml
 man/sd_journal_get_cutoff_realtime_usec.xml
 man/sd_journal_get_data.xml
-man/sd_journal_get_data.xml
-man/sd_journal_get_fd.xml
 man/sd_journal_get_fd.xml
 man/sd_journal_get_realtime_usec.xml
-man/sd_journal_get_realtime_usec.xml
-man/sd_journal_get_usage.xml
 man/sd_journal_get_usage.xml
 man/sd_journal_has_runtime_files.xml
-man/sd_journal_has_runtime_files.xml
-man/sd_journal_next.xml
 man/sd_journal_next.xml
 man/sd_journal_open.xml
-man/sd_journal_open.xml
-man/sd_journal_print.xml
 man/sd_journal_print.xml
 man/sd_journal_query_unique.xml
-man/sd_journal_query_unique.xml
-man/sd_journal_seek_head.xml
 man/sd_journal_seek_head.xml
 man/sd_journal_stream_fd.xml
-man/sd_journal_stream_fd.xml
-man/sd-journal.xml
 man/sd-journal.xml
 man/sd_listen_fds.xml
-man/sd_listen_fds.xml
-man/sd_machine_get_class.xml
+man/sd_login_monitor_new.xml
+man/sd-login.xml
 man/sd_machine_get_class.xml
 man/sd_notify.xml
-man/sd_notify.xml
+man/sd_pid_get_session.xml
+man/sd_seat_get_active.xml
+man/sd_session_is_active.xml
 man/sd_uid_get_state.xml
 man/sd_watchdog_enabled.xml
-man/sd_watchdog_enabled.xml
 man/shutdown.xml
-man/shutdown.xml
-man/sysctl.d.xml
 man/sysctl.d.xml
-man/sys-emd-gpt-auto-generator.xml
 man/systemctl.xml
-man/systemctl.xml
-man/systemd-analyze.xml
 man/systemd-analyze.xml
 man/systemd-ask-password-console.service.xml
-man/systemd-ask-password-console.service.xml
-man/systemd-ask-password.xml
 man/systemd-ask-password.xml
 man/systemd.automount.xml
+man/systemd-backlight@.service.xml
+man/systemd-binfmt.service.xml
 man/systemd-cat.xml
-man/systemd-cat.xml
-man/systemd-cgls.xml
 man/systemd-cgls.xml
 man/systemd-cgtop.xml
-man/systemd-cgtop.xml
-man/systemd-debug-generator.xml
+man/systemd-coredump.xml
+man/systemd-cryptsetup-generator.xml
+man/systemd-cryptsetup@.service.xml
 man/systemd-debug-generator.xml
 man/systemd-delta.xml
-man/systemd-delta.xml
-man/systemd-detect-virt.xml
 man/systemd-detect-virt.xml
 man/systemd.device.xml
-man/systemd-escape.xml
+man/systemd-environment-d-generator.xml
+man/systemd.environment-generator.xml
 man/systemd-escape.xml
 man/systemd.exec.xml
-man/systemd-fsck@.service.xml
+man/systemd-firstboot.xml
 man/systemd-fsck@.service.xml
 man/systemd-fstab-generator.xml
-man/systemd-fstab-generator.xml
 man/systemd.generator.xml
 man/systemd-getty-generator.xml
-man/systemd-getty-generator.xml
 man/systemd-gpt-auto-generator.xml
 man/systemd-halt.service.xml
-man/systemd-halt.service.xml
+man/systemd-hibernate-resume-generator.xml
+man/systemd-hibernate-resume@.service.xml
+man/systemd-hostnamed.service.xml
+man/systemd-hwdb.xml
+man/systemd-importd.service.xml
 man/systemd.index.xml
 man/systemd-inhibit.xml
-man/systemd-inhibit.xml
 man/systemd-initctl.service.xml
-man/systemd-initctl.service.xml
-man/systemd-journald.service.xml
 man/systemd-journald.service.xml
 man/systemd.journal-fields.xml
+man/systemd-journal-gatewayd.service.xml
+man/systemd-journal-remote.xml
+man/systemd-journal-upload.xml
 man/systemd.kill.xml
 man/systemd.link.xml
+man/systemd-localed.service.xml
+man/systemd-logind.service.xml
+man/systemd-machined.service.xml
 man/systemd-machine-id-commit.service.xml
-man/systemd-machine-id-commit.service.xml
-man/systemd-machine-id-setup.xml
 man/systemd-machine-id-setup.xml
-man/systemd-mount.xml
+man/systemd-modules-load.service.xml
 man/systemd-mount.xml
 man/systemd.mount.xml
-man/systemd-notify.xml
+man/systemd.netdev.xml
+man/systemd-networkd.service.xml
+man/systemd-networkd-wait-online.service.xml
+man/systemd.network.xml
 man/systemd-notify.xml
 man/systemd-nspawn.xml
-man/systemd-nspawn.xml
 man/systemd.nspawn.xml
 man/systemd.offline-updates.xml
 man/systemd-path.xml
-man/systemd-path.xml
 man/systemd.path.xml
 man/systemd.preset.xml
+man/systemd-quotacheck.service.xml
+man/systemd-random-seed.service.xml
 man/systemd-remount-fs.service.xml
-man/systemd-remount-fs.service.xml
-man/systemd.resourcssion_is_active.xml
-man/systemd-run.xml
+man/systemd-resolved.service.xml
+man/systemd-resolve.xml
+man/systemd.resource-control.xml
+man/systemd-rfkill.service.xml
 man/systemd-run.xml
+man/systemd.scope.xml
+man/systemd.service.xml
 man/systemd-sleep.conf.xml
-man/systemd-sleep.conf.xml
-man/systemd-socket-activate.xml
+man/systemd.slice.xml
 man/systemd-socket-activate.xml
 man/systemd-socket-proxyd.xml
-man/systemd-socket-proxyd.xml
-man/systemd-suspend.service.xml
+man/systemd.socket.xml
+man/systemd.special.xml
 man/systemd-suspend.service.xml
+man/systemd.swap.xml
 man/systemd-sysctl.service.xml
-man/systemd-sysctl.service.xml
-man/systemd-system.conf.xml
 man/systemd-system.conf.xml
 man/systemd-system-update-generator.xml
-man/systemd-system-update-generator.xml
-man/systemd-sysusers.xml
 man/systemd-sysusers.xml
 man/systemd-sysv-generator.xml
-man/systemd-tmpfiles.xml
+man/systemd.target.xml
+man/systemd-timedated.service.xml
+man/systemd.timer.xml
+man/systemd-timesyncd.service.xml
+man/systemd.time.xml
 man/systemd-tmpfiles.xml
 man/systemd-tty-ask-password-agent.xml
 man/systemd-udevd.service.xml
+man/systemd.unit.xml
 man/systemd-update-done.service.xml
+man/systemd-update-utmp.service.xml
 man/systemd-user-sessions.service.xml
+man/systemd-vconsole-setup.service.xml
+man/systemd-veritysetup-generator.xml
+man/systemd-veritysetup@.service.xml
 man/systemd-volatile-root.service.xml
 man/systemd.xml
+man/sysusers.d.xml
+man/telinit.xml
+man/timedatectl.xml
+man/timesyncd.conf.xml
+man/tmpfiles.d.xml
+man/udevadm.xml
+man/udev.conf.xml
+man/udev_device_get_syspath.xml
+man/udev_device_has_tag.xml
+man/udev_device_new_from_syspath.xml
+man/udev_enumerate_add_match_subsystem.xml
+man/udev_enumerate_new.xml
+man/udev_enumerate_scan_devices.xml
+man/udev_list_entry.xml
+man/udev_monitor_filter_update.xml
+man/udev_monitor_new_from_netlink.xml
+man/udev_monitor_receive_device.xml
+man/udev_new.xml
+man/udev.xml
+man/vconsole.conf.xml
```
