### ISSUE TITLE
test: test-bus-vtable fails

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#5989]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

f731ad4456def2badc840dd52e69f2ba243c5155 which merges #5957.

### Used distribution

Fedora 25, 26 and rawhide x86_64

### In case of bug report: Unexpected behaviour you saw

test-bus-vtable fails as follows.
```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.tTMb0A
+ umask 022
+ cd /builddir/build/BUILD
+ cd systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c
+ export LANG=C.utf8
+ LANG=C.utf8
+ /usr/bin/ninja test -v -j8 -C x86_64-redhat-linux-gnu
ninja: Entering directory `x86_64-redhat-linux-gnu'
[0/1] '/usr/bin/python3' '/usr/bin/mesontest' '--no-rebuild' '--print-errorlogs'
  1/243 cc-sd-bus.h:c                           OK       0.03 s
(snip)
173/243 test-bus-vtable                         FAIL     5.40 s
(snip)
186/243 test-bus-vtable-cc                      FAIL     5.21 s
(snip)
OK:       225
FAIL:       2
SKIP:      16
TIMEOUT:    0
The output from the failed tests:
173/243 test-bus-vtable                         FAIL     5.40 s
--- command ---
SYSTEMD_KBD_MODEL_MAP='/builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/src/locale/language-fallback-map' PATH='/builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/x86_64-redhat-linux-gnu:/usr/bin:/bin:/usr/sbin:/sbin' /builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/x86_64-redhat-linux-gnu/test-bus-vtable
--- stderr ---
test-bus-vtable: ../src/libsystemd/sd-bus/test-bus-vtable.c:68: test_vtable: Assertion `sd_bus_start(bus) >= 0' failed.
-------
186/243 test-bus-vtable-cc                      FAIL     5.21 s
--- command ---
SYSTEMD_KBD_MODEL_MAP='/builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/src/locale/language-fallback-map' PATH='/builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/x86_64-redhat-linux-gnu:/usr/bin:/bin:/usr/sbin:/sbin' /builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/x86_64-redhat-linux-gnu/test-bus-vtable-cc
--- stderr ---
test-bus-vtable-cc: ../src/libsystemd/sd-bus/test-bus-vtable-cc.cc:68: void test_vtable(): Assertion `sd_bus_start(bus) >= 0' failed.
-------
Full log written to /builddir/build/BUILD/systemd-cb4d8b2d05c50b28a329b5096771f4ec931ae79c/x86_64-redhat-linux-gnu/meson-logs/testlog.txt
FAILED: test 
'/usr/bin/python3' '/usr/bin/mesontest' '--no-rebuild' '--print-errorlogs'
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.tTMb0A (%check)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.tTMb0A (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.5/site-packages/mockbuild/util.py", line 590, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M a73200d0c85047598e24ad4e68c420ff -D /var/lib/mock/fedora-rawhide-x86_64-systemd-43152/root -a --private-network --setenv=HOME=/builddir --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.utf8 --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=HOSTNAME=mock --setenv=SHELL=/bin/bash --setenv=TERM=vt100 -u mockbuild /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/systemd.spec
```

**Comment by yuwata** [comment]
The tests pass on local build, but they fails on chrooted environments such as mock build environment as shown above.

**Comment by AsciiWolf** [comment]
Same issue when using mkosi (#5987).
