### ISSUE TITLE
Assertion 's->type == SERVICE_ONESHOT' failed at ../src/core/service.c:2022, function service_run_next_main(). Aborting.

### ISSUE THREAD

**Issue by julianbrost** [systemd/systemd#6533]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 234
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

Debian (version string above), also reproducible on Arch with systemd 234

### In case of bug report: Expected behaviour you didn't see

PID 1 does not crash when playing around with service files.

### In case of bug report: Unexpected behaviour you saw

> systemd[1]: Assertion 's->type == SERVICE_ONESHOT' failed at ../src/core/service.c:2022, function service_run_next_main(). Aborting.
> systemd[1]: Caught <ABRT>, dumped core as pid 1433.
> systemd[1]: Freezing execution.

### In case of bug report: Steps to reproduce the problem

Run the following shell script (**obvious warning: crashes PID 1 and overwrites a file in /etc if it already exists**):

```
#!/bin/sh

cat > /etc/systemd/system/killme.service <<EOF
[Service]
Type=simple
ExecStart=/bin/sleep 5
EOF

systemctl daemon-reload
systemctl start killme.service
sleep 2

echo ExecStart=/bin/true >> /etc/systemd/system/killme.service

systemctl daemon-reload

journalctl -f
```

### What I've found out so far

```
(gdb) bt
#0  0x00007f9ab99fe317 in kill () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000003e8fc4a0a1 in crash.lto_priv.205 (sig=6) at ../src/core/main.c:190
#2  <signal handler called>
#3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x00007f9ab99ff42a in __GI_abort () at abort.c:89
#5  0x0000003e8fcdfa92 in log_assert_failed_realm.constprop.201 (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>, realm=LOG_REALM_SYSTEMD)
    at ../src/basic/log.c:809
#6  0x0000003e8fcc219b in service_run_next_main (s=0x3e90e437b0) at ../src/core/service.c:2022
#7  service_sigchld_event.lto_priv.384 (u=0x3e90e437b0, pid=<optimized out>, code=<optimized out>, status=0) at ../src/core/service.c:2893
#8  0x0000003e8fcea5fd in invoke_sigchld_event (m=m@entry=0x3e90dab9b0, u=u@entry=0x3e90e437b0, si=si@entry=0x7fff61118210) at ../src/core/manager.c:1856
#9  0x0000003e8fcea8dc in manager_dispatch_sigchld (m=<optimized out>, m=<optimized out>) at ../src/core/manager.c:1904
#10 0x0000003e8fcec920 in manager_dispatch_signal_fd.lto_priv.907 (source=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=<optimized out>, userdata=<optimized out>)
    at ../src/core/manager.c:2168
#11 0x00007f9ab95e7cc8 in source_dispatch (s=s@entry=0x3e90dae550) at ../src/libsystemd/sd-event/sd-event.c:2272
#12 0x00007f9ab95e7ea4 in sd_event_dispatch (e=e@entry=0x3e90dae0a0) at ../src/libsystemd/sd-event/sd-event.c:2631
#13 0x00007f9ab95e8077 in sd_event_run (e=0x3e90dae0a0, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:2690
#14 0x0000003e8fced6a3 in manager_loop (m=0x3e90dab9b0) at ../src/core/manager.c:2287
#15 0x0000003e8fc459e4 in main (argc=1, argv=<optimized out>) at ../src/core/main.c:1924
(gdb) frame 6
#6  0x0000003e8fcc219b in service_run_next_main (s=0x3e90e437b0) at ../src/core/service.c:2022
2022	../src/core/service.c: No such file or directory.
(gdb) p s->main_command->path 
$1 = 0x3e90e35d90 "/bin/sleep"
(gdb) p s->main_command->command_next->path 
$2 = 0x3e90e0dc60 "/bin/true"
```

**Comment by evverx** [comment]
The regression has been introduced in e266c068b5597e18b2.
