### ISSUE TITLE
mkosi: locale is not UTF-8 inside the image

### ISSUE THREAD

**Issue by johnlinp** [systemd/systemd#7238]
### Submission type

- Bug report

### systemd version the issue has been seen with

v235

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

Successfully build `mkosi` image.

### In case of bug report: Unexpected behaviour you saw

Part of the build log:

```
+ ninja -C build all 
ninja: Entering directory `build'
[1/1857] Generating systemd.bg.catalog with a meson_exe.py custom command.
FAILED: catalog/systemd.bg.catalog
/usr/bin/python /usr/bin/meson --internal exe /root/src/build/meson-private/meson_exe_sed_93b480d1444bd1bcbceb4e7087cb8dd55acb9f1f.dat
Warning: You are using 'ANSI_X3.4-1968' which is not a Unicode-compatible locale.
You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
Please switch to a UTF-8 locale for your platform.
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 311, in run 
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 278, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_exe.py", line 76, in run 
    return run_exe(exe)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_exe.py", line 59, in run_exe
    p, stdout, stderr = Popen_safe(cmd + exe.cmd_args, env=child_env, cwd=exe.workdir)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 549, in Popen_safe
    o, e = p.communicate(write)
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1554, in _communicate
    self.stdout.errors)
  File "/usr/lib/python3.6/subprocess.py", line 740, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1040: ordinal not in range(128)
```

### In case of bug report: Steps to reproduce the problem

1. Make symlink `mkosi.default -> .mkosi/mkosi.arch`
2. `mkosi`
3. The error above appears.

### Workaround

I can workaround this by changing the line in `mkosi.build`:

```
export LC_CTYPE=C.UTF-8
```

into these lines:

```
echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
locale-gen
export LC_CTYPE=en_US.UTF-8
```

But I'm not sure the correct way to fix this.

**Comment by poettering** [comment]
hmm, it appears archlinux doesn't issue "locale-gen" as part of their install scripts. I figure mkosi should add that then, and we shouldn't have to work around this here in systemd.

**Comment by johnlinp** [comment]
Okay, I will file an issue in mkosi and close this one. Thanks.

**Comment by johnlinp** [comment]
I am reopening this because I recalled that I can't set `export LC_CTYPE=C.UTF-8` in `mkosi.build`.

In the built image:

```
image login: root
Last login: Thu Nov  2 02:56:27 on console
[root@image ~]# locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
[root@image ~]# export LC_CTYPE=C.UTF-8
-bash: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8): No such file or directory
[root@image ~]# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C
LC_CTYPE=C.UTF-8
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
[root@image ~]# python -c 'import locale; print(locale.getpreferredencoding())'
ANSI_X3.4-1968
```

However, if I use `en_US.UTF-8`:

```
[root@image ~]# echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
[root@image ~]# locale-gen
Generating locales...
  en_US.UTF-8... done
Generation complete.
[root@image ~]# export LC_CTYPE=en_US.UTF-8
[root@image ~]# python -c 'import locale; print(locale.getpreferredencoding())'
UTF-8
```

Everything will be fine.

So I suggest that the `locale-gen` part should be in `mkosi`, and `LC_CTYPE` part should be in `systemd/mkosi.build`. I will submit a pull request for that.
