### ISSUE TITLE
There seems to be a memory leak in `test-routing-policy-rule`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#7495]
When 9491f55f74a1c61, 93f9da6e0a9e7 and 93f9da6e0a9e701e were merged, `./build/test-routing-policy-rule` started to fail while running under `asan`.
```
$ ./build/test-routing-policy-rule
...
==17254==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f6546e2b30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f6546818bbd in free_and_strdup ../src/basic/string-util.c:855
    #2 0x56169ba1bd3c in routing_policy_load_rules ../src/network/networkd-routing-policy-rule.c:1025
    #3 0x56169ba12d3f in test_rule_serialization ../src/network/test-routing-policy-rule.c:48
    #4 0x56169ba136f3 in main ../src/network/test-routing-policy-rule.c:96
    #5 0x7f654621d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x7f6546e2b30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f6546818bbd in free_and_strdup ../src/basic/string-util.c:855
    #2 0x56169ba1bcd5 in routing_policy_load_rules ../src/network/networkd-routing-policy-rule.c:1020
    #3 0x56169ba12d3f in test_rule_serialization ../src/network/test-routing-policy-rule.c:48
    #4 0x56169ba1370d in main ../src/network/test-routing-policy-rule.c:99
    #5 0x7f654621d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x7f6546e2b30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f6546818bbd in free_and_strdup ../src/basic/string-util.c:855
    #2 0x56169ba1bcd5 in routing_policy_load_rules ../src/network/networkd-routing-policy-rule.c:1020
    #3 0x56169ba12d3f in test_rule_serialization ../src/network/test-routing-policy-rule.c:48
    #4 0x56169ba136db in main ../src/network/test-routing-policy-rule.c:92
    #5 0x7f654621d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x7f6546e2b30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f6546818bbd in free_and_strdup ../src/basic/string-util.c:855
    #2 0x56169ba1bd3c in routing_policy_load_rules ../src/network/networkd-routing-policy-rule.c:1025
    #3 0x56169ba12d3f in test_rule_serialization ../src/network/test-routing-policy-rule.c:48
    #4 0x56169ba1370d in main ../src/network/test-routing-policy-rule.c:99
    #5 0x7f654621d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 14 byte(s) leaked in 4 allocation(s).
```

**Comment by evverx** [comment]
https://github.com/systemd/systemd/pull/7492 is likely to fix the issue.

**Comment by yuwata** [comment]
#7492 is merged. Let's close this.
