### ISSUE TITLE
There seems to be a heap-buffer-overflow

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#7598]
```
=================================================================
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d0000109a6 at pc 0x7f0e397bd1e9 bp 0x7ffc217a6f90 sp 0x7ffc217a6708
READ of size 135 at 0x60d0000109a6 thread T0 (systemd)
    #0 0x7f0e397bd1e8  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x601e8)
    #1 0x7f0e397be145 in __interceptor_vsnprintf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x61145)
    #2 0x563bf54ab6a9 in log_internalv_realm ../src/basic/log.c:699
    #3 0x563bf54ab8a0 in log_internal_realm ../src/basic/log.c:716
    #4 0x563bf525cfa2 in main ../src/core/main.c:2423
    #5 0x7f0e36fef82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x563bf524f6c8 in _start (/lib/systemd/systemd+0x13c6c8)

0x60d0000109a6 is located 0 bytes to the right of 134-byte region [0x60d000010920,0x60d0000109a6)
allocated by thread T0 (systemd) here:
    #0 0x7f0e397f5602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x563bf52dedfc in malloc_multiply ../src/basic/alloc-util.h:74
    #2 0x563bf52f9d1d in manager_taint_string ../src/core/manager.c:3877
    #3 0x563bf525cf1a in main ../src/core/main.c:2421
    #4 0x7f0e36fef82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 ??
Shadow bytes around the buggy address:
  0x0c1a7fffa0e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fffa0f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fffa100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fffa110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fffa120: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c1a7fffa130: 00 00 00 00[06]fa fa fa fa fa fa fa fa fa 00 00
  0x0c1a7fffa140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 fa
  0x0c1a7fffa150: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c1a7fffa160: fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa
  0x0c1a7fffa170: fa fa fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c1a7fffa180: fd fd fd fa fa fa fa fa fa fa fa fa fd fd fd fd
```

**Comment by evverx** [comment]
This is likely to be fixed in https://github.com/systemd/systemd/pull/7597.

**Comment by yuwata** [comment]
#7597 is merged. Let's close this.
