### ISSUE TITLE
There seems to be a memory leak in `test-dhcp6-client`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#7882]
Since https://github.com/systemd/systemd/pull/7582 was merged, `test-dhcp6-client` has been failing with the following error:
```sh
$ sudo ./build/test-dhcp6-client
...
==16612==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fd6e290579a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x56123d974138 in dhcp6_option_parse_pdprefix ../src/libsystemd-network/dhcp6-option.c:341
    #2 0x56123d974f96 in dhcp6_option_parse_ia ../src/libsystemd-network/dhcp6-option.c:470
    #3 0x56123d95f414 in test_option_status ../src/libsystemd-network/test-dhcp6-client.c:270
    #4 0x56123d9645b0 in main ../src/libsystemd-network/test-dhcp6-client.c:932
    #5 0x7fd6e1c8682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fd6e290579a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x56123d973bce in dhcp6_option_parse_address ../src/libsystemd-network/dhcp6-option.c:301
    #2 0x56123d974ea7 in dhcp6_option_parse_ia ../src/libsystemd-network/dhcp6-option.c:453
    #3 0x56123d95f297 in test_option_status ../src/libsystemd-network/test-dhcp6-client.c:262
    #4 0x56123d9645b0 in main ../src/libsystemd-network/test-dhcp6-client.c:932
    #5 0x7fd6e1c8682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x7fd6e290579a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x56123d974138 in dhcp6_option_parse_pdprefix ../src/libsystemd-network/dhcp6-option.c:341
    #2 0x56123d974f96 in dhcp6_option_parse_ia ../src/libsystemd-network/dhcp6-option.c:470
    #3 0x56123d95f68e in test_option_status ../src/libsystemd-network/test-dhcp6-client.c:281
    #4 0x56123d9645b0 in main ../src/libsystemd-network/test-dhcp6-client.c:932
    #5 0x7fd6e1c8682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 192 byte(s) leaked in 4 allocation(s).
```
@pfl, could you take a look?

**Comment by pfl** [comment]
Darn, missed fix by 43 minutes. Oh well :-)
