### ISSUE TITLE
ssertion 'fd >= 0' failed at ../src/login/logind-session-device.c:126, function sd_drmsetmaster()

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#8291]
This is a followup to https://github.com/systemd/systemd/issues/8035#issuecomment-368670186

### Submission type

 - Bug report

### systemd version the issue has been seen with

v237-git 4cbbc2a

### Used distribution

Fedora 27

### In case of bug report: Expected behaviour you didn't see

no assert, it indicates error in programming (unless there is a nasty failure in the underlying platform like a cpu bug).

### In case of bug report: Unexpected behaviour you saw

```
#0  0x00007f5b46faf66b in raise () from /lib64/libc.so.6
#1  0x00007f5b46fb1381 in abort () from /lib64/libc.so.6
#2  0x00007f5b47869b15 in log_assert_failed_realm (realm=LOG_REALM_SYSTEMD, text=0x56104c097580 "fd >= 0", 
    file=0x56104c097500 "../src/login/logind-session-device.c", line=126, func=0x56104c0976d0 <__PRETTY_FUNCTION__.11557> "sd_drmsetmaster")
    at ../src/basic/log.c:833
#3  0x000056104c07c7c4 in sd_drmsetmaster (fd=-1) at ../src/login/logind-session-device.c:126
#4  0x000056104c07ca75 in session_device_start (sd=0x56104d8b56d0) at ../src/login/logind-session-device.c:200
#5  0x000056104c07d51f in session_device_resume_all (s=0x56104d8a5b00) at ../src/login/logind-session-device.c:461
#6  0x000056104c076386 in seat_set_active (s=0x56104d89f7b0, session=0x56104d8a5b00) at ../src/login/logind-seat.c:257
#7  0x000056104c07686e in seat_active_vt_changed (s=0x56104d89f7b0, vtnr=1) at ../src/login/logind-seat.c:368
#8  0x000056104c076c8a in seat_read_active_vt (s=0x56104d89f7b0) at ../src/login/logind-seat.c:411
#9  0x000056104c06ddd2 in manager_dispatch_console (s=0x56104d894080, fd=14, revents=8, userdata=0x56104d8926c0) at ../src/login/logind.c:640
#10 0x00007f5b4791b8f0 in source_dispatch (s=0x56104d894080) at ../src/libsystemd/sd-event/sd-event.c:2307
#11 0x00007f5b4791cd05 in sd_event_dispatch (e=0x56104d8938d0) at ../src/libsystemd/sd-event/sd-event.c:2667
#12 0x00007f5b4791d197 in sd_event_run (e=0x56104d8938d0, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:2727
#13 0x000056104c070a26 in manager_run (m=0x56104d8926c0) at ../src/login/logind.c:1207
#14 0x000056104c070cda in main (argc=1, argv=0x7ffefea7a638) at ../src/login/logind.c:1265
```

the full log messages were

```
$ journalctl  -b -u systemd-logind --no-pager
-- Logs begin at Mon 2017-09-25 14:55:52 BST, end at Tue 2018-02-27 11:49:42 GMT. --
Feb 27 09:16:39 fedora27-vm systemd[1]: Starting Login Service...
Feb 27 09:16:39 fedora27-vm systemd-logind[634]: New seat seat0.
Feb 27 09:16:39 fedora27-vm systemd-logind[634]: Watching system buttons on /dev/input/event0 (Power Button)
Feb 27 09:16:39 fedora27-vm systemd-logind[634]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
Feb 27 09:16:39 fedora27-vm systemd[1]: Started Login Service.
Feb 27 09:16:50 fedora27-vm systemd-logind[634]: New session c1 of user gdm.
Feb 27 09:18:21 fedora27-vm systemd-logind[634]: New session 3 of user alan-sysop.
Feb 27 09:18:28 fedora27-vm systemd-logind[634]: New session 4 of user alan-sysop.
Feb 27 09:24:02 fedora27-vm systemd[1]: Stopping Login Service...
Feb 27 09:24:02 fedora27-vm systemd[1]: Stopped Login Service.
Feb 27 09:24:02 fedora27-vm systemd[1]: Starting Login Service...
Feb 27 09:24:02 fedora27-vm systemd-logind[2269]: New seat seat0.
Feb 27 09:24:02 fedora27-vm systemd-logind[2269]: Watching system buttons on /dev/input/event0 (Power Button)
Feb 27 09:24:02 fedora27-vm systemd-logind[2269]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
Feb 27 09:24:02 fedora27-vm systemd[1]: Started Login Service.
Feb 27 09:24:02 fedora27-vm systemd-logind[2269]: New session 4 of user alan-sysop.
Feb 27 09:24:02 fedora27-vm systemd-logind[2269]: New session 3 of user alan-sysop.
Feb 27 09:24:02 fedora27-vm systemd-logind[2269]: New session c1 of user gdm.
Feb 27 10:17:51 fedora27-vm systemd-logind[2269]: Assertion 'fd >= 0' failed at ../src/login/logind-session-device.c:126, function sd_drmsetmaster(). Aborting.
Feb 27 10:17:51 fedora27-vm systemd[1]: systemd-logind.service: Main process exited, code=dumped, status=6/ABRT
Feb 27 10:17:51 fedora27-vm systemd[1]: systemd-logind.service: Failed with result 'core-dump'.
Feb 27 10:17:51 fedora27-vm systemd[1]: systemd-logind.service: Service has no hold-off time, scheduling restart.
Feb 27 10:17:51 fedora27-vm systemd[1]: systemd-logind.service: Scheduled restart job, restart counter is at 1.
Feb 27 10:17:51 fedora27-vm systemd[1]: Stopped Login Service.
Feb 27 10:17:51 fedora27-vm systemd[1]: Starting Login Service...
Feb 27 10:17:51 fedora27-vm systemd-logind[2453]: New seat seat0.
Feb 27 10:17:52 fedora27-vm systemd[1]: Started Login Service.
Feb 27 10:17:52 fedora27-vm systemd-logind[2453]: Watching system buttons on /dev/input/event0 (Power Button)
Feb 27 10:17:52 fedora27-vm systemd-logind[2453]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
Feb 27 10:17:52 fedora27-vm systemd-logind[2453]: New session 4 of user alan-sysop.
Feb 27 10:17:52 fedora27-vm systemd-logind[2453]: New session c1 of user gdm.
Feb 27 10:17:52 fedora27-vm systemd-logind[2453]: New session 3 of user alan-sysop.
Feb 27 10:18:31 fedora27-vm systemd-logind[2453]: Removed session c1.
```

### In case of bug report: Steps to reproduce the problem

1. Fedora 27 in a VM (virt-manager)
2. Log in to GNOME.
3. `systemctl restart systemd-logind` # Note this will freeze GNOME as it loses all input devices.  It is a [reported bug](https://bugzilla.redhat.com/show_bug.cgi?id=1540321).
4. ssh in
5. echo 1 | sudo tee /proc/sys/kernel/sysrq
6. echo r | sudo tee /proc/sysrq-trigger
7. Verify message `sysrq: SysRq : Keyboard mode set to system default` appears in `dmesg`.
8. Inject the keypress Ctrl+Alt+F1 in to the VM.

    (My memory is not 100% certain this last step is exactly what I did, but the rest is all confirmed by the logs.  So for now lets assume it was something very much like this, and that it won't be hard to reproduce).

**Comment by poettering** [comment]
Could you give #8332 a whirl? It should fix your issue

**Comment by sourcejedi** [comment]
Yep :).  That seems to have stopped it from crashing.
