### ISSUE TITLE
There seems to be a memory leak in systemd-portabled

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9086]
I started to play with `portablectl` and came across a memory leak reported by `ASAN`. I think `attach` and `stop` should be enough to reproduce it:
```sh
-bash-4.4# /usr/lib/systemd/portablectl attach GIBBERISH
(Matching unit files with prefix 'GIBBERISH'.)
Failed to attach image: No image 'GIBBERISH' found.

-bash-4.4# systemctl stop systemd-portabled
```
Here is what I found in the journal:
```sh
systemd-portabled.service: Trying to enqueue job systemd-portabled.service/stop/replace
systemd-portabled.service: Installed new job systemd-portabled.service/stop as 335
systemd-portabled.service: Enqueued job systemd-portabled.service/stop as 335
systemd-portabled.service: Changed running -> stop-sigterm
Stopping Portable Service Manager...
systemd-portabled.service: D-Bus name org.freedesktop.portable1 no longer registered by :1.12
=================================================================
==152==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x7f467b823238 in __interceptor_strdup (/lib64/libasan.so.4+0x77238)
    #1 0x7f467abc222d in strv_extend ../src/basic/strv.c:501
    #2 0x7f467ac70403 in bus_message_read_strv_extend ../src/libsystemd/sd-bus/bus-message.c:5503
    #3 0x7f467ac706ff in sd_bus_message_read_strv ../src/libsystemd/sd-bus/bus-message.c:5525
    #4 0x5594d5aa88f9 in bus_image_common_attach ../src/portable/portabled-image-bus.c:235
    #5 0x5594d5aa58af in redirect_method_to_image ../src/portable/portabled-bus.c:215
    #6 0x5594d5aa5bf4 in method_attach_image ../src/portable/portabled-bus.c:250
    #7 0x7f467ac783a9 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:407
    #8 0x7f467ac7fa48 in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1265
    #9 0x7f467ac80ca9 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1381
    #10 0x7f467acc3e82 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2666
    #11 0x7f467acc42f4 in process_running ../src/libsystemd/sd-bus/sd-bus.c:2708
    #12 0x7f467acc64a3 in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:2927
    #13 0x7f467acc666b in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:2954
    #14 0x7f467acc922c in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3299
    #15 0x7f467ad61e85 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:2294
    #16 0x7f467ad65bd2 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:2652
    #17 0x7f467ad66829 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:2709
    #18 0x7f467a9d15db in bus_event_loop_with_idle ../src/shared/bus-util.c:124
    #19 0x5594d5aaf406 in manager_run ../src/portable/portabled.c:117
    #20 0x5594d5aaf9d1 in main ../src/portable/portabled.c:161
    #21 0x7f46791eaf29 in __libc_start_main (/lib64/libc.so.6+0x20f29)
SUMMARY: AddressSanitizer: 10 byte(s) leaked in 1 allocation(s).
systemd-portabled.service: Child 152 belongs to systemd-portabled.service.
systemd-portabled.service: Main process exited, code=exited, status=1/FAILURE
systemd-portabled.service: Failed with result 'exit-code'.
systemd-portabled.service: Changed stop-sigterm -> failed
systemd-portabled.service: Job systemd-portabled.service/stop finished, result=done
Stopped Portable Service Manager.
systemd-portabled.service: Unit entered failed state.
```

**Comment by evverx** [comment]
Sorry I forgot to add the milestone. I hope it won't happen again.
