### ISSUE TITLE
There seems to be a memory leak in test-conf-parser

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9180]
```sh
$ ./build/test-conf-parser
...
== test_config_parse[11] ==
/tmp/test-conf-parser.S0cvwv:1: Continuation line too long

=================================================================
==26212==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x7fdcce84b238 in __interceptor_strdup (/lib64/libasan.so.4+0x77238)
    #1 0x7fdccda11527 in config_parse_path ../src/shared/conf-parser.c:723
    #2 0x5616828abcab in test_config_parse_path_one ../src/test/test-conf-parser.c:21
    #3 0x5616828ad14f in test_config_parse_path ../src/test/test-conf-parser.c:102
    #4 0x5616828af856 in main ../src/test/test-conf-parser.c:394
    #5 0x7fdccc422f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

Direct leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0x7fdcce84b238 in __interceptor_strdup (/lib64/libasan.so.4+0x77238)
    #1 0x7fdccda11527 in config_parse_path ../src/shared/conf-parser.c:723
    #2 0x5616828abcab in test_config_parse_path_one ../src/test/test-conf-parser.c:21
    #3 0x5616828ad160 in test_config_parse_path ../src/test/test-conf-parser.c:103
    #4 0x5616828af856 in main ../src/test/test-conf-parser.c:394
    #5 0x7fdccc422f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

SUMMARY: AddressSanitizer: 27 byte(s) leaked in 2 allocation(s).
```

**Comment by evverx** [comment]
It seems that the leak is being fixed in https://github.com/systemd/systemd/pull/9177.
