### ISSUE TITLE
udev race condition involving RUN directives and the notification sempahore

### ISSUE THREAD

**Issue by agusdallalba** [systemd/systemd#9469]
**systemd version the issue has been seen with**
> 238

**Used distribution**
 > Arch Linux

**Steps to reproduce the problem**

A consequence of this bug is that `cryptsetup open` hangs on the `semop` syscall. I discovered this problem because my system got stuck at boot.

0. Fist let's test that cryptsetup works properly:

`fallocate -l 1M test0_file && cryptsetup --debug plainOpen test0_file test0`
```
# cryptsetup 2.0.3 processing "cryptsetup --debug plainOpen test0_file test0"
# Running command open.
# Locking memory.
# Installing SIGINT/SIGTERM handler.
# Unblocking interruption on signal.
# Allocating context for crypt device test0_file.
# Trying to open and read device test0_file with direct-io.
# Initialising device-mapper backend library.
# Formatting device test0_file as type PLAIN.
# Crypto backend (gcrypt 1.8.3) initialized in cryptsetup library version 2.0.3.
# Detected kernel Linux 4.17.2-1-ARCH x86_64.
# Interactive passphrase entry requested.
Enter passphrase for test0_file: 
# Activating volume test0 [keyslot -1] using passphrase.
# dm version   [ opencount flush ]   [16384] (*1)
# dm versions   [ opencount flush ]   [16384] (*1)
# Detected dm-ioctl version 4.39.0.
# Detected dm-crypt version 1.18.1.
# Device-mapper backend running with UDEV support enabled.
# dm status test0  [ opencount flush ]   [16384] (*1)
# Plain: hashing passphrase using ripemd160.
# Allocating a free loop device.
# Trying to open and read device /dev/loop0 with direct-io.
# Calculated device size is 20480 sectors (RW), offset 0.
# Trying to activate PLAIN device test0 using cipher aes-cbc-essiv:sha256.
# DM-UUID is CRYPT-PLAIN-test0
# Udev cookie 0xd4d5ac1 (semid 2359325) created
# Udev cookie 0xd4d5ac1 (semid 2359325) incremented to 1
# Udev cookie 0xd4d5ac1 (semid 2359325) incremented to 2
# Udev cookie 0xd4d5ac1 (semid 2359325) assigned to CREATE task(0) with flags DISABLE_LIBRARY_FALLBACK         (0x20)
# dm create test0 CRYPT-PLAIN-test0 [ opencount flush ]   [16384] (*1)
# dm reload test0  [ opencount flush securedata ]   [16384] (*1)
# dm resume test0  [ opencount flush securedata ]   [16384] (*1)
# test0: Stacking NODE_ADD (254,1) 0:0 0600 [trust_udev]
# test0: Stacking NODE_READ_AHEAD 256 (flags=1)
# Udev cookie 0xd4d5ac1 (semid 2359325) decremented to 1
# Udev cookie 0xd4d5ac1 (semid 2359325) waiting for zero
# Udev cookie 0xd4d5ac1 (semid 2359325) destroyed
# test0: Skipping NODE_ADD (254,1) 0:0 0600 [trust_udev]
# test0: Processing NODE_READ_AHEAD 256 (flags=1)
# test0 (254:1): read ahead is 256
# test0: retaining kernel read ahead of 256 (requested 256)
# Releasing crypt device test0_file context.
# Releasing device-mapper backend.
# Closed loop /dev/loop0 (test0_file).
# Unlocking memory.
Command successful.
```
Everything works for now.
udev debug output from the journal:
```systemd-udevd[5202]: seq 2953 queued, 'change' 'block'
systemd-udevd[5202]: Validate module index
systemd-udevd[5202]: Check if link configuration needs reloading.
systemd-udevd[5202]: seq 2953 forked new worker [23471]
systemd-udevd[23471]: seq 2953 running
systemd-udevd[23471]: removing watch on '/dev/loop0'
systemd-udevd[23471]: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/60-persistent-storage.rules:90
systemd-udevd[23471]: probe /dev/loop0 raid offset=0
systemd-udevd[5202]: seq 2954 queued, 'add' 'bdi'
systemd-udevd[5202]: seq 2954 forked new worker [23473]
systemd-udevd[5202]: seq 2955 queued, 'add' 'block'
systemd-udevd[23473]: seq 2954 running
systemd-udevd[23471]: handling device node '/dev/loop0', devnum=b7:0, mode=0600, uid=0, gid=0
systemd-udevd[23471]: preserve already existing symlink '/dev/block/7:0' to '../loop0'
systemd-udevd[5202]: seq 2955 forked new worker [23475]
systemd-udevd[23473]: seq 2954 processed
systemd-udevd[23471]: adding watch on '/dev/loop0'
systemd-udevd[23471]: seq 2953 processed
systemd-udevd[23475]: seq 2955 running
systemd-udevd[23475]: GROUP 6 /usr/lib/udev/rules.d/50-udev-default.rules:59
systemd-udevd[23475]: handling device node '/dev/dm-1', devnum=b254:1, mode=0660, uid=0, gid=6
systemd-udevd[23475]: set permissions /dev/dm-1, 060660, uid=0, gid=6
systemd-udevd[23475]: creating symlink '/dev/block/254:1' to '../dm-1'
systemd-udevd[23475]: seq 2955 processed
systemd-udevd[5202]: cleanup idle workers
systemd-udevd[23471]: Unload module index
systemd-udevd[23475]: Unload module index
systemd-udevd[23475]: Unloaded link configuration context.
systemd-udevd[23471]: Unloaded link configuration context.
systemd-udevd[23473]: Unload module index
systemd-udevd[23473]: Unloaded link configuration context.
systemd-udevd[5202]: worker [23471] exited
systemd-udevd[5202]: worker [23475] exited
systemd-udevd[5202]: cleanup idle workers
systemd-udevd[5202]: worker [23473] exited
systemd-udevd[5202]: seq 2956 queued, 'change' 'block'
systemd-udevd[5202]: seq 2956 forked new worker [23478]
systemd-udevd[23478]: seq 2956 running
systemd-udevd[23478]: IMPORT '/usr/bin/dmsetup udevflags 6350208' /usr/lib/udev/rules.d/10-dm.rules:53
[23479]: starting '/usr/bin/dmsetup udevflags 6350208'
systemd-udevd[23478]: '/usr/bin/dmsetup udevflags 6350208'(out) 'DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG='1''
systemd-udevd[23478]: '/usr/bin/dmsetup udevflags 6350208'(out) 'DM_UDEV_PRIMARY_SOURCE_FLAG='1''
systemd-udevd[23478]: Process '/usr/bin/dmsetup udevflags 6350208' succeeded.
systemd-udevd[23478]: LINK 'mapper/test0' /usr/lib/udev/rules.d/10-dm.rules:135
systemd-udevd[23478]: LINK 'disk/by-id/dm-name-test0' /usr/lib/udev/rules.d/13-dm-disk.rules:17
systemd-udevd[23478]: LINK 'disk/by-id/dm-uuid-CRYPT-PLAIN-test0' /usr/lib/udev/rules.d/13-dm-disk.rules:18
systemd-udevd[23478]: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/13-dm-disk.rules:23
systemd-udevd[23478]: probe /dev/dm-1 raid offset=0
systemd-udevd[23478]: RUN '/usr/bin/dmsetup udevcomplete $env{DM_COOKIE}' /usr/lib/udev/rules.d/95-dm-notify.rules:12
systemd-udevd[23478]: handling device node '/dev/dm-1', devnum=b254:1, mode=0600, uid=0, gid=0
systemd-udevd[23478]: preserve already existing symlink '/dev/block/254:1' to '../dm-1'
systemd-udevd[23478]: creating link '/dev/disk/by-id/dm-name-test0' to '/dev/dm-1'
systemd-udevd[23478]: creating symlink '/dev/disk/by-id/dm-name-test0' to '../../dm-1'
systemd-udevd[23478]: creating link '/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-test0' to '/dev/dm-1'
systemd-udevd[23478]: creating symlink '/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-test0' to '../../dm-1'
systemd-udevd[23478]: creating link '/dev/mapper/test0' to '/dev/dm-1'
systemd-udevd[23478]: creating symlink '/dev/mapper/test0' to '../dm-1'
[23480]: starting '/usr/bin/dmsetup udevcomplete 6350208'
systemd-udevd[23478]: Process '/usr/bin/dmsetup udevcomplete 6350208' succeeded.
systemd-udevd[23478]: adding watch on '/dev/dm-1'
systemd-udevd[5202]: inotify event: 8 for /dev/loop0
systemd-udevd[23478]: seq 2956 processed
systemd-udevd[5202]: device /dev/loop0 closed, synthesising 'change'
systemd-udevd[5202]: seq 2957 queued, 'change' 'block'
systemd-udevd[5202]: seq 2957 forked new worker [23481]
systemd-udevd[23481]: seq 2957 running
systemd-udevd[23481]: removing watch on '/dev/loop0'
systemd-udevd[5202]: inotify event: 8000 for /dev/loop0
systemd-udevd[5202]: removing watch on '/dev/loop0'
systemd-udevd[23481]: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/60-persistent-storage.rules:90
systemd-udevd[23481]: probe /dev/loop0 raid offset=0
systemd-udevd[23481]: handling device node '/dev/loop0', devnum=b7:0, mode=0600, uid=0, gid=0
systemd-udevd[23481]: preserve already existing symlink '/dev/block/7:0' to '../loop0'
systemd-udevd[23481]: adding watch on '/dev/loop0'
systemd-udevd[23481]: seq 2957 processed
systemd-udevd[5202]: cleanup idle workers
systemd-udevd[23481]: Unload module index
systemd-udevd[23481]: Unloaded link configuration context.
systemd-udevd[5202]: worker [23481] exited
systemd-udevd[5202]: cleanup idle workers
systemd-udevd[23478]: Unload module index
systemd-udevd[23478]: Unloaded link configuration context.
systemd-udevd[5202]: worker [23478] exited
```

1. Now I create a rule with a RUN directive that is triggered many times in quick succession:
`mkdir /run/udev/rules.d && echo 'RUN="/bin/true"' > /etc/udev/rules.d/test.rules`

2. If we try again with cryptsetup:
`fallocate -l 1M test_file && cryptsetup --debug plainOpen test_file test`
```
# cryptsetup 2.0.3 processing "cryptsetup --debug plainOpen test_file test"
# Running command open.
# Locking memory.
# Installing SIGINT/SIGTERM handler.
# Unblocking interruption on signal.
# Allocating context for crypt device test_file.
# Trying to open and read device test_file with direct-io.
# Initialising device-mapper backend library.
# Formatting device test_file as type PLAIN.
# Crypto backend (gcrypt 1.8.3) initialized in cryptsetup library version 2.0.3.
# Detected kernel Linux 4.17.2-1-ARCH x86_64.
# Interactive passphrase entry requested.
Enter passphrase for test_file: 
# Activating volume test [keyslot -1] using passphrase.
# dm version   [ opencount flush ]   [16384] (*1)
# dm versions   [ opencount flush ]   [16384] (*1)
# Detected dm-ioctl version 4.39.0.
# Detected dm-crypt version 1.18.1.
# Device-mapper backend running with UDEV support enabled.
# dm status test  [ opencount flush ]   [16384] (*1)
# Plain: hashing passphrase using ripemd160.
# Allocating a free loop device.
# Trying to open and read device /dev/loop1 with direct-io.
# Calculated device size is 2048 sectors (RW), offset 0.
# Trying to activate PLAIN device test using cipher aes-cbc-essiv:sha256.
# DM-UUID is CRYPT-PLAIN-test
# Udev cookie 0xd4d7151 (semid 2654239) created
# Udev cookie 0xd4d7151 (semid 2654239) incremented to 1
# Udev cookie 0xd4d7151 (semid 2654239) incremented to 2
# Udev cookie 0xd4d7151 (semid 2654239) assigned to CREATE task(0) with flags DISABLE_LIBRARY_FALLBACK         (0x20)
# dm create test CRYPT-PLAIN-test [ opencount flush ]   [16384] (*1)
# dm reload test  [ opencount flush securedata ]   [16384] (*1)
# dm resume test  [ opencount flush securedata ]   [16384] (*1)
# test: Stacking NODE_ADD (254,2) 0:0 0600 [trust_udev]
# test: Stacking NODE_READ_AHEAD 256 (flags=1)
# Udev cookie 0xd4d7151 (semid 2654239) decremented to 1
# Udev cookie 0xd4d7151 (semid 2654239) waiting for zero
```
Now `cryptsetup` is stuck in the `semop` syscall.

3. `gdb -p $(pgrep cryptsetup)`
```
[snip]
(gdb) where
#0  0x00007ff43af5a297 in semop () from /usr/lib/libc.so.6
#1  0x00007ff43ac19e73 in _udev_wait (cookie=223179089, nowait=nowait@entry=0x7ffc3cc74ee4) at libdm-common.c:2610
#2  0x00007ff43ac1b577 in dm_udev_wait (cookie=<optimized out>) at libdm-common.c:2629
#3  0x00007ff43b64a8fa in _dm_create_device (name=name@entry=0x7ffc3cc7761c "test", type=type@entry=0x7ff43b66a940 "PLAIN", 
    device=0x564250661eb0, flags=flags@entry=0, uuid=0x0, size=2048, target=DM_CRYPT, 
    params=0x564250664718 "aes-cbc-essiv:sha256 9c1185a5c5e9fc54612808977ee8f548b2258d31ddadef707ba62c166051b9e3 0 /dev/loop1 0", 
    reload=0) at lib/libdevmapper.c:1127
#4  0x00007ff43b64ad5c in dm_create_device (cd=cd@entry=0x5642506623d0, name=name@entry=0x7ffc3cc7761c "test", 
    type=type@entry=0x7ff43b66a940 "PLAIN", dmd=dmd@entry=0x7ffc3cc75100, reload=reload@entry=0) at lib/libdevmapper.c:1207
#5  0x00007ff43b63ca7b in PLAIN_activate (cd=cd@entry=0x5642506623d0, name=name@entry=0x7ffc3cc7761c "test", vk=<optimized out>, 
    size=<optimized out>, flags=flags@entry=0) at lib/setup.c:512
#6  0x00007ff43b63f7f8 in _activate_by_passphrase (cd=0x5642506623d0, name=0x7ffc3cc7761c "test", keyslot=<optimized out>, 
    passphrase=<optimized out>, passphrase_size=<optimized out>, flags=0) at lib/setup.c:2938
#7  0x000056424ece45be in action_open_plain () at src/cryptsetup.c:240
#8  action_open () at src/cryptsetup.c:1766
#9  0x000056424ecdb393 in run_action (action=<optimized out>) at src/cryptsetup.c:2119
#10 main (argc=5, argv=0x7ffc3cc75518) at src/cryptsetup.c:2553
(gdb) up
#1  0x00007ff43ac19e73 in _udev_wait (cookie=223179089, nowait=nowait@entry=0x7ffc3cc74ee4) at libdm-common.c:2610
2610		if (semop(semid, &sb, 1) < 0) {
(gdb) print (int)semctl(semid, 0, 12)
$1 = 1
```
The semaphore is `1`, and udev doesn't decrement it.

New udev debug output from the journal:

```
systemd-udevd[5202]: seq 2958 queued, 'change' 'block'
systemd-udevd[5202]: Unload module index
systemd-udevd[5202]: Unloaded link configuration context.
systemd-udevd[5202]: Load module index
systemd-udevd[5202]: Parsed configuration file /usr/lib/systemd/network/99-default.link
systemd-udevd[5202]: Created link configuration context.
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/10-dm.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/11-dm-lvm.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/13-dm-disk.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/25-gpsd-usb.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/39-usbmuxd.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/40-gphoto.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/40-hpet-permissions.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/49-sane.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/51-android.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/51-usb-device.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/55-Argyll.rules
systemd-udevd[5202]: /usr/lib/udev/rules.d/55-Argyll.rules:132: IMPORT found builtin 'usb_id --export %p', replacing
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/56-hpmud.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-block.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-cdrom_id.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-fprint-autosuspend.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-heimdall.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-input-id.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-persistent-v4l.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-rfkill.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/60-vboxdrv.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/61-gdm.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/61-gnome-bluetooth-rfkill.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/61-gnome-settings-daemon-rfkill.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/63-md-raid-arrays.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/64-btrfs-dm.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/64-md-raid-assembly.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/65-kvm.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/65-libwacom.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/69-cd-sensors.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/69-dm-lvm-metad.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/69-libmtp.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-htc-vive.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-infrared.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-joystick.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-power-switch.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-printers.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-steam-controller.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/70-uaccess.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/71-seat.rules
systemd-udevd[5202]: Reading rules file: /etc/udev/rules.d/71-trackpoint.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/73-seat-late.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/75-net-description.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-cinterion-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-dell-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-ericsson-mbm.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-haier-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-huawei-net-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-longcheer-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-mtk-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-nokia-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-pcmcia-device-blacklist.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-sierra.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-simtech-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-telit-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-ublox-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-usb-device-blacklist.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-usb-serial-adapters-greylist.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-x22x-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/77-mm-zte-port-types.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/80-drivers.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/80-libinput-device-groups.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/80-mm-candidate.rules
systemd-udevd[5202]: Skipping empty file: /etc/udev/rules.d/80-net-setup-link.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/80-udisks2.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/84-nm-drivers.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/85-nm-unmanaged.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/85-tlp.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/90-alsa-restore.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/90-libgpod.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/90-libinput-model-quirks.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/90-pulseaudio.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/90-vconsole.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/95-cd-devices.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/95-dm-notify.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/95-upower-csr.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/95-upower-hid.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/95-upower-wup.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/99-fuse3.rules
systemd-udevd[5202]: Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
systemd-udevd[5202]: Reading rules file: /run/udev/rules.d/test.rules
systemd-udevd[5202]: rules contain 393216 bytes tokens (32768 * 12 bytes), 38652 bytes strings
systemd-udevd[5202]: 32610 strings (261882 bytes), 28673 de-duplicated (227168 bytes), 3938 trie nodes used
systemd-udevd[5202]: seq 2958 forked new worker [23687]
systemd-udevd[23687]: seq 2958 running
systemd-udevd[23687]: removing watch on '/dev/loop1'
systemd-udevd[5202]: inotify event: 8 for /dev/loop1
systemd-udevd[23687]: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/60-persistent-storage.rules:90
systemd-udevd[23687]: probe /dev/loop1 raid offset=0
systemd-udevd[23687]: RUN '/bin/true' /run/udev/rules.d/test.rules:1
systemd-udevd[23687]: handling device node '/dev/loop1', devnum=b7:1, mode=0600, uid=0, gid=0
systemd-udevd[23687]: preserve already existing symlink '/dev/block/7:1' to '../loop1'
systemd-udevd[5202]: device /dev/loop1 closed, synthesising 'change'
systemd-udevd[5202]: seq 2959 queued, 'add' 'bdi'
[23688]: starting '/bin/true'
systemd-udevd[5202]: seq 2959 forked new worker [23689]
systemd-udevd[5202]: seq 2960 queued, 'add' 'block'
systemd-udevd[23689]: seq 2959 running
systemd-udevd[5202]: seq 2960 forked new worker [23690]
systemd-udevd[23689]: RUN '/bin/true' /run/udev/rules.d/test.rules:1
systemd-udevd[5202]: seq 2961 queued, 'change' 'block'
systemd-udevd[23687]: Process '/bin/true' succeeded.
systemd-udevd[23687]: adding watch on '/dev/loop1'
systemd-udevd[5202]: seq 2962 queued, 'change' 'block'
systemd-udevd[23690]: seq 2960 running
systemd-udevd[23690]: GROUP 6 /usr/lib/udev/rules.d/50-udev-default.rules:59
systemd-udevd[23690]: RUN '/bin/true' /run/udev/rules.d/test.rules:1
[23691]: starting '/bin/true'
systemd-udevd[23690]: handling device node '/dev/dm-2', devnum=b254:2, mode=0660, uid=0, gid=6
systemd-udevd[23690]: set permissions /dev/dm-2, 060660, uid=0, gid=6
systemd-udevd[23690]: creating symlink '/dev/block/254:2' to '../dm-2'
systemd-udevd[23689]: Process '/bin/true' succeeded.
[23692]: starting '/bin/true'
systemd-udevd[23689]: seq 2959 processed
systemd-udevd[23690]: Process '/bin/true' succeeded.
systemd-udevd[23690]: seq 2960 processed
systemd-udevd[23689]: seq 2961 running
systemd-udevd[23689]: IMPORT '/usr/bin/dmsetup udevflags 6320465' /usr/lib/udev/rules.d/10-dm.rules:53
systemd-udevd[23687]: seq 2958 processed
systemd-udevd[23687]: seq 2962 running
systemd-udevd[23687]: removing watch on '/dev/loop1'
systemd-udevd[23687]: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/60-persistent-storage.rules:90
systemd-udevd[23687]: probe /dev/loop1 raid offset=0
[23693]: starting '/usr/bin/dmsetup udevflags 6320465'
systemd-udevd[23687]: RUN '/bin/true' /run/udev/rules.d/test.rules:1
systemd-udevd[23687]: handling device node '/dev/loop1', devnum=b7:1, mode=0600, uid=0, gid=0
systemd-udevd[23687]: preserve already existing symlink '/dev/block/7:1' to '../loop1'
[23694]: starting '/bin/true'
systemd-udevd[23689]: '/usr/bin/dmsetup udevflags 6320465'(out) 'DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG='1''
systemd-udevd[23689]: '/usr/bin/dmsetup udevflags 6320465'(out) 'DM_UDEV_PRIMARY_SOURCE_FLAG='1''
systemd-udevd[23689]: Process '/usr/bin/dmsetup udevflags 6320465' succeeded.
systemd-udevd[23689]: LINK 'mapper/test' /usr/lib/udev/rules.d/10-dm.rules:135
systemd-udevd[23689]: LINK 'disk/by-id/dm-name-test' /usr/lib/udev/rules.d/13-dm-disk.rules:17
systemd-udevd[23689]: LINK 'disk/by-id/dm-uuid-CRYPT-PLAIN-test' /usr/lib/udev/rules.d/13-dm-disk.rules:18
systemd-udevd[23689]: IMPORT builtin 'blkid' /usr/lib/udev/rules.d/13-dm-disk.rules:23
systemd-udevd[23689]: probe /dev/dm-2 raid offset=0
systemd-udevd[23687]: Process '/bin/true' succeeded.
systemd-udevd[23687]: adding watch on '/dev/loop1'
systemd-udevd[23687]: seq 2962 processed
systemd-udevd[23689]: RUN '/usr/bin/dmsetup udevcomplete $env{DM_COOKIE}' /usr/lib/udev/rules.d/95-dm-notify.rules:12
systemd-udevd[23689]: RUN '/bin/true' /run/udev/rules.d/test.rules:1
systemd-udevd[23689]: handling device node '/dev/dm-2', devnum=b254:2, mode=0600, uid=0, gid=0
systemd-udevd[23689]: preserve already existing symlink '/dev/block/254:2' to '../dm-2'
systemd-udevd[23689]: creating link '/dev/disk/by-id/dm-name-test' to '/dev/dm-2'
systemd-udevd[23689]: creating symlink '/dev/disk/by-id/dm-name-test' to '../../dm-2'
systemd-udevd[23689]: creating link '/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-test' to '/dev/dm-2'
systemd-udevd[23689]: creating symlink '/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-test' to '../../dm-2'
systemd-udevd[23689]: creating link '/dev/mapper/test' to '/dev/dm-2'
systemd-udevd[23689]: creating symlink '/dev/mapper/test' to '../dm-2'
[23695]: starting '/bin/true'
systemd-udevd[23689]: Process '/bin/true' succeeded.
systemd-udevd[23689]: adding watch on '/dev/dm-2'
systemd-udevd[23689]: seq 2961 processed
systemd-udevd[5202]: cleanup idle workers
systemd-udevd[23687]: Unload module index
systemd-udevd[23687]: Unloaded link configuration context.
systemd-udevd[23690]: Unload module index
systemd-udevd[23690]: Unloaded link configuration context.
systemd-udevd[5202]: worker [23687] exited
systemd-udevd[23689]: Unload module index
systemd-udevd[5202]: worker [23690] exited
systemd-udevd[5202]: cleanup idle workers
systemd-udevd[23689]: Unloaded link configuration context.
systemd-udevd[5202]: cleanup idle workers
systemd-udevd[5202]: worker [23689] exited
```

This is as far as I'm able to debug this. I hope it helps.

Thank you.

**Comment by poettering** [comment]
This is a an issue with the DM client side code. It's outside of the scope of sysemd/scope. Please contact the cryptsetup/dm/lvm people about this. Thank you!
