### ISSUE TITLE
Memory leaks in systemd-resolved when "No appropriate name servers or networks for name found"

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9510]
It seems to have happened in a container where the network was down:
```
# SYSTEMD_LOG_LEVEL=debug resolvectl query google.com
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → AUTHENTICATING
Resolving google.com (family *, interface *).
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.752 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
Got message type=error sender=:1.753 destination=:1.752 path=n/a interface=n/a member=n/a cookie=6 reply_cookie=2 signature=s error-name=org.freedesktop.resolve1.NoNameServers error-message=No appropriate name servers or networks for name found
google.com: resolve call failed: No appropriate name servers or networks for name found
Bus n/a: changing state RUNNING → CLOSED
```
```
Stopping Network Name Resolution...
=================================================================
==229==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 69312 byte(s) in 722 object(s) allocated from:
    #0 0x7f82cb9e0a38 in __interceptor_calloc (/usr/lib64/libasan.so.4+0xdea38)
    #1 0x7f82cadbba1a in bus_slot_allocate ../src/libsystemd/sd-bus/bus-slot.c:22
    #2 0x7f82cade8eb8 in sd_bus_call_async ../src/libsystemd/sd-bus/sd-bus.c:1968
    #3 0x7f82cad30bae in sd_bus_call_method_async ../src/libsystemd/sd-bus/bus-convenience.c:79
    #4 0x7f82cad2f21e in bus_add_match_internal_async ../src/libsystemd/sd-bus/bus-control.c:840
    #5 0x7f82cadf4e49 in bus_add_match_full ../src/libsystemd/sd-bus/sd-bus.c:3226
    #6 0x7f82cadf52d3 in sd_bus_add_match_async ../src/libsystemd/sd-bus/sd-bus.c:3282
    #7 0x7f82cadd276a in sd_bus_track_add_name ../src/libsystemd/sd-bus/bus-track.c:237
    #8 0x7f82cadd3722 in sd_bus_track_add_sender ../src/libsystemd/sd-bus/bus-track.c:353
    #9 0x559b6698a310 in dns_query_bus_track ../src/resolve/resolved-dns-query.c:1064
    #10 0x559b66943fa7 in bus_method_resolve_hostname ../src/resolve/resolved-bus.c:349
    #11 0x7f82cada39a0 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:402
    #12 0x7f82cadab03f in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1260
    #13 0x7f82cadac2a0 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1376
    #14 0x7f82cadeffd6 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2661
    #15 0x7f82cadf0448 in process_running ../src/libsystemd/sd-bus/sd-bus.c:2703
    #16 0x7f82cadf25f7 in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:2922
    #17 0x7f82cadf27bf in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:2949
    #18 0x7f82cadf5405 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3302
    #19 0x7f82cae97c43 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3101
    #20 0x7f82cae9c746 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3514
    #21 0x7f82cae9d3ad in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3571
    #22 0x7f82cae9d6aa in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:3593
    #23 0x559b6691ff43 in main ../src/resolve/resolved.c:96
    #24 0x7f82c8705f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)
SUMMARY: AddressSanitizer: 69312 byte(s) leaked in 722 allocation(s).
```
There is another backtrace which most likely was caused by `resolvectl service`, but I haven't checked it yet:
```sh
==1743==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x7fb6adb60a38 in __interceptor_calloc (/usr/lib64/libasan.so.4+0xdea38)
    #1 0x7fb6acf3ba1a in bus_slot_allocate ../src/libsystemd/sd-bus/bus-slot.c:22
    #2 0x7fb6acf68eb8 in sd_bus_call_async ../src/libsystemd/sd-bus/sd-bus.c:1968
    #3 0x7fb6aceb0bae in sd_bus_call_method_async ../src/libsystemd/sd-bus/bus-convenience.c:79
    #4 0x7fb6aceaf21e in bus_add_match_internal_async ../src/libsystemd/sd-bus/bus-control.c:840
    #5 0x7fb6acf74e49 in bus_add_match_full ../src/libsystemd/sd-bus/sd-bus.c:3226
    #6 0x7fb6acf752d3 in sd_bus_add_match_async ../src/libsystemd/sd-bus/sd-bus.c:3282
    #7 0x7fb6acf5276a in sd_bus_track_add_name ../src/libsystemd/sd-bus/bus-track.c:237
    #8 0x7fb6acf53722 in sd_bus_track_add_sender ../src/libsystemd/sd-bus/bus-track.c:353
    #9 0x55b3a3ec0310 in dns_query_bus_track ../src/resolve/resolved-dns-query.c:1064
    #10 0x55b3a3e83a9a in bus_method_resolve_service ../src/resolve/resolved-bus.c:1198
    #11 0x7fb6acf239a0 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:402
    #12 0x7fb6acf2b03f in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1260
    #13 0x7fb6acf2c2a0 in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1376
    #14 0x7fb6acf6ffd6 in process_message ../src/libsystemd/sd-bus/sd-bus.c:2661
    #15 0x7fb6acf70448 in process_running ../src/libsystemd/sd-bus/sd-bus.c:2703
    #16 0x7fb6acf725f7 in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:2922
    #17 0x7fb6acf727bf in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:2949
    #18 0x7fb6acf75405 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3302
    #19 0x7fb6ad017c43 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3101
    #20 0x7fb6ad01c746 in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:3514
    #21 0x7fb6ad01d3ad in sd_event_run ../src/libsystemd/sd-event/sd-event.c:3571
    #22 0x7fb6ad01d6aa in sd_event_loop ../src/libsystemd/sd-event/sd-event.c:3593
    #23 0x55b3a3e55f43 in main ../src/resolve/resolved.c:96
    #24 0x7fb6aa885f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)
SUMMARY: AddressSanitizer: 96 byte(s) leaked in 1 allocation(s).
```

**Comment by evverx** [comment]
I don't know why GitHub didn't close the issue automatically. Probably "closes A and closes B" should have been used instead of "closes A and B". Anyway, the leak is gone, so there's no need to keep it open.
