### ISSUE TITLE
ASan seems to report a heap-buffer-overflow in systemd-journald

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#9820]
This seems to be another bug introduced in https://github.com/systemd/systemd/pull/9346 (which I found trying to figure out how to fix https://github.com/systemd/systemd/issues/9795).
```sh
bash-4.4# printf "<13>Aug  4 04:08:03 something-is-about-to-go-wrong:" | nc -u -U /run/systemd/journal/dev-log

bash-4.4# journalctl --no-pager -t something-is-about-to-go-wrong -o verbose
Sat 2018-08-04 04:46:01.366391 UTC [s=3b96f23c6c334f7b9e724b7e03b5d854;i=17b;b=afdea9be6eab48489226ade39509549c;m=5b1f7fc272;t=57294b899cb8b;x=697e93e0825c1f1b]
    _UID=0
    _GID=0
    _SELINUX_CONTEXT=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=afdea9be6eab48489226ade39509549c
    _MACHINE_ID=ac8afcedce83415495faf201074a71fa
    _HOSTNAME=systemd-testsuite
    _CAP_EFFECTIVE=fdecafff
    _SYSTEMD_CGROUP=/system.slice/rescue.service
    _SYSTEMD_UNIT=rescue.service
    _SYSTEMD_INVOCATION_ID=d5a62942c7cc47c299db7300f4dc788a
    _TRANSPORT=syslog
    PRIORITY=5
    SYSLOG_FACILITY=1
    SYSLOG_TIMESTAMP=Aug  4 04:08:03
    _COMM=nc
    _EXE=/usr/bin/ncat
    _CMDLINE=nc -u -U /run/systemd/journal/dev-log
    SYSLOG_IDENTIFIER=something-is-about-to-go-wrong
    MESSAGE=ervice.c
            CODE_LINE=3627
            CODE_FUNC=service_notify_message
            UNIT=systemd-journald.service
            INVOCATION_ID=9d8d6bee4df1429ab153d1f2f27c0d17
            SYSLOG_IDENTIFIER=systemd
            MESSAGE=systemd-journald.service: Got notification message from PID 110 (WATCHDOG=1)
    _PID=150
    _SOURCE_REALTIME_TIMESTAMP=1533357961366391
```
As you might have noticed, the "MESSAGE" field contains quite surprising data which shouldn't be here.

The fuzzer I was talking about in #9795 crashes with
```sh
=================================================================
==14==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000017a at pc 0x000000485c04 bp 0x7ffd1649bfd0 sp 0x7ffd1649b780
READ of size 1 at 0x60300000017a thread T0
    #0 0x485c03 in __interceptor_strlen.part.33 /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:356
    #1 0x55455f in server_process_syslog_message /work/build/../../src/systemd/src/journal/journald-syslog.c:407:13
    #2 0x534242 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:28:9
    #3 0x59ca22 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x574d4a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x580415 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #6 0x564c6c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7fee4da1482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #8 0x420e38 in _start (/out/fuzz-journald+0x420e38)

0x60300000017a is located 0 bytes to the right of 26-byte region [0x603000000160,0x60300000017a)
allocated by thread T0 here:
    #0 0x4efb6f in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x7fee4ec025e4 in memdup_suffix0 /work/build/../../src/systemd/src/basic/alloc-util.c:30:15
    #2 0x534172 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journald.c:23:20
    #3 0x59ca22 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:580:15
    #4 0x574d4a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #5 0x580415 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #6 0x564c6c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7fee4da1482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:356 in __interceptor_strlen.part.33
Shadow bytes around the buggy address:
  0x0c067fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff8000: fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00
  0x0c067fff8010: 00 fa fa fa 00 00 00 00 fa fa 00 00 00 01 fa fa
=>0x0c067fff8020: 00 00 00 01 fa fa 00 00 00 fa fa fa 00 00 00[02]
  0x0c067fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==14==ABORTING
```

**Comment by evverx** [comment]
In case anyone is interested, the fuzzer can be found at https://github.com/evverx/systemd/commit/deaaecd9c43334e55d71b65c452f1eb8fe1790f4.
